### PR TITLE
fix: assign session to remote webContents

### LINKED ISSUE #23615: No webPreferences and session in e.sender received from an extension background page
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Ref #19447

### Issue Details

* **Electron Version:**
  * 9.0.0-beta.24
* **Operating System:**
  * macOS 10.15, Windows 10
* **Last Known Working Electron version:**
  * none

### Expected Behavior
`e.sender` object received from an extension background page should have `webPreferences` and `session` initialized. It looks like `options` in `api::WebContents` constructor don't get initialized properly for an extension background page.

### Actual Behavior
`e.sender` object doesn't have `session` and `e.sender.getWebPreferences()` returns `null`.

### To Reproduce
https://github.com/sentialx/electron-quick-start/tree/extensions/no-session

Just run it and you will see something like this:
image

### Additional Information
This is a real blocker for anyone who would want to provide own `chrome` APIs in background pages initialized from different sessions.

### PR DESCRIPTION
**Pull request by sentialx**
#### Description of Change
This PR ensures that remote webContents (such as devtools and extension background pages) get initialized with `session_` set.

Could this be backported to 9-x-y and 10-x-y, please?

Closes #23615
Ref #19447

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).
- [x] This is **NOT A BREAKING CHANGE**. Breaking changes may not be merged to master until 11-x-y is branched.

#### Release Notes

Notes: Fixed no `session` in webContents of type remote.

### CODE REVIEW

File: shell/browser/api/electron_api_web_contents.cc [hunk 1]
```diff
@@ -393,17 +393,22 @@ WebContents::WebContents(v8::Isolate* isolate,
...
+  auto session = Session::CreateFrom(isolate, GetBrowserContext());
+  session_.Reset(isolate, session.ToV8());
+
   web_contents->SetUserAgentOverride(blink::UserAgentOverride::UserAgentOnly(
                                          GetBrowserContext()->GetUserAgent()),
                                      false);
   Init(isolate);
   AttachAsUserData(web_contents);
   InitZoomController(web_contents, gin::Dictionary::CreateEmpty(isolate));
+
```
Comment (stewartlord) [inline shell/browser/api/electron_api_web_contents.cc:405]: Nit: needless whitespace change (and another one below)
