### PR TITLE
fix: honor webContents.print dpi horizontal/vertical options

### LINKED ISSUE #50785: webContents.print produces tiny print out and wrong page size when silent is true, dpi and paperSize passed it
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

41.1.1

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11 Enterprise 10.0.26200 Build 26200

### What arch are you using?

x64

### Last Known Working Electron version

40.1.0

### Does the issue also appear in Chromium / Google Chrome?

No

### Expected Behavior

In Electron v41.1.1, when calling webContents.print with silent: true and with paperSize and dpi defined, the printout should respect the specified page size and DPI settings, and scale the content to fit the page.
```
 win.webContents.print({
      deviceName:"Microsoft Print to PDF",
      silent: true, 
      margins:{marginType: "default"},
      pageSize:"Letter",
      printBackground:true,
      color: false,
      header: "I am header",
      footer:"I am footer",
      dpi:{horizontal:600, vertical:600}
});
```

### Actual Behavior

The printout falls back to A4 size (8.27 × 11.69 in), and the content appears tiny in the middle of the page.

It looks like we may have introduced a variation of [issue#41928](https://github.com/electron/electron/issues/41928) or [issue#39179](https://github.com/electron/electron/issues/39179).

Image

### Testcase Gist URL

https://gist.github.com/Hedwig188/b508f1be790feee9a257df4577ee1ce8

### Additional Information

The exact same code works in v40.1.0, it may be related to the recent change in #49523.

### PR DESCRIPTION
**Pull request by xakep8**
#### Description of Change

Fixes #50785

This PR fixes a regression in silent printing where custom DPI values from webContents.print were not honored, causing incorrect output scaling in real-world print flows.

#### Checklist

- [x] I have built and tested this change
- [x] I have filled out the PR description
- [ ] [I have reviewed and verified the changes](https://github.com/electron/governance/blob/main/policy/ai.md)
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant API documentation, tutorials, and examples are updated and follow the [documentation style guide](https://github.com/electron/electron/blob/main/docs/development/style-guide.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: This PR fixes a regression in silent printing where custom DPI values from webContents.print were not honored, causing incorrect output scaling in real-world print flows.

### CODE REVIEW

File: shell/browser/api/electron_api_web_contents.cc [hunk 1]
```diff
@@ -3365,13 +3365,13 @@ void WebContents::Print(gin::Arguments* const args) {
...
-                 dpi.ValueOrDefault("vertical",
-                                    dpi.ValueOrDefault(
-                                        printing::kSettingDpiVertical, 72)));
+                 dpi.ValueOrDefault(
+                     "horizontal",
+                     dpi.ValueOrDefault(printing::kSettingDpiHorizontal, 72)));
+    settings.Set(
+        printing::kSettingDpiVertical,
+        dpi.ValueOrDefault(
+            "vertical", dpi.ValueOrDefault(printing::kSettingDpiVertical, 72)));
```
Comment (codebytere) [inline shell/browser/api/electron_api_web_contents.cc]: Please make a [new constant](https://github.com/electron/electron/blob/2e3da1d079f611a3eca1d9d8454f3d2ce75326f9/shell/browser/api/electron_api_web_contents.cc#L437-L467)

**Review by codebytere — CHANGES_REQUESTED** [review]

**Review by codebytere — APPROVED** [review]

**Review by jkleinsc — APPROVED** [review]
