### PR TITLE
Fix #8911

### LINKED ISSUE #8911: beforeunload event not called on subsequent reloads
* Electron version: 1.6.3
* Operating system: Linux

### Expected behavior

When registering a `beforeunload` handler which cancels unloading, I would expect the handler to be called for every `BrowserWindow.reload()`.

### Actual behavior

On 1.6.3, the `beforeunload` handler is called for the first `reload` but not on subsequent calls. Even after removing the event handler, `reload` will not reload the window anymore.

### How to reproduce

```javascript
const cancelUnload = e => {
   console.log('cancelUnload called')
   e.returnValue = false
}

window.addEventListener('beforeunload', cancelUnload)

remote.getCurrentWindow().reload()  // [1] -> cancelUnload called
remote.getCurrentWindow().reload()  // [2] -> cancelUnload called

remote.getCurrentWindow().close()   // [3] -> cancelUnload called
remote.getCurrentWindow().close()   // [4] -> cancelUnload called

window.removeEventListener('beforeunload', cancelUnload)

remote.getCurrentWindow().reload()  // [5] -> reloads window

remote.getCurrentWindow().close()   // [6] -> closes window
```
I would expect `cancelUnload` to be printed to the console four times and the step at `[5]` to actually reload the window. This is works up to Electron 1.6.2.

On Electron 1.6.3 `cancelUnload` is not printed at step `[2]` (nor on any subsequent calls to reload). What's more, event after removing the `beforeunload` handler, `reload` does not work anymore: at step `[5]` the window does not reload (but closing the window at `[6]` works).

### PR DESCRIPTION
**Pull request by 22222**
This would be an addition to the changes in #8724 to handle cases where the navigation is cancelled.

I'm not completely sure that overriding the `BeforeUnloadDialogCancelled` method is the best way to handle this, or if there's more that should be cleaned up.  This fixes the one case I was testing for (#8911) and doesn't break any unit tests (at least when I run them), but I didn't do much other testing to see if there are any other negative side-effects.

And this is my first time even looking at the Electron source code, so don't make any assumptions that I know what I'm doing here.

Fixes #8911

### CODE REVIEW

File: atom/browser/api/atom_api_web_contents.cc [hunk 1]
```diff
@@ -861,6 +861,12 @@ void WebContents::Observe(int type,
   }
 }
 
+void WebContents::BeforeUnloadDialogCancelled() {
+  if (deferred_load_url_.id) {
```
Comment (deepak1556) [inline atom/browser/api/atom_api_web_contents.cc]: `BeforeUnloadDialogCancelled` will also be called for any cancellation inside iframes, we do not want to clear the defer load params in that situation, it would have been better if there was an argument that contained the frame id. The only way now is to check if there is an pending entry or not. This observer will be called only after clearing navigation controller states for this `webContents`, so we can be sure any pending entry would have been cleared.

```
if (deferrer_load_url_.id && !controller.GetPendingEntry())
```

File: spec/api-browser-window-spec.js [hunk 2]
```diff
@@ -1106,6 +1106,90 @@ describe('BrowserWindow module', function () {
       })
       w.loadURL('file://' + path.join(fixtures, 'api', 'close-beforeunload-empty-string.html'))
     })
+
+    it('fires for each close attempt', function (done) {
+      var closeCount = 5
+
+      var timeoutHandle = setTimeout(() => {
```
Comment (deepak1556) [inline spec/api-browser-window-spec.js]: The `timeoutHandle` can lead to a flaky spec, better to remove it. Sometimes the spec may take longer than expected. We do have an overall timeout.

File: spec/api-browser-window-spec.js [hunk 3]
```diff
@@ -1106,6 +1106,90 @@ describe('BrowserWindow module', function () {
...
+        w.webContents.executeJavaScript('isDone = true')
```
Comment (deepak1556) [inline spec/api-browser-window-spec.js]: `executeJavaScript` is an async operation, spec should be ended once its resolved.

File: atom/browser/api/atom_api_web_contents.cc (hunk 1 above)
Comment (22222) [inline atom/browser/api/atom_api_web_contents.cc]: Awesome, thanks for this feedback.  I figured there'd be some special case I hadn't considered.

File: spec/api-browser-window-spec.js (hunk 2 above)
Comment (22222) [inline spec/api-browser-window-spec.js]: Good point, I should have rethought that before I submitted the pull request.  That was all just to workaround issues with the after test hooks not being able to close a page that has a beforeunload handler stopping that.

I'll rework these tests so they're more like the other beforeunload tests (where the beforeunload events stop preventing the window from closing after a fixed number of calls).

File: atom/browser/api/atom_api_web_contents.cc [hunk 4]
```diff
@@ -861,6 +861,16 @@ void WebContents::Observe(int type,
...
+    auto web_contents = managed_web_contents()->GetWebContents();
+    auto& controller = web_contents->GetController();
```
Comment (deepak1556) [inline atom/browser/api/atom_api_web_contents.cc]: This can be just `auto& controller = web_contents()->GetController();`

File: spec/fixtures/api/beforeunload-false-prevent3.html [hunk 5]
```diff
@@ -0,0 +1,17 @@
+<html>
+<body>
+<script type="text/javascript" charset="utf-8">
+  // Only prevent unload on the first three window closes
+  var unloadPreventedCount = 0;
+  window.onbeforeunload = function() {
+    setTimeout(function() {
```
Comment (deepak1556) [inline spec/fixtures/api/beforeunload-false-prevent3.html]: Is it required to be called in next tick ?

**Comment by kevinsawicki** [comment]
Thanks for this @22222 👍 👍
