### PR TITLE
fix: increase corner radius for vibrancy view on big sur

### LINKED ISSUE #27061: [Big Sur] Transpearent Window Corners
### Issue Details

Possibly related to https://github.com/electron/electron/issues/24319 and https://github.com/electron/electron/pull/24642

* **Electron Version:**
  * v11.1.0
* **Operating System:**
  * MacOS 11.1 (20C69)

### Expected Behavior

Platform normalized corners

### Actual Behavior

The corners of the window are off by a few pixels

### To Reproduce

```javascript
    return new BrowserWindow({
      titleBarStyle: 'hidden',
      transparent: true,
      hasShadow: true,
      vibrancy: 'ultra-dark',
    });
```

### Screenshots

Screen Shot 2020-12-16 at 10 34 13 PM

Screen Shot 2020-12-16 at 10 39 54 PM

### LINKED ISSUE #27080: [Big Sur] window corners are not rounded when using vibrancy effects
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11x
* **Operating System:**
  * macOS 11.1 [Big Sur]
* **Last Known Working Electron version:**
  * 

### Expected Behavior
when using BrowserWindow vibrancy effects eg: `vibrancy: 'sidebar'`, the corners of the window are squared.

### To Reproduce
Create a new BrowserWindow with vibrancy effects eg: `vibrancy: 'sidebar'`.

https://gist.github.com/262108f4d281d9aa780ecc18f7ade2ba

### Screenshots
squared-corners

### Additional Information
Adding `titleBarStyle: 'hidden'` rounds the corners, but the corner radius is smaller that normal windows in Big Sur.
small-radius
Which seems to be the issue shown here: https://github.com/electron/electron/issues/27061

### PR DESCRIPTION
**Pull request by robin-fowler**
#### Description of Change
Fix #27061 Fix #27080 

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: Fixed corner radius for vibrancy view in macOS 11

### CODE REVIEW

File: shell/browser/native_window_mac.mm [hunk 1]
```diff
@@ -1288,7 +1288,11 @@ void ViewDidMoveToSuperview(NSView* self, SEL _cmd) {
     const bool no_rounded_corner =
         [window_ styleMask] & NSWindowStyleMaskFullSizeContentView;
     if (!has_frame() && !is_modal() && !no_rounded_corner) {
-      CGFloat radius = 5.0f;  // default corner radius
+      if (@available(macOS 11, *)) {
```
Comment (codebytere) [inline shell/browser/native_window_mac.mm:1291]: `(@available(macOS 11, *))` -> `(@available(macOS 11.0, *))`

File: shell/browser/native_window_mac.mm [hunk 2]
```diff
@@ -1288,7 +1288,11 @@ void ViewDidMoveToSuperview(NSView* self, SEL _cmd) {
...
+        CGFloat radius = 9.0f;
+      } else {
```
Comment (codebytere) [inline shell/browser/native_window_mac.mm:1293]: needs to be declared outside this conditional:

```cpp
CGFloat radius;
if (@available(macOS 11.0, *)) {
   radius = 9.0f;
} else {
   radius = 5.0f;
}
```

**Review by codebytere — CHANGES_REQUESTED** [review]

File: shell/browser/native_window_mac.mm (hunk 2 above)
Comment (robin-fowler) [reply shell/browser/native_window_mac.mm:1294]: Ah thanks for the help!

**Review by codebytere — APPROVED** [review]
Thanks!

**Comment by codebytere** [comment]
@robin-fowler lint is still failing:

```
} else {
-        radius = 5.0f; // smaller corner radius on older versions
+        radius = 5.0f;  // smaller corner radius on older versions
       }
```

but once that's done this is good to go!

File: ELECTRON_VERSION [hunk 3]
```diff
@@ -1 +1 @@
-14.0.0-nightly.20210413
\ No newline at end of file
+14.0.0-nightly.20210414
```
Comment (MarshallOfSound) [inline ELECTRON_VERSION:1]: This change shouldn't be here

File: package.json [hunk 4]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "electron",
-  "version": "14.0.0-nightly.20210413",
+  "version": "14.0.0-nightly.20210414",
```
Comment (MarshallOfSound) [inline package.json:3]: Same here

File: shell/browser/native_window_mac.mm [hunk 5]
```diff
@@ -1288,7 +1288,16 @@ void ViewDidMoveToSuperview(NSView* self, SEL _cmd) {
     const bool no_rounded_corner =
         [window_ styleMask] & NSWindowStyleMaskFullSizeContentView;
     if (!has_frame() && !is_modal() && !no_rounded_corner) {
-      CGFloat radius = 5.0f;  // default corner radius
+      CGFloat radius;
+      if (@available(macOS 11.0, *)) {
+        radius = 9.0f;
+      } else {
+<<<<<<< HEAD
```
Comment (MarshallOfSound) [inline shell/browser/native_window_mac.mm:1295]: There's a git conflict here somehow?

File: shell/browser/resources/win/electron.rc [hunk 6]
```diff
@@ -50,8 +50,8 @@ END
 //
 
 VS_VERSION_INFO VERSIONINFO
- FILEVERSION 14,0,0,20210413
```
Comment (MarshallOfSound) [inline shell/browser/resources/win/electron.rc:53]: This also shouldn't be checked in

**Review by MarshallOfSound — CHANGES_REQUESTED** [review]

File: shell/browser/resources/win/electron.rc (hunk 6 above)
Comment (robin-fowler) [reply shell/browser/resources/win/electron.rc]: Madness. That should be resolved now

**Review by MarshallOfSound — APPROVED** [review]

**Comment by KishanBagaria** [comment]
Can this be backported to 11.x as well? We're not upgrading to Electron 12 atm because it adds ~1000ms to app launch time.

**Comment by MarshallOfSound** [comment]
@KishanBagaria Do you have a bug open with a repro for -->

> We're not upgrading to Electron 12 atm because it adds ~1000ms to app launch time.

**Comment by KishanBagaria** [comment]
> @KishanBagaria Do you have a bug open with a repro for -->
> 
> > We're not upgrading to Electron 12 atm because it adds ~1000ms to app launch time.

Will post issue once I've the repro steps isolated

**Comment by itsnwa** [comment]
This seems to be broken after screensaver and screen changes.

This is the window right after launching the app:
CleanShot 2021-08-13 at 12 45 11@2x

Then after I turned my external monitor off and on again:
CleanShot 2021-08-13 at 12 48 54@2x

**Comment by paulrosania** [comment]
We are also seeing this, on Electron 13.2.3.
