### PR TITLE
Fix app.makeSingleInstance hanging on posix systems

### LINKED ISSUE #9880: app.makeSingleInstance doesn't work under linux, Electron 1.7.x
* Electron version: 1.7.x
* Operating system: Linux

Works in 1.6.11.

### Expected behavior

`app.makeSingleInstance` callback is called when opening an associated file from file manager and application is already opened

### Actual behavior

`app.makeSingleInstance` callback is delayed with about 30-60 seconds before being called

### How to reproduce

You could reproduce the problem by downloading [Caret 3.0 .deb](https://github.com/careteditor/caret/releases/tag/3.0.0) and then following the steps described [here](https://github.com/careteditor/caret/issues/399).

The issue stops reproducing when releasing the same code with 1.6.11.

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Wait for the IO thread to be a thing before attempting to listen on the socket

Fixes #9880

### CODE REVIEW

File: atom/browser/atom_browser_main_parts.cc [hunk 1]
```diff
@@ -183,6 +184,8 @@ void AtomBrowserMainParts::PreMainMessageLoopRun() {
   std::unique_ptr<base::DictionaryValue> empty_info(new base::DictionaryValue);
   Browser::Get()->DidFinishLaunching(*empty_info);
 #endif
+
+  atom::api::App::Get()->PreMainMessageLoopRun();
```
Comment (zcbenz) [inline atom/browser/atom_browser_main_parts.cc]: For consistent behavior on different platforms, this should be put before the `WillFinishLaunching ` call, so the actual listening starts before the `ready` event.

Comment (zcbenz) [reply atom/browser/atom_browser_main_parts.cc]: For clean architecture the classes under `api` namespace usually should not be accessed by the outside namespace, otherwise the browser initialization code would have to know when the module system starts.

A cleaner design to achieve this is to add `PreMainMessageLoopRun` to `BrowserObserver` and then call `Browser::Get()->PreMainMessageLoopRun()`.

File: chromium_src/chrome/browser/process_singleton_posix.cc [hunk 2]
```diff
@@ -1032,12 +1049,13 @@ bool ProcessSingleton::Create() {
...
   DCHECK(BrowserThread::IsMessageLoopValid(BrowserThread::IO));
-  BrowserThread::PostTask(
-      BrowserThread::IO,
-      FROM_HERE,
-      base::Bind(&ProcessSingleton::LinuxWatcher::StartListening,
-                 watcher_,
-                 sock));
+  sock_ = sock;
+
+  if (atom::Browser::Get()->is_ready()) {
```
Comment (zcbenz) [inline chromium_src/chrome/browser/process_singleton_posix.cc]: You can use `BrowserThread::IsMessageLoopValid(BrowserThread::IO)` to avoiding involving `atom::Browser` here.

I'm not sure why `DCHEK` does not work in this file, but you should remove the previous call since it will abort after we fixed the `DCHECK`.

**Comment by MarshallOfSound** [comment]
If I never have to debug this threading single instance locking stuff every again I'll be a happy person 😆

**Comment by zcbenz** [comment]
@MarshallOfSound I pushed a fix for the singleton callback being called on a non-UI thread, which should be able to fix the root cause.
