### PR TITLE
Fix webpreferences not accepting numeric options

### LINKED ISSUE #8492: Support setting numeric options from webpreferences attribute
Hello everyone, ask a question:
        How to set the minimumFontSize property to webview ?
        like BrowserWindow ,webPreferences.minimumFontSize

### PR DESCRIPTION
**Pull request by yamgent**
The webpreferences attribute values are parsed as strings instead
of numbers. Therefore, a conversion is required.

Fixes #8492.

fix-min-size

### CODE REVIEW

File: atom/browser/web_contents_preferences.cc [hunk 1]
```diff
@@ -216,6 +217,25 @@ bool WebContentsPreferences::IsSandboxed(content::WebContents* web_contents) {
...
+
+  // if it is already an integer, no conversion needed
+  if (pref->web_preferences_.GetInteger(attributeName, intValue)) {
+    return true;
+  }
+
+  std::string stringValue;
+
+  if (pref->web_preferences_.GetString(attributeName, &stringValue)) {
+    std::stringstream(stringValue) >> *intValue;
```
Comment (kevinsawicki) [inline atom/browser/web_contents_preferences.cc]: Chrome has a nice helper for this built-in called `base::StringToInt`, mind switching it to that one instead for consistency with the rest of the codebase?

Comment (yamgent) [inline atom/browser/web_contents_preferences.cc]: Noted! Thanks for pointing it out, I am still relatively new to the codebase. :)

**Comment by kevinsawicki** [comment]
Thanks for fixing this @yamgent 👍 

I rebased this on top of the latest master and made one minor change, making your new helper method an instance method instead of a static method so that it was more concise to call.
