### PR TITLE
fix: extend tracing startRecording API to take a full tracing config

### LINKED ISSUE #12506: contentTracing categoryFilter regression on 2.0.0-beta.6
* Electron version: 2.0.0-beta.6
* Operating system: confirmed on macOS locally, assume same on other OS

### Expected behavior
`disabled-by-default-memory-infra` should be collected.

### Actual behavior
It is not. 

**It does seem some of other categories are also not working correctly, but hard to verify what's working vs. what's not working**

### How to reproduce

Below's minimal code to automatically trigger content tracing, with single category filter `disabled-by-default-memory-infra` specified:

index.js
```
const { app, BrowserView, BrowserWindow, contentTracing } = require('electron')
const path = require('path')
const url = require('url')

let win
function createWindow() {
  win = new BrowserWindow({ width: 800, height: 600 })

  win.loadURL(url.format({
    pathname: path.join(`${__dirname}/src`, 'index.html'),
    protocol: 'file:',
    slashes: true
  }));

  //setup browserview to create dummy `load` to capture memory change
  let view = new BrowserView({
    webPreferences: {
      nodeIntegration: false
    }
  })

  win.setBrowserView(view)
  view.setBounds({ x: 0, y: 0, width: 300, height: 300 })
  view.webContents.loadURL('https://web.basemark.com/')

  win.on('closed', () => {
    win = null
  })

  const options = {
    traceOptions: 'record-until-full',
    categoryFilter: '-*,disabled-by-default-memory-infra' //exclude all category, set memory-infra only
  }

  contentTracing.startRecording(options, () => {
    console.log('Tracing started')

    setTimeout(() => {
      contentTracing.stopRecording('./a.trace', (path) => {
        console.log('Tracing data recorded to ' + path)
      })
    }, 10000)
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (win === null) {
    createWindow()
  }
})
```

index.html
```
<!DOCTYPE html>
  <html>
    <head>
      <meta charset="UTF-8">
      <title>Hello World!</title>
    </head>
    <body>
      <h1>Hello World!</h1>
      We are using node <script>document.write(process.versions.node)</script>,
      Chrome <script>document.write(process.versions.chrome)</script>,
      and Electron <script>document.write(process.versions.electron)</script>.
    </body>
  </html>
```

On 1.8.4, it collects memory infra stats correctly: 
image

On 2.0.0, the collected trace is simply empty: 
image

this is full trace metadata on 2.0.0. As you could see below, it doesn't contain any actual trace but only initial metadata when trace kicked off 
```
{"traceEvents":[{"pid":93553,"tid":0,"ts":0,"ph":"M","cat":"__metadata","name":"num_cpus","args":{"number":8}},
{"pid":93553,"tid":13827,"ts":0,"ph":"M","cat":"__metadata","name":"process_sort_index","args":{"sort_index":-1}},
{"pid":93553,"tid":13827,"ts":0,"ph":"M","cat":"__metadata","name":"process_name","args":{"name":"GPU Process"}},
{"pid":93553,"tid":13827,"ts":0,"ph":"M","cat":"__metadata","name":"process_uptime_seconds","args":{"uptime":10}},{"pid":93565,"tid":0,"ts":0,"ph":"M","cat":"__metadata","name":"num_cpus","args":{"number":8}},
{"pid":93565,"tid":21511,"ts":0,"ph":"M","cat":"__metadata","name":"process_sort_index","args":{"sort_index":-5}},
{"pid":93565,"tid":21511,"ts":0,"ph":"M","cat":"__metadata","name":"process_name","args":{"name":"Renderer"}},
{"pid":93565,"tid":21511,"ts":0,"ph":"M","cat":"__metadata","name":"process_uptime_seconds","args":{"uptime":0}},
{"pid":93565,"tid":21511,"ts":0,"ph":"M","cat":"__metadata","name":"process_labels","args":{"labels":"Basemark Web 3.0 | Main page"}},
{"pid":93565,"tid":775,"ts":0,"ph":"M","cat":"__metadata","name":"thread_sort_index","args":{"sort_index":-1}},{"pid":93556,"tid":0,"ts":0,"ph":"M","cat":"__metadata","name":"num_cpus","args":{"number":8}},
{"pid":93556,"tid":21511,"ts":0,"ph":"M","cat":"__metadata","name":"process_sort_index","args":{"sort_index":-5}},
{"pid":93556,"tid":21511,"ts":0,"ph":"M","cat":"__metadata","name":"process_name","args":{"name":"Renderer"}},
{"pid":93556,"tid":21511,"ts":0,"ph":"M","cat":"__metadata","name":"process_uptime_seconds","args":{"uptime":10}},
{"pid":93556,"tid":775,"ts":0,"ph":"M","cat":"__metadata","name":"thread_sort_index","args":{"sort_index":-1}},{"pid":93554,"tid":0,"ts":0,"ph":"M","cat":"__metadata","name":"num_cpus","args":{"number":8}},
{"pid":93554,"tid":8455,"ts":0,"ph":"M","cat":"__metadata","name":"process_sort_index","args":{"sort_index":-5}},
{"pid":93554,"tid":8455,"ts":0,"ph":"M","cat":"__metadata","name":"process_name","args":{"name":"Renderer"}},
{"pid":93554,"tid":8455,"ts":0,"ph":"M","cat":"__metadata","name":"process_uptime_seconds","args":{"uptime":10}},
{"pid":93554,"tid":8455,"ts":0,"ph":"M","cat":"__metadata","name":"process_labels","args":{"labels":"Hello World!"}},
{"pid":93554,"tid":775,"ts":0,"ph":"M","cat":"__metadata","name":"thread_sort_index","args":{"sort_index":-1}},{"pid":93551,"tid":775,"ts":473973638595,"ph":"M","cat":"__metadata","name":"IsTimeTicksHighResolution","args":{"value":true},"tts":311029},
{"pid":93551,"tid":0,"ts":0,"ph":"M","cat":"__metadata","name":"num_cpus","args":{"number":8}},
{"pid":93551,"tid":26883,"ts":0,"ph":"M","cat":"__metadata","name":"process_sort_index","args":{"sort_index":-6}},
{"pid":93551,"tid":26883,"ts":0,"ph":"M","cat":"__metadata","name":"process_name","args":{"name":"Browser"}},
{"pid":93551,"tid":26883,"ts":0,"ph":"M","cat":"__metadata","name":"process_uptime_seconds","args":{"uptime":10}}],"metadata": {"clock-domain":"MAC_MACH_ABSOLUTE_TIME","command_line":"/Users/ojkwon/github/dummy-electron/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --no-sandbox --allow-file-access-from-files --enable-avfoundation ./src/index.js","cpu-brand":"Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz","cpu-family":6,"cpu-model":70,"cpu-stepping":1,"gpu-devid":26657,"gpu-driver":"","gpu-glver":"","gpu-psver":"","gpu-venid":4098,"gpu-vsver":"","highres-ticks":true,"network-type":"WiFi","num-cpus":8,"os-arch":"x86_64","os-name":"Mac OS X","os-version":"10.13.3","physical-memory":16384,"product-version":"Chrome/61.0.3163.100","trace-capture-datetime":"2018-4-2 17:23:53","trace-config":"{\"enable_argument_filter\":false,\"enable_systrace\":false,\"excluded_categories\":[\"*\"],\"included_categories\":[\"disabled-by-default-memory-infra\"],\"memory_dump_config\":{\"allowed_dump_modes\":[\"background\",\"light\",\"detailed\"],\"triggers\":[]},\"record_mode\":\"record-until-full\"}","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Electron/2.0.0-beta.6 Safari/537.36","v8-version":"6.1.534.41"}}
```

**Both (1.8.4/2.0.0) getCategories reports given trace category is supported one**

I couldn't verify each category, but it does seem few other categories are not working as well (mostly around `net-*` related, but based on limited testing)

### PR DESCRIPTION
**Pull request by ZacWalk**
This allows memory-infra to be traced correctly. For memory-infra to be traced memory_dump_config and triggers need to be defined.
Fixes #12506.

Example usage:
```js
const options = {
  "record_mode": "record-until-full",
  "enable_systrace": true,
  "enable_argument_filter": false,
  "excluded_categories": ["*"],
  "included_categories": ["disabled-by-default-memory-infra"],
  "memory_dump_config": {allowed_dump_modes: ["background", "light", "detailed"],
  "triggers": [{min_time_between_dumps_ms: 1000,  "mode": "detailed", "type": "periodic_interval"}]},
}

contentTracing.startRecording(options, () => { })
```
More? docs https://chromium.googlesource.com/chromium/src/+/master/docs/memory-infra/memory_infra_startup_tracing.md#the-advanced-way

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: allow passing a trace config as options to a "contentTracing.startRecording" call

### CODE REVIEW

File: atom/browser/api/atom_api_content_tracing.cc [hunk 1]
```diff
@@ -18,20 +19,28 @@ using content::TracingController;
...
-      return false;
-    std::string category_filter, trace_options;
-    if (!options.Get("categoryFilter", &category_filter) ||
-        !options.Get("traceOptions", &trace_options))
-      return false;
-    *out = base::trace_event::TraceConfig(category_filter, trace_options);
-    return true;
+    if (ConvertFromV8(isolate, val, &options)) {
+      std::string category_filter, trace_options;
+      if (options.Get("categoryFilter", &category_filter) ||
```
[the remark this answers is not in the document]
Comment (ZacWalk) [reply atom/browser/api/atom_api_content_tracing.cc]: I think it is valid to provide only one of categoryFilter or traceOptions. So I think this is correct.

[the remark this answers is not in the document]
Comment (nornagon) [reply atom/browser/api/atom_api_content_tracing.cc]: I'm just going off the previous logic, which is

```cpp
if (!options.Get("categoryFilter", &category_filter) ||
        !options.Get("traceOptions", &trace_options))
```

and de morgan's law :)
!A ∨ !B === !(A ∧ B)

**Comment by codebytere** [comment]
@ZacWalk would you still like to land this?

**Comment by alexeykuzmin** [comment]
@codebytere I'm going to land this.

File: atom/browser/api/atom_api_content_tracing.cc (hunk 1 above)
[the remark this answers is not in the document]
Comment (alexeykuzmin) [reply atom/browser/api/atom_api_content_tracing.cc]: @nornagon changed it to `&&` to preserve exiting logic.

File: atom/browser/api/atom_api_content_tracing.cc [hunk 2]
```diff
@@ -24,14 +25,22 @@ struct Converter<base::trace_event::TraceConfig> {
...
+      std::string category_filter, trace_options;
+      if (options.Get("categoryFilter", &category_filter) &&
+          options.Get("traceOptions", &trace_options)) {
+        *out = base::trace_event::TraceConfig(category_filter, trace_options);
+        return true;
+      }
+    }
+
+    base::DictionaryValue memory_dump_config;
+    if (ConvertFromV8(isolate, val, &memory_dump_config)) {
```
Comment (nornagon) [inline atom/browser/api/atom_api_content_tracing.cc]: should this come before the dictionary version?

**Comment by alexeykuzmin** [comment]
> needs a test.

Yeah. That's why two checkboxes in the description are left unchecked, and the `wip` label is there =)

File: docs/api/content-tracing.md [hunk 3]
```diff
@@ -52,8 +52,6 @@ Once all child processes have acknowledged the `getCategories` request the
 ### `contentTracing.startRecording(options, callback)`
 
 * `options` Object
-  * `categoryFilter` String
-  * `traceOptions` String
```
Comment (alexeykuzmin) [inline docs/api/content-tracing.md]: @MarshallOfSound How properly reflect the the docs the fact that the `options` Object can have two different formats?
First format is `{categoryFilter: "...", traceOptions: "..."}`, another one something like
```js
{
  "startup_duration": 4,
  "result_file": "/tmp/trace.json",
  "trace_config": {
    "included_categories": ["disabled-by-default-memory-infra"],
    "excluded_categories": ["*"],
    "memory_dump_config": {
      "triggers": [
        { "mode": "light", "periodic_interval_ms": 50 },
        { "mode": "detailed", "periodic_interval_ms": 1000 }
      ]
    }
  }
}
```

File: docs/api/content-tracing.md [hunk 4]
```diff
@@ -51,9 +51,7 @@ Once all child processes have acknowledged the `getCategories` request the
 
 ### `contentTracing.startRecording(options, callback)`
 
-* `options` Object
-  * `categoryFilter` String
-  * `traceOptions` String
+* `options` ([TraceCategoriesAndOptions](structures/trace-categories-and-options.md) | [TraceConfig](structures/trace-config.md))
```
Comment (alexeykuzmin) [inline docs/api/content-tracing.md]: @MarshallOfSound Can it work like this?

File: atom/browser/api/atom_api_content_tracing.cc (hunk 2 above)
Comment (alexeykuzmin) [reply atom/browser/api/atom_api_content_tracing.cc]: @nornagon Can you take a look again?

**Comment by codebytere** [comment]
@alexeykuzmin it's erroring here: https://github.com/electron/electron-typescript-definitions/blob/master/test-smoke/electron/test/main.ts#L465; you'll need to update that test to correspond to the new parameters and structures introduced in this PR

File: spec/api-content-tracing-spec.js [hunk 5]
```diff
@@ -0,0 +1,140 @@
...
+
+      expect(fs.existsSync(outputFilePath)).to.be.true()
+
+      const fileSizeInKiloBytes = getFileSizeInKiloBytes(outputFilePath)
+      expect(fileSizeInKiloBytes).to.be.above(0,
+        `the trace output file is empty, check "${outputFilePath}"`)
+    })
+
+    it('accepts a trace config', async () => {
+      // XXX(alexeykuzmin): All categories are excluded on purpose,
```
Comment (nornagon) [inline spec/api-content-tracing-spec.js]:
```suggestion
      // NOTE(alexeykuzmin): All categories are excluded on purpose,
```

File: spec/api-content-tracing-spec.js [hunk 6]
```diff
@@ -0,0 +1,140 @@
...
+
+      expect(fileSizeInKiloBytes).to.be.above(0,
+        `the trace output file is empty, check "${outputFilePath}"`)
+      expect(fileSizeInKiloBytes).to.be.below(expectedMaximumFileSize,
+        `the trace output file is suspiciously large (${fileSizeInKiloBytes}KB),
+        check "${outputFilePath}"`)
+    })
+
+    it('accepts "categoryFilter" and "traceOptions" as a config', async () => {
+      // XXX(alexeykuzmin): All categories are excluded on purpose,
```
Comment (nornagon) [inline spec/api-content-tracing-spec.js]:
```suggestion
      // NOTE(alexeykuzmin): All categories are excluded on purpose,
```

File: docs/api/content-tracing.md (hunk 3 above)
Comment (nornagon) [reply docs/api/content-tracing.md]: It's a little 😬 that one of these formats uses `camelCase` and the other uses `snake_case`. Is it worth converting one of them?

Comment (alexeykuzmin) [reply docs/api/content-tracing.md]: @nornagon the `{categoryFilter: "...", traceOptions: "..."}` variant is the only currently available, I don't want to break existing code.
The other one is a Chromium thing, and I don't want to overcomplicate it by adding format converting logic.

**Comment by alexeykuzmin** [comment]
Can anyone from the @electron/docs team review it please?

File: docs/api/structures/trace-categories-and-options.md [hunk 7]
```diff
@@ -0,0 +1,18 @@
+# TraceCategoriesAndOptions Object
+
+* `categoryFilter` String – is a filter to control what category groups
```
Comment (codebytere) [inline docs/api/structures/trace-categories-and-options.md]: nit: can just be 
`categoryFilter` String – a filter

Comment (alexeykuzmin) [reply docs/api/structures/trace-categories-and-options.md]: I just copied it from the old docs.

File: docs/api/structures/trace-categories-and-options.md [hunk 8]
```diff
@@ -0,0 +1,18 @@
...
+  should be traced. A filter can have an optional `-` prefix to exclude
+  category groups that contain a matching category. Having both included
+  and excluded category patterns in the same list is not supported. Examples:
+  `test_MyTest*`, `test_MyTest*,test_OtherStuff`, `-excluded_category1,-excluded_category2`.
+* `traceOptions` String - Controls what kind of tracing is enabled,
+  it is a comma-delimited sequence of the following strings:
+  `record-until-full`, `record-continuously`, `trace-to-console`, `enable-sampling`, `enable-systrace`,
```
Comment (nornagon) [inline docs/api/structures/trace-categories-and-options.md]: i went looking, and fwiw i don't think `enable-sampling` and `enable-systrace` actually do anything in latest chromium.

File: docs/api/structures/trace-categories-and-options.md [hunk 9]
```diff
@@ -0,0 +1,18 @@
...
+  e.g. `'record-until-full,enable-sampling'`.
+  The first 3 options are trace recording modes and hence mutually exclusive.
+  If more than one trace recording modes appear in the `traceOptions` string,
+  the last one takes precedence. If none of the trace recording modes are
+  specified, recording mode is `record-until-full`.
+  The trace option will first be reset to the default option (`record_mode` set
+  to `record-until-full`, `enable_sampling` and `enable_systrace`
```
Comment (nornagon) [inline docs/api/structures/trace-categories-and-options.md]: is it `enable-sampling` or `enable_sampling`?

Perhaps we should just link to https://paulirish.github.io/debugger-protocol-viewer/tot/Tracing/#type-TraceConfig or similar?

File: spec/api-content-tracing-spec.js [hunk 10]
```diff
@@ -0,0 +1,145 @@
...
+const dirtyChai = require('dirty-chai')
+const fs = require('fs')
+const path = require('path')
+
+const { expect } = chai
+const { app, contentTracing } = remote
+
+chai.use(dirtyChai)
+
+const timeout = async (milliseconds) => {
```
Comment (nornagon) [inline spec/api-content-tracing-spec.js]: no need for `async` here

**Comment by alexeykuzmin** [comment]
> LGTM but 4.0.0 is frozen and this isn't a blocker, so let's track this for 4.0.1

Ok, but I'll create a PR anyway. We'll merge it after the stable release then.
