### PR TITLE
Remove the race condition between new process creation and context release

### LINKED ISSUE #12316: Error: Cannot get property 'id' on missing remote object
* Electron version: 2.0.0-beta.4
* Operating system: macOS 10.13.3

### Expected behavior

A reload of the window works.

### Actual behavior

A reload of the window does not work.

### How to reproduce

* run VSCode exploration ([download](https://az764295.vo.msecnd.net/exploration/6bc3274250cc949c7fb1d654cbb6e59c8ddad697/VSCode-darwin-exploration.zip))
* run "Reload Window" command
* sometimes I see the window stay blank after doing so and checking the console I see:

```
Uncaught (in promise) Error: Cannot get property 'id' on missing remote object 3
Error: Cannot get property 'id' on missing remote object 3
    at throwRPCError (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/browser/rpc-server.js:384:7)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at WebContents.<anonymous> (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at throwRPCError (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/browser/rpc-server.js:384:7)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at WebContents.<anonymous> (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/renderer/api/remote.js:209:30)
    at metaToValue (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/renderer/api/remote.js:213:28)
    at Object.descriptor.get [as id] (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/renderer/api/remote.js:132:16)
    at file:///Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js:11:97
    at new Promise (<anonymous>)
    at file:///Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js:10:838
```

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Previously there was a race condition where the getId() method would return the new context ID even
though the release was for the old context.  This changes it to send the "initial" context ID with
the release message to ensure there is no race.

Fixes #12316

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
I looked into adding a test for this but I couldn't make an initially failing test 100% of the time (it's a seemingly random 50/50~ish race condition) so a test wouldn't really help for this 😢

**Comment by MarshallOfSound** [comment]
I have zero clue why the builds are failing, cleaned locally and ran from scratch and everything is 🆗

**Comment by MarshallOfSound** [comment]
> but instead of using the command line mechanism this can be hooked into the render process preferences api.

Afaics that preferences API is used across **all** web contents instead of targeting specific ones 🤔  Can we merge this and potentially clean up / move somewhere else later?

File: atom/browser/atom_browser_client.cc [hunk 1]
```diff
@@ -322,6 +323,11 @@ void AtomBrowserClient::AppendExtraCommandLineSwitches(
         web_contents, command_line);
     SessionPreferences::AppendExtraCommandLineSwitches(
         web_contents->GetBrowserContext(), command_line);
+
+    auto context_id = atom::api::WebContents::GetIDForContents(
+      web_contents);
+    command_line->AppendSwitchASCII(switches::kContextId,
+      base::IntToString(context_id));
```
Comment (sethlu) [inline atom/browser/atom_browser_client.cc]: @MarshallOfSound here we should use `base::Int64ToString`, which should fix half of the problem in https://github.com/electron/electron/issues/8205.

`atom::api::WebContents::GetIDForContents` returns `int64_t`, I'm not very sure why the compiler didn't warn about this typing thing.

Comment (MarshallOfSound) [reply atom/browser/atom_browser_client.cc]: @sethlu good find

Comment (sethlu) [reply atom/browser/atom_browser_client.cc]: 🤔 Prolly `auto context_id` was interpreted as `int64_t`!?

File: atom/browser/atom_browser_client.cc [hunk 2]
```diff
@@ -322,6 +323,11 @@ void AtomBrowserClient::AppendExtraCommandLineSwitches(
         web_contents, command_line);
     SessionPreferences::AppendExtraCommandLineSwitches(
         web_contents->GetBrowserContext(), command_line);
+
+    auto context_id = atom::api::WebContents::GetIDForContents(
+      web_contents);
```
Comment (alexeykuzmin) [inline atom/browser/atom_browser_client.cc]: Indentation here doesn't look right.
Did `clang-format` throw any warnings?

Comment (MarshallOfSound) [reply atom/browser/atom_browser_client.cc]: @alexeykuzmin I think this was before clang-format was introduced
