### PR TITLE
Fix child touch bar items not updating

### LINKED ISSUE #11761: `TouchBarButton` doesn't update when inside a `TouchBarGroup`
* Electron version: v1.7.11
* Operating system: macOS

### Expected behavior

Changing `TouchBarButton` properties should immediately update the button on the touch bar.

### Actual behavior

Changing `TouchBarButton` properties has no effect when the `TouchBarButton` is inside a `TouchBarGroup`.

### How to reproduce

```js
const updatingButton = new TouchBarButton({'label': 'change'});
setInterval(() => updatingButton.label = '' + Math.random(), 1000);

// Button label updates every second
const touchBar = new TouchBar([updatingButton]);

// Button label never updates
const touchBar = new TouchBar([new TouchBarGroup({items: [updatingButton]})]);

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Deep children of a TouchBar didn't cause the top level touch bar to update, now they do

Fixes #11761.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
This PR also explicitly marks some properties we set on TouchBarItem's to be immutable (will throw an error if you try to set them) this is just to stop users breaking things 👍

File: lib/browser/api/touch-bar.js [hunk 1]
```diff
@@ -135,7 +135,21 @@ class TouchBar extends EventEmitter {
...
+    this._addImmutableProperty('id', `${nextItemID++}`)
+    this._parents = []
+  }
+
+  _addImmutableProperty (name, value) {
+    Object.defineProperty(this, name, {
+      get: function () {
+        return value
+      },
+      set: function (newValue) {
```
Comment (alexeykuzmin) [inline lib/browser/api/touch-bar.js]: `newValue` is unused.
