### PR TITLE
fix: normalize path before calling `showItemInFolder` and `openPath`

### LINKED ISSUE #11617: shell.showItemInFolder won't open Explorer if forward slashes are present in path
* Electron version: 1.7.10
* Operating system: Windows 10, build 1709

If a path contains forward slash(es) on Windows (e.g. `C:\some\app/index.html`), ~~showItemInFolder will open the containing directory but will not select the file.~~ In Electron 8.x and newer, showItemInFolder will not open an Explorer window at all if forward slashes are present in path.

### How to reproduce

https://github.com/YellowAfterlife/abug-electron-showItemInFolder-forward-slashes
```js
const electron = require('electron')
const app = electron.app
const path = require('path')
app.on('ready', () => {
	let test = path.join(__dirname, 'index.html')
	test = test.replace(/^(.+)\\(.+)$/, "$1/$2") // simulate a forward slash in path
	console.log(test)
	console.log(electron.shell.showItemInFolder(test))
	app.quit()
})
```

From what I've seen, no other shell functions show this kind of "partial success" behaviour while returning `true`.

### PR DESCRIPTION
**Pull request by piotrpdev**
#### Description of Change

Resolves #11617, e.g. before Windows Explorer wouldn't open when calling `shell.showItemInFolder(fullPath)` with a path that contains forward slashes. This PR makes the change of first normalizing the path that was passed in using `NormalizePathSeparators()`.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed `shell.showItemInFolder` not opening Windows Explorer if the passed path contains forward slashes

### CODE REVIEW

**Comment by piotrpdev** [comment]
Not sure why this Mac test is the only one that's failing; it doesn't seem relevant to me.

https://github.com/electron/electron/blob/7609156ae176cf0308c38ded42eb0cee9b502882/spec/webview-spec.ts#L2110-L2142

**Comment by piotrpdev** [comment]
Not sure who to ask for review on this (maybe @codebytere?), very small change anyway.

File: shell/common/api/electron_api_shell.cc [hunk 1]
```diff
@@ -71,6 +71,12 @@ v8::Local<v8::Promise> OpenExternal(const GURL& url, gin::Arguments* args) {
   return handle;
 }
 
+void ShowItemInFolder(const base::FilePath& full_path) {
```
Comment (codebytere) [inline shell/common/api/electron_api_shell.cc:74]: it looks like this function [upstream](https://source.chromium.org/gn/gn/+/main:src/base/files/file_path.h;l=353?q=NormalizePathSeparators&sq=package:chromium&type=cs) does nothing on POSIX systems, so instead of adding this extra functionality here, let's instead call it directly [where relevant](https://github.com/electron/electron/blob/04b2ba84cd9c1c883498e0cee8492c4bb59088ec/shell/common/platform_util_win.cc#L335):

```diff
diff --git a/shell/common/platform_util_win.cc b/shell/common/platform_util_win.cc
index a2deae69bf..38bf94ab2e 100644
--- a/shell/common/platform_util_win.cc
+++ b/shell/common/platform_util_win.cc
@@ -336,7 +336,7 @@ void ShowItemInFolder(const base::FilePath& full_path) {
   base::ThreadPool::CreateCOMSTATaskRunner(
       {base::MayBlock(), base::TaskPriority::USER_BLOCKING})
       ->PostTask(FROM_HERE,
-                 base::BindOnce(&ShowItemInFolderOnWorkerThread, full_path));
+                 base::BindOnce(&ShowItemInFolderOnWorkerThread, full_path.NormalizePathSeparators()));
 }
 
 void OpenPath(const base::FilePath& full_path, OpenCallback callback) {
```

**Review by codebytere — CHANGES_REQUESTED** [review]
Thanks for working on this! It also looks like `shell.openPath` might be subject to the same issue [in the Windows impl](https://github.com/electron/electron/blob/04b2ba84cd9c1c883498e0cee8492c4bb59088ec/shell/common/platform_util_win.cc#L342-L350)? We should address that here as well if that's the case.

**Review by jkleinsc — APPROVED** [review]
