### PR TITLE
fix: in GTK open dialog, do not preview huge files

### LINKED ISSUE #31630: [Bug]: Image preview during dialog.showOpenDialog() crashes app on large image files
### Electron Version

13.0.0

### Operating System Version

Ubuntu 18.04

### Last Known Working Electron version

None

### Expected Behavior

Asking user to choose an image through a dialog:
```
try {
  const response = await dialog.showOpenDialog({
    buttonLabel: "Choose an image",
    defaultPath: app.getPath("desktop"),
    properties: ["openFile"],
  });
  if (!response.canceled) {
    const srcImgPath = response.filePaths[0];
  }
} catch (err) {
  console.error(err);
}
```
In the dialog, if the user chooses an image file, a preview of said image will be shown.

Expected behavior: `srcImgPath` contains the path to the file that the user chose.

### Actual Behavior

When user chooses an image file that has the size > 1Gb, the program crashes with the following error:

`tcmalloc: large alloc 1073741824 bytes == 0x12874fac2000 @  0x555c486f6e35 0x7ff5a81a76cf`

This is because the file is too big to be previewed. Electron currently does not offer a way to turn off this preview feature, or at least limit the size of files that can be previewed.

### Additional Information

Related issue: https://github.com/electron/electron/issues/8875
Related SO question: https://stackoverflow.com/questions/67954227/disable-image-preview-in-dialog-box

### PR DESCRIPTION
**Pull request by ckerr**
#### Description of Change

Fixes #31630.

Adds a size check to the image file before previewing it. I've set the cutoff at 100 MB since "100 MB ought to be enough for anybody" but if there's a strong use case for previewing 100 MB image files we could increase it.

CC @codebytere 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed crash in GTK open dialog when trying to preview huge image files.

### CODE REVIEW

File: shell/browser/ui/file_dialog_gtk.cc [hunk 1]
```diff
@@ -369,6 +369,24 @@ void FileChooserDialog::AddFilters(const Filters& filters) {
...
+  if (!S_ISREG(st.st_mode)) {
+    return false;
+  }
+
+  // Don't preview huge files; they may crash.
+  // https://github.com/electron/electron/issues/31630
+  // Setting an arbitrary filesize max t at 100 MB here.
+  constexpr off_t ArbitraryMax = 100000000ULL;
+  if (st.st_size >= ArbitraryMax) {
+    return false;
```
Comment (codebytere) [inline shell/browser/ui/file_dialog_gtk.cc:384]: tiny nit but we can probably just
```
return st.st_size < ArbitraryMax;
```
here!

**Review by codebytere — APPROVED** [review]

File: shell/browser/ui/file_dialog_gtk.cc (hunk 1 above)
Comment (ckerr) [reply shell/browser/ui/file_dialog_gtk.cc]: SGTM. 957804830ea4b1857dbc65e7e9f969008abdea16

**Review by zcbenz — APPROVED** [review]
