### PR TITLE
fix: draggable regions on MAS

### LINKED ISSUE #37414: [Bug]: Frameless window is not draggable when running MAS build
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.1

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

22.3.1

### Expected Behavior

Window should be draggable.

### Actual Behavior

Window is not draggable.

### Testcase Gist URL

https://gist.github.com/1387d3e19cbf2717cd21bbf3befaf159

### Additional Information

To be noted, dragging works as expected on standard Electron builds but consistently fails when using Mac Apple Store builds (>= v23).

@nornagon I understand you've been working on some related issues recently, please let me know if this is a known/fixed issue and I'll close this one, thanks!

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change

This makes draggable regions work on MAS builds again, after they broke in
https://github.com/electron/electron/pull/35603.

The [mas_disable_custom_window_frame.patch](https://github.com/electron/electron/blob/main/patches/chromium/mas_disable_custom_window_frame.patch) patch prevents the Chrome custom frame from being used on MAS, but the new draggable regions impl on macOS requires it, so we need to find another way of getting this behavior without tripping the MAS guards.

Fixes #37414.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed draggable regions not working in Mac App Store builds.

### CODE REVIEW

**Review by VerteDinde — APPROVED** [review]

File: shell/browser/ui/cocoa/electron_ns_window.mm [hunk 1]
```diff
@@ -19,8 +22,65 @@
 
 @interface NSWindow (PrivateAPI)
 - (NSImage*)_cornerMask;
+- (long long)_resizeDirectionForMouseLocation:(CGPoint)location;
```
Comment (VerteDinde) [inline shell/browser/ui/cocoa/electron_ns_window.mm:25]: Actually, sorry, it looks like lint is mad about this typing:
```
(cpplint) Use int16/int64/etc, rather than the C type long
```

Comment (nornagon) [reply shell/browser/ui/cocoa/electron_ns_window.mm:25]: it's very funny to me that _that_ is what the linter complains about in this change :D

File: shell/browser/ui/cocoa/electron_ns_window.mm [hunk 2]
```diff
@@ -36,6 +96,37 @@ - (id)initWithShell:(electron::NativeWindowMac*)shell
...
+    // This is only necessary on MAS where we can't directly refer to
+    // NSNextStepFrame or NSThemeFrame, as they are private APIs.
+    // See components/remote_cocoa/app_shim/native_widget_mac_nswindow.mm for
+    // the non-MAS-compatible way of doing this.
+    if (styleMask & NSWindowStyleMaskTitled) {
+      if (!g_nsthemeframe_mousedown) {
+        NSView* theme_frame = [[self contentView] superview];
+        DCHECK(strcmp(class_getName([theme_frame class]), "NSThemeFrame") == 0)
+            << "Expected NSThemeFrame but was "
+            << class_getName([theme_frame class]);
```
Comment (MarshallOfSound) [inline shell/browser/ui/cocoa/electron_ns_window.mm:112]: Can we not use `DCHECK_EQ` here? Should do the messaging for us

**Review by MarshallOfSound — APPROVED** [review]
Terrifying, I love it.  One non-blocking nit on the dcheck

File: shell/browser/ui/cocoa/electron_ns_window.mm (hunk 2 above)
Comment (nornagon) [reply shell/browser/ui/cocoa/electron_ns_window.mm:112]: Nope, DCHECK_EQ on `const char*` compares pointer values, which are not equal.
