### PR TITLE
Parent's visibility trumps inherited 'show' option

### LINKED ISSUE #12125: Bug: 2.0.0-beta.1 window.open(…) not showing when called from new BrowserWindow({show: false}).show()
* Electron version: 2.0.0-beta.1
* Operating system: macOS High 10.13.3 (17D102)

### Expected behavior

When creating a BrowserWindow:

```js
  browserWindow = new BrowserWindow({ show: false });
  browserWindow.once('ready-to-show', () => browserWindow.show());
```

Which show the following:

```html
  <button onclick="() => window.open('…', 'custom-target')">Open</button>
```

Clicking the button should open a "shown" window, regardless of the `show` parameter passed when creating the initial browserWindow.

### Actual behavior

What happens is that the window opens but is not visible.

If instead we modified `main.js` as follows:

```js
  browserWindow = new BrowserWindow();
  browserWindow.hide(); // dynamically hide instead
  browserWindow.once('ready-to-show', () => browserWindow.show());
```

Then the child window created by `window.open(…)` opens and is shown as expected.

### How to reproduce

This is a straightforward scenario:

**main.js**
```js
browserWindow = new BrowserWindow({
  // Disable this in test b
  show: false,
});

// Disable this in test a
browserWindow.hide();

browserWindow.loadURL(`file://${__dirname}/index.html`)

browserWindow.once('ready-to-show', () => browserWindow.show());
```

**index.html**
```html
<script>
  window.open('chrome://gpu', 'chrome-gpu');
</script>
```

But let me know if you can't reproduce it.

### PR DESCRIPTION
**Pull request by ckerr**
The fix works but needs a spec.

Fixes #12125.

### CODE REVIEW

File: lib/browser/guest-window-manager.js [hunk 1]
```diff
@@ -47,8 +47,19 @@ const mergeBrowserWindowOptions = function (embedder, options) {
     options.webPreferences = {}
   }
   if (embedder.browserWindowOptions != null) {
+    let parentOptions = {...embedder.browserWindowOptions}
```
Comment (MarshallOfSound) [inline lib/browser/guest-window-manager.js]: /nit we'll be cloning the object needlessly 99% of the time here, maybe `let parentOptions = embedder.browserWindowOptions` and then spread it inside the `if` below

File: spec/chromium-spec.js [hunk 2]
```diff
@@ -223,6 +223,26 @@ describe('chromium feature', () => {
       b = window.open(`file://${fixtures}/pages/window-open-size.html`, '', 'show=no')
     })
 
+    for (const show in [true, false]) {
+      it(`inherits parent visibility over parent {show=${show}} option`, (done) => {
+        let w = new BrowserWindow({show: show})
+
+        // toggle visibility
+        if (show) {
```
Comment (codebytere) [inline spec/chromium-spec.js]: (nit) for something this short, maybe use a ternary?

Comment (ckerr) [reply spec/chromium-spec.js]: Tried it that way and wound up in an ad-hoc bikeshed session with Sam and Alexey with more opinions than people. Let's leave it as-is.

Comment (codebytere) [reply spec/chromium-spec.js]: sounds good to me 😁 already approved, ready whenever!

File: spec/chromium-spec.js [hunk 3]
```diff
@@ -223,6 +223,26 @@ describe('chromium feature', () => {
       b = window.open(`file://${fixtures}/pages/window-open-size.html`, '', 'show=no')
     })
 
+    for (const show in [true, false]) {
+      it(`inherits parent visibility over parent {show=${show}} option`, (done) => {
+        let w = new BrowserWindow({show: show})
```
Comment (alexeykuzmin) [inline spec/chromium-spec.js]:
```js
const w = new BrowserWindow({show})

File: lib/browser/guest-window-manager.js [hunk 4]
```diff
@@ -47,8 +47,19 @@ const mergeBrowserWindowOptions = function (embedder, options) {
     options.webPreferences = {}
   }
   if (embedder.browserWindowOptions != null) {
+    let parentOptions = embedder.browserWindowOptions
+
+    // if parent's visibility is available, that overrides 'show' flag (#12125)
+    const win = BrowserWindow.fromWebContents(embedder.webContents)
+    if (win != null) {
+      const show = win.isVisible()
+      if (typeof show === 'boolean') {
```
Comment (alexeykuzmin) [inline lib/browser/guest-window-manager.js]: The docs say that `isVisible()` always returns a boolean
https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winisvisible

Comment (MarshallOfSound) [reply lib/browser/guest-window-manager.js]: Yeah didn't really query this, but looking at it, it can only ever be true/false right?

File: spec/chromium-spec.js (hunk 3 above)
Comment (MarshallOfSound) [reply spec/chromium-spec.js]: technically the `let` shouldn't be here, but `w` is declared slightly higher as a `let` so we can't make it const here 👍

Comment (alexeykuzmin) [reply spec/chromium-spec.js]: I think you can. You just declare a new variable that simply shadows the one declared above it.

File: spec/chromium-spec.js [hunk 5]
```diff
@@ -223,6 +223,26 @@ describe('chromium feature', () => {
       b = window.open(`file://${fixtures}/pages/window-open-size.html`, '', 'show=no')
     })
 
+    for (const show in [true, false]) {
```
Comment (alexeykuzmin) [inline spec/chromium-spec.js]:
```js
for (const show of [true, false])
```

`of` iterates over array entries (kinda), `in` over an object properties.

Comment (MarshallOfSound) [reply spec/chromium-spec.js]: Lol, I love how this works regardless though, because `0` is falsey and `1` is truthy 😆

Comment (alexeykuzmin) [reply spec/chromium-spec.js]: shia_lebeouf_magic.gif

**Comment by ckerr** [comment]
Armed with only the help of three other highly-paid engineers of @codebytere, @MarshallOfSound, and @alexeykuzmin  I was able to write two paragraphs of ES6 Electron code today. :2nd_place_medal: 

In all seriousness: even though this PR is trivial I appreciate the feedback on writing more idiomatic ES6.  Thanks for the reviews. :+1:

**Comment by MarshallOfSound** [comment]
ignore

**Comment by MarshallOfSound** [comment]
test
