### PR TITLE
Fix crash when opening devtools for frameless window

### LINKED ISSUE #13628: Electron crash during open DevTools on MacOS (v3.0.0-beta.2)
* Electron Version: v3.0.0-beta.2
* Operating System (Platform and Version): macOS 10.13.5
* Last known working Electron version: v3.0.0-beta.1

**Expected Behavior**
Launching DevTools

**Actual behavior**
Electron crash with current dump:
```
Crashing on exception: *** -[__NSArrayM objectAtIndex:]: index 1 beyond bounds [0 .. 0]

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff489d332b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fff6fb41c76 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff48a14634 _CFThrowFormattedException + 202
3   CoreFoundation                      0x00007fff488f2290 __CFStringDecodeByteStream3 + 0
4   Electron Framework                  0x000000010e7554c2 _ZN9brightray8IOThread7CleanUpEv + 2210
...
```

**Additional info** 
`BrowserWindow` should contain `titleBarStyle` with `hiddenInset` value.

Full dump attached to [link](https://github.com/electron/electron/files/2185677/dump.txt)

### PR DESCRIPTION
**Pull request by zcbenz**
Close  #13628.
This PR fixes the crash caused by #13599 when opening devtools for frameless window.

### CODE REVIEW

File: spec/api-browser-window-spec.js [hunk 1]
```diff
@@ -839,6 +839,14 @@ describe('BrowserWindow module', () => {
     })
   })
 
+  describe('BrowserWindow.openDevTools()', () => {
+    it('does not crash for frameless window', () => {
+      w.destroy()
+      w = new BrowserWindow({ show: false })
```
Comment (nornagon) [inline spec/api-browser-window-spec.js]: hm... this test doesn't actually open a frameless window. should this be `frame: false`?

Comment (zcbenz) [reply spec/api-browser-window-spec.js]: yeah, I forgot to add `frame: false`.
