### PR TITLE
fix: correctly support the webkitdirectory input attr

### LINKED ISSUE #839: full support for multiple webkitdirectory
<input> file . multiple webkitdirectory in chrome can get sub files.but atom-shell can select directory,sub file set only current directory? is bug?

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #839

The implementation here was loosely inspired by the implementation in
`//chrome` found in their FileSelectHelper.  I.e. That's where the usage
of `net::DirectoryList` comes from.

Refs: https://cs.chromium.org/chromium/src/chrome/browser/file_select_helper.cc

Notes: Fixed support for the `webkitdirectory` attribute on `input[type=file]` elements

### CODE REVIEW

**Comment by codebytere** [comment]
Do we also want this to target `5-0-x`? This could be perceived as a fix or a feature, depending on strictness of evaluation 🤔

**Comment by zcbenz** [comment]
If an app is using the `webkitdirectory` attribute then it is currently relying on the old buggy behavior and will likely break with this change, so I think we should at least bump the minor version for it, and it may even belong to the breaking changes.

**Comment by MarshallOfSound** [comment]
> then it is currently relying on the old buggy behavior and will likely break with this change

I'm firmly in the camp of "if you're relying on broken, non-spec behavior then when it's fixed that's on you to deal with".  But will defer to @codebytere / @electron/wg-releases on this one 👍

File: atom/browser/web_dialog_helper.cc [hunk 1]
```diff
@@ -216,6 +258,30 @@ file_dialog::Filters GetFileTypesFromAcceptType(
...
+    const net::DirectoryLister::DirectoryListerData& data) {
+  // We don't want to return directory paths, only file paths
+  if (data.info.IsDirectory())
+    return;
+
+  paths_.push_back(data.path);
+}
+void DirectoryListerHelper::OnListDone(int error) {
+  std::vector<FileChooserFileInfoPtr> file_info;
+  for (auto path : paths_)
```
Comment (deepak1556) [inline atom/browser/web_dialog_helper.cc]: Why copy ? could have taken references.

File: atom/browser/web_dialog_helper.cc [hunk 2]
```diff
@@ -71,23 +72,61 @@ class FileSelectHelper : public base::RefCounted<FileSelectHelper>,
...
+    Release();
+  }
+
  private:
   friend class base::RefCounted<FileSelectHelper>;
 
   ~FileSelectHelper() override {}
 
+  void EnumerateDirectory(base::FilePath base_dir) {
+    auto* lister = new net::DirectoryLister(
```
Comment (deepak1556) [inline atom/browser/web_dialog_helper.cc]: Whats the lifetime of the `lister` ? I don't see it being destroyed.

File: atom/browser/web_dialog_helper.cc [hunk 3]
```diff
@@ -71,23 +72,61 @@ class FileSelectHelper : public base::RefCounted<FileSelectHelper>,
...
-          file_info.push_back(FileChooserFileInfo::NewNativeFile(
-              blink::mojom::NativeFileInfo::New(
-                  path, path.BaseName().AsUTF16Unsafe())));
+        // If we are uploading a folder we need to enumerate its contents
+        if (mode_ == FileChooserParams::Mode::kUploadFolder &&
+            paths.size() >= 1) {
+          base_dir = paths[0];
+
+          // Actually enumerate soemwhere off-thread
+          base::SequencedTaskRunnerHandle::Get()->PostTask(
```
Comment (deepak1556) [inline atom/browser/web_dialog_helper.cc]: This doesn't mean off-thread, it will be a task that runs on the same sequence as where its called but will be guaranteed to run in a defined order. Prefer `base::PostTaskWithTraits`.

**Comment by jkleinsc** [comment]
Per discussion with @electron/wg-releases it was decided to not backport this to 5-0-x

**Comment by mklnz** [comment]
So previously I was able to get the path of the directory selected. However with the "fixed" version I'm only able to get a list of files within that directory, how to get the directory path if there are no files inside said directory since the target.files array is empty?

**Comment by maayanalbert** [comment]
I'm using npm as my package manager and my version of electron doesn't seem to contain this fix (I'm on 6.0.11). How can I access this fix? Thanks!

**Comment by maayanalbert** [comment]
Thanks @MarshallOfSound for the fix! I'm using npm as my package manager and my version of electron doesn't seem to contain these changes (I'm on 6.0.11). Is there I way I can access this via npm? Thanks!

**Comment by maayanalbert** [comment]
Oops just had to do `npm i -D electron@latest`, lols
