### PR TITLE
Propagate referrer to new windows

### LINKED ISSUE #9205: No setting referrer when clicking on an anchor with target='_blank'
* Electron version: 1.6.2
* Operating system: Windows 7

### Expected behavior

Click on a link with `target=_blank` attribute should open a new browser window and open the clicked url with referrer header set to the original window's url.

### Actual behavior

No referrer header is sent with request on created browser window

### How to reproduce
Put this in any public or local domain
index.php
```
  <a href='/' target='_blank'>Link</a>
  <pre><?php print_r(getallheaders()); ?></pre>

```

### PR DESCRIPTION
**Pull request by nornagon**
Fixes #9205

There are a couple of things I'm unsure about with this PR still, but pushing to get some feedback.

1. The LoadURL API doesn't have a place to pass a referrer policy through, so I'm discarding that information. That feels wrong; I suspect it's worth updating the API to accept a referrer policy in addition to the referrer URL. If not, and the URL is all the info we need, then I should update the places that convert a `content::Referrer` to V8 to just encode the URL instead of the URL + policy.
2. Passing `{ url: '', policy: 2 }` feels like a bit of a hack in the places that don't have a clear referrer (e.g. `new BrowserWindow`). `null` should probably be interpreted as 'no referrer'.
3. I feel like I might have accidentally broken a public API without realising it (what's the difference between `new-window` and `-new-window`? Nothing seems to listen to the former, but I added an argument to its call site)

### CODE REVIEW

File: atom/browser/api/atom_api_web_contents.cc [hunk 1]
```diff
@@ -527,12 +527,14 @@ bool WebContents::DidAddMessageToConsole(content::WebContents* source,
...
 void WebContents::OnCreateWindow(
     const GURL& target_url,
+    const content::Referrer& referrer,
     const std::string& frame_name,
     WindowOpenDisposition disposition,
     const std::vector<std::string>& features,
     const scoped_refptr<content::ResourceRequestBody>& body) {
   if (type_ == BROWSER_WINDOW || type_ == OFF_SCREEN)
-    Emit("-new-window", target_url, frame_name, disposition, features, body);
+    Emit("-new-window", target_url, referrer, frame_name, disposition, features,
```
Comment (MarshallOfSound) [inline atom/browser/api/atom_api_web_contents.cc]: Although it's not technically public API, we can try to not break people using it _for whatever reason_.

Just making this new `referrer` arg the last arg in the list should make this 🆗

**Comment by deepak1556** [comment]
LGTM in general.

> The LoadURL API doesn't have a place to pass a referrer policy through, so I'm discarding that information. That feels wrong; I suspect it's worth updating the API to accept a referrer policy in addition to the referrer URL. If not, and the URL is all the info we need, then I should update the places that convert a content::Referrer to V8 to just encode the URL instead of the URL + policy.

I am good with adding the referrer policy option to loadURL, but the default policy should serve the purpose for users. Adding this option expects users to know details about the different policies and use them correctly. It would be sufficient to encode the url with default policy for resolving this issue.

> I feel like I might have accidentally broken a public API without realising it (what's the difference between new-window and -new-window? Nothing seems to listen to the former, but I added an argument to its call site)


`-new-window` is used internally to intercept calls to `window.open` and create windows with our implementation of `window.open` in the default non-sandboxed mode. I would suggest following @MarshallOfSound advice regarding the argument position for not breaking the api.

**Comment by nornagon** [comment]
`httpReferrer` now accepts either a string URL referrer, with which it will use the default referrer policy, or an object of the form `{ url: "<url>", policy: <policy> }`, where `<policy>` is one of `"default"|"unsafe-url"|"no-referrer-when-downgrade"|"no-referrer"|"origin"|"strict-origin-when-cross-origin"|"same-origin"|"strict-origin"` (matching the [Referrer-Policy spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)).

File: lib/browser/guest-window-manager.js [hunk 2]
```diff
@@ -242,13 +244,14 @@ ipcMain.on('ELECTRON_GUEST_WINDOW_MANAGER_WINDOW_OPEN', (event, url, frameName,
...
 })
 
 // Routed window.open messages with fully parsed options
-ipcMain.on('ELECTRON_GUEST_WINDOW_MANAGER_INTERNAL_WINDOW_OPEN', function (event, url, frameName,
-                                                                  disposition, options,
+ipcMain.on('ELECTRON_GUEST_WINDOW_MANAGER_INTERNAL_WINDOW_OPEN', function (event, url, referrer,
+                                                                  frameName, disposition, options,
                                                                   additionalFeatures, postData) {
   options = mergeBrowserWindowOptions(event.sender, options)
   event.sender.emit('new-window', event, url, frameName, disposition, options, additionalFeatures)
```
Comment (deepak1556) [inline lib/browser/guest-window-manager.js]: `referrer` should be provided here and documented in `new-window` event options.

File: spec/api-web-contents-spec.js [hunk 3]
```diff
@@ -708,4 +708,50 @@ describe('webContents module', () => {
...
+          })
+          w.webContents.executeJavaScript('a.click()')
+        })
+        w.loadURL(url)
+      })
+    })
+
+    // TODO(jeremy): window.open() in a real browser passes the referrer, but
+    // our hacked-up window.open() shim doesn't. It should.
+    xit('propagates referrer information to windows opened with window.open', (done) => {
```
Comment (deepak1556) [inline spec/api-web-contents-spec.js]: Is the plan to work on fixing this spec in this PR or separate ? Rest of the code LGTM.

Comment (nornagon) [reply spec/api-web-contents-spec.js]: I think it would make sense to land this and fix the `window.open` issue separately, since it'll be almost entirely unrelated code and this PR at least improves the situation somewhat. Should I remove the `xit` test?

Comment (deepak1556) [reply spec/api-web-contents-spec.js]: I think its fine to have the test.

File: docs/api/web-contents.md [hunk 4]
```diff
@@ -609,7 +612,7 @@ for windows with *offscreen rendering* enabled.
 
 * `url` String
 * `options` Object (optional)
-  * `httpReferrer` String (optional) - A HTTP Referrer url.
+  * `httpReferrer` (String | [Referrer](structures/referrer.md)) (optional) - A HTTP Referrer url.
```
Comment (zeke) [inline docs/api/web-contents.md]: A HTTP -> An HTTP

File: docs/api/web-contents.md [hunk 5]
```diff
@@ -151,6 +151,9 @@ Returns:
   [`BrowserWindow`](browser-window.md).
 * `additionalFeatures` String[] - The non-standard features (features not handled
   by Chromium or Electron) given to `window.open()`.
+* `referrer` [Referrer](structures/referrer.md) - The referrer that will be
```
Comment (zeke) [inline docs/api/web-contents.md]: Not sure if this is relevant, but I remember that there was a historical misspelling of the `referer` HTTP header. Are we affected by this? Should we also be spelling it "wrong"?

> The misspelling of referrer originated in the original proposal by computer scientist Phillip Hallam-Baker to incorporate the field into the HTTP specification.[3] The misspelling was set in stone by the time of its incorporation into the Request for Comments standards document RFC 1945

File: docs/api/structures/referrer.md [hunk 6]
```diff
@@ -0,0 +1,12 @@
+# Referrer Object
+
+* `url` String - HTTP Referrer URL.
+* `policy` String - Referrer Policy, as specified in the [Referrer-Policy
+  header][1].
+
+`policy` can be one of `default`, `unsafe-url`, `no-referrer-when-downgrade`,
```
Comment (zeke) [inline docs/api/structures/referrer.md]: @MarshallOfSound do you remember if the docs linter will pick up allowable values in this format?

Comment (MarshallOfSound) [reply docs/api/structures/referrer.md]: It has to be inline in the description of the property.

So:

```markdown
* `policy` String - Can be `a`, `b`, `c` or `d`.  This part then describes policy
```

File: docs/api/web-contents.md (hunk 5 above)
Comment (nornagon) [reply docs/api/web-contents.md]: Almost all other documentation that refers to the `Referer` header uses `Referrer` wherever it can. The HTTP header for referrer policy is called `Referrer-Policy`, without the misspelling. The web community as a whole appears to deeply regret the error, and prefers to pretend it never happened :D

**Comment by ckerr** [comment]
@zeke thanks for taking a look!
