### PR TITLE
Use callback dialog methods in RunFileChooser

### LINKED ISSUE #8457: macOS: buggy / crashy Quick Look via <input type="file">'s open dialog
* Electron version: 1.4.15 (probably older versions too).
* Operating system: macOS 10.12.2

When Quick Look is launched by right-clicking a file in a file dialog, clicking its close button doesn't work (and there's an audible beep), and after enough clicking around frequently it crashes. I suspect the same thing would happen using `dialog.showOpenDialog` presented as a sheet, but I haven't tested.

Minimal app to reproduce:
```js
const {app, BrowserWindow} = require('electron')

app.on('ready', () => {
  const win = new BrowserWindow({width: 300, height: 100})
  win.loadURL('data:text/html,<input type="file">')
})
```

Example:
quicklook

Crash log: https://gist.github.com/javan/4c19dddd73b0581e60f6baf3b75d4dd8

### PR DESCRIPTION
**Pull request by kevinsawicki**
This pull request switches the open and save dialogs opened in `WebDialogHelper::RunFileChooser` to be callback-based instead of synchronous.

Inspired by https://cs.chromium.org/chromium/src/chrome/browser/file_select_helper.h

- [x] Manually test on macOS
- [x] Manually test on Windows
- [x] Manually test on Linux

Closes #8457

### CODE REVIEW

File: atom/browser/web_dialog_helper.cc [hunk 1]
```diff
@@ -26,6 +28,94 @@
 
 namespace {
 
+class FileSelectHelper : public base::RefCountedThreadSafe<
```
Comment (deepak1556) [inline atom/browser/web_dialog_helper.cc]: Minor nit: this can be just `base::RefCounted`, I don't see this class being used across threads. Also its good practice to make destructor private for ref counted classes.

File: atom/browser/web_dialog_helper.cc [hunk 2]
```diff
@@ -26,6 +28,94 @@
...
+    auto web_contents = content::WebContents::FromRenderFrameHost(
+        render_frame_host);
+    content::WebContentsObserver::Observe(web_contents);
+    // Add ref that will be released when the dialog is completed
+    AddRef();
+  }
+
+  void ShowOpenDialog(const file_dialog::DialogSettings& settings) {
+    auto callback = base::Bind(&FileSelectHelper::OnOpenDialogDone,
+                               base::Unretained(this));
```
Comment (deepak1556) [inline atom/browser/web_dialog_helper.cc]: its not necessary for `unretained` wrapper here.

**Comment by kevinsawicki** [comment]
Thanks @deepak1556 for taking a look at this 👍

File: atom/browser/web_dialog_helper.cc [hunk 3]
```diff
@@ -16,7 +16,9 @@
 #include "base/strings/utf_string_conversions.h"
 #include "chrome/common/pref_names.h"
 #include "components/prefs/pref_service.h"
+#include "content/public/browser/browser_thread.h"
```
Comment (deepak1556) [inline atom/browser/web_dialog_helper.cc]: Minor change, this header is not used.
