### PR TITLE
fix: do not wait on promise returned by remote APIs

### LINKED ISSUE #18638: Setting new src in webview is slow in v6
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta.6
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * 5.0.2

### Expected Behavior
Setting new src in previous version of electron would take only 1–2ms.

### Actual Behavior
Setting new src in electron v6 takes ~600–700ms.

### To Reproduce
1. Clone this repo: https://github.com/steverandy/electron-quick-start/
2. Checkout branch `slow-webview`
3. Run `npm install` and `npm start`
4. Open devtool to see the time took to set new src

### Screenshots

Screenshot 2019-06-05 at 10 23 12 AM

### PR DESCRIPTION
**Pull request by zcbenz**
#### Description of Change

Close #18638.

This PR fixes the bug in `ipcMainUtils.handle` that, the helper waits on Promise returned by handler when it shouldn't.
 
For the original issue, `ipcMainUtils.handle` waits on the Promised returned by `WebContents.loadURL`, resulting in setting src being blocked until the URL is loaded. 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fix setting `src` on `<webview>` being too slow.

### CODE REVIEW

**Comment by miniak** [comment]
I get the problem we are trying to solve, however I am not sure if the solution is correct. I think about it a bit more

**Comment by zcbenz** [comment]
@miniak Another way to fix it is to split `ipcMainUtils.handle` into 2 parts, one handling normal functions and one handling async functions. Would that feel right to you?

**Comment by zcbenz** [comment]
I have refactored the code to add `ipcMainUtils.handleAsync`, so the behavior of the helper is more clear.

**Comment by miniak** [comment]
@zcbenz We actually had `handle` and `handleSync` before :) I've merged them into a single method, as I wanted the caller to decide whether to use `invoke` or `invokeSync` and have the handler be generic.

**Comment by miniak** [comment]
I would suggest one of these 2 solutions:
- https://github.com/electron/electron/compare/miniak/webview-load-url?expand=1
- https://github.com/electron/electron/compare/miniak/webview-load-url-v2?expand=1

**Comment by zcbenz** [comment]
@miniak The results of `asyncMethods` are still being awaited, so `<webview>.loadURL` still won't work correctly in first version.

I'm good with the second version.

**Comment by miniak** [comment]
@zcbenz it is awaited but it does not block the renderer.

**Comment by zcbenz** [comment]
@miniak Yeah you are right, both versions should work then.

**Comment by zcbenz** [comment]
@miniak Do you want to open a PR for your solution?

File: lib/common/web-view-methods.js [hunk 1]
```diff
@@ -54,6 +53,7 @@ exports.syncMethods = new Set([
 ])
 
 exports.asyncMethods = new Set([
+  'loadURL',
```
Comment (jkleinsc) [inline lib/common/web-view-methods.js]: Shouldn't there be a corresponding doc change to note the loadURL is now async?

Comment (zcbenz) [reply lib/common/web-view-methods.js]: @jkleinsc The `<webview>.loadURL` was actually asynchronous while it was under put `syncMethods`, the `WebContents.loadURL` API works asynchronously that it only starts the loading and returns immediately without waiting for anything.

So with this PR `<webview>.loadURL` won't change any documented behavior.

The side effect of this PR is making `<webview>.loadURL` return a `Promise`, but since we are backporting it to 6.0, I think it is probably better keeping it undocumented otherwise it would be a `feat`.

**Comment by deepak1556** [comment]
I agree @jkleinsc we should document the api signature change for master, for the backport we can do two things either, take this as a feature and get it through the release-wg process which should be easy based on

https://github.com/electron/governance/tree/master/wg-releases#feature-backport-requests-for-major-versions-in-beta

```
Backport requests after Week 3 will only be considered if there is a very good reason. For backport requests please submit the link to the PR and reason for backport to the Releases WG agenda for consideration.
```

or the backport PR can create a separate handler for `loadURL` that still uses the `ipcRendererUtils.invoke` but maintains the current return value type.

**Comment by zcbenz** [comment]
I have added documentation for the return value change.

For the backport (#19190), I found the code would be rather dirty if we want to keep the return value unchanged, as currently `<webview>.loadURL` returns a serialized version of Promise object. So I kept the backport as it is and it requires release-wg to approve.
