### PR TITLE
fix: defer Wrappable destruction in SecondWeakCallback to a posted task

### LINKED ISSUE #45416: Electron 34.x mysteriously crashes with `Invoke in DisallowJavascriptExecutionScope`
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

34.0.2

### What operating system(s) are you using?

Ubuntu

### Operating System Version

```
Linux ubuntu 6.8.0-52-generic #53-Ubuntu SMP PREEMPT_DYNAMIC Sat Jan 11 00:06:25 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

### What arch are you using?

x64

### Last Known Working Electron version

33.3.x (Which we can't even roll back to due to #43400)

### Expected Behavior

Using IPC does not mysteriously lead to this untraceable crash.

### Actual Behavior

Following printed in console, followed by `renderer-process-gone` and no attributable cause:
```
# Fatal error in , line 0
# Invoke in DisallowJavascriptExecutionScope
```

### Testcase Gist URL

_No response_

### Additional Information

Suspected related to this change: https://github.com/electron/electron/pull/45229

### LINKED ISSUE #47420: DisallowJavascriptExecutionScope crash
### Confirmation

- [x] I am a [maintainer](https://github.com/orgs/electron/people) of the Electron project. (If not, please create a [different issue type](https://github.com/electron/electron/issues/new/).)

### Description

Observed when investigating https://github.com/electron/electron/issues/46109

<details><summary>Details</summary>
<p>

```
#
# Fatal error in ../../v8/src/execution/execution.cc, line 364
# Invoke in DisallowJavascriptExecutionScope
#
#
#
#FailureMessage Object: 0x16b03f0b8
----- Native stack trace -----
1: 0x11e79f2c8 node::NodePlatform::GetStackTracePrinter()::$_0::__invoke() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
2: 0x12594a560 V8_Fatal(char const*, int, char const*, ...) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
3: 0x12010a544 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
4: 0x120108734 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::DirectHandle<v8::internal::Object>, v8::internal::DirectHandle<v8::internal::Object>, v8::base::Vector<v8::internal::DirectHandle<v8::internal::Object> const>) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
5: 0x11fe4b6a8 v8::Function::Call(v8::Isolate*, v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
6: 0x11e66504c node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context, v8::Local<v8::Value>) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
7: 0x11e665420 node::InternalMakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context, v8::Local<v8::Value>) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
8: 0x11e5b1cb0 gin_helper::internal::CallMethodWithArgs(v8::Isolate*, v8::Local<v8::Object>, char const*, base::span<v8::Local<v8::Value>, 18446744073709551615ul, v8::Local<v8::Value>*>) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
9: 0x11e47a2b0 bool gin_helper::EventEmitterMixin<electron::api::WebContents>::Emit<>(std::__Cr::basic_string_view<char, std::__Cr::char_traits<char>>) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x11e479d94 electron::api::WebContents::~WebContents() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x11e47a588 electron::api::WebContents::Destroy() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x11e4aa714 electron::api::WebContentsView::~WebContentsView() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x11e4aa7e4 electron::api::WebContentsView::~WebContentsView() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x120185c80 v8::internal::GlobalHandles::InvokeSecondPassPhantomCallbacks() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x120188bb4 std::__Cr::__function::__func<v8::internal::GlobalHandles::PostGarbageCollectionProcessing(v8::GCCallbackFlags)::$_0, std::__Cr::allocator<v8::internal::GlobalHandles::PostGarbageCollectionProcessing(v8::GCCallbackFlags)::$_0>, void ()>::operator()() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
16: 0x11e79da9c node::PerIsolatePlatformData::RunForegroundTask(std::__Cr::unique_ptr<v8::Task, std::__Cr::default_delete<v8::Task>>) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
17: 0x11e79c91c node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
18: 0x11e38e184 uv__async_io [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
19: 0x11e39fe6c uv__io_poll [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
20: 0x11e38e678 uv_run [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
21: 0x11e5b96d4 electron::NodeBindings::UvRunOnce() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
22: 0x11e3a7e34 base::OnceCallback<void ()>::Run() && [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
23: 0x1240ceaf0 base::TaskAnnotator::RunTaskImpl(base::PendingTask&) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
24: 0x1240feed8 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
25: 0x1240fe5dc base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
26: 0x12416c8fc base::MessagePumpCFRunLoopBase::RunWork() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
27: 0x12416b438 base::apple::CallWithEHFrame(void () block_pointer) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
28: 0x12416bce8 base::MessagePumpCFRunLoopBase::RunWorkSource(void*) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
29: 0x181691cd4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
30: 0x181691c68 __CFRunLoopDoSource0 [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
31: 0x1816919d4 __CFRunLoopDoSources0 [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
32: 0x181690628 __CFRunLoopRun [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
33: 0x18168fc58 CFRunLoopRunSpecific [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
34: 0x18d12427c RunCurrentEventLoopInMode [/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox]
35: 0x18d1274e8 ReceiveNextEventCommon [/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox]
36: 0x18d2b2484 _BlockUntilNextEventMatchingListInModeWithFilter [/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox]
37: 0x1855b7ab4 _DPSNextEvent [/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit]
38: 0x185f565b0 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] [/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit]
39: 0x1855aac64 -[NSApplication run] [/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit]
40: 0x12416d438 base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
41: 0x12416b4b8 base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
42: 0x1240ffc9c base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
43: 0x1240ad06c base::RunLoop::Run(base::Location const&) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
44: 0x12231be94 content::BrowserMainLoop::RunMainMessageLoop() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
45: 0x12231dd38 content::BrowserMainRunnerImpl::Run() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
46: 0x12231896c content::BrowserMain(content::MainFunctionParams) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
47: 0x11ea5f198 content::RunBrowserProcessMain(content::MainFunctionParams, content::ContentMainDelegate*) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
48: 0x11ea616c8 content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
49: 0x11ea60f30 content::ContentMainRunnerImpl::Run() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
50: 0x11ea5e818 content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
51: 0x11ea5e938 content::ContentMain(content::ContentMainParams) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
52: 0x11e3a0724 ElectronMain [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
53: 0x104db4628 main [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/MacOS/Electron]
54: 0x181206b98 start [/usr/lib/dyld]

Electron exited with signal SIGTRAP.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by MarshallOfSound**
## Description of Change

V8's second-pass weak callbacks run inside a `DisallowJavascriptExecutionScope` — they may touch the V8 API but **must not invoke JavaScript**, directly or indirectly. Several Electron `gin_helper::Wrappable` subclasses (`WebContents` in particular) emit JS events from their destructors (`'will-destroy'` / `'destroyed'`), so when `SecondWeakCallback` synchronously `delete`s the C++ object inside that scope, the destructor's `Emit()` → `node::MakeCallback` → `v8::Function::Call` aborts with:

```
# Fatal error in ../../v8/src/execution/execution.cc, line 364
# Invoke in DisallowJavascriptExecutionScope
```

This was previously latent and timing-dependent — it required GC to collect the JS wrapper from a foreground GC task posted by V8's incremental marking finalizer, which only happened under specific heap-layout / allocation-timing conditions. It surfaced as #47420, #45416, podman-desktop/podman-desktop#12409, and intermittent flakes of `spec/fixtures/crash-cases/webcontentsview-create-leak-exit`.

### Fix

Both `WrappableBase::SecondWeakCallback` and `DeprecatedWrappableBase::SecondWeakCallback` now post the deletion via `base::SequencedTaskRunner::GetCurrentDefault()->{DeleteSoon,PostTask}` so the destructor (and any `Emit()` it does) runs once V8 has left the GC scope. Falls back to synchronous deletion when no task runner is bound (early/late process lifetime).

### Regression test

`spec/fixtures/crash-cases/wrappable-gc-weak-callback-emit/` reproduces the crash deterministically on `main` by setting `v8.setFlagsFromString('--stress-incremental-marking')` (which forces foreground GC tasks on every allocation step) and leaking three `WebContentsView` instances before `app.quit()`. Verified on a Linux testing build:

| | runs | crashes |
|---|---|---|
| Before fix | 5/5 | 5 |
| After fix | 10/10 | 0 |

All 23 existing crash-case fixtures continue to pass.

### Checklist

- [x] PR description has a clear explanation of the change
- [x] `npm run lint` passes
- [x] regression test added (`spec/fixtures/crash-cases/wrappable-gc-weak-callback-emit`)
- [x] all `spec/fixtures/crash-cases/*` pass

Fixes #47420
Fixes #45416

Notes: Fixed an intermittent `Invoke in DisallowJavascriptExecutionScope` crash on application quit when a `WebContents` (or other JS-emitting native object) is garbage-collected during shutdown.

### CODE REVIEW

File: shell/common/gin_helper/wrappable.cc [hunk 1]
```diff
@@ -126,9 +142,20 @@ void DeprecatedWrappableBase::SecondWeakCallback(
...
+  // See WrappableBase::SecondWeakCallback for why deletion is posted: V8's
+  // second-pass weak callbacks run inside a DisallowJavascriptExecutionScope,
+  // and several Wrappables emit JS events from their destructors.
+  // https://github.com/electron/electron/issues/47420
   DeprecatedWrappableBase* wrappable = data.GetParameter();
-  if (wrappable)
+  if (!wrappable)
+    return;
+  if (base::SequencedTaskRunner::HasCurrentDefault()) {
+    base::SequencedTaskRunner::GetCurrentDefault()->PostTask(
```
Comment (deepak1556) [inline shell/common/gin_helper/wrappable.cc]: Any reason to not use `DeleteSoon` helper here ? The helper uses non-nestable task internally

**Review by deepak1556 — COMMENTED** [review]
LGTM

Those destruction events are a problem even when we move the class to cppgc, will see how that goes.

File: shell/common/gin_helper/wrappable.cc (hunk 1 above)
Comment (MarshallOfSound) [reply shell/common/gin_helper/wrappable.cc]: Yeah, tried that first, it did something funky I can't remember what. I can found out though lemme run it again

Comment (MarshallOfSound) [reply shell/common/gin_helper/wrappable.cc]: Ah. `DeprecatedWrappableBase` has a protected destructor. I can work around that differently though

**Review by ahamedy6 — COMMENTED** [review]
ahamed
