### PR TITLE
Explicitly hide tooltip when the window is deactivated (master)

### LINKED ISSUE #9943: Tooltip from minimized window impossible to dismiss
* Electron version: 1.7.1
* Operating system: Windows

### Expected behavior
Tooltip shouldn't be shown on the screen.

### Actual behavior
Minimize tooltip stays on the screen until electron app is brought into foreground

Same as - https://bugs.chromium.org/p/chromium/issues/detail?id=724538

### How to reproduce

Look into https://bugs.chromium.org/p/chromium/issues/detail?id=724538

### PR DESCRIPTION
**Pull request by brenca**
This is here to fix #9943 on master

### CODE REVIEW

**Comment by alexeykuzmin** [comment]
@brenca Can you please rebase your changes onto the latest master to fix the **electron-linux-ia32** failure?

**Comment by brenca** [comment]
@alexeykuzmin done!

File: atom/browser/ui/win/atom_desktop_native_widget_aura.cc [hunk 1]
```diff
@@ -3,12 +3,16 @@
...
+#include "ui/views/corewm/tooltip_controller.h"
+#include "ui/wm/public/tooltip_client.h"
 
 namespace atom {
 
 AtomDesktopNativeWidgetAura::AtomDesktopNativeWidgetAura(
     views::internal::NativeWidgetDelegate* delegate)
     : views::DesktopNativeWidgetAura(delegate) {
+  // This is to enable the override of OnWindowActivated
+  wm::SetActivationChangeObserver(GetNativeWindow(), this);
```
Comment (ckerr) [inline atom/browser/ui/win/atom_desktop_native_widget_aura.cc]: From the libcc API, it looks like we can only have one observer:

```c++
WM_PUBLIC_EXPORT void SetActivationChangeObserver(
    aura::Window* window,
    ActivationChangeObserver* observer);
WM_PUBLIC_EXPORT ActivationChangeObserver* GetActivationChangeObserver(
    aura::Window* window);
```

Are we certain that there's not some another observer being overwriting here?

File: atom/browser/ui/win/atom_desktop_native_widget_aura.cc [hunk 2]
```diff
@@ -19,4 +23,22 @@ void AtomDesktopNativeWidgetAura::Activate() {
...
+    reason, gained_active, lost_active);
+  if (lost_active != nullptr) {
+    auto* tooltip_controller = static_cast<views::corewm::TooltipController*>(
+      wm::GetTooltipClient(lost_active->GetRootWindow()));
+
+    // This will cause the tooltip to be hidden when a window is deactivated,
+    // as it should be.
+    // TODO(brenca): Remove this fix when the chromium issue is fixed.
+    // crbug.com/724538
+    tooltip_controller->OnCancelMode(nullptr);
```
Comment (ckerr) [inline atom/browser/ui/win/atom_desktop_native_widget_aura.cc]: Is there any way for `wm::GetTooltipClient()` to return `nullptr` such that this would be a null pointer dereference?

File: atom/browser/ui/win/atom_desktop_native_widget_aura.cc (hunk 1 above)
Comment (brenca) [reply atom/browser/ui/win/atom_desktop_native_widget_aura.cc]: Our `AtomDesktopNativeWidgetAura` is a subclass of the original `views::DesktopNativeWidgetAura`, which in the contructor [calls](https://cs.chromium.org/chromium/src/ui/views/widget/desktop_aura/desktop_native_widget_aura.cc?l=251) `SetActivationChangeObserver` with the `content_window_` and `this`. In our case, we call it with the same thing, since `GetNativeWindow` [returns `content_window_`](https://cs.chromium.org/chromium/src/ui/views/widget/desktop_aura/desktop_native_widget_aura.cc?l=400), and `this` still behaves the same as before (except for the fact that the subclass method gets called now in case of `OnWindowActivated`, where we call the original handler at the beginning to stay compatible).

According to the call hierarchy part of the code search site, `SetActivationChangeObserver` is only called from `NativeWidgetAura` (which we don't disturb) and from `DesktopNativeWidgetAura`, which we correctly handle. I don't see any way that we could overwrite another observer here, because we only effectively overwrite with the same class instance.

File: atom/browser/ui/win/atom_desktop_native_widget_aura.cc (hunk 2 above)
Comment (brenca) [reply atom/browser/ui/win/atom_desktop_native_widget_aura.cc]: That could return `NULL`, 'tho I don't really see when. Let's add an if just in case.
