### PR TITLE
Suppress dispatching to PDF viewer if plugins are disabled

### LINKED ISSUE #9412: PDF plugin ignores webPreferences: { plugins: false }
* Electron version: 1.6.6
* Operating system: macOS 10.12.4

### Expected behavior

When creating a new `BrowserWindow` the [PDF plugin](https://github.com/electron/electron/pull/8435) should respect the BrowserWindow `webPreferences.plugins` option as stated in the [API documentation](https://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions):
> plugins Boolean (optional) - Whether plugins should be enabled. Default is false.

### Actual behavior

The plugin is always enabled. Even if `plugins` is explicitly set to `false` like that:
```
    mainWindow = new BrowserWindow({
      webPreferences: {
        plugins: false  // set it explicitly to false even if it should be the default
      }
    })
```

### How to reproduce

  $ git clone https://github.com/rreimann/electron-quick-start.git -b pdf-plugin-always-enabled
  $ npm install
  $ npm start || electron .

See that "Chromium PDF Viewer" is contained in the listed plugins and the PDF link opens the PDF Viewer instead of downloading the PDF as it would be the case if the plugin was not enabled.

### PR DESCRIPTION
**Pull request by rreimann**
Suppress dispatching pdf resource requests to the native pdf viewer if plugins are disabled in `BrowserWindow.webPreferences` as suggested by @deepak1556 in https://github.com/electron/electron/issues/9412#issuecomment-300208701.

Note to the reviewer(s):
Since i've no clue about writing C++ code i tried to keep the changes as small as possible and skipped the following potential improvements:
* `web_contents_getter.Run()` is now called twice during the request at [ShouldInterceptResourceAsStream](https://github.com/rreimann/electron/blob/2f08b55a8a21cdc6a340ec663afcb79b6f48b6fc/atom/browser/atom_resource_dispatcher_host_delegate.cc#L128) and at [OnPdfResourceIntercepted](https://github.com/rreimann/electron/blob/2f08b55a8a21cdc6a340ec663afcb79b6f48b6fc/atom/browser/atom_resource_dispatcher_host_delegate.cc#L69). If i'd known the required syntax i would have called it just once and passed the resulting `WebContents` to `OnPdfResourceIntercepted`

* After adding `IsPluginsEnabled` to the existing methods `IsSandboxed` and `UsesNativeWindowOpen` there are now [three methods](https://github.com/rreimann/electron/blob/2f08b55a8a21cdc6a340ec663afcb79b6f48b6fc/atom/browser/web_contents_preferences.cc#L202-L246) that seem widely redundant. I did't know if the preexisting redundancy was intentional so i didn't try to extract a common method for all of them.

Fixes #9412

### CODE REVIEW

File: atom/browser/atom_resource_dispatcher_host_delegate.cc [hunk 1]
```diff
@@ -124,7 +125,10 @@ bool AtomResourceDispatcherHostDelegate::ShouldInterceptResourceAsStream(
     std::string* payload) {
   const content::ResourceRequestInfo* info =
       content::ResourceRequestInfo::ForRequest(request);
-  if (mime_type == "application/pdf" && info->IsMainFrame()) {
+  content::WebContents* web_contents =
+      info->GetWebContentsGetterForRequest().Run();
+  if (mime_type == "application/pdf" && info->IsMainFrame() &&
+      WebContentsPreferences::IsPluginsEnabled(web_contents)) {
```
Comment (deepak1556) [inline atom/browser/atom_resource_dispatcher_host_delegate.cc]: `WebContentsPreferences` is not thread safe, the check should be moved to `OnPdfResourceIntercepted` and implement a `webContents::DownloadURL` like call when plugin is disabled so that `will-download` event of session is triggered.

```
if (!WebContentsPreferences::IsPluginsEnabled(web_contents)) {
    auto browser_context = web_contents->GetBrowserContext();
    auto download_manager =
      content::BrowserContext::GetDownloadManager(browser_context);

    download_manager->DownloadUrl(
        content::DownloadUrlParameters::CreateForWebContentsMainFrame(
            web_contents, original_url));
    return;
  }
```

File: atom/browser/web_contents_preferences.cc [hunk 2]
```diff
@@ -230,6 +230,22 @@ bool WebContentsPreferences::UsesNativeWindowOpen(
   return use;
 }
 
+bool WebContentsPreferences::IsPluginsEnabled(
```
Comment (deepak1556) [inline atom/browser/web_contents_preferences.cc]: Its fine to have this helper, but like you suggested it would be better to have them unified into a single `IsPreferenceEnabled`. @kevinsawicki thoughts ?

File: atom/browser/atom_resource_dispatcher_host_delegate.cc (hunk 1 above)
Comment (rreimann) [inline atom/browser/atom_resource_dispatcher_host_delegate.cc]: Thanks for the review. I moved the check in commit 5ce0e57

File: atom/browser/web_contents_preferences.cc (hunk 2 above)
Comment (rreimann) [inline atom/browser/web_contents_preferences.cc]: Extracted the redundant code in commit b85b701

File: atom/browser/web_contents_preferences.cc [hunk 3]
```diff
@@ -199,7 +199,9 @@ void WebContentsPreferences::AppendExtraCommandLineSwitches(
   }
 }
 
-bool WebContentsPreferences::IsSandboxed(content::WebContents* web_contents) {
+bool WebContentsPreferences::IsPreferenceEnabled(
```
Comment (deepak1556) [inline atom/browser/web_contents_preferences.cc]: The helper can be moved to anonymous namespace.

File: atom/browser/web_contents_preferences.cc [hunk 4]
```diff
@@ -199,7 +199,9 @@ void WebContentsPreferences::AppendExtraCommandLineSwitches(
...
+    const std::string& attributeName,
```
Comment (kevinsawicki) [inline atom/browser/web_contents_preferences.cc]: This should be `attribute_name`.

File: atom/browser/web_contents_preferences.h [hunk 5]
```diff
@@ -37,8 +37,11 @@ class WebContentsPreferences
   static void AppendExtraCommandLineSwitches(
       content::WebContents* web_contents, base::CommandLine* command_line);
 
+  static bool IsPreferenceEnabled(const std::string& attributeName,
+                                  content::WebContents* web_contents);
```
Comment (kevinsawicki) [inline atom/browser/web_contents_preferences.h]: This should be `attribute_name`.

File: spec/chromium-spec.js [hunk 6]
```diff
@@ -1023,7 +1025,23 @@ describe('chromium feature', function () {
       w.webContents.loadURL(pdfSource)
     })
 
+    it('should download a pdf when plugins are disabled', function (done) {
+      createBrowserWindow(false)
+      ipcRenderer.sendSync('set-download-option', false, false)
+      ipcRenderer.once('download-done', function (event, state, url,
```
Comment (kevinsawicki) [inline spec/chromium-spec.js]: I don't think you need to wrap the arguments here, long lines are fine in specs.

If you do want to wrap, can you align the `mimeType` param with the `event` param?

File: atom/browser/web_contents_preferences.cc [hunk 7]
```diff
@@ -209,25 +211,23 @@ bool WebContentsPreferences::IsSandboxed(content::WebContents* web_contents) {
     return false;
 
   base::DictionaryValue& web_preferences = self->web_preferences_;
-  bool sandboxed = false;
-  web_preferences.GetBoolean("sandbox", &sandboxed);
-  return sandboxed;
+  bool boolValue = false;
```
Comment (kevinsawicki) [inline atom/browser/web_contents_preferences.cc]: This should be `bool_value`.

**Comment by rreimann** [comment]
Fixed the requested naming/formatting changes in commit https://github.com/electron/electron/pull/9507/commits/8f9e553def72c419e99ae22a37c6223b38a8120b. @kevinsawicki would it be ok if i open another PR to backport this fix into the `1-6-x` brach after  it was merged into master?

**Comment by kevinsawicki** [comment]
Thanks for this @rreimann 👍 🚢 

> would it be ok if i open another PR to backport this fix into the 1-6-x brach after it was merged into master?

Yes, sounds good, thanks 👍
