### PR TITLE
fix: allow persistent media salts

### LINKED ISSUE #22144: mediaDevices.enumerateDevices returns different deviceIds on every reload
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Tested with 8.0.0 and v9.0.0-beta.1
* **Operating System:**
  * macOS 10.15.3 (19D76)
* **Last Known Working Electron version:**
  * 7.1.12

### Expected Behavior

`navigator.mediaDevices.enumerateDevices()` should return a list of MediaDevices with a `label` and a `deviceId` property. The `deviceId` property should stay the same across reloads and restarts.

### Actual Behavior
The `deviceId` property changes with every reload/restart.

### To Reproduce
Simply execute `navigator.mediaDevices.enumerateDevices()` in the renderer process and compare the ids of the media devices to a different execution.

See this fork for an example:
https://github.com/codedrift/electron-quick-start

```sh
$ git clone https://github.com/codedrift/electron-quick-start -b media-device-ids
$ npm install
$ npm start || electron .
```

### Additional Information
It seems to work fine in a regular Chrome 80 browser.

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #22144

A new BrowserClient method was added and we didn't implement it to retain the old behavior, this fills that gap 👍 

Notes: deviceId from `navigator.mediaDevices.enumerateDevices` is now consistent across reloads

### CODE REVIEW

File: shell/browser/electron_browser_client.cc [hunk 1]
```diff
@@ -872,6 +872,14 @@ bool ElectronBrowserClient::ShouldUseProcessPerSite(
 #endif
 }
 
+bool ElectronBrowserClient::ArePersistentMediaDeviceIDsAllowed(
+    content::BrowserContext* browser_context,
+    const GURL& scope,
+    const GURL& site_for_cookies,
+    const base::Optional<url::Origin>& top_frame_origin) {
+  return true;
```
Comment (deepak1556) [inline shell/browser/electron_browser_client.cc]: Might be better to return `false` for `browser_context->IsOffTheRecord()` types, I don't see upstream covering that condition.

Comment (deepak1556) [reply shell/browser/electron_browser_client.cc]: Nm: I misunderstood the persistent level of id , the spec makes it clear https://w3c.github.io/mediacapture-main/#privacy-and-security-considerations

**Comment by LuoJinghua** [comment]
Could we make it optional or let the app decide whether this feature should be enabled for a site? Some web sites is already using the persistent media device id to tracking users.

**Comment by koenoe** [comment]
Will this fix be released in 8.0.3? We're currently struggling with this issue.
