### PR TITLE
fix: use StartUpdating method for PipeWire capturer

### LINKED ISSUE #37463: [Bug]: DesktopCapturer doesn't work in Ubuntu 22.04.2 LTS
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.1

### What operating system are you using?

Ubuntu

### Operating System Version

22.04.2

### What arch are you using?

x64

### Last Known Working Electron version

_No response_

### Expected Behavior

Get access to screens for capture recording using desktopCapturer in electron Api

### Actual Behavior

There are difficulties to report the problem because no specific error is received in the terminal, only the message below

```bash
tiago@tghpereira:~/Área de Trabalho/electron/test$ yarn start
yarn run v1.22.19
$ electron .
/home/tiago/Área de Trabalho/electron/test/node_modules/electron/dist/electron exited with signal SIGSEGV
error Command failed with exit code 1.
```

I followed the official Electronjs documentation step by step and tried several approaches mentioned in forums to find ways to solve the problem, but without success.
Please help us with this issue which is greatly affecting many packages.

### Testcase Gist URL

https://gist.github.com/68498fa7437a78b9daf435f3413c9a43

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by aiddya**
#### Description of Change

Fixed a crash related to PipeWire capturer by adapting to Chromium's interface changes. Chromium expects a call to
`NativeDesktopMediaList::StartUpdating` with an implementation of `DesktopMediaListObserver` for delegated capturers like PipeWire. This interface allows listening to user permission events and listing sources only after the user has made a choice on the permission dialog.

The interface has been implemented by an inner class to allow listening to screen and window capture permissions concurrently using two instances of the class. A patch that was resetting the capturer on the first refresh has been changed to exclude PipeWire. PipeWire capturer object will follow the lifecycle of `NativeDesktopMediaList`, as is the case in Chromium.

Fixes #37463

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed a crash when listing desktop capture sources on Wayland with PipeWire.

### CODE REVIEW

**Comment by sunknudsen** [comment]
Not the right person to add value to this PR, but can’t wait for [issue](https://github.com/electron/electron/issues/37463) to be fixed. Thanks for working on this @aiddya!

**Comment by byquanton** [comment]
With this PR applied, it crashes somewhere else.
```
Thread 46 "DesktopMediaLis" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff518656c0 (LWP 1905627)]
NativeDesktopMediaList::Worker::Refresh (this=0x2e3c0195d380, view_dialog_id=@0x2e3c0299af18: -1, 
    update_thumnails=true) at ../../chrome/browser/media/webrtc/native_desktop_media_list.cc:271
```

Before:
```
Thread 43 "DesktopMediaLis" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff530686c0 (LWP 1911851)]
webrtc::BaseCapturerPipeWire::CaptureFrame (this=<optimized out>) at ../../third_party/webrtc/modules/desktop_capture/linux/wayland/base_capturer_pipewire.cc:163
```

**Comment by aiddya** [comment]
@byquanton Can you share the following information?

1. How did you test this patch? Can you share the electron code as a fiddle?
2. Did you apply this patch on main or a branch?
3. What OS and OS version did you test this with?
4. What desktop environment are you using? If it's not GNOME or KDE, what portal implementation are you using?
5. Did you run electron with any flags?
6. Did you test this on Wayland?

**Comment by byquanton** [comment]
> @byquanton Can you share the following information?
> 
>     1. How did you test this patch? Can you share the electron code as a fiddle?
> 
>     2. Did you apply this patch on main or a branch?
> 
>     3. What OS and OS version did you test this with?
> 
>     4. What desktop environment are you using? If it's not GNOME or KDE, what portal implementation are you using?
> 
>     5. Did you run electron with any flags?
> 
>     6. Did you test this on Wayland?

1. I ran Element with it.
2. Applied it on main
3. Fedora 38
4. GNOME (xdg-desktop-portal-gnome)
5. Without any Flags
6. Wayland

**Comment by aiddya** [comment]
@byquanton I have no idea what Element is doing and its code base is too large to debug.

However, the crash message that you're seeing is expected if you don't apply the updated `desktop_media_list.patch`. Did you run `gclient sync -f` to reapply the Chomium patches after you applied my patch? Can you verify that `chrome/browser/media/webrtc/native_desktop_media_list.cc` reflects the changes made in this PR?

**Comment by aiddya** [comment]
I pushed a commit to fix thumbnail generation. I've validated the fixes using a more extensive test case that lists sources, displays thumbnails and initiates a stream using the source ID: https://gist.github.com/aiddya/d368bc2cb7f72a9b030b918ee1332299

**Comment by byquanton** [comment]
> @byquanton I have no idea what Element is doing and its code base is too large to debug.
> 
> However, the crash message that you're seeing is expected if you don't apply the updated `desktop_media_list.patch`. Did you run `gclient sync -f` to reapply the Chomium patches after you applied my patch? Can you verify that `chrome/browser/media/webrtc/native_desktop_media_list.cc` reflects the changes made in this PR?

Rebuild it again, and now it works.

**Comment by sunknudsen** [comment]
Hey @ckerr and @VerteDinde, has one of you had a chance to look into this PR?

Screen sharing is currently broken when using Linux/Wayland on [Element](https://github.com/vector-im/element-desktop/issues/957), [Jitsi](https://github.com/jitsi/jitsi-meet-electron/issues/829) and [Signal](https://github.com/signalapp/Signal-Desktop/issues/5350) which is affecting thousands is not millions of users.

Sending love to the universe… looking forward to a fix. 🙏

**Comment by theofficialgman** [comment]
This also affects https://github.com/SpacingBat3/WebCord with 35K installs from pi-apps alone with thousands more from other avenues. I agree this is likely affecting millions of users/application installs.

**Comment by ToasterUwU** [comment]
This also affects Armcord and Vencord Desktop. Which are both Linux focused Discord Clients.

**Comment by VerteDinde** [comment]
@aiddya Thanks for the PR! Sorry, I was out of the office when you submitted the PR originally, I take a look at it this week 🙇‍♀️

File: shell/browser/api/electron_api_desktop_capturer.cc [hunk 1]
```diff
@@ -181,6 +181,42 @@ DesktopCapturer::DesktopCapturer(v8::Isolate* isolate) {}
...
+}
+
+void DesktopCapturer::DesktopListListener::OnSourceThumbnailChanged(int index) {
+  if (have_selection_) {
+    // This is called every time a thumbnail is refreshed. Reset variable to
+    // ensure that the callback is not run again.
+    have_selection_ = false;
+
+    // PipeWire returns a single source, so index is not relevant.
+    std::move(this->update_callback_).Run();
```
Comment (codebytere) [inline shell/browser/api/electron_api_desktop_capturer.cc:210]: This new logic applies cross-platform, though - is there a situation where we'd need this index?

File: shell/browser/api/electron_api_desktop_capturer.cc [hunk 2]
```diff
@@ -181,6 +181,42 @@ DesktopCapturer::DesktopCapturer(v8::Isolate* isolate) {}
...
+  } else {
+    have_thumbnail_ = true;
+  }
+}
+
+void DesktopCapturer::DesktopListListener::OnDelegatedSourceListDismissed() {
+  std::move(this->failure_callback_).Run();
```
Comment (codebytere) [inline shell/browser/api/electron_api_desktop_capturer.cc:217]:
```suggestion
  std::move(failure_callback_).Run();
```

File: shell/browser/api/electron_api_desktop_capturer.cc (hunk 1 above)
Comment (codebytere) [inline shell/browser/api/electron_api_desktop_capturer.cc:210]:
```suggestion
    std::move(update_callback_).Run();
```

File: shell/browser/api/electron_api_desktop_capturer.cc [hunk 3]
```diff
@@ -181,6 +181,42 @@ DesktopCapturer::DesktopCapturer(v8::Isolate* isolate) {}
...
+  update_callback_ = std::move(update_callback);
+  failure_callback_ = std::move(failure_callback);
+  have_thumbnail_ = skip_thumbnails;
+}
+
+DesktopCapturer::DesktopListListener::~DesktopListListener() = default;
+
+void DesktopCapturer::DesktopListListener::OnDelegatedSourceListSelection() {
+  if (have_thumbnail_) {
+    std::move(this->update_callback_).Run();
```
Comment (codebytere) [inline shell/browser/api/electron_api_desktop_capturer.cc:197]: We don't need to use `this`:

```suggestion
    std::move(update_callback_).Run();
```

File: shell/browser/api/electron_api_desktop_capturer.cc [hunk 4]
```diff
@@ -269,12 +327,7 @@ void DesktopCapturer::UpdateSourcesList(DesktopMediaList* list) {
       // |media_list_sources|.
       if (!webrtc::DxgiDuplicatorController::Instance()->GetDeviceNames(
               &device_names)) {
-        v8::Isolate* isolate = JavascriptEnvironment::GetIsolate();
-        v8::HandleScope scope(isolate);
-        gin_helper::CallMethod(this, "_onerror", "Failed to get sources.");
-
-        Unpin();
-
+        this->HandleFailure();
```
Comment (codebytere) [inline shell/browser/api/electron_api_desktop_capturer.cc:330]:
```suggestion
        HandleFailure();
```

File: shell/browser/api/electron_api_desktop_capturer.cc [hunk 5]
```diff
@@ -181,6 +181,42 @@ DesktopCapturer::DesktopCapturer(v8::Isolate* isolate) {}
...
 DesktopCapturer::~DesktopCapturer() = default;
 
+DesktopCapturer::DesktopListListener::DesktopListListener(
+    OnceCallback update_callback,
+    OnceCallback failure_callback,
+    bool skip_thumbnails) {
+  update_callback_ = std::move(update_callback);
+  failure_callback_ = std::move(failure_callback);
+  have_thumbnail_ = skip_thumbnails;
+}
```
Comment (codebytere) [inline shell/browser/api/electron_api_desktop_capturer.cc:191]: nit: we typically use initializer lists:

```suggestion
DesktopCapturer::DesktopListListener::DesktopListListener(
    OnceCallback update_callback,
    OnceCallback failure_callback,
    bool skip_thumbnails) :  update_callback_(std::move(update_callback)), 
                                              failure_callback_(std::move(failure_callback)),                                               
                                              have_thumbnail_(skip_thumbnails) {}
```

**Review by codebytere — COMMENTED** [review]
Thanks for working on this!

File: patches/chromium/desktop_media_list.patch [hunk 6]
```diff
@@ -94,17 +94,20 @@ index b548c9fbd3c0bf425447b29dcd866cd27e96b14c..f994ac6086c7b4cd3e8534f34691189d
...
-@@ -457,6 +457,9 @@ void NativeDesktopMediaList::Worker::RefreshNextThumbnail() {
+@@ -457,6 +457,12 @@ void NativeDesktopMediaList::Worker::RefreshNextThumbnail() {
        FROM_HERE,
        base::BindOnce(&NativeDesktopMediaList::UpdateNativeThumbnailsFinished,
                       media_list_));
 +
 +  // This call is necessary to release underlying OS screen capture mechanisms.
-+  capturer_.reset();
++  // Skip if the source list is delegated, as the source list window will be active.
++  if (!capturer_->GetDelegatedSourceListController()) {
```
[the remark this answers is not in the document]
Comment (aiddya) [reply patches/chromium/desktop_media_list.patch:104]: I don't think we can. That variable is declared in the outer class, while this method is defined in the inner `Worker` class. The worker class has a weak pointer to the instance of the outer class and it has been declared as a friend, but weak pointer does not remain valid every time this method is called. The worker [owns the `capturer_` object](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/media/webrtc/native_desktop_media_list.cc;l=246;bpv=0;bpt=1), so this way is more reliable.

File: shell/browser/api/electron_api_desktop_capturer.cc (hunk 1 above)
Comment (aiddya) [reply shell/browser/api/electron_api_desktop_capturer.cc:210]: Not unless Chromium makes significant changes/refactors. PipeWire is the only delegated capturer right now. As a result, this code path will not be executed on other platforms.

Secondly, [according to Chromium documentation](https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:chrome/browser/media/webrtc/desktop_media_list.h;l=122-128;drc=89758767fb0fae96a59967eb47e7921ce49fafcb), delegated capturers manage their own UI for source selection and will return a single source. This logic should hold even if there's a new delegated capturer in the future.

File: shell/browser/api/electron_api_desktop_capturer.cc (hunk 5 above)
Comment (aiddya) [reply shell/browser/api/electron_api_desktop_capturer.cc]: I've pushed new commits to address the remaining comments.

**Comment by aiddya** [comment]
@VerteDinde Thanks! I had [added some background information](https://github.com/electron/electron/issues/37463#issuecomment-1586663196) in the linked issue, in case that helps. I had gotten some minor details of  `DesktopMediaListObserver` interface wrong, but the rest should hold up.

**Review by VerteDinde — APPROVED** [review]
Built and tested this locally on Mac and Windows as well as Linux, just to make sure we didn't regress the other platforms - everything seems to be working as expected. Thanks so much for fixing this! 🙇‍♀️

**Comment by byquanton** [comment]
When calling `desktopCapturer.getSources({ types: ['window', 'screen'] })` it opens two PipeWire pickers, one for a window and one for a screen. It can't get the sources if one of them is canceled (e.g. the user only wants to share a window or screen and cancels the other one). Maybe use a combined Picker for that case (again), or ignore if one is canceled. 

image


https://gist.github.com/68498fa7437a78b9daf435f3413c9a43

**Comment by orowith2os** [comment]
> Maybe use a combined Picker for that case (again), or ignore if one is canceled.

It would be best if there were just one picker, yes. That's the standard behavior on other applications, and works for a better UX.

**Comment by VerteDinde** [comment]
@byquanton Could I ask you to please file a new issue for the screen capturer pickers? Given that this PR fixes a hard crash, I'm going to prioritize getting the crash fix in, and we can then refine the picker behavior for when both options are selected. 👍 Thanks for testing this behavior!

**Review by codebytere — APPROVED** [review]

**Comment by sunknudsen** [comment]
Hey!

Are others experiencing following issues on Ubuntu 22.04.1 LTS (or equivalent) and Electron 25.3.0 (which implements this PR)?

First, calling `desktopCapturer.getSources` triggers screen share prompt asking user to allow specific window (wasn’t the case before… screen share prompt was only triggered by `navigator.mediaDevices.getUserMedia`… that said, window names and thumbnails were not displayed which likely explains why prompt was not required).

```typescript
const sources = await desktopCapturer.getSources({
  types: ["window"],
})
```

Then, calling `navigator.mediaDevices.getUserMedia` using following constraints triggers screen share prompt (again).

```typescript
const constraints = {
    audio: false,
    video: {
      mandatory: {
        chromeMediaSource: "desktop",
        chromeMediaSourceId: sourceRef.current.id,
        maxFrameRate: maxFrameRate,
      },
    },
  }
}

await navigator.mediaDevices.getUserMedia(constraints)
```

This is pretty bad for user experience… and wasn’t the case on previous “working” versions of Electron (running on Ubuntu 22.04.1 LTS).

Second, when window is selected, moving app window causes app to crash with following error.

```console
Dropping DMA-BUF modifier: 72057594037927935 and trying to renegotiate stream parameters
Segmentation fault (core dumped)
```

Puzzled…

**Comment by ToasterUwU** [comment]
@sunknudsen i think you are talking about the same thing that was [mentioned in this very same PR earlier](https://github.com/electron/electron/pull/38833#issuecomment-1629416400). There already is the Issue #39043 for resolving this bad experience stuff.

**Comment by sunknudsen** [comment]
@ToasterUwU Did you experience segmentation fault during testing?

**Comment by ToasterUwU** [comment]
@sunknudsen I have only tried it once for testing if it fixed the screenshare issue on a Discord Client, have not checked if it actually spits any errors while running. You can see the entire 40 second video i recorded of me trying it in Vencord/Vesktop#40, just so you know what exactly i did. It worked for me, even tho it was tedious to use. So if there was an error, it wasnt a fatal one (like Segmentation Fault typically is).

Im on PikaOS 23.04, which is Ubuntu based.

**Comment by aiddya** [comment]
@sunknudsen You should not see the second popup if the portal implementation you're using supports screencast restoration. That's supported by [xdg-desktop-portal 1.12](https://github.com/flatpak/xdg-desktop-portal/releases/tag/1.12.0) and [xdg-desktop-portal-gnome 42](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/blob/main/NEWS).

I tested moving and resizing the shared window with Electron 25.3.0, but I haven't seen any crash on Fedora 38. Do you see any of these issues on Chrome/Chromium? You can test using [Mozilla's gUM example page](https://mozilla.github.io/webrtc-landing/gum_test.html).

**Comment by sunknudsen** [comment]
Hey @aiddya and @VerteDinde, thanks for helping out… please see https://github.com/electron/electron/issues/39131. Ideas?
