### PR TITLE
fix: drag regions in child windows

### LINKED ISSUE #49223: app-region: drag does not working in child windows since Electron 40
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

40.0.0-beta.4

### What operating system(s) are you using?

Windows/MacOS/Linux

### What arch are you using?

x64

### Last Known Working Electron version

39.x.x

### Does the issue also appear in Chromium / Google Chrome?

No

### Expected Behavior

Child windows should be draggable using `app-region: drag` style

### Actual Behavior

`app-region: drag;` style does not working in child windows

### Testcase Gist URL

https://gist.github.com/bukharin/48ac395d4a1d05bd9deeeffdb0237429

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by clavin**
#### Description of Change

Fixes #49223

Upstream [moved `SetSupportsDraggableRegions`](https://chromium-review.googlesource.com/c/chromium/src/+/7043264) from the renderer-side `WebViewImpl` to the browser-side `content::WebContents`.

This PR adapts to that change by calling `SetSupportsDraggableRegions` during `WebContents` initialization, matching the previous behavior of `ElectronRenderFrameObserver`. The call is placed in two locations to cover all `WebContents` types: owned `WebContents` (`InitWithWebContents`) and remote `WebContents` (constructor).

In the process, we also discovered https://github.com/electron/electron/issues/49256

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed drag regions in child windows

### CODE REVIEW

**Comment by deepak1556** [comment]
We should also handle for child frames and across navigations per our old logic in https://github.com/electron/electron/commit/58c17ef8ef78c03fafadf46122dc7939140db742, `HandleNewRenderFrame` could be better home for this call ?

File: shell/browser/api/electron_api_web_contents.cc [hunk 1]
```diff
@@ -754,6 +754,12 @@ WebContents::WebContents(v8::Isolate* isolate,
   script_executor_ = std::make_unique<extensions::ScriptExecutor>(web_contents);
 #endif
 
+  // In Chrome, draggable regions are only supported in the main frame.
+  // However, we need to support draggable regions on other local
+  // frames/windows, so extend support beyond the main frame by enabling
+  // it for all WebContents.
```
Comment (deepak1556) [inline shell/browser/api/electron_api_web_contents.cc]: Is this statement true ? Upstream still restricts to main frame internally, should be rephrased.

Comment (clavin) [reply shell/browser/api/electron_api_web_contents.cc]: You are correct that these are incorrect! I've updated them in 2c76f1dcb223898b568f888c6c9bf8d49036f71f
