### PR TITLE
ci: fix WOA failing tests

### LINKED ISSUE #24942: Enable early-in-memory-session-create spec on WOA for 10-x-y
This started failing in the Chromium roll for 10-x-y #24706,

eg on https://github.visualstudio.com/electron/_build/results?buildId=78029&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86&l=1824:

```
Unhandled exception in main spec runner: AssertionError: should have exited with code 0: expected 3221225477 to equal 0
    at ChildProcess.<anonymous> (C:\vsts-agent-win-x86-2.166.4\_work\1\s\src\electron\spec-main\crash-spec.ts:26:23)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  showDiff: true,
  actual: 3221225477,
  expected: 0
}
not ok 1459 crash cases the "early-in-memory-session-create" case should not crash
  AssertionError: should have exited with code 0: expected 3221225477 to equal 0
      at ChildProcess.<anonymous> (electron\spec-main\crash-spec.ts:26:23)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
not ok 1460 crash cases "after each" hook for "the "early-in-memory-session-create" case should not crash"
  AssertionError: all child processes should have exited cleanly: expected [ Array(1) ] to have a length of 0 but got 1
      at Context.<anonymous> (electron\spec-main\crash-spec.ts:38:30)
      at processImmediate (internal/timers.js:456:21)
[5240:0810/110300.660:WARNING:discardable_shared_memory_manager.cc(432)] Some MojoDiscardableSharedMemoryManagerImpls are still alive. They will be leaked.
Received fatal exception EXCEPTION_ACCESS_VIOLATION
Backtrace:
	v8::Unlocker::~Unlocker [0x00007FF7E2ABADD0+26944]
	v8::MemorySpan<char const >::MemorySpan<char const > [0x00007FF7E1AC2C4C+2588]
	std::__1::__vector_base<v8::CpuProfileDeoptInfo,std::__1::allocator<v8::CpuProfileDeoptInfo> >::clear [0x00007FF7E197A4DC+26524]
	cppgc::Platform::GetForegroundTaskRunner [0x00007FF7E1A82ECC+12204]
	v8::ResourceConstraints::max_zone_pool_size [0x00007FF7E1AF5F18+41848]
	v8::ResourceConstraints::max_zone_pool_size [0x00007FF7E1AF5EC8+41768]
	uv_gettimeofday [0x00007FF7E531E19C+341532]
	uv_gettimeofday [0x00007FF7E531E39C+342044]
	uv_mutex_unlock [0x00007FF7E49B1B18+2468232]
	uv_mutex_unlock [0x00007FF7E49AC9F0+2447456]
	uv_mutex_unlock [0x00007FF7E49A3674+2409700]
	uv_mutex_unlock [0x00007FF7E49AACA0+2439952]
	uv_fs_get_path [0x00007FF7E4151C28+5838872]
	uv_fs_get_path [0x00007FF7E4151D2C+5839132]
	uv_fs_get_path [0x00007FF7E4151210+5836288]
	uv_fs_get_path [0x00007FF7E4150F48+5835576]
	uv_fs_get_path [0x00007FF7E41510E8+5835992]
	uv_fs_get_path [0x00007FF7E4150904+5833972]
	uv_fs_get_path [0x00007FF7E3C903A0+851856]
	IsSandboxedProcess [0x00007FF7E4FAE77C+463484]
	v8::CpuProfilingOptions::max_samples [0x00007FF7E27496B0+936912]
	Ordinal0 [0x00007FF7E19613CC+5068]
	uv_random [0x00007FF7E89FA9A4+18610468]
	uv_random [0x00007FF7E89FAA30+18610608]
	BaseThreadInitThunk [0x00007FFE2B994974+52]
	RtlUserThreadStart [0x00007FFE2D6F86F4+68]
✗ Electron tests failed with code 0xc0000005.
````

### PR DESCRIPTION
**Pull request by jkleinsc**
#### Description of Change

This PR resolves multiple issues on WOA testing:

1. The test suite failing with `Electron tests failed with code 0xc0000409.` (eg https://github.visualstudio.com/electron/_build/results?buildId=78491&view=logs&j=35d3790f-8c7d-56fd-eac0-8a56c1219de3&t=85db0f66-8e8b-5884-80a5-e918e0330cfe&l=2087).  This was due to testing on webContents.startDrag setting the icon to the current file.  Using a different file resolves the issue.

2. The `early-in-memory-session-create` crash test was failing with an exit code of `3221225477` instead of 0.  This changes the app to exit in the next microtask instead of immediately after session is created.  Thanks to @deepak1556 for this suggestion.  This resolves #24942.

3. Because our WOA tests do no run in a container, this PR also makes sure that user app directories are clean for testing.
#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).
- [x] This is **NOT A BREAKING CHANGE**. Breaking changes may not be merged to master until 11-x-y is branched.

#### Release Notes

Notes: none

### CODE REVIEW

File: spec-main/api-web-contents-spec.ts [hunk 1]
```diff
@@ -760,7 +761,7 @@ describe('webContents module', () => {
       }).to.throw('Must specify non-empty \'icon\' option');
 
       expect(() => {
-        w.webContents.startDrag({ file: __filename, icon: __filename });
+        w.webContents.startDrag({ file: __filename, icon: path.join(mainFixturesPath, 'blank.html') });
```
Comment (nornagon) [inline spec-main/api-web-contents-spec.ts:764]: yikes, it is surprising that specifying the js file would cause such a weird crash.

do we have any idea what the underlying cause is?

File: spec-main/fixtures/crash-cases/early-in-memory-session-create/index.js [hunk 2]
```diff
@@ -2,5 +2,7 @@ const { app, session } = require('electron');
 
 app.on('ready', () => {
   session.fromPartition('in-memory');
-  process.exit(0);
+  setImmediate(() => {
+    process.exit(0);
+  });
```
Comment (nornagon) [inline spec-main/fixtures/crash-cases/early-in-memory-session-create/index.js:7]: it's weird that this crashes on woa but not elsewhere 🤔

File: spec-main/api-web-contents-spec.ts (hunk 1 above)
Comment (jkleinsc) [reply spec-main/api-web-contents-spec.ts:764]: @nornagon I'm wondering if it is because the file isn't an icon?  In my local testing I used an empty file and it was fine but when I used a file that had contents in it, it again failed.  This latest commit uses an empty file.

File: spec-main/fixtures/crash-cases/early-in-memory-session-create/index.js (hunk 2 above)
Comment (jkleinsc) [reply spec-main/fixtures/crash-cases/early-in-memory-session-create/index.js:7]: indeed

File: spec-main/api-web-contents-spec.ts (hunk 1 above)
Comment (nornagon) [reply spec-main/api-web-contents-spec.ts:764]: Perhaps we could explicitly use an "empty file" file rather than overloading something that's expected in a lot of places to be html?

File: spec-main/index.js [hunk 3]
```diff
@@ -16,6 +16,12 @@ process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = 'true';
 
 const { app, protocol } = require('electron');
 
+try {
+  require('fs').rmdirSync(app.getPath('userData'), { recursive: true });
```
Comment (deepak1556) [inline spec-main/index.js:20]: Is this needed ? the domain before `ready` event of an app is an undefined area, its hard to get the timing right to delete the user dir unless we emit some sort of signal from the native side. There can be some initialization on the native side that might write into the user dir early on, one example would be spellchecker. The newly failing linux specs are definitely related to this change.

Comment (deepak1556) [reply spec-main/index.js:20]: If there is need to ensure deletion of user data dir, I think its better to have `kUserDataDir` implemented https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/chrome_switches.cc;l=594 and the ci test script launches the app explicitly with `--user-data-dir <path>` and deletes path after the test stage finishes.

Comment (jkleinsc) [reply spec-main/index.js:20]: @deepak1556 I don't think its needed anymore.  I'll remove it. I figured out a way to just delete on WOA after all the test runs are done: https://github.com/electron/electron/pull/25018/commits/5af1fbd36fc4626be099dd442bef5236bafac980

File: spec-main/api-web-contents-spec.ts (hunk 1 above)
Comment (jkleinsc) [reply spec-main/api-web-contents-spec.ts]: @nornagon I figured out why this was crashing... it is an issue with NativeImage
callstack3
a `longjmp` is failing.  Apparently Windows thinks it is invalid for the process, as far as I can understand from this: https://docs.microsoft.com/en-us/windows/win32/devnotes/guardchecklongjumptarget

Here's where `setjmp` gets called: https://source.chromium.org/chromium/chromium/src/+/master:ui/gfx/codec/jpeg_codec.cc;l=179
and here's where `longjmp` gets called: https://source.chromium.org/chromium/chromium/src/+/master:ui/gfx/codec/jpeg_codec.cc;l=43

File: spec/api-native-image-spec.js [hunk 4]
```diff
@@ -186,7 +192,8 @@ describe('nativeImage module', () => {
     });
   });
 
-  describe('createFromBuffer(buffer, options)', () => {
+  // TODO fix nativeImage.createFromBuffer on WOA
+  ifdescribe(process.platform !== 'win32' || process.arch !== 'arm64')('createFromBuffer(buffer, options)', () => {
```
Comment (nornagon) [inline spec/api-native-image-spec.js:196]: nit:
```suggestion
  ifdescribe(!(process.platform === 'win32' && process.arch === 'arm64'))('createFromBuffer(buffer, options)', () => {
```

is a easier to read imo!

Comment (jkleinsc) [reply spec/api-native-image-spec.js:196]: 👍

**Comment by jkleinsc** [comment]
Merging as mac failure is unrelated to PR change.

**Comment by deepak1556** [comment]
Nice work @jkleinsc
