### PR TITLE
return null when theme color is transparent or not found

### LINKED ISSUE #10240: When no theme color is found the event returns #000000
* Electron version: 1.7.5

### Expected behavior

When a theme color is no longer present the webContents did-change-theme-color event should return `null`.

### Actual behavior

The event returns `"#000000"`.

### How to reproduce

1. Log the returned color of the webContents did-change-theme-color event.
2. Go to https://electron.atom.io which has a theme color.
3. Go to https://atom.io which does not have a theme color.

### PR DESCRIPTION
**Pull request by liusy182**
fixes #10240

A followup PR from #10247

### CODE REVIEW

File: atom/browser/api/atom_api_web_contents.cc [hunk 1]
```diff
@@ -757,7 +757,11 @@ void WebContents::MediaStoppedPlaying(const MediaPlayerInfo& video_type,
 }
 
 void WebContents::DidChangeThemeColor(SkColor theme_color) {
-  Emit("did-change-theme-color", atom::ToRGBHex(theme_color));
+  if (theme_color != SK_ColorTRANSPARENT) {
+    Emit("did-change-theme-color", atom::ToRGBHex(theme_color));
+  } else {
+    Emit("did-change-theme-color", nullptr_t());
```
Comment (enlight) [inline atom/browser/api/atom_api_web_contents.cc]: > nullptr will not work in this case because Emit takes a reference but not a pointer as argument. Alternatively we can overload Emit to take pointers but probably it is a overkill for this change.

I've just tested `Emit("did-change-theme-color", nullptr)` and stepped through the `nullptr` -> `v8::Null` conversion step by step to make sure it works as expected, it works, and it doesn't require any changes other than the one already in `native_mate`. I'm using VS2015.

**Comment by liusy182** [comment]
Thanks @enlight strangely using `nullptr` keep crashing on my previous try with Mac but it worked now.

File: docs/api/web-contents.md [hunk 2]
```diff
@@ -403,6 +403,12 @@ a meta tag:
 <meta name='theme-color' content='#ff0000'>
 ```
 
+Returns:
+
+* `event` Event
+* `color` string
+  * Theme color in format '#rrggbb'. `null` when theme color is not found.
```
Comment (enlight) [inline docs/api/web-contents.md]: `when theme color is not found` -> `when theme color is not set`

File: docs/api/web-contents.md [hunk 3]
```diff
@@ -403,6 +403,12 @@ a meta tag:
 <meta name='theme-color' content='#ff0000'>
 ```
 
+Returns:
+
+* `event` Event
+* `color` string
```
Comment (xywz) [inline docs/api/web-contents.md]: ``string or `null` ``

File: docs/api/web-contents.md [hunk 4]
```diff
@@ -403,6 +403,12 @@ a meta tag:
 <meta name='theme-color' content='#ff0000'>
 ```
 
+Returns:
+
+* `event` Event
+* `color` string or `null`
```
Comment (MarshallOfSound) [inline docs/api/web-contents.md]: I know you just changed this but the correct notation for our documentation parser is:

```markdown
(String | null)
```

Note the brackets and no backticks

File: docs/api/web-contents.md [hunk 5]
```diff
@@ -403,6 +403,12 @@ a meta tag:
...
+  * Theme color in format '#rrggbb'. `null` when theme color is not set.
```
Comment (MarshallOfSound) [inline docs/api/web-contents.md]: So we don't confuse the docs parser this needs to either be a new paragraph or on the same line as `color`

E.g.

```markdown
* `color` (String | null) - Theme color is in the format '#rrggbb'. It is `null` when no theme color is set
```

Comment (liusy182) [inline docs/api/web-contents.md]: got it thanks!

**Comment by xywz** [comment]
Fixes #10238.
