### PR TITLE
fix: use tiled edges to calculate frame inset sizes in Linux

### LINKED ISSUE #39470: [Bug]: with wayland & gnome, maximizing a window to the side results in margin around the window
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.3.1 and 22.3.18

### What operating system are you using?

Other Linux

### Operating System Version

Linux jig 6.1.41-1-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Jul 25 09:17:30 UTC 2023 x86_64 GNU/Linux

### What arch are you using?

x64

### Expected Behavior

The demo app maximizes to the right or the left to take up half the screen, and the window extends to the top, bottom, and side all the way.

### Actual Behavior

The demo app maximizes to the right or the left to take up half the screen, but the borders of the app don't extend all the way to the side and bottom of the screen. The title-bar extends all the way to the top of the screen, but the title bar is double the height it should be, and it seems to only respond to clicks in the bottom half

image

#### Reproduction steps

- Install Manjaro with GNOME Shell 44.3, use gnome with wayland

```
pamac install electron
electron --ozone-platform=wayland --enable-features=WaylandWindowDecorations
```

- Drag demo app to side of screen to maximize to the right or the left

[Screencast from 2023-08-11 12-25-01.webm](https://github.com/electron/electron/assets/133676745/7e2cec76-df18-4de1-aea3-06c095d8ab68)

Note: maximizing full screen works as intended, but this may be related to https://github.com/electron/electron/issues/33161

### PR DESCRIPTION
**Pull request by aiddya**
#### Description of Change

Adapt to the window frame size calculation changes in [CL 3970920](https://chromium-review.googlesource.com/c/chromium/src/+/3970920) by setting the inset sizes to 0 for tiled edges.

cc @jkleinsc 

Fixes #39470 

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed decorations for tiled windows on Wayland.

### CODE REVIEW

File: shell/browser/ui/views/client_frame_view_linux.cc [hunk 1]
```diff
@@ -150,7 +150,11 @@ void ClientFrameViewLinux::Init(NativeWindowViews* window,
 }
 
 gfx::Insets ClientFrameViewLinux::GetBorderDecorationInsets() const {
-  return frame_provider_->GetFrameThicknessDip();
+  const auto insets = frame_provider_->GetFrameThicknessDip();
+  return gfx::Insets::TLBR(tiled_edges_.top ? 0 : insets.top(),
+                           tiled_edges_.left ? 0 : insets.left(),
+                           tiled_edges_.bottom ? 0 : insets.bottom(),
+                           tiled_edges_.right ? 0 : insets.right());
```
Comment (codebytere) [inline shell/browser/ui/views/client_frame_view_linux.cc:157]: small nit, but we can use the `tiled_edges()` accessor here. It might also help to add an explanatory comment above this logic 

```suggestion
const auto insets = frame_provider_->GetFrameThicknessDip();
  // We shouldn't draw frame decorations for the tiled edges.
  // See https://wayland.app/protocols/xdg-shell#xdg_toplevel:enum:state
  return gfx::Insets::TLBR(tiled_edges().top ? 0 : insets.top(),
                           tiled_edges().left ? 0 : insets.left(),
                           tiled_edges().bottom ? 0 : insets.bottom(),
                           tiled_edges().right ? 0 : insets.right());
```

**Review by codebytere — APPROVED** [review]
