### PR TITLE
override window.confirm in devtools

### LINKED ISSUE #7960: Electron's Developer Tools cannot 'Remove folder from workspace'
* Electron version: ^1.4.5
* Operating system: Windows 10@last-version

### Expected behavior

Electron's Developer Tools should be able to 'Remove folder from workspace' after successfully adding them with the 'Add folder to workspace' option.

### Actual behavior

Electron's Developer Tools cannot 'Remove folder from workspace' after successfully adding one with the 'Add folder to workspace' option.

### How to reproduce

* run a basic electron app
* open the embedded Developer Tools
* use the Add folder to workspace option in the sources' left panel
* try to remove it

### PR DESCRIPTION
**Pull request by deepak1556**
Result of the operation is required to complete the `remove from workspace` menu item action in the navigator view. https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/front_end/sources/NavigatorView.js?l=649-658

Fixes #7960

### CODE REVIEW

File: lib/renderer/inspector.js [hunk 1]
```diff
@@ -6,6 +6,22 @@ window.onload = function () {
   window.WebInspector.createFileSelectorElement = createFileSelectorElement
 }
 
+window.confirm = function (message, title) {
+  const {dialog} = require('electron').remote
+  let buttons, cancelId
```
Comment (kevinsawicki) [inline lib/renderer/inspector.js]: What do you think about inlining these both in the `showMessageBox` call like:

```js
return !dialog.showMessageBox({
  message: message,
  title: title,
  buttons: ['OK', 'Cancel'],
  cancelId: 1
})
```

**Comment by kevinsawicki** [comment]
Thanks for fixing this @deepak1556 👍 🚢

**Comment by deepak1556** [comment]
:+1:
