### PR TITLE
Fix transparent windows losing transparency when devtools detaches

### LINKED ISSUE #11833: Closing OSR devtools in software rendering mode causes OnPaint callback for transparent window to be permanently filled with white background
* Electron version: 1.8.2beta5
* Operating system: Windows 32-bit

### Expected behavior

After closing devtools, OSR rendered window should remain transparent. This is the case with 1.7.12 (latest 1.7 version as of this bug report)

### Actual behavior

OSR rendered window is filled with white background.

### How to reproduce

`electron main.js` (with the following two files stuck somewhere). dev tools will open themselves. OSR onpaint gets the correct transparent window, until devtools is closed, at which point, background becomes permanently white, destroying transparency.

main.js:
```
const {app, BrowserWindow} = require('electron')
const fs = require('fs');

app.disableHardwareAcceleration()

var counter = 0;

let win
app.once('ready', () => {
  win = new BrowserWindow({
    webPreferences: {
      offscreen: true,
    },
    show: false,
    transparent: true,
    width: 800,
    height: 600,
    frame: false,
  })
  win.loadURL(`file://${__dirname}/index.html`);
  win.webContents.on('paint', (event, dirty, image) => {
    // updateBitmap(dirty, image.getBitmap())
    ++counter;
    fs.writeFile('bitmap' + counter + '.raw', image.getBitmap(), (err) => {
      if (err) throw err;
      console.log('It\'s saved!');
    });
  })
  win.webContents.setFrameRate(30)
  win.toggleDevTools();
})
```

index.html:
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>OSR test</title>
        <style>
          html, body { background: rgba(0, 0, 0, 0); }
       </style>
    </head>
    <body><font color=#ffffff>testing</font></body>
</html>
```

### PR DESCRIPTION
**Pull request by brenca**
Fixes #11833 

[Related chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=800285&can=1&q=devtools%20transparent%20white&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified). This might be a permament fix, since before we relied on the [`SetBaseBackgroundColorOverride`](https://cs.chromium.org/chromium/src/content/renderer/render_view_impl.cc?q=setbackgroundcoloroverride&dr=C&l=2092) that was called by [`SetBackgroundOpaque`](https://cs.chromium.org/chromium/src/content/browser/renderer_host/render_widget_host_impl.cc?type=cs&l=2429), which is now gonna be cleared when the devtools is detached.

### CODE REVIEW

File: atom/renderer/renderer_client_base.cc [hunk 1]
```diff
@@ -170,7 +170,7 @@ void RendererClientBase::RenderViewCreated(content::RenderView* render_view) {
     // If backgroundColor is specified then use it.
     std::string name = cmd->GetSwitchValueASCII(switches::kBackgroundColor);
     // Otherwise use white background.
```
Comment (poiru) [inline atom/renderer/renderer_client_base.cc]: Comment is now out of date. I'd just remove the two comments above since the code is obvious.
