### PR TITLE
fix: browser contexts live forever

### LINKED ISSUE #24823: Electron crash after page redirected when in-memory partition enabled on linux since v9.0.0
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0~9.1.2
* **Operating System:**
  * Linux (CentOS/Amazon)
  * Docker image node:12.18.3-slim
  * Docker image circleci/node:12.14.1-browsers
* **Last Known Working Electron version:**
  * 8.4.1
  * 9.1.2 on OSX

### Expected Behavior
load pages, print "ok"

### Actual Behavior
crash

### To Reproduce

Run following code:
```
const {app, BrowserWindow} = require('electron');
console.log(process.versions);
app.on('ready', async () => {
  const win = new BrowserWindow({webPreferences: {partition: '123321'}});
  await win.loadURL('http://httpbin.org/get');
  await win.loadURL('http://httpbin.org/html');
  console.log('ok');
  app.quit()
});
```

### Additional Information

minidump:

```
Operating system: Linux
                  0.0.0 Linux 4.14.165-133.209.amzn2.x86_64 #1 SMP Sun Feb 9 00:21:30 UTC 2020 x86_64
CPU: amd64
     family 6 model 85 stepping 4
     1 CPU

GPU: UNKNOWN

Crash reason:  SIGSEGV /SEGV_MAPERR
Crash address: 0xfffff529cbb474c5
Process uptime: not available

Thread 0 (crashed)
 0  electron!tc_memalign [free_list.h : 0 + 0x0]
    rax = 0x000000000000000d   rdx = 0x0000000000000100
    rcx = 0x0000564b230940a8   rbx = 0x00000ad48591de80
    rsi = 0x0000000000000100   rdi = 0x0000000000000008
    rbp = 0x00007ffddc856400   rsp = 0x00007ffddc856370
     r8 = 0x0000000000000000    r9 = 0x0000000000000000
    r10 = 0x0000000000000000   r11 = 0x00000ad485d781c0
    r12 = 0x00000ad48591dc80   r13 = 0x00000002b258e852
    r14 = 0xfffff529cbb474bd   r15 = 0x00000ad4860b9500
    rip = 0x0000564b22bc7a5e
    Found by: given as instruction pointer in context
 1  electron!__posix_memalign + 0xae
    rbx = 0x0000564b22d25da0   rbp = 0x00007ffddc856440
    rsp = 0x00007ffddc856410   r12 = 0x0000000000000100
    r13 = 0x0000000000000008   r14 = 0x00007ffddc856458
    r15 = 0x0000000000000000   rip = 0x0000564b1f44479e
    Found by: call frame info
 2  electron!base::AlignedAlloc(unsigned long, unsigned long) [aligned_memory.cc : 31 + 0x5]
    rbx = 0x00000ad4861bfac0   rbp = 0x00007ffddc856460
    rsp = 0x00007ffddc856450   r12 = 0x00000ad4861bfac0
    r13 = 0x00007ffddc856590   r14 = 0x00000000000000f0
    r15 = 0x0000000000000000   rip = 0x0000564b1f3ad03c
    Found by: call frame info
 3  electron!mojo::core::Channel::Message::Message(unsigned long, unsigned long, unsigned long) [channel.cc : 122 + 0xd]
    rbx = 0x00000ad4861bfac0   rbp = 0x00007ffddc856480
    rsp = 0x00007ffddc856470   r12 = 0x00000ad4861bfac0
    r13 = 0x00007ffddc856590   r14 = 0x00000000000000f0
    r15 = 0x0000000000000000   rip = 0x0000564b1da9f723
    Found by: call frame info
 4  electron!mojo::core::NodeChannel::CreateEventMessage(unsigned long, unsigned long, void**, unsigned long) [memory : 3043 + 0x11]
    rbx = 0x00000000000000f0   rbp = 0x00007ffddc8564c0
    rsp = 0x00007ffddc856490   r12 = 0x00000ad4861bfac0
    r13 = 0x00007ffddc856590   r14 = 0x00000000000000f0
    r15 = 0x0000000000000000   rip = 0x0000564b1daad86e
    Found by: call frame info
 5  electron!mojo::core::(anonymous namespace)::CreateOrExtendSerializedEventMessage(mojo::core::ports::UserMessageEvent*, unsigned long, unsigned long, mojo::core::Dispatcher::DispatcherInTransit const*, unsigned long, std::__1::unique_ptr<mojo::core::Channel::Message, std::__1::default_delete<mojo::core::Channel::Message> >*, void**, unsigned long*, void**) [user_message_impl.cc : 148 + 0xb]
    rbx = 0xaaaaaaaaaaaaaaaa   rbp = 0x00007ffddc856610
    rsp = 0x00007ffddc8564d0   r12 = 0x0000000000000098
    r13 = 0x00000000000000e8   r14 = 0x0000000000000000
    r15 = 0x0000000000000028   rip = 0x0000564b1daba7e2
    Found by: call frame info
 6  electron!mojo::core::UserMessageImpl::CommitSize() [user_message_impl.cc : 527 + 0x11]
    rbx = 0x00000ad485db4e10   rbp = 0x00007ffddc856670
    rsp = 0x00007ffddc856620   r12 = 0x0000000000000000
    r13 = 0x00007ffddc856878   r14 = 0x0000000000000000
    r15 = 0x00000ad485db4e70   rip = 0x0000564b1dabb345
    Found by: call frame info
 7  electron!mojo::core::Core::AppendMessageData(unsigned long, unsigned int, unsigned int const*, unsigned int, MojoAppendMessageDataOptions const*, void**, unsigned int*) [core.cc : 397 + 0x8]
    rbx = 0x00000ad485db4e10   rbp = 0x00007ffddc856830
    rsp = 0x00007ffddc856680   r12 = 0x0000000000000000
    r13 = 0x00007ffddc856878   r14 = 0x0000000000000000
    r15 = 0x0000000000000010   rip = 0x0000564b1daa1e4b
    Found by: call frame info
 8  electron!MojoAppendMessageDataImpl [entrypoints.cc : 92 + 0x9]
    rbx = 0x00007ffddc856988   rbp = 0x00007ffddc856850
    rsp = 0x00007ffddc856840   r12 = 0x00007ffddc856980
    r13 = 0x0000000000000eaa   r14 = 0x00007ffddc856878
    r15 = 0x00007ffddc856884   rip = 0x0000564b1daa94a5
    Found by: call frame info
 9  electron!mojo::internal::Buffer::Seal() [buffer.cc : 118 + 0x10]
    rbx = 0x00007ffddc856988   rbp = 0x00007ffddc8568a0
    rsp = 0x00007ffddc856860   r12 = 0x00007ffddc856980
    r13 = 0x0000000000000eaa   r14 = 0x00007ffddc856878
    r15 = 0x00007ffddc856884   rip = 0x0000564b1f6f000b
    Found by: call frame info
10  electron!mojo::Message::TakeMojoMessage() [message.cc : 433 + 0x5]
    rbx = 0x00007ffddc856980   rbp = 0x00007ffddc8568c0
    rsp = 0x00007ffddc8568b0   r12 = 0x00007ffddc856980
    r13 = 0x0000000000000eaa   r14 = 0x00007ffddc8568e0
    r15 = 0x0000000000000000   rip = 0x0000564b1f6f1086
    Found by: call frame info
11  electron!mojo::Connector::Accept(mojo::Message*) [connector.cc : 338 + 0x8]
    rbx = 0x00000ad4861f9601   rbp = 0x00007ffddc856910
    rsp = 0x00007ffddc8568d0   r12 = 0x00007ffddc856980
    r13 = 0x0000000000000eaa   r14 = 0x00000ad48617f468
    r15 = 0x0000000000000000   rip = 0x0000564b1f6e0192
    Found by: call frame info
12  electron!mojo::InterfaceEndpointClient::Accept(mojo::Message*) [interface_endpoint_client.cc : 276 + 0x9]
    rbx = 0x00000ad4861f9600   rbp = 0x00007ffddc856930
    rsp = 0x00007ffddc856920   r12 = 0x00007ffddc856940
    r13 = 0x00007ffddc856a48   r14 = 0x00007ffddc856980
    r15 = 0x00007ffddc856940   rip = 0x0000564b1f6e2f93
    Found by: call frame info
13  electron!storage::mojom::PartitionProxy::BindLocalStorageControl(mojo::PendingReceiver<storage::mojom::LocalStorageControl>) [partition.mojom.cc : 166 + 0x9]
    rbx = 0x00007ffddc856980   rbp = 0x00007ffddc856a30
    rsp = 0x00007ffddc856940   r12 = 0x00007ffddc856940
    r13 = 0x00007ffddc856a48   r14 = 0x00000ad4861e8360
    r15 = 0x00007ffddc856940   rip = 0x0000564b1ee1e773
    Found by: call frame info
14  electron!content::DOMStorageContextWrapper::MaybeBindLocalStorageControl() [dom_storage_context_wrapper.cc : 340 + 0x9]
    rbx = 0x00000ad4861e8360   rbp = 0x00007ffddc856ab0
    rsp = 0x00007ffddc856a40   r12 = 0x00000ad4861bf8c0
    r13 = 0x00000ad4861bf8c0   r14 = 0x00007ffddc856a48
    r15 = 0x00007ffddc856a60   rip = 0x0000564b1e9a03c0
    Found by: call frame info
15  electron!content::DOMStorageContextWrapper::DOMStorageContextWrapper(content::StoragePartitionImpl*, storage::SpecialStoragePolicy*) [dom_storage_context_wrapper.cc : 135 + 0x8]
    rbx = 0x00000ad4860fd300   rbp = 0x00007ffddc856ae0
    rsp = 0x00007ffddc856ac0   r12 = 0x00000ad4861bf8c0
    r13 = 0x00000ad4861bf8c0   r14 = 0x0000000000000000
    r15 = 0x00000ad4861e8960   rip = 0x0000564b1e9a014c
    Found by: call frame info
16  electron!content::DOMStorageContextWrapper::Create(content::StoragePartitionImpl*, storage::SpecialStoragePolicy*) [dom_storage_context_wrapper.cc : 111 + 0xe]
    rbx = 0x00000ad4860fd300   rbp = 0x00007ffddc856b40
    rsp = 0x00007ffddc856af0   r12 = 0x00000ad4861bf8c0
    r13 = 0x00000ad4861bf8c0   r14 = 0x00000ad485fee680
    r15 = 0x00007ffddc856be0   rip = 0x0000564b1e99fcb3
    Found by: call frame info
17  electron!content::StoragePartitionImpl::Initialize() [storage_partition_impl.cc : 1446 + 0xb]
    rbx = 0x00000ad485a30280   rbp = 0x00007ffddc856ce0
    rsp = 0x00007ffddc856b50   r12 = 0x00000ad485fee680
    r13 = 0x00000ad4861bf8c0   r14 = 0x00000ad485e21a80
    r15 = 0x00000ad485fee6a0   rip = 0x0000564b1eca34f1
    Found by: call frame info
18  electron!content::StoragePartitionImplMap::Get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool) [storage_partition_impl_map.cc : 354 + 0x8]
    rbx = 0x00007ffddc856e20   rbp = 0x00007ffddc856dc0
    rsp = 0x00007ffddc856cf0   r12 = 0x00000ad4861290c0
    r13 = 0x00007ffddc856e20   r14 = 0x00000ad485fee680
    r15 = 0x00007ffddc856cf0   rip = 0x0000564b1ecafb97
    Found by: call frame info
19  electron!content::(anonymous namespace)::GetStoragePartitionFromConfig(content::BrowserContext*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool) [browser_context.cc : 176 + 0x16]
    rbx = 0x00000ad4860fcb00   rbp = 0x00007ffddc856e10
    rsp = 0x00007ffddc856dd0   r12 = 0x0000000000000001
    r13 = 0x00007ffddc856e20   r14 = 0x00000ad4861290c0
    r15 = 0x0000000000000000   rip = 0x0000564b1e8a95dd
    Found by: call frame info
20  electron!content::BrowserContext::GetDefaultStoragePartition(content::BrowserContext*) [browser_context.cc : 327 + 0xd]
    rbx = 0x00000ad486045300   rbp = 0x00007ffddc856e60
    rsp = 0x00007ffddc856e20   r12 = 0x00000ad4860fcbf1
    r13 = 0x00000ad4860fcbd8   r14 = 0x00000ad486045300
    r15 = 0x00007ffddc856f28   rip = 0x0000564b1e8a9739
    Found by: call frame info
21  electron!electron::CookieChangeNotifier::StartListening() [cookie_change_notifier.cc : 41 + 0x5]
    rbx = 0x00000ad486045300   rbp = 0x00007ffddc856eb0
    rsp = 0x00007ffddc856e70   r12 = 0x00000ad4860fcbf1
    r13 = 0x00000ad4860fcbd8   r14 = 0x00000ad486045300
    r15 = 0x00007ffddc856f28   rip = 0x0000564b1cfbc3b9
    Found by: call frame info
22  electron!electron::ElectronBrowserContext::ElectronBrowserContext(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, base::DictionaryValue) [memory : 3043 + 0xb]
    rbx = 0x00000ad486045300   rbp = 0x00007ffddc856f70
    rsp = 0x00007ffddc856ec0   r12 = 0x00000ad4860fcbf1
    r13 = 0x00000ad4860fcbd8   r14 = 0x00000ad4860fcb00
    r15 = 0x00007ffddc856f28   rip = 0x0000564b1cfc65be
    Found by: call frame info
23  electron!electron::ElectronBrowserContext::From(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, base::DictionaryValue) [electron_browser_context.cc : 457 + 0x12]
    rbx = 0x00000ad4860fcb00   rbp = 0x00007ffddc857020
    rsp = 0x00007ffddc856f80   r12 = 0x00007ffddc857070
    r13 = 0x0000000000000000   r14 = 0x00007ffddc856f80
    r15 = 0x00007ffddc856fd0   rip = 0x0000564b1cfc7def
    Found by: call frame info
24  electron!electron::ElectronExtensionsBrowserClient::GetOriginalContext(content::BrowserContext*) [electron_extensions_browser_client.cc : 115 + 0xa]
    rbx = 0x00007ffddc857050   rbp = 0x00007ffddc8570b0
    rsp = 0x00007ffddc857030   r12 = 0x00000ad485c60400
    r13 = 0x0000000000000000   r14 = 0x00000ad485d43eb0
    r15 = 0x0000000000000001   rip = 0x0000564b1d077ae0
    Found by: call frame info
25  electron!KeyedServiceFactory::GetServiceForContext(void*, bool) [keyed_service_factory.cc : 56 + 0xc]
    rbx = 0x00000ad485c77420   rbp = 0x00007ffddc8570f0
    rsp = 0x00007ffddc8570c0   r12 = 0x00000ad485c60400
    r13 = 0x0000000000000000   r14 = 0x00000ad485d43eb0
    r15 = 0x0000000000000001   rip = 0x0000564b2012b50e
    Found by: call frame info
26  electron!electron::ElectronBrowserClient::IsSuitableHost(content::RenderProcessHost*, GURL const&) [electron_browser_client.cc : 953 + 0x8]
    rbx = 0x00000ad485c77420   rbp = 0x00007ffddc857140
    rsp = 0x00007ffddc857100   r12 = 0x00000ad485c60400
    r13 = 0x0000000000000000   r14 = 0x00000ad485c60400
    r15 = 0x00007ffddc857330   rip = 0x0000564b1cfbfecc
    Found by: call frame info
27  electron!content::RenderProcessHostImpl::IsSuitableHost(content::RenderProcessHost*, content::IsolationContext const&, GURL const&, GURL const&, bool) [render_process_host_impl.cc : 4056 + 0x10]
    rbx = 0x00007ffddc857330   rbp = 0x00007ffddc8572a0
    rsp = 0x00007ffddc857150   r12 = 0x00000ad485df4380
    r13 = 0x0000000000000000   r14 = 0x00000ad485c60400
    r15 = 0x00000ad485fd3710   rip = 0x0000564b1ebbc093
    Found by: call frame info
28  electron!content::SiteInstanceImpl::IsSuitableForURL(GURL const&) [site_instance_impl.cc : 551 + 0x5]
    rbx = 0x00000ad485ff72c0   rbp = 0x00007ffddc8573d0
    rsp = 0x00007ffddc8572b0   r12 = 0x00007ffddc8572b0
    r13 = 0x0000000000000001   r14 = 0x00007ffddc857330
    r15 = 0x00000ad485f5e600   rip = 0x0000564b1ec903b1
    Found by: call frame info
29  electron!content::RenderFrameHostManager::IsCurrentlySameSite(content::RenderFrameHostImpl*, GURL const&) [render_frame_host_manager.cc : 1963 + 0xb]
    rbx = 0x00000ad485c77420   rbp = 0x00007ffddc8574b0
    rsp = 0x00007ffddc8573e0   r12 = 0x00000ad485fe1000
    r13 = 0x0000000000000001   r14 = 0x00000ad485ff72c0
    r15 = 0x0000000022bd7101   rip = 0x0000564b1ea31438
    Found by: call frame info
30  electron!content::RenderFrameHostManager::ShouldSwapBrowsingInstancesForNavigation(GURL const&, bool, content::SiteInstanceImpl*, content::SiteInstanceImpl*, content::SiteInstance*, GURL const&, bool, ui::PageTransition, bool, bool, bool, bool) [render_frame_host_manager.cc : 1413 + 0xb]
    rbx = 0x0000000000000000   rbp = 0x00007ffddc8575a0
    rsp = 0x00007ffddc8574c0   r12 = 0x00000ad4859feea0
    r13 = 0x00000ad485f5b410   r14 = 0x00000ad485f5e600
    r15 = 0x00000ad485ff72c0   rip = 0x0000564b1ea3115f
    Found by: call frame info
31  electron!content::RenderFrameHostManager::GetSiteInstanceForNavigation(GURL const&, content::SiteInstanceImpl*, content::SiteInstanceImpl*, content::SiteInstanceImpl*, ui::PageTransition, bool, bool, bool, bool, bool, bool) [render_frame_host_manager.cc : 1488 + 0x5a]
    rbx = 0x00000ad485ff72c0   rbp = 0x00007ffddc857770
    rsp = 0x00007ffddc8575b0   r12 = 0x0000000000000000
    r13 = 0x0000000000000000   r14 = 0x00000ad485f5e600
    r15 = 0x00000ad485f5b410   rip = 0x0000564b1ea31803
    Found by: call frame info
32  electron!content::RenderFrameHostManager::GetSiteInstanceForNavigationRequest(content::NavigationRequest*) [render_frame_host_manager.cc : 2502 + 0x43]
    rbx = 0x0000000000000000   rbp = 0x00007ffddc857890
    rsp = 0x00007ffddc857780   r12 = 0x0000000000000000
    r13 = 0x00000ad485e27000   r14 = 0x0000000000000000
    r15 = 0x00000ad485f5b410   rip = 0x0000564b1ea2ffaa
    Found by: call frame info
33  electron!content::RenderFrameHostManager::GetFrameHostForNavigation(content::NavigationRequest*) [render_frame_host_manager.cc : 812 + 0x12]
    rbx = 0x00000ad485e27000   rbp = 0x00007ffddc8579a0
    rsp = 0x00007ffddc8578a0   r12 = 0x00000ad485c77420
    r13 = 0x00000ad485f5b410   r14 = 0x00000ad485f5e600
    r15 = 0x00007ffddc857b28   rip = 0x0000564b1ea2f3fe
    Found by: call frame info
34  electron!content::RenderFrameHostManager::DidCreateNavigationRequest(content::NavigationRequest*) [render_frame_host_manager.cc : 777 + 0xb]
    rbx = 0x00000ad485e27000   rbp = 0x00007ffddc8579c0
    rsp = 0x00007ffddc8579b0   r12 = 0x00007ffddc857b90
    r13 = 0x00000ad48600bba0   r14 = 0x00000ad485f5b410
    r15 = 0x00007ffddc857b28   rip = 0x0000564b1ea2f2f7
    Found by: call frame info
35  electron!content::FrameTreeNode::CreatedNavigationRequest(std::__1::unique_ptr<content::NavigationRequest, std::__1::default_delete<content::NavigationRequest> >) [frame_tree_node.cc : 471 + 0x5]
    rbx = 0x00000ad485f5b400   rbp = 0x00007ffddc8579f0
    rsp = 0x00007ffddc8579d0   r12 = 0x00007ffddc857b90
    r13 = 0x00000ad48600bba0   r14 = 0x0000000000000001
    r15 = 0x00007ffddc857b28   rip = 0x0000564b1e9d94e8
    Found by: call frame info
36  electron!content::NavigatorImpl::Navigate(std::__1::unique_ptr<content::NavigationRequest, std::__1::default_delete<content::NavigationRequest> >, content::ReloadType, content::RestoreType) [navigator_impl.cc : 326 + 0x8]
    rbx = 0x00000ad485f5b400   rbp = 0x00007ffddc857b60
    rsp = 0x00007ffddc857a00   r12 = 0x00007ffddc857b90
    r13 = 0x00000ad48600bba0   r14 = 0x00007ffddc857a01
    r15 = 0x0000000000000001   rip = 0x0000564b1ea012c0
    Found by: call frame info
37  electron!content::NavigationControllerImpl::NavigateWithoutEntry(content::NavigationController::LoadURLParams const&) [navigation_controller_impl.cc : 2968 + 0xb]
    rbx = 0x00000ad485e27000   rbp = 0x00007ffddc857c00
    rsp = 0x00007ffddc857b70   r12 = 0x00007ffddc857eb8
    r13 = 0x00000ad485f5b400   r14 = 0x0000000000000000
    r15 = 0x00000ad485cf2480   rip = 0x0000564b1e9df984
    Found by: call frame info
38  electron!content::NavigationControllerImpl::LoadURLWithParams(content::NavigationController::LoadURLParams const&) [navigation_controller_impl.cc : 983 + 0xb]
    rbx = 0x0000000000000000   rbp = 0x00007ffddc857c80
    rsp = 0x00007ffddc857c10   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0xaaaaaaaaaaaaaaaa   r14 = 0x00007ffddc857eb8
    r15 = 0x00000ad485cf2480   rip = 0x0000564b1e9df342
    Found by: call frame info
39  electron!electron::api::WebContents::LoadURL(GURL const&, gin_helper::Dictionary const&) [electron_api_web_contents.cc : 1551 + 0x9]
    rbx = 0x00007ffddc857da0   rbp = 0x00007ffddc8581f0
    rsp = 0x00007ffddc857c90   r12 = 0x00007ffddc857fa0
    r13 = 0xaaaaaaaaaaaaaaaa   r14 = 0x00007ffddc857dc0
    r15 = 0x00000ad485f990f0   rip = 0x0000564b1cf914a8
    Found by: call frame info
40  electron!gin_helper::Dispatcher<void (electron::api::WebContents*, GURL const&, gin_helper::Dictionary const&)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) [callback.h : 132 + 0x3]
    rbx = 0x00007ffddc858200   rbp = 0x00007ffddc858300
    rsp = 0x00007ffddc858200   r12 = 0x0000269d00000000
    r13 = 0x00007ffddc858430   r14 = 0x00007ffddc858208
    r15 = 0xaaaaaaaaaaaaaaaa   rip = 0x0000564b1cfa1f21
    Found by: call frame info
41  electron!v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [api-arguments-inl.h : 158 + 0x5]
    rbx = 0x00007ffddc8583f0   rbp = 0x00007ffddc858480
    rsp = 0x00007ffddc858310   r12 = 0x0000269d00000000
    r13 = 0x00007ffddc858430   r14 = 0x0000000000000000
    r15 = 0x0000269d084209fd   rip = 0x0000564b1dc516b7
    Found by: call frame info
42  electron!Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 0x38
    rbx = 0x0000564b1dc51200   rbp = 0x00007ffddc8584a0
    rsp = 0x00007ffddc858490   r12 = 0x0000269d08426561
    r13 = 0x0000269d00000000   r14 = 0x0000000000000007
    r15 = 0x00007ffddc8584e0   rip = 0x0000564b1e5b7b18
    Found by: call frame info
43  electron!Builtins_InterpreterEntryTrampoline + 0xd5
    rbp = 0x00007ffddc858540   rsp = 0x00007ffddc8584b0
    rip = 0x0000564b1e54b7b5
    Found by: previous frame's frame pointer
44  electron!Builtins_InterpreterEntryTrampoline + 0xd5
    rbp = 0x00007ffddc8585b0   rsp = 0x00007ffddc858550
    rip = 0x0000564b1e54b7b5
    Found by: previous frame's frame pointer
45  electron!Builtins_ArgumentsAdaptorTrampoline + 0xbf
    rbp = 0x00007ffddc8585e8   rsp = 0x00007ffddc8585c0
    rip = 0x0000564b1e5451ff
    Found by: previous frame's frame pointer
46  electron!Builtins_InterpreterEntryTrampoline + 0xd5
    rbp = 0x00007ffddc858660   rsp = 0x00007ffddc8585f8
    rip = 0x0000564b1e54b7b5
    Found by: previous frame's frame pointer
47  electron!Builtins_AsyncFunctionAwaitResolveClosure + 0x31
    rbp = 0x00007ffddc8586a0   rsp = 0x00007ffddc858670
    rip = 0x0000564b1e57a451
    Found by: previous frame's frame pointer
48  electron!Builtins_PromiseFulfillReactionJob + 0x2f
    rbp = 0x00007ffddc8586d8   rsp = 0x00007ffddc8586b0
    rip = 0x0000564b1e5fbe4f
    Found by: previous frame's frame pointer
49  electron!Builtins_RunMicrotasks + 0x290
    rbp = 0x00007ffddc858738   rsp = 0x00007ffddc8586e8
    rip = 0x0000564b1e56c7f0
    Found by: previous frame's frame pointer
50  electron!Builtins_JSRunMicrotasksEntry + 0x78
    rbp = 0x00007ffddc8587a0   rsp = 0x00007ffddc858748
    rip = 0x0000564b1e549258
    Found by: previous frame's frame pointer
51  electron!v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [simulator.h : 142 + 0x5]
    rbp = 0x00007ffddc858870   rsp = 0x00007ffddc8587b0
    rip = 0x0000564b1dd00616
    Found by: previous frame's frame pointer
52  electron!v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [execution.cc : 427 + 0xb]
    rbx = 0x00007ffddc858888   rbp = 0x00007ffddc8588e0
    rsp = 0x00007ffddc858880   r12 = 0x00007ffddc8588f8
    r13 = 0x0000269d00000000   r14 = 0x00000ad485a5fbd0
    r15 = 0x0000269d00000000   rip = 0x0000564b1dd00cc0
    Found by: call frame info
53  electron!v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [execution.cc : 504 + 0x5]
    rbx = 0x0000564b2318591d   rbp = 0x00007ffddc858950
    rsp = 0x00007ffddc8588f0   r12 = 0x0000000000000002
    r13 = 0x0000269d00000000   r14 = 0x00000ad485a5fbd0
    r15 = 0x00000ad485a2a4b8   rip = 0x0000564b1dd00dbe
    Found by: call frame info
54  electron!v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [microtask-queue.cc : 165 + 0xb]
    rbx = 0x0000564b2318591d   rbp = 0x00007ffddc858a20
    rsp = 0x00007ffddc858960   r12 = 0x0000000000000002
    r13 = 0x0000269d00000000   r14 = 0x00000ad485a5fbd0
    r15 = 0x00000ad485a2a4b8   rip = 0x0000564b1dd221d5
    Found by: call frame info
55  electron!v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [microtask-queue.cc : 117 + 0x5]
    rbx = 0x0000269d00000000   rbp = 0x00007ffddc858a40
    rsp = 0x00007ffddc858a30   r12 = 0x0000000000000002
    r13 = 0x00000ad485a2a488   r14 = 0x00000ad485b39100
    r15 = 0x00000ad485a2a4b8   rip = 0x0000564b1dd22007
    Found by: call frame info
56  electron!node::InternalCallbackScope::Close() [callback.cc : 104 + 0x5]
    rbx = 0x00007ffddc858ae0   rbp = 0x00007ffddc858a80
    rsp = 0x00007ffddc858a50   r12 = 0x0000000000000002
    r13 = 0x00000ad485a2a488   r14 = 0x00000ad485b39100
    r15 = 0x00000ad485a2a4b8   rip = 0x0000564b2295c575
    Found by: call frame info
57  electron!node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [callback.cc : 169 + 0x5]
    rbx = 0x0000000000000000   rbp = 0x00007ffddc858b40
    rsp = 0x00007ffddc858a90   r12 = 0x0000000000000002
    r13 = 0x00000ad485a2a488   r14 = 0x00000ad4860f0f30
    r15 = 0x00000ad485a2a4b8   rip = 0x0000564b2295c8d5
    Found by: call frame info
58  electron!node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [callback.cc : 222 + 0x1f]
    rbx = 0x00000ad485a2a4b0   rbp = 0x00007ffddc858ba0
    rsp = 0x00007ffddc858b50   r12 = 0x00000ad485a2a488
    r13 = 0x00000ad485a2a4a8   r14 = 0x00000ad485b39100
    r15 = 0x00000ad485a7c940   rip = 0x0000564b2295cb31
    Found by: call frame info
59  electron!gin_helper::internal::CallMethodWithArgs(v8::Isolate*, v8::Local<v8::Object>, char const*, std::__1::vector<v8::Local<v8::Value>, std::__1::allocator<v8::Local<v8::Value> > >*) [event_emitter_caller.cc : 23 + 0x14]
    rbx = 0x0000269d00000000   rbp = 0x00007ffddc858be0
    rsp = 0x00007ffddc858bb0   r12 = 0x00007ffddc858c38
    r13 = 0x0000269d00000000   r14 = 0x0000564b1c2d907c
    r15 = 0x00000ad485a2a488   rip = 0x0000564b1d0414bd
    Found by: call frame info
60  electron!bool gin_helper::EventEmitter<electron::api::WebContents>::EmitWithEvent<>(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, v8::Local<v8::Object>) [event_emitter_caller.h : 50 + 0x16]
    rbx = 0x0000269d00000000   rbp = 0x00007ffddc858c80
    rsp = 0x00007ffddc858bf0   r12 = 0x00000ad485a2a488
    r13 = 0x00000ad485a2a490   r14 = 0x00000ad485a2a468
    r15 = 0x00000ad485a2a468   rip = 0x0000564b1cf9b140
    Found by: call frame info
61  electron!bool gin_helper::EventEmitter<electron::api::WebContents>::Emit<>(base::BasicStringPiece<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >) [event_emitter.h : 79 + 0x11]
    rbx = 0x00000ad485f99020   rbp = 0x00007ffddc858ce0
    rsp = 0x00007ffddc858c90   r12 = 0x00007ffddc858d40
    r13 = 0x00000ad485fe1068   r14 = 0x000000000000000f
    r15 = 0x0000564b1c3fe7c5   rip = 0x0000564b1cf8a430
    Found by: call frame info
62  electron!electron::api::WebContents::DidFinishLoad(content::RenderFrameHost*, GURL const&) [electron_api_web_contents.cc : 1070 + 0x14]
    rbx = 0x00007ffddc858cf8   rbp = 0x00007ffddc858d30
    rsp = 0x00007ffddc858cf0   r12 = 0x00007ffddc858d40
    r13 = 0x00000ad485fe1068   r14 = 0x00000ad485f99020
    r15 = 0x00000ad485fe1000   rip = 0x0000564b1cf8d290
    Found by: call frame info
63  electron!content::WebContentsImpl::OnDidFinishLoad(content::RenderFrameHost*, GURL const&) [web_contents_impl.cc : 4964 + 0xf]
    rbx = 0x00000ad485ea4bb0   rbp = 0x00007ffddc858e10
    rsp = 0x00007ffddc858d40   r12 = 0x00007ffddc858d40
    r13 = 0x00000ad485fe1068   r14 = 0x00000ad485cf2400
    r15 = 0x00000ad485fe1000   rip = 0x0000564b1ece21f8
    Found by: call frame info
64  electron!blink::mojom::LocalFrameHostStubDispatch::Accept(blink::mojom::LocalFrameHost*, mojo::Message*) [frame.mojom.cc : 4035 + 0x14]
    rbx = 0x00000ad4861f7610   rbp = 0x00007ffddc859050
    rsp = 0x00007ffddc858e20   r12 = 0x0000000000000000
    r13 = 0x00000ad485fe1068   r14 = 0xaaaaaaaaaaaaaaaa
    r15 = 0x00007ffddc859180   rip = 0x0000564b1d9d3a28
    Found by: call frame info
65  electron!mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*) [interface_endpoint_client.cc : 554 + 0x9]
    rbx = 0x00007ffddc8590a8   rbp = 0x00007ffddc8590e0
    rsp = 0x00007ffddc859060   r12 = 0x00007ffddc859090
    r13 = 0x00000ad486159c00   r14 = 0x00007ffddc859180
    r15 = 0x00000ad486159df0   rip = 0x0000564b1f6e2049
    Found by: call frame info
66  electron!mojo::MessageDispatcher::Accept(mojo::Message*) [message_dispatcher.cc : 46 + 0x9]
    rbx = 0x00000ad486159cf0   rbp = 0x00007ffddc859130
    rsp = 0x00007ffddc8590f0   r12 = 0x00000ad486159c00
    r13 = 0x00000ad485c77160   r14 = 0x00007ffddc859180
    r15 = 0x00007ffddc8590f8   rip = 0x0000564b1f6e507f
    Found by: call frame info
67  electron!IPC::(anonymous namespace)::ChannelAssociatedGroupController::AcceptOnProxyThread(mojo::Message) [ipc_mojo_bootstrap.cc : 933 + 0xb]
    rbx = 0x0000000000000004   rbp = 0x00007ffddc859170
    rsp = 0x00007ffddc859140   r12 = 0x00000ad486159c00
    r13 = 0x00000ad485c77160   r14 = 0x00000ad485c77260
    r15 = 0x00007ffddc859180   rip = 0x0000564b1f91fe25
    Found by: call frame info
68  electron!base::internal::Invoker<base::internal::BindState<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message), scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController>, mojo::Message>, void ()>::RunOnce(base::internal::BindStateBase*) [bind_internal.h : 489 + 0x9]
    rbx = 0x00000ad485c77160   rbp = 0x00007ffddc859210
    rsp = 0x00007ffddc859180   r12 = 0x00000ad485fe2000
    r13 = 0xaaaaaaaaaaaaaaaa   r14 = 0x00007ffddc859180
    r15 = 0x0000564b1f91fda0   rip = 0x0000564b1f91dbf3
    Found by: call frame info
69  electron!base::TaskAnnotator::RunTask(char const*, base::PendingTask*) [callback.h : 98 + 0x3]
    rbx = 0xaaaaaaaaaaaaaaaa   rbp = 0x00007ffddc8592d0
    rsp = 0x00007ffddc859220   r12 = 0x00000ad485fe2000
    r13 = 0xaaaaaaaaaaaaaaaa   r14 = 0x0000000000000000
    r15 = 0x0000564b23101ee8   rip = 0x0000564b1f3ddb98
    Found by: call frame info
70  electron!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*) [thread_controller_with_message_pump_impl.cc : 324 + 0xf]
    rbx = 0x0000564b1f91d4fe   rbp = 0x00007ffddc8593b0
    rsp = 0x00007ffddc8592e0   r12 = 0x0000000000000000
    r13 = 0x00000ad485fe2000   r14 = 0x00000ad485a1fc60
    r15 = 0x00007ffddc8593c0   rip = 0x0000564b1f3ee6a4
    Found by: call frame info
71  electron!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() [thread_controller_with_message_pump_impl.cc : 248 + 0xb]
    rbx = 0x00000ad485a1fc60   rbp = 0x00007ffddc859400
    rsp = 0x00007ffddc8593c0   r12 = 0x00000ad485cca160
    r13 = 0x0000000000000000   r14 = 0x00000ad485a1fd48
    r15 = 0x00007ffddc8593c0   rip = 0x0000564b1f3ee432
    Found by: call frame info
72  electron!base::(anonymous namespace)::WorkSourceDispatch(_GSource*, int (*)(void*), void*) [message_pump_glib.cc : 409 + 0x6]
    rbx = 0x00000ad485a195a0   rbp = 0x00007ffddc859420
    rsp = 0x00007ffddc859410   r12 = 0x00000ad485cca160
    r13 = 0x0000000000000000   r14 = 0x0000564b1f3afe00
    r15 = 0x00000ad4859ec5b0   rip = 0x0000564b1f3afe17
    Found by: call frame info
73  libglib-2.0.so.0 + 0x49310
    rbx = 0x00000ad4859ebbb0   rbp = 0x0000000000000000
    rsp = 0x00007ffddc859430   r12 = 0x00000ad485cca160
    r13 = 0x0000000000000000   r14 = 0x0000564b1f3afe00
    r15 = 0x00000ad4859ec5b0   rip = 0x00007f940d352310
    Found by: call frame info
74  libglib-2.0.so.0 + 0x58130
    rsp = 0x00007ffddc8594b0   rip = 0x00007f940d361130
    Found by: stack scanning
75  libglib-2.0.so.0 + 0x49675
    rsp = 0x00007ffddc8594c0   rip = 0x00007f940d352675
    Found by: stack scanning
76  libglib-2.0.so.0 + 0x496fc
    rsp = 0x00007ffddc859520   rip = 0x00007f940d3526fc
    Found by: stack scanning
77  electron!base::MessagePumpGlib::Run(base::MessagePump::Delegate*) [message_pump_glib.cc : 439 + 0x5]
    rsp = 0x00007ffddc859540   rip = 0x0000564b1f3afc72
    Found by: stack scanning
78  electron!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) [thread_controller_with_message_pump_impl.cc : 429 + 0x3]
    rsp = 0x00007ffddc859590   rip = 0x0000564b1f3eec94
    Found by: stack scanning
79  electron!base::RunLoop::Run() [run_loop.cc : 124 + 0x10]
    rsp = 0x00007ffddc8595c0   rip = 0x0000564b1f3c8b2e
    Found by: stack scanning
80  electron!operator new(unsigned long) [allocator_shim.cc : 161 + 0xa]
    rsp = 0x00007ffddc8595d0   rip = 0x0000564b1f44432b
    Found by: stack scanning
81  electron!base::RunLoop::QuitWhenIdleClosure() [run_loop.cc : 189 + 0x5]
    rsp = 0x00007ffddc8595f0   rip = 0x0000564b1f3c96d0
    Found by: stack scanning
82  electron!content::BrowserMainLoop::RunMainMessageLoopParts() [browser_main_loop.cc : 1496 + 0x8]
    rsp = 0x00007ffddc859650   rip = 0x0000564b1e8bf3f4
    Found by: stack scanning
83  electron!content::BrowserMainRunnerImpl::Run() [browser_main_runner_impl.cc : 150 + 0x5]
    rsp = 0x00007ffddc8596c0   rip = 0x0000564b1e8c11f2
    Found by: stack scanning
84  electron!content::BrowserMain(content::MainFunctionParams const&) [browser_main.cc : 47 + 0x3]
    rsp = 0x00007ffddc8596e0   rip = 0x0000564b1e8bc72d
    Found by: stack scanning
85  electron!content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams&, bool) [content_main_runner_impl.cc : 530 + 0x5]
    rsp = 0x00007ffddc859730   rip = 0x0000564b1e7ae449
    Found by: stack scanning
86  electron!content::ContentMainRunnerImpl::Run(bool) [content_main_runner_impl.cc : 879 + 0x10]
    rsp = 0x00007ffddc8597c0   rip = 0x0000564b1e7ae07a
    Found by: stack scanning
87  electron!content::ContentServiceManagerMainDelegate::IsEmbedderSubprocess() [__string : 217 + 0xc]
    rsp = 0x00007ffddc8597f0   rip = 0x0000564b1db25b62
    Found by: stack scanning
88  electron!service_manager::Main(service_manager::MainParams const&) [main.cc : 454 + 0x9]
    rsp = 0x00007ffddc859840   rip = 0x0000564b208b44ea
    Found by: stack scanning
89  electron!tcmalloc::CentralFreeList::Populate() [central_freelist.cc : 366 + 0x8]
    rsp = 0x00007ffddc859880   rip = 0x0000564b1d09f26e
    Found by: stack scanning
90  electron!tcmalloc::CentralFreeList::RemoveRange(void**, void**, int) [central_freelist.cc : 284 + 0x11]
    rsp = 0x00007ffddc8598e0   rip = 0x0000564b1d09ebd8
    Found by: stack scanning
91  electron!std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, node::loader::PackageConfig const>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, node::loader::PackageConfig const>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, node::loader::PackageConfig const>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, node::loader::PackageConfig const> > >::__rehash(unsigned long) + 0x47
    rsp = 0x00007ffddc8599e0   rip = 0x0000564b1cf44567
    Found by: stack scanning
92  electron!operator new(unsigned long) [allocator_shim.cc : 161 + 0xa]
    rsp = 0x00007ffddc859af0   rip = 0x0000564b1f44432b
    Found by: stack scanning
93  electron!content::ContentMain(content::ContentMainParams const&) [content_main.cc : 19 + 0x8]
    rsp = 0x00007ffddc859b40   rip = 0x0000564b1db26701
    Found by: stack scanning
94  electron!operator new(unsigned long) [allocator_shim.cc : 161 + 0xa]
    rsp = 0x00007ffddc859b60   rip = 0x0000564b1f44432b
    Found by: stack scanning
95  electron!main [electron_main.cc : 231 + 0x5]
    rsp = 0x00007ffddc859bd0   rip = 0x0000564b1cf1a73d
    Found by: stack scanning
96  electron + 0x182c440
    rsp = 0x00007ffddc859ca0   rip = 0x0000564b1cf1a440
    Found by: stack scanning
97  electron!chrome_pdf::(anonymous namespace)::DeleteFont(_FPDF_SYSFONTINFO*, void*) [core.h : 44 + 0xe]
    rsp = 0x00007ffddc859cb8   rip = 0x0000564b22bc4550
    Found by: stack scanning
98  libc.so.6 + 0x2102a
    rbx = 0x0000000000000000   rbp = 0x0000564b22bc4550
    rsp = 0x00007ffddc859cc0   rip = 0x00007f940752e02a
    Found by: call frame info
99  electron!frame_dummy + 0x10
    rsp = 0x00007ffddc859ce0   rip = 0x0000564b1cf1a550
    Found by: stack scanning
100  electron + 0x182c440
    rsp = 0x00007ffddc859cf8   rip = 0x0000564b1cf1a440
    Found by: stack scanning
101  ld-linux-x86-64.so.2 + 0xeec6
    rsp = 0x00007ffddc859d50   rip = 0x00007f940e515ec6
    Found by: stack scanning
102  electron + 0x182c440
    rsp = 0x00007ffddc859d70   rip = 0x0000564b1cf1a440
    Found by: stack scanning
103  electron!_start + 0x2a
    rsp = 0x00007ffddc859d80   rip = 0x0000564b1cf1a46a
    Found by: stack scanning
104  0x7ffddc859d88
    rsp = 0x00007ffddc859d88   rip = 0x00007ffddc859d88
    Found by: call frame info
105  0x7ffddc8a3000
    rsp = 0x00007ffddc859eb8   rip = 0x00007ffddc8a3000
    Found by: stack scanning
106  0x7f940e507000
    rsp = 0x00007ffddc859f28   rip = 0x00007f940e507000
    Found by: stack scanning
107  electron + 0x182c440
    rsp = 0x00007ffddc859f48   rip = 0x0000564b1cf1a440
    Found by: stack scanning
```

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Fixes #24823.
Fixes https://github.com/electron/electron/issues/24094.

Prior to this change, `ElectronBrowserContext` was held with a `scoped_refptr`, which lead to some code paths creating and then immediately destroying a browser context, with surprising results.

ezgif com-add-text

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).
- [x] This is **NOT A BREAKING CHANGE**. Breaking changes may not be merged to master until 11-x-y is branched.

#### Release Notes

Notes: Fixed a crash that could occur when using in-memory sessions.

### CODE REVIEW

**Comment by deepak1556** [comment]
QQ: previously the lifetime of browser context was tied to the lifetime of session mainly because of refcount, with this change will the browser context live till the v8 context in main process is destroyed ?

Follow-up question, if an app creates multiple short lived sessions an example would be isolating different webview hosting third party content, will these long lived browser context now cause an increase in memory for the main process over the lifetime of the app ?

**Comment by nornagon** [comment]
> QQ: previously the lifetime of browser context was tied to the lifetime of session mainly because of refcount, with this change will the browser context live till the v8 context in main process is destroyed ?

Lifetime of the session == lifetime of the v8 context in main process.

https://github.com/electron/electron/blob/8798571a77a4d2a7e073b046d2e8b56caa4d1e68/shell/browser/api/electron_api_session.cc#L942-L944

**Comment by deepak1556** [comment]
Ah okay, then why is this crash seen when session holds a reference to the browser context ?

**Comment by nornagon** [comment]
Because the browser context isn't always created with a session.

**Comment by deepak1556** [comment]
I keep forgetting we have `//extensions` 🤦 

Thanks for the clarification!

File: shell/browser/common_web_contents_delegate.cc [hunk 1]
```diff
@@ -253,11 +253,11 @@ void CommonWebContentsDelegate::ResetManagedWebContents(bool async) {
     base::ThreadTaskRunnerHandle::Get()->PostNonNestableTask(
         FROM_HERE,
         base::BindOnce(
-            [](scoped_refptr<ElectronBrowserContext> browser_context,
+            [](ElectronBrowserContext* browser_context,
                std::unique_ptr<InspectableWebContents> web_contents) {
               web_contents.reset();
             },
-            base::RetainedRef(browser_context_), std::move(web_contents_)));
+            base::Unretained(browser_context_), std::move(web_contents_)));
```
Comment (deepak1556) [inline shell/browser/common_web_contents_delegate.cc:260]: this should not be needed anymore https://github.com/electron/electron/commit/363aafc25b945567e6ab596edb52d319df2701cc, can you remove and see if crash happens.

```
base::ThreadTaskRunnerHandle::Get()->DeleteSoon(FROM_HERE,
                                                web_contents_.release());
```

Comment (nornagon) [reply shell/browser/common_web_contents_delegate.cc:260]: nice catch, updated.

**Comment by nornagon** [comment]
CI failures unrelated; merging.
