### PR TITLE
app: select-client-certificate event callback can accept certificate optionally

### LINKED ISSUE #8088: There should be a way to skip client cert request
* Electron version: 1.4.8
* Operating system: Windows 8.1 x64

### Expected behavior

**There should be a way to skip client cert request.**

Server can ask for the client cert optionally and even if the client didn't send client certificate, server will still continues with the connection as usual. 

For ex, Tomcat can be configured like: `<Connector port="9443" protocol="HTTP/1.1" clientAuth="want" scheme="https" ...>`. Similarly, Node.js server can be configured to `{requestCert: true, rejectUnauthorized: false, ...}` while creating server instance (as mentioned [here](https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener)). Server can be configured like this, and another filter/middleware can reject the request for some resources.

### Actual behavior

Currently there is no way to not sending any client cert when server asks for it. 

If I call the `callback` without any certificate arg, `Caught unhandled exception: TypeError: Insufficient number of arguments.` is coming. If I didn't invoke the `callback` at all, the request is in pending state till the timeout occur, which is expected.

### How to reproduce

    app.on('select-client-certificate', (event, webContents, url, list, callback) => {
        event.preventDefault()
        callback(list[ 0 ])
    })

### PR DESCRIPTION
**Pull request by deepak1556**
Fixes #8088

### CODE REVIEW

File: spec/static/main.js [hunk 1]
```diff
@@ -184,3 +185,20 @@ app.on('ready', function () {
...
   })
 })
+
+ipcMain.on('set-client-certificate-option', function (event, skip) {
+  app.once('select-client-certificate', function (event, webContents, url, list, callback) {
+    event.preventDefault()
+    if (skip) {
+      callback()
+    } else {
+      assert.equal(list.length, 1)
```
Comment (kevinsawicki) [inline spec/static/main.js]: Just curious, could this still be done in the render process?

Assertion failures in the main process cause the specs to immediately terminate on CI, where as in the render process they will continue to run and finish.

File: atom/browser/api/atom_api_app.cc [hunk 2]
```diff
@@ -380,7 +380,7 @@ void OnClientCertificateSelected(
     mate::Arguments* args) {
   mate::Dictionary cert_data;
   if (!args->GetNext(&cert_data)) {
-    args->ThrowError();
```
Comment (kevinsawicki) [inline atom/browser/api/atom_api_app.cc]: So if you call the callback with an empty object, string, number, etc. now it will continue the request where previously it would error out.

Perhaps it would be better to explicitly check for the argument being null/undefined and still throw an error when an invalid parameter was specified to prevent accidental continuing.

What do you think?

Comment (deepak1556) [inline atom/browser/api/atom_api_app.cc]: Sounds good to throw error for invalid arguments.

**Comment by deepak1556** [comment]
Have addressed the comments, thanks!

File: atom/browser/api/atom_api_app.cc [hunk 3]
```diff
@@ -378,9 +378,21 @@ void OnClientCertificateSelected(
     v8::Isolate* isolate,
     std::shared_ptr<content::ClientCertificateDelegate> delegate,
     mate::Arguments* args) {
+  if (args->Length() == 2) {
```
Comment (kevinsawicki) [inline atom/browser/api/atom_api_app.cc]: I'm not sure I understand this check for `2` here.

Calling `callback(cert, null)` would hit here and return early and not use the cert  but calling `callback(cert, null, null)` would continue with the cert. 

What case is this targeting?

Comment (deepak1556) [inline atom/browser/api/atom_api_app.cc]: We want request to continue with `nullptr` when the callback is called with no arguments or null. Here `callback` has already two bound arguments on c++ side, so when `callback()` is called, the condition will be satisfied.

Comment (kevinsawicki) [inline atom/browser/api/atom_api_app.cc]: Oh awesome, totally makes sense, thanks for explaining 👍

**Comment by kevinsawicki** [comment]
Thanks for this @deepak1556 🚢
