### PR TITLE
Fix frameless windows with vibrancy

### LINKED ISSUE #10521: hiddenInset and vibrancy cause a invisible/low-alpha titlebar on 10.13
* Electron version: 1.7.6
* Operating system: MacOS High Sierra GM

### Expected behavior

Title bar should not be invisible

screen shot 2017-09-14 at 11 22 04 am

### Actual behavior

Title bar is invisible

### How to reproduce
```
  mainWindow = new BrowserWindow({
      vibrancy: 'light',
      titleBarStyle: 'hiddenInset',
      width: 800,
      height: 600
  })
```

```
 $ git clone git@github.com:gerges/electron-quick-start.git -b  issue/invisible-titlebar
 $ npm install
 $ npm run start
```

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #10521 

Tested with `setVibrancy` as well so this supports dynamically switching vibrancy still as well.

### CODE REVIEW

File: atom/browser/native_window_mac.mm [hunk 1]
```diff
@@ -1682,12 +1684,30 @@ static bool FromV8(v8::Isolate* isolate, v8::Handle<v8::Value> val,
...
+    auto render_view_host = web_contents()->GetRenderViewHost();
+    if (render_view_host) {
+      content::RenderWidgetHostImpl* impl = content::RenderWidgetHostImpl::FromID(
+          render_view_host->GetProcess()->GetID(),
+          render_view_host->GetRoutingID());
+      if (impl)
+        impl->SetBackgroundOpaque(opaque);
+    }
+  }
+}
```
Comment (ckerr) [inline atom/browser/native_window_mac.mm]: This is a pretty egregious [demeter violation](https://hackernoon.com/object-oriented-tricks-2-law-of-demeter-4ecc9becad85) but I'm not sure what the Right Thing is here since some of these conditionals are for upstream classes out of our control :thinking:

File: atom/browser/native_window_mac.h [hunk 2]
```diff
@@ -213,6 +215,9 @@ class NativeWindowMac : public NativeWindow,
   NSRect original_frame_;
   NSUInteger simple_fullscreen_mask_;
 
+  NSColor* background_color_before_vibrancy_ = nil;
```
Comment (ckerr) [inline atom/browser/native_window_mac.h]: I'm not positive but should this be a `base::scoped_nsobject<NSColor>`?

File: atom/browser/native_window_mac.mm (hunk 1 above)
Comment (MarshallOfSound) [reply atom/browser/native_window_mac.mm]: Yeah, I tried to collapse it as much as I could but everything is just consecutive potentially nullptr values 🤔

File: atom/browser/native_window_mac.h (hunk 2 above)
Comment (MarshallOfSound) [reply atom/browser/native_window_mac.h]: You right 👍 😄

**Comment by MarshallOfSound** [comment]
@ckerr Updated 👍

File: atom/browser/native_window_mac.mm (hunk 1 above)
Comment (MarshallOfSound) [reply atom/browser/native_window_mac.mm]: I inverted the logic to collapse it a bit 👍

Comment (MarshallOfSound) [reply atom/browser/native_window_mac.mm]: Still like 4 steps of separation though so idk 🤔

**Comment by sallar** [comment]
@codebytere when do you think this will be released?

**Comment by codebytere** [comment]
@sallar it's on the table for 2.0, i believe, so fairly soon

**Comment by HuChundong** [comment]
not include in 2.0 beta1?

**Comment by MarshallOfSound** [comment]
@HuChundong It should be, do you have a case where it's not working?

**Comment by HuChundong** [comment]
@MarshallOfSound  
yes,there is something wrong with me, at first i'm sorry for my poor english,thanks for your quick reply
``
  mainWindow = new BrowserWindow({
    height: 540,
    minHeight: 540,
    width: 830,
    minWidth: 830,
    useContentSize: true,
    webPreferences: {webSecurity: false},
    resizable: true,
    alwaysOnTop: false,
    transparent: true,
    show: false,
    frame: false,
    titleBarStyle: 'hiddenInset',
    vibrancy: 'ultra-dark'
  })
``

this main window still lose round corner in high sierra 10.13.3
i need to set fullscreen and then exit full screen to get round corner back

**Comment by MarshallOfSound** [comment]
This PR was not intended to fix the round / square corner issue.  There is a separate open issue for that

**Comment by tcaer** [comment]
Hi, I don't know what I am doing wrong but this is still not working for me... running MacOS 10.13.3. I still get the same error of the transparent bar showing up.
Here is my window code:
```
function createWindow() {
	var bounds = electron.screen.getPrimaryDisplay().workAreaSize;

	/*
	* Fix the issue where the window bounds are not correct in windows 10
	*/
	var shouldMaximize;
	if (process.platform == 'win32') {
		if (bounds.x === 0 || bounds.y === 0 || bounds.x === -8 || bounds.y === -8) {
        	var screenSize = electron.screen.getPrimaryDisplay().workAreaSize
        	if ((screenSize.width === bounds.width || bounds.width - screenSize.width === 16) && (screenSize.height === bounds.height || bounds.height - screenSize.height === 16)) {
          		shouldMaximize = true
        	}
      	}
	}

	mainWindow = new electron.BrowserWindow({
		width: bounds.width,
		minWidth: 300,
		height: bounds.height,
		minHeight: 430,
		x: 0,
		y: 0,
		titleBarStyle: 'hidden-inset',
		show: false,
		frame: false,
		vibrancy: 'light'
	});

	if (shouldMaximize) {
		mainWindow.maximize();
	}

	if (process.platform == 'win32') {
		mainWindow.setMenu(null);
	}

	mainWindow.loadURL(path.join('file://', __dirname, '/public/app/index.html'));

	mainWindow.once('ready-to-show', function() {
		mainWindow.show();
	});

	mainWindow.on('closed', function() {
		mainWindow = null;
	});
}
```

**Comment by sallar** [comment]
@huangruichang @tcaer Remove `frame: false` from your configs to see if it makes any difference.

**Comment by huangruichang** [comment]
@sallar Maybe I am not the person you wanna notice :rofl:

**Comment by tcaer** [comment]
@sallar No luck... I get the square corners and the invisible tab :/

**Comment by MarshallOfSound** [comment]
@tcaer Can you share repro?

**Comment by Igor10k** [comment]
@tcaer add `transparent: true`. The invisible tab should disappear but that was working even before this PR. There's no fix for the rounded corners though.

Judging by your comments this PR fixes nothing.

**Comment by sallar** [comment]
I just tested beta1. This fix changes nothing. Vibrancy+Square Corners was also possible before (using `transparent: true` and `frame: false`). This issue should be re-opened.

image

**Comment by tommoor** [comment]
Also just tested and unfortunately I'm also seeing much worse behavior than before the fix.

Previously there was just a transparent area where the titlebar would normally be – now it's showing corrupted artifacts and the titlebar has reverted to the standard thickness / position even with `titleBarStyle: "hidden-inset"` window option.

image

**Comment by MarshallOfSound** [comment]
@tommoor Super weird, let me test this real quick 🤔

**Comment by MarshallOfSound** [comment]
@tommoor Two quick things

* `hidden-inset` shouldn't be an option in 2.0.0-beta.1 it has been replaced with `hiddenInset` (the other one was deprecated for a while)
* Can you share your exact browser window constructor options object, I can't repro what you have a screenshot of

**Comment by tommoor** [comment]
Oh, interesting I did check the release notes for breaking changes and there wasn't a mention of that property being deprecated but that would explain the first part of the issue 😄. I wonder if having the deprecated option there caused it. Was the deprecation removed in 2.0? If so I guess we should add that to the notes.

The screenshot doesn't capture it too well, basically the entire titlebar is showing artifacts depending on what's behind - It mostly looks black / transparent. Options are:

```
{
      titleBarStyle: "hidden-inset",
      acceptFirstMouse: true,
      file: "index",
      webPreferences: { scrollBounce: true, textAreasAreResizable: false },
      x,
      y,
      width,
      height
}
```

**Comment by MarshallOfSound** [comment]
And just to prove no bamboozle, here is a screenshot from `electron-quick-start` using the above config using `electron@2.0.0.-beta.1`

screen shot 2018-02-27 at 3 24 09 pm

**Comment by tommoor** [comment]
Thanks @MarshallOfSound – I'm out for the day now, but I'll try with 2.0 again tomorrow and the **correct** hiddenInset option, hopefully that does the trick 👍

**Comment by MarshallOfSound** [comment]
@tommoor It might also be the `frame` and `transparent` options helping out, let me know if you can't make it look like mine 😆

**Comment by tommoor** [comment]
Maybe, I don't want to use those options as the square corners are unacceptable on macOS unfortunately 😞

**Comment by MarshallOfSound** [comment]
Hm, fair enough, we had an issue somewhere for the square corner thing.  Will try take a look at that later this week if I get a chance.

**Comment by tcaer** [comment]
Thanks so much for all the help!

**Comment by MarshallOfSound** [comment]
@tcaer Known bug and I think it's already fixed 😆

**Comment by stevenfabre** [comment]
Hey guys, thanks so much for fixing this!

Does this fix the corner radius bug too? In my build, the top two corners aren't rounded when I use the following settings:

```
titleBarStyle: 'default',
transparent: true,
vibrancy: 'dark',
```

**Comment by mlabod** [comment]
Rounded corners are still missing at the top edges, when vibrancy is activated. 
Tested in Electron `2.0.2`
