### PR TITLE
fix: window bounds not scaled from screen coordinates

### LINKED ISSUE #25811: Will-move event listener newBounds parameter incorrect value
I have created simple window and add `will-move` listener. After moving window little bit down (few pixels only in vertical direction), `will-move` listener is called with `newBounds` parameter object, that contains incorrect values (`x`, `width`, `height` changed). Please look at simple demonstation:

Script:
```
mainWindow.once('will-move', (e, newBounds) => {
   console.log('Window current bounds: ', mainWindow.getBounds());
   console.log('Window newBounds', newBounds);
})
```
Result (logs in terminal after moving window little bit down (few pixels only in vertical direction)):

image

As you can see, here `x` property changed (but it should not, because i'm moving window only in vertical direction), `height` and `width` also changed (but it should not, because i'm not resizing window, i'm just moving it).

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.1
* **Operating System:**
  * Windows 10 (version 1903, 18362.1082)
* **Last Known Working Electron version:**
  * -

### Expected Behavior
`newBounds` parameter value should have `x`, `width` and `height` values same as in bounds returned by `mainWindow.getBounds()` but only `y` value should be different (because i'm moving window little bit down).

### Actual Behavior

As you can see, here after moving window little bit down (few pixels only in vertical direction), `x`, `width` and `height` properties values in `newBounds` is not same as the corresponding properties values in bounds object returned by `mainWindow.getBounds()`.

### To Reproduce
I have created demo branch from quick start repo: [demo commit](https://github.com/bohdanzhylavskyi/electron-quick-start/commit/fa8f3ef0713b6476eb18d47ad762fc47f2fb0f22). To reproduce please run application `npm start`, try to move window and look at terminal log.

### PR DESCRIPTION
**Pull request by samuelmaddock**
#### Description of Change

fixed #25811

possibly related to #25420 #21777

On Windows, the `will-resize` and `will-move` events emit the pending bounds of the window. However, they're reported in screen coordinates which aren't scaled according to the display scale factor.

Here's a clip of a window being moved between a 4k and 1080p monitor which causes its scale factor to change. The width/height of `newBounds` remains the same with this fix.

(as an aside, there seems to be an unrelated rounding bug with the width/height of `currentBounds` you can also see)

https://user-images.githubusercontent.com/1656324/118202321-a9c64680-b427-11eb-82d0-8574ee10eb58.mp4

No tests are included as I'm not sure whether we have a way to test display scale changes.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed `will-resize` and `will-move` events not scaling the emitted `newBounds` rectangle to the appropriate Windows display scale factor.

### CODE REVIEW

File: shell/browser/native_window_views_win.cc [hunk 1]
```diff
@@ -260,11 +260,12 @@ bool NativeWindowViews::PreHandleMSG(UINT message,
...
-      NotifyWindowWillResize(gfx::Rect(*reinterpret_cast<RECT*>(l_param)),
-                             &prevent_default);
+      gfx::Rect bounds = gfx::Rect(*reinterpret_cast<RECT*>(l_param));
+      HWND hwnd = GetAcceleratedWidget();
+      gfx::Rect dpi_bounds = ScreenToDIPRect(hwnd, bounds);
+      NotifyWindowWillResize(dpi_bounds, &prevent_default);
       if (prevent_default) {
-        ::GetWindowRect(GetAcceleratedWidget(),
-                        reinterpret_cast<RECT*>(l_param));
+        ::GetWindowRect(hwnd, reinterpret_cast<RECT*>(l_param));
```
Comment (samuelmaddock) [inline shell/browser/native_window_views_win.cc:268]: Anyone know what the purpose of this line is?

Comment (pavelserbajlo) [reply shell/browser/native_window_views_win.cc:268]: this line makes very little sense to me 🤔

**Review by pavelserbajlo — APPROVED** [review]
changes look good to me, amazing catch, Sam! 👏 👏

File: shell/browser/native_window_views_win.cc (hunk 1 above)
Comment (samuelmaddock) [reply shell/browser/native_window_views_win.cc:268]: This line is responsible for preventing the window from moving or resizing depending on the event. It's very unclear how it works given the description of [GetWindowRect](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowrect).

Comment (samuelmaddock) [reply shell/browser/native_window_views_win.cc:268]: Ah, I realized what it's doing. It's updating `l_param` to the current window dimensions prior to being resizing/moved. This is described in the docs for [`WM_SIZING`](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-sizing).

**Review by MarshallOfSound — APPROVED** [review]

**Review by zcbenz — APPROVED** [review]
