### PR TITLE
fix: update the FileSelectHelper to support the new promise API

### LINKED ISSUE #18254: DCHECK in file chooser
To repro: click on an `<input type=file>` in debug mode.
```
#
# Fatal error in ../../v8/src/api-inl.h, line 126
# Debug check failed: allow_empty_handle || that != nullptr.
#
#
#
#FailureMessage Object: 0x7ffee3550f30Received signal 4 <unknown> 00019dbc4f82
0   libbase.dylib                       0x00000001179e03b1 base::debug::CollectStackTrace(void**, unsigned long) + 33
1   libbase.dylib                       0x00000001176a5ecb base::debug::StackTrace::StackTrace(unsigned long) + 75
2   libbase.dylib                       0x00000001176a5f1d base::debug::StackTrace::StackTrace(unsigned long) + 29
3   libbase.dylib                       0x000000011769a0f5 base::debug::StackTrace::StackTrace() + 37
4   libbase.dylib                       0x00000001179e0221 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 1393
5   libsystem_platform.dylib            0x00007fff7a836b5d _sigtramp + 29
6   ???                                 0x000000000000ffff 0x0 + 65535
7   libv8_libbase.dylib                 0x000000019dbbc045 v8::base::(anonymous namespace)::DefaultDcheckHandler(char const*, int, char const*) + 21
8   libv8.dylib                         0x0000000172cc363e v8::Utils::OpenHandle(v8::Context const*, bool) + 270
9   libv8.dylib                         0x0000000172cc7366 v8::Context::Enter() + 38
10  Electron Framework                  0x000000010e3fbb29 v8::Context::Scope::Scope(v8::Local<v8::Context>) + 57
11  Electron Framework                  0x000000010e3fb88d v8::Context::Scope::Scope(v8::Local<v8::Context>) + 29
12  Electron Framework                  0x000000010e425314 v8::MaybeLocal<v8::Promise> atom::util::Promise::Then<void, bool, std::__1::vector<base::FilePath, std::__1::allocator<base::FilePath> > const&>(base::OnceCallback<void (bool, std::__1::vector<base::FilePath, std::__1::allocator<base::FilePath> > const&)>) + 132
13  Electron Framework                  0x000000010e4225fc (anonymous namespace)::FileSelectHelper::ShowOpenDialog(file_dialog::DialogSettings const&) + 236
14  Electron Framework                  0x000000010e421b6b atom::WebDialogHelper::RunFileChooser(content::RenderFrameHost*, std::__1::unique_ptr<content::FileSelectListener, std::__1::default_delete<content::FileSelectListener> >, blink::mojom::FileChooserParams const&) + 987
15  Electron Framework                  0x000000010e302e24 atom::CommonWebContentsDelegate::RunFileChooser(content::RenderFrameHost*, std::__1::unique_ptr<content::FileSelectListener, std::__1::default_delete<content::FileSelectListener> >, blink::mojom::FileChooserParams const&) + 212
16  libcontent.dylib                    0x000000011b43801c content::WebContentsImpl::RunFileChooser(content::RenderFrameHost*, std::__1::unique_ptr<content::FileSelectListener, std::__1::default_delete<content::FileSelectListener> >, blink::mojom::FileChooserParams const&) + 156
17  libcontent.dylib                    0x000000011a909e37 content::FileChooserImpl::OpenFileChooser(mojo::StructPtr<blink::mojom::FileChooserParams>, base::OnceCallback<void (mojo::StructPtr<blink::mojom::FileChooserResult>)>) + 471```

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #18254

So it turns out we've successfully introduced a way to write
non-typesafe C++.

This fixes two things:
* Uses the object the promise resolves
* Ensures we attach the Then handler before moving the promise

Notes: Fixed the `input[type=file]` element not showing a file dialog

### CODE REVIEW

File: atom/browser/web_dialog_helper.cc [hunk 1]
```diff
@@ -123,7 +123,6 @@ class FileSelectHelper : public base::RefCounted<FileSelectHelper>,
       listener_.reset();
     }
     render_frame_host_ = nullptr;
-    Release();
```
Comment (MarshallOfSound) [inline atom/browser/web_dialog_helper.cc]: This was causing a crash because we were releasing an already-released ref.  (ref_count_ was `0`)

File: atom/common/promise_util.h [hunk 2]
```diff
@@ -104,9 +104,25 @@ class Promise {
...
+  // Please note that using Then is effectively the same as calling .then
+  // in javascript.  This means (a) it is not type safe and (b) please note
+  // it is NOT type safe.
+  // If the base::Callback you provide here is of type void(boolean) and you
+  // resolve the promise with a string, Electron will compile successfully and
+  // then that promise will be rejected as soon as you try to use it as the
+  // mate converters doing work behind the scenes will throw an error for you.
+  // This can be really hard to trace so until either
+  //   * This helper becomes typesafe (by templating the class instead of each
+  //   method)
```
Comment (ckerr) [inline atom/common/promise_util.h]: If we're already doing this anywhere, would be great to cite an example here so that devs looking to use this function in the future will have something to crib from as an alternative to using `Then()`

File: atom/browser/web_dialog_helper.cc (hunk 1 above)
Comment (ckerr) [reply atom/browser/web_dialog_helper.cc]: It's not clear to me, is `ref_count_` _always_ 0 when we reach this point, e.g. regardless of whether or not it was cancelled?

File: atom/browser/atom_download_manager_delegate.cc [hunk 3]
```diff
@@ -127,63 +127,57 @@ void AtomDownloadManagerDelegate::OnDownloadPathGenerated(
...
-    bool result,
-    const base::FilePath& path,
-    const std::string& bookmark)
-#else
 void AtomDownloadManagerDelegate::OnDownloadSaveDialogDone(
     uint32_t download_id,
     const content::DownloadTargetCallback& download_callback,
-    bool result,
-    const base::FilePath& path)
-#endif
```
Comment (ckerr) [inline atom/browser/atom_download_manager_delegate.cc]: :+1: on dropping the `#ifdef`s

File: atom/common/promise_util.h [hunk 4]
```diff
@@ -104,9 +104,25 @@ class Promise {
...
+  //   * or the world goes mad
+  // Please try your hardest not to use this method
+  // The world thanks you
+  template <typename... ResolveType>
   v8::MaybeLocal<v8::Promise> Then(
-      base::OnceCallback<ReturnType(ArgTypes...)> cb) {
+      base::OnceCallback<void(ResolveType...)> cb) {
+    static_assert(sizeof...(ResolveType) <= 1,
```
Comment (ckerr) [inline atom/common/promise_util.h]: :+1:

File: atom/common/promise_util.h (hunk 2 above)
Comment (MarshallOfSound) [reply atom/common/promise_util.h]: We're not doing this yet, I plan at some point to follow up and do this but it's a bigger / more time consuming fix

File: atom/browser/web_dialog_helper.cc (hunk 1 above)
Comment (MarshallOfSound) [reply atom/browser/web_dialog_helper.cc]: Based on my testing, yes, the ref count appears to be working fine now

File: atom/browser/atom_download_manager_delegate.cc (hunk 3 above)
Comment (nornagon) [reply atom/browser/atom_download_manager_delegate.cc]: what do we lose by dropping the `bookmark`s?

Comment (MarshallOfSound) [reply atom/browser/atom_download_manager_delegate.cc]: Nothing, the `bookmark` is exposed to the user facing API.  Not the internal chromium usage
