### PR TITLE
fix: check for draggable regions outside of main frame

### LINKED ISSUE #41212: [Bug]: `-webkit-app-region: drag` still doesn't works after #41030
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

29.0.0-beta.4

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2 (22631)

### What arch are you using?

x64

### Last Known Working Electron version

29.0.0-alpha.7

### Expected Behavior

If `-webkit-app-region: drag` was used, it should be possible to click on the region and drag the `Window`. 

### Actual Behavior

It will behave as if the property is not applied.

### Testcase Gist URL

https://gist.github.com/JellyBrick/ec1ef4b79d55bc8a46fcdcd289259996

### Additional Information

In this case (gist), `YouTube` internally overrides the browser's events (like `MouseEvent`, `Event`, etc), which seems to cause `-webkit-app-region: drag` to be ignored. (Until `29.0.0-alpha.7`, `-webkit-app-region: drag` was not ignored and worked fine)

- Related to #40985

### PR DESCRIPTION
**Pull request by VerteDinde**
#### Description of Change

Fixes #41212 

Fixes a bug introduced by [crrev.com/c/4814003](https://chromium-review.googlesource.com/c/chromium/src/+/4814003), where draggable regions on local frames (set using the app-region CSS property) are no longer automatically set and calculated unless an app uses a Window Controls Overlay or is Borderless. In the upstream CL, the change assumes that the local frame is a browser tab, and doesn't need draggable regions calculated; on Electron's side, we can't make that assumption.

This PR modifies the check to `SetSupportsAppRegion()` to also check for frames outside of the main frame.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed an issue where the `-webkit-app-region: drag` property was not respected on some windows.

### CODE REVIEW

**Review by codebytere — APPROVED** [review]

**Review by ckerr — APPROVED** [review]

File: shell/renderer/electron_render_frame_observer.cc [hunk 1]
```diff
@@ -58,10 +58,10 @@ ElectronRenderFrameObserver::ElectronRenderFrameObserver(
...
   net::NetModule::SetResourceProvider(NetResourceProvider);
 
-  // App regions are only supported in the main frame.
-  auto* main_frame = frame->GetMainRenderFrame();
-  if (main_frame && main_frame == frame)
-    render_frame_->GetWebView()->SetSupportsAppRegion(true);
+  // In Chrome, app regions are only supported in the main frame.
+  // However, we need to support draggable regions on other
+  // local frames/windows, so extend support beyond the main frame.
+  render_frame_->GetWebView()->SetSupportsAppRegion(true);
```
Comment (deepak1556) [inline shell/renderer/electron_render_frame_observer.cc:64]: Reason for excluding child frames was devtools inspect gets broken, refs https://electronhq.slack.com/archives/CB6CG54DB/p1705578798763399?thread_ts=1705578659.730389&cid=CB6CG54DB. Please check if inspect continues to work with this change.

/cc @marekharanczyk
