### PR TITLE
fix: resolve getFileHandle concurrent stalling by queuing callbacks

### LINKED ISSUE #50559: `getFileHandle` (and `getDirectoryHandle`) hangs on concurrent calls for the same path
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

41.1.0

### What operating system(s) are you using?

macOS

### Operating System Version

macos 15.7.3 (24G419)

### What arch are you using?

arm64

### Last Known Working Electron version

_No response_

### Does the issue also appear in Chromium / Google Chrome?

No

### Expected Behavior

when calling `getFileHandle` on the same path concurrently (e.g. via Promise.all), both promises resolve with the same result

### Actual Behavior

both promises hang indefinitely

### Testcase Gist URL

https://gist.github.com/teidesu/423012d643f517875c752d8124888617

1. open some directory
2. click "Test Sequential" - notice everything works fine
3. click "Test Concurrent" - notice how both promises hang and nothing is printed

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by xakep8**
#### Description of Change

Closes #50559

Previously, concurrent calls to FileSystemAccessPermissionContext::ConfirmSensitiveEntryAccess for the same file path would silently discard the subsequent callbacks because the internal callback map used a single callback per file path and std::map::try_emplace would drop the callback if the key already existed. This caused Promises in JS (e.g., dirHandle.getFileHandle()) to stall indefinitely.

This commit updates the callback map to hold a vector of callbacks, so all concurrent requesters for the same filepath are grouped together and resolved once the asynchronous blocklist check completes.

#### Checklist

- [x] PR description included
- [x] I have built and tested this PR
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant API documentation, tutorials, and examples are updated and follow the [documentation style guide](https://github.com/electron/electron/blob/main/docs/development/style-guide.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed an issue where concurrent `getFileHandle` requests on the same path could stall indefinitely.

### CODE REVIEW

**Comment by xakep8** [comment]
@deepak1556 does this seem like a possible fix?

File: shell/browser/file_system_access/file_system_access_permission_context.cc [hunk 1]
```diff
@@ -697,7 +697,13 @@ void FileSystemAccessPermissionContext::ConfirmSensitiveEntryAccess(
...
     base::OnceCallback<void(SensitiveEntryResult)> callback) {
   DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
-  callback_map_.try_emplace(path_info.path, std::move(callback));
+
+  auto result = callback_map_.try_emplace(
+      path_info.path,
+      std::vector<base::OnceCallback<void(SensitiveEntryResult)>>());
+  result.first->second.push_back(std::move(callback));
+  if (!result.second)
+    return;
```
Comment (deepak1556) [inline shell/browser/file_system_access/file_system_access_permission_context.cc]: can be implicit with

```suggestion
  auto [it, _] = callback_map_.try_emplace(path_info.path);
  it->second.push_back(std::move(callback));
```

File: spec/chromium-spec.ts [hunk 2]
```diff
@@ -1065,6 +1065,51 @@ describe('chromium features', () => {
...
+        show: false,
+        webPreferences: {
+          nodeIntegration: true,
+          contextIsolation: false,
+          sandbox: false
+        }
+      });
+
+      w.webContents.session.setPermissionRequestHandler((wc, permission, callback) => {
+        callback(true);
```
Comment (deepak1556) [inline spec/chromium-spec.ts]: Isolate the session or scope it to filesystem similar to other specs in this group, don't allow all permissions especially bad when this is the default session.

```
if (permission === 'fileSystem') {
    const { href } = url.pathToFileURL(writablePath);
   expect(details).to.deep.equal({
          fileAccessType: 'writable',
          isDirectory: false,
          isMainFrame: true,
          filePath: testFile,
          requestingUrl: href
        });
    callback(true)
}
```
