### PR TITLE
Handle empty handles

### LINKED ISSUE #11593: Segfault calling Browser window with options Proxy.
* Electron version: 1.6.15
* Operating system: Linux

### Expected behavior

Open a `BrowserWindow` with passed options

### Actual behavior

  - Usually a Segmentation fault.
  - Sometimes `[12843:0100/000000.043847:FATAL:zygote_linux.cc(479)] Failed to synchronise with parent zygote process`
  - Sometimes `[12819:0100/000000.719122:FATAL:zygote_linux.cc(509)] Check failed: len > 0 (0 vs. 0)`

### How to reproduce

I'm still working on making a smaller reproduction case. The issue goes away with small tweaks.

1. Starting from https://github.com/daurnimator/fengari-electron-example
2. Modify main.lua to contain:
```lua
local js = require "js"
local electron = require "electron"

electron.app:on("ready", function()
	local win = js.new(electron.BrowserWindow, js.createproxy({
		backgroundColor = '#2e2c29';
	}, "object"))
	win:loadURL("https://fengari.io")
end)
```

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #11593

Basically just because we have a `mate::Handle` doesn't mean it actually contains anything.  In fact, a `mate::Handle` is deliberately made when the `v8::Value` is `null` or `undefined`.  I think I found all the cases where we need to do this check 👍

### CODE REVIEW

File: spec/api-browser-window-spec.js [hunk 1]
```diff
@@ -86,6 +86,14 @@ describe('BrowserWindow module', () => {
     return closeWindow(w).then(() => { w = null })
   })
 
+  describe('BrowserWindow constructor', () => {
+    it('allows passing void 0 as the webContents', () => {
+      w = new BrowserWindow({
+        webContents: void 0
```
Comment (alexeykuzmin) [inline spec/api-browser-window-spec.js]: Can we simply use `undefined` here? )
I have never seen the `void` operator being used and I guess a lot of people don't  know it even exists )

**Comment by alexeykuzmin** [comment]
@MarshallOfSound Can you please rebase your branch onto the latest master?
to check if the test failures are caused by your changes or not.

File: spec/api-browser-window-spec.js (hunk 1 above)
Comment (MarshallOfSound) [reply spec/api-browser-window-spec.js]: `undefined` didn't trigger the failure in this exact case, I'm assuming because we have an undefined check somewhere else 🤔 `void 0` triggered it everytime so I just left that in the test

Comment (alexeykuzmin) [reply spec/api-browser-window-spec.js]: That's weird. [`void` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void) simply returns the `undefined` value for any expression it's used with. There cannot be any difference.

**Comment by alexeykuzmin** [comment]
The tests keep failing =/
