### PR TITLE
fix: prevent traffic light buttons flashing on deminiaturize

### LINKED ISSUE #50099: trafficLightPosition buttons flash at (0,0) on minimize/restore (macOS)
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

40.7.0

### What operating system(s) are you using?

macOS

### Operating System Version

MacOS 26.2

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

_No response_

### Does the issue also appear in Chromium / Google Chrome?

No

### Expected Behavior

When a window with `titleBarStyle: 'hiddenInset'` and `trafficLightPosition: { x: 31, y: 26 }` is minimized and then restored (via dock click or `app.on('activate')`), the native traffic light buttons (close, minimize, fullscreen) should appear at the configured position (31, 26) immediately, without any visible movement or repositioning during the restore animation.

### Actual Behavior

When the window is restored from minimization, the traffic light buttons briefly appear at position (0, 0) — the top-left corner of the window frame — instead of the configured `trafficLightPosition`. After approximately 1 second, they jump to the correct configured position (31, 26). This creates a visible flash and repositioning artifact during the restore animation.

### Testcase Gist URL

https://gist.github.com/rubywwwilde/031350b7c4d91f5afc0e2cff51bb6173

### Additional Information

- Electron Fiddle itself exhibits the same bug — traffic lights flash at (0, 0) on minimize/restore
- `titleBarOverlay: { height }` alone does not fix it
- `setWindowButtonPosition()` in `restore`/`show`/`focus` event handlers does not fix it (fires too late)
- Hiding buttons before minimize with `setWindowButtonVisibility(false)` does not fix it
- The flash occurs on every minimize/restore cycle

**Workaround:** Calling `win.show()` in the `activate` handler forces a state transition that avoids the flash:

```js
app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  } else if (win) {
    win.show()
  }
})
```

This was discovered by reducing Mattermost Desktop's behavior — their activation/show path prevented the flash.

This report was written with the help of AI, though I read every piece of it, it may contain errors.

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Fixes https://github.com/electron/electron/issues/50099

When a window with a custom `trafficLightPosition` is minimized and restored, macOS re-layouts the title bar container during the deminiaturize animation, causing the traffic light buttons to briefly appear at their default position before being repositioned.

Fix this by hiding the buttons container in `windowWillMiniaturize` and restoring them (with a redraw to the correct position) in `windowDidDeminiaturize`.

Tested with https://gist.github.com/rubywwwilde/031350b7c4d91f5afc0e2cff51bb6173

Fixes #50099

#### Checklist

- [x] PR description included
- [x] I have built and tested this PR
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed an issue where traffic light buttons would flash at position (0,0) when restoring a window with a custom `trafficLightPosition` from minimization on macOS.

### CODE REVIEW

**Comment by nikwen** [comment]
Mark as "Fixes https://github.com/electron/electron/issues/50099"?

File: shell/browser/native_window_mac.mm [hunk 1]
```diff
@@ -1535,6 +1535,18 @@ static bool FromV8(v8::Isolate* isolate,
     [buttons_proxy_ redraw];
 }
 
+void NativeWindowMac::PrepareTrafficLightsForMiniaturize() {
```
Comment (deepak1556) [inline shell/browser/native_window_mac.mm]: Seems like nice wrappers to hide and restore the button container, could we rename it as `HideTrafficLights` and `ShowTrafficLights` to be reused in other places that need them as well ?

**Review by deepak1556 — COMMENTED** [review]
LGTM, just a comment about reusing the new functions.
