### PR TITLE
fix: move BrowserWindow's WebContentsView to be a child of rootview

### LINKED ISSUE #41141: [Bug]: BrowserViews doesn't work correctly on macOS
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.0-nightly.20231214

### What operating system are you using?

macOS

### Operating System Version

13.5

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

30.0.0-nightly.20231213

### Expected Behavior

1. Launch following app
[views_problem.zip](https://github.com/electron/electron/files/14065597/views_problem.zip)
2. Wait for full cycle to complete (all three views show)

After that first view should be displayed again

### Actual Behavior

Views dissapear and none of them shows again.

### Testcase Gist URL

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change

Fixes #41141.

Previously, BrowserWindow#contentView was a reference to the BrowserWindow's
WebContentsView, and any child views that were added would be children of the
WebContentsView. This caused some strange behavior, including BrowserViews
sometimes being painted _behind_ the BrowserWindow's web contents.

This PR has BrowserWindow's WebContentsView be a _sibling_ to the content view,
inserted before it, so that the BrowserWindow's WebContents will always display
behind its children as intended.

It also prevents users from doing dangerous, unsupported and probably entirely
broken things like swapping out the BrowserWindow's contentView for another
view.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed an issue where child views in a BrowserWindow could sometimes be
painted behind the main web content.

### CODE REVIEW

File: shell/browser/api/electron_api_browser_window.cc [hunk 1]
```diff
@@ -92,7 +93,7 @@ BrowserWindow::BrowserWindow(gin::Arguments* args,
   InitWithArgs(args);
 
   // Install the content view after BaseWindow's JS code is initialized.
-  SetContentView(gin::CreateHandle<View>(isolate, web_contents_view.get()));
+  window()->GetContentsView()->AddChildViewAt(web_contents_view->view(), 0);
```
Comment (samuelmaddock) [inline shell/browser/api/electron_api_browser_window.cc:96]: Before:
- Window
  - ContentView (WebContentsView)

After:
- Window
  - ContentView
    - WebContentsView

Is this the expected hierarchy of the views? My understanding is that WebContentsView is a child which has me confused by this line:
> This PR has BrowserWindow's WebContentsView be a **sibling** to the content view

File: shell/browser/api/electron_api_browser_window.cc [hunk 2]
```diff
@@ -77,6 +77,7 @@ BrowserWindow::BrowserWindow(gin::Arguments* args,
       WebContentsView::Create(isolate, web_preferences);
   DCHECK(web_contents_view.get());
   window_->AddDraggableRegionProvider(web_contents_view.get());
+  web_contents_view_.Reset(isolate, web_contents_view.ToV8());
```
Comment (samuelmaddock) [inline shell/browser/api/electron_api_browser_window.cc:80]: This means that the WebContents can't be disposed of without destroying its originating BrowserWindow, right?

File: shell/browser/api/electron_api_browser_window.cc (hunk 1 above)
Comment (nornagon) [reply shell/browser/api/electron_api_browser_window.cc:96]: No, your comment here is inaccurate—"GetContentsView()" here is actually not doing what you think it's doing :)

File: shell/browser/api/electron_api_browser_window.cc (hunk 2 above)
Comment (nornagon) [reply shell/browser/api/electron_api_browser_window.cc:80]: This is already true, I believe.

File: shell/browser/api/electron_api_browser_window.cc (hunk 1 above)
Comment (samuelmaddock) [reply shell/browser/api/electron_api_browser_window.cc:96]: Ahhh, I missed the 's' in `GetContentsView()`. If my understanding is correct, a more accurate picture might look something like this now:

- Window
  - ContentsView (root)
    - WebContentsView
    - ContentView
      - BrowserView (A)
      - BrowserView (B)
      - ...

I think for now this is fine and keeps the expected behavior. In the future, it'd be great if we can simplify it to:

- Window
  - ContentsView (root)
    - ContentView
      - WebContentsView
      - ~~BrowserView~~ WebContentsView
      - ...

Maybe that's possible already by using BaseWindow directly.

**Review by samuelmaddock — APPROVED** [review]
API LGTM

**Comment by samuelmaddock** [comment]
Looks like the menu bar is expecting a different amount of children after this PR

https://github.com/electron/electron/blob/4367c5ad9e44ec6f4464cdd7a08a0e447203d21b/shell/browser/ui/views/root_view.cc#L92-L98

File: shell/browser/api/electron_api_browser_window.cc (hunk 1 above)
Comment (nornagon) [reply shell/browser/api/electron_api_browser_window.cc:96]: I don't think the hierarchy you proposed is desirable for BrowserWindow, as BrowserWindow has a lot of functionality that depends on having one single "blessed" WebContentsView. Having the "blessed" WebContentsView be part of ContentView means it would be accessible to JS, which could e.g. remove it, leading to strange behavior.

File: shell/browser/api/electron_api_browser_window.cc [hunk 3]
```diff
@@ -92,7 +93,8 @@ BrowserWindow::BrowserWindow(gin::Arguments* args,
   InitWithArgs(args);
 
   // Install the content view after BaseWindow's JS code is initialized.
-  SetContentView(gin::CreateHandle<View>(isolate, web_contents_view.get()));
+  window()->GetContentsView()->AddChildViewAt(web_contents_view->view(), 0);
```
Comment (zcbenz) [inline shell/browser/api/electron_api_browser_window.cc:96]: Can you add a comment with a link to the issue?

**Review by zcbenz — APPROVED** [review]
API LGTM

**Comment by zcbenz** [comment]
The WoA CI consistently fails with a `[5812:0228/072758.443:FATAL:frame_subscriber.cc(45)] Check failed: !size.IsEmpty().` crash, can you try merging latest main?

**Comment by zcbenz** [comment]
WoA still crashes, maybe just remove the line?
