### PR TITLE
protocol: allow standard schemes to support filesystem api

### LINKED ISSUE #6949: webkitRequestFileSystem fails with SecurityError in custom protocols
* Electron version:
1.3.3
* Operating system:
OSX El Capitan

```javascript
      function cbError(e) {
         console.error('failure', e);
      }

      navigator.webkitPersistentStorage.requestQuota( 10 * 1024* 1024, function(granted) {
        webkitRequestFileSystem(PERSISTENT, granted, cb, cbError);
      },
      cbError)
```

webkitRequestFileSystem is failing with:

```
FileError {code: 2, name: "SecurityError", message: "It was determined that certain files are unsafe fo… too many calls are being made on file resources."}code: 2message: "It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources."name: "SecurityError"__proto__: FileError
```

This page is being served from a custom:// scheme if that matters.

### PR DESCRIPTION
**Pull request by deepak1556**
It isn't necessary for the scheme to be standard for accessing filesystem api, but the registeration has to happen during context creation which means to add another api to protocol for use before `ready` event. Would it be better to have an api like

```
protocol.registerCustomSchemes({
  'scheme1': 'filesystem, standard',
  'scheme2': 'serviceworker'
})
```

instead of a strict `registerStandardSchemes` api, thoughts ?

Fixes #6949

### CODE REVIEW

File: atom/browser/atom_browser_client.cc [hunk 1]
```diff
@@ -279,6 +280,21 @@ bool AtomBrowserClient::CanCreateWindow(
   return false;
 }
 
+void AtomBrowserClient::GetAdditionalAllowedSchemesForFileSystem(
+    std::vector<std::string>* additional_schemes) {
+  // Parse --standard-schemes=scheme1,scheme2
```
Comment (zcbenz) [inline atom/browser/atom_browser_client.cc]: You can use `GetStandardSchemes` which is defined in `atom_api_protocol.h`.

Comment (deepak1556) [inline atom/browser/atom_browser_client.cc]: Fixed, thanks!

**Comment by zcbenz** [comment]
:+1:
