### PR TITLE
fix: use appropriate site instance for cross-site nav's

### LINKED ISSUE #8100: In sandbox mode, window.opener doesn't work when children are from different domain
* Electron version: 1.4.10
* Operating system: Darwin x64

### Expected behavior
When a popup pointed to a different domain from the parent is opened. window.opener should not be null. It is required for many OAuth authentication where the parent and the child (popup) is from different domains.

### Actual behavior

When a popup is pointed towards the same domain window.opener is present but when its pointed towards a different domain window.opener is null

### How to reproduce

**main.js**
`app.on('ready', () => { console.log("ready"); const win = new BrowserWindow({webPreferences: { sandbox: true }}) win.loadURL('http://localhost:8888/index.html'); })`

**index.html**
`<a href="javascript:window.open('https://app.asana.com')">Click here</a>`

window.opener is null at app.asana.com because the domain is different from the parent

### PR DESCRIPTION
**Pull request by ppontes**
#### Description of Change
When a window is opened with window.open to navigate to a cross-site destination, the new site instance should belong to the browsing instance of the opener window in order not to break scripting relationships between windows.

fixes #8100.

This change turns Chromium's site isolation on and depends on it being on in order to work properly. Turning on site isolation revealed the following latent problems that are / will be fixed also in this PR:
- [X] If a cross-site redirection happens during a navigation, the renderer process that will handle the final URL will be locked to the pre-redirection URL with Chromium's child process security. If the page tries to access local resources, Chromium will refuse and kill the renderer process.
- [X] Chromium now kills renderer processes that attempt to access resources for which they have no permissions. This means that the "custom non standard schemes cannot access localStorage" UT had to be adapted.

The fix also requires the following to be addressed:

- [x] If a cross-site redirection happens during a navigation, Chromium discards the speculative RFH that was created for the pre-redirection URL. This is harmless in Chromium but Electron reacts by asynchronously closing the associated BrowserWindow. User sees the new window navigating to the final URL and then being closed.

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: Fixed a bug where `window.opener` of a window created with window.open from a sandboxed renderer was null.

### CODE REVIEW

File: atom/browser/api/atom_api_web_contents.cc [hunk 1]
```diff
@@ -781,8 +781,23 @@ void WebContents::RenderViewCreated(content::RenderViewHost* render_view_host) {
...
 void WebContents::RenderViewDeleted(content::RenderViewHost* render_view_host) {
   Emit("render-view-deleted", render_view_host->GetProcess()->GetID());
+
+  // When the RVH that has been deleted is the current RVH it means that the
+  // the embedder is closing the window.
+  if (-1 == currently_committed_process_id ||
+      render_view_host->GetProcess()->GetID() ==
+          currently_committed_process_id) {
+    currently_committed_process_id = -1;
+    Emit("current-render-view-deleted",
```
Comment (ppontes) [inline atom/browser/api/atom_api_web_contents.cc]: Better name for this event?

File: atom/browser/api/atom_api_web_contents.cc [hunk 2]
```diff
@@ -781,8 +781,23 @@ void WebContents::RenderViewCreated(content::RenderViewHost* render_view_host) {
     impl->disable_hidden_ = !background_throttling_;
 }
 
+void WebContents::RenderViewHostChanged(content::RenderViewHost* old_host,
+                                        content::RenderViewHost* new_host) {
+  currently_committed_process_id = new_host->GetProcess()->GetID();
```
Comment (deepak1556) [inline atom/browser/api/atom_api_web_contents.cc]: member variables should end with trailing `_`

File: atom/browser/api/atom_api_web_contents.cc [hunk 3]
```diff
@@ -781,8 +781,23 @@ void WebContents::RenderViewCreated(content::RenderViewHost* render_view_host) {
...
+}
+
 void WebContents::RenderViewDeleted(content::RenderViewHost* render_view_host) {
   Emit("render-view-deleted", render_view_host->GetProcess()->GetID());
```
Comment (deepak1556) [inline atom/browser/api/atom_api_web_contents.cc]: A little comment stating that this event is necessary for tracking any states with respect to intermediate render view hosts aka speculative render view hosts. Currently used by `object-registry.js` to ref count remote objects.

File: atom/browser/atom_browser_client.cc [hunk 4]
```diff
@@ -220,6 +232,26 @@ bool AtomBrowserClient::ShouldCreateNewSiteInstance(
   return !IsSameWebSite(browser_context, src_url, url);
 }
 
+bool AtomBrowserClient::NavigationWasRedirectedCrossSite(
+    content::BrowserContext* browser_context,
+    content::SiteInstance* current_instance,
+    content::SiteInstance* speculative_instance,
+    const GURL& dest_url,
+    bool has_response_started) const {
+  bool navigationWasRedirected = false;
```
Comment (deepak1556) [inline atom/browser/atom_browser_client.cc]: variable should be snake case, `navigation_was_redirected`

**Comment by ppontes** [comment]
@deepak1556 done!

**Comment by zcbenz** [comment]
Failing tests are the usual flaky ones, I'm merging with them ignored.

**Comment by MarshallOfSound** [comment]
@ppontes You need to be on an approved user list to run trop commands.

`4.x` is nearing the end of its beta cycle, the previous iteration of this change broke the release.  How confident are we this won't destabilize 4.0?

**Comment by deepak1556** [comment]
@MarshallOfSound I would like to see this backported to 4.x line, and get an early feedback on using site isolation. There is only so much we can test here wrt navigations. Also this PR fixes some really troublesome usages of site instances. The only reason the last PR got reverted was because it compromised a common navigation code path.

**Comment by MarshallOfSound** [comment]
Thanks @ppontes and @deepak1556 

I'm tentatively going to land this ready for the next 4.x release but cc'ing @sofianguy to give a heads up to the AFP folks that this change is landing.  Basically any weird navigation or `window.open` behavior in the next 4.x release is probably coming from this PR, although we don't expect anything bad to happen and we've tested the common paths as well as we can without sending it through apps.

We can always revert before the next 4.x release if someone finds something.

**Comment by MarshallOfSound** [comment]
cc @ppontes looks like the patch doesn't apply cleanly, can you take care of the manual backport?

**Comment by ppontes** [comment]
@MarshallOfSound yep, will do. Thanks.

**Comment by ckerr** [comment]
@ppontes, do you have an estimate on when you can do this?

I'm wondering if we should try to get this into a beta release later this week so that there will more public testing time leading up to 4.0.0

**Comment by ppontes** [comment]
@ckerr sorry for the delay, got some surprising UT failures as a setting failed to reach brightray in 4-0-x, as brightray is gone from master. Everything's fine now and the PR is read: https://github.com/electron/electron/pull/15969

**Comment by dataich** [comment]
Do you have plan to release this fix on 4.x?

**Comment by dataich** [comment]
@ppontes thanks for your reply. I wait stable 5.x release😢

File: spec/api-browser-window-spec.js [hunk 5]
```diff
@@ -1470,29 +1472,6 @@ describe('BrowserWindow module', () => {
 
       const preload = path.join(fixtures, 'module', 'preload-sandbox.js')
 
-      // http protocol to simulate accessing another domain. This is required
```
Comment (alexstrat) [inline spec/api-browser-window-spec.js]: @ppontes is there any reason why you removed the usage of `interceptStringProtocol`? I'm considering using this again for https://github.com/electron/electron/pull/18173

Comment (ppontes) [reply spec/api-browser-window-spec.js]: Unfortunately, I don't remember the reason. Feel free to try to use it again according to your needs.

File: lib/browser/guest-window-manager.js [hunk 6]
```diff
@@ -90,9 +90,9 @@ const setupGuest = function (embedder, frameName, guest, options) {
   }
   const closedByUser = function () {
     embedder._sendInternal('ELECTRON_GUEST_WINDOW_MANAGER_WINDOW_CLOSED_' + guestId)
-    embedder.removeListener('render-view-deleted', closedByEmbedder)
+    embedder.removeListener('current-render-view-deleted', closedByEmbedder)
   }
-  embedder.once('render-view-deleted', closedByEmbedder)
+  embedder.once('current-render-view-deleted', closedByEmbedder)
```
Comment (tarruda) [inline lib/browser/guest-window-manager.js:95]: Are we sure that "RenderViewDeleted" implies that the window should be closed?

Our Electron app is failing to use Google Sign-in, with a similar behavior to what is described [here](https://github.com/google/google-api-javascript-client/issues/506#issue-408397778), and I've traced the issue to the `current-render-view-deleted` event being emitted before the sign-in is ready causing it to close prematurely.

For our app, the `current-render-view-deleted` event is only emitted in this situation, so it was safe to simply comment this line. Do you know what are the general implications of removing this handler?

Comment (ppontes) [reply lib/browser/guest-window-manager.js:95]: Did you understand what causes RenderViewDeleted to be fired in the first place?

@deepak1556 can confirm / correct me, I believe we need to depend on this event to cleanup our BrowserWindow stuff when we assume that something other than the user is triggering the window to close. So it'd be useful to understand why something's triggering the RenderView to be deleted while Google Sign-in still depends on the popup window being open.

Comment (nornagon) [reply lib/browser/guest-window-manager.js:95]: FWIW @tarruda, Google is shutting down sign-in in non-browsers: https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html

It's quite possible there's a separate issue here, but for Google sign-in specifically, you should probably see if you can switch to the OAuth flow.

Comment (tarruda) [reply lib/browser/guest-window-manager.js:95]: > Did you understand what causes RenderViewDeleted to be fired in the first place?

Not certain, but it seemed to happen when the Google SSO window navigated to another URL (where it normally shows "please wait..." before closing the window).

Also, this didn't always happen: When I tried to sign in by opening our app login window directly with a BrowserWindow, the issue was not reproducible. It only happened during normal app usage, when the login window was opened with `window.open`.

Comment (tarruda) [reply lib/browser/guest-window-manager.js:95]: > FWIW @tarruda, Google is shutting down sign-in in non-browsers: https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html

> It's quite possible there's a separate issue here, but for Google sign-in specifically, you should probably see if you can switch to the OAuth flow.

@nornagon  I'm not familiar with the details of how theh Google sign-in works, but I assume we already use the OAuth flow since that announcement is already one year old and everything was working fine for the past couple of months.

Comment (nornagon) [reply lib/browser/guest-window-manager.js:95]: Not necessarily; Google has been rolling it out on a percentage basis per-account since a few months ago. OAuth flow means you do sign-in in the browser and get a token back in your app.

Comment (tarruda) [reply lib/browser/guest-window-manager.js:95]: > Not necessarily; Google has been rolling it out on a percentage basis per-account since a few months ago. OAuth flow means you do sign-in in the browser and get a token back in your app.

Hmm now I remember having to change user-agent in order for Google Sign-in to work, that must have been the reason :)

Comment (nornagon) [reply lib/browser/guest-window-manager.js:95]: Right, that seems to work for some people for now, but Google is pretty committed to preventing people from doing what you're doing, so I wouldn't be at all surprised if they break it in other, more difficult-to-work-around ways without warning in the future.

**Comment by bughit** [comment]
> This change turns Chromium's site isolation on and depends on it being on in order to work properly.

Could someone please clarify whether the above means that disabling site isolation via `--disable-site-isolation-trials` is unsupported?
