### PR TITLE
Area near the top border in frameless window is clickable

### LINKED ISSUE #983: Area near the border not clickable in frameless window
When adding a button on the top corner, the top half of the button is not clickable and the bottom can be clicked. The frameless mode come with transparency border?

```
document.body.appendChild(btn);
btn.style.position='absolute';
btn.style.left='958px';
btn.style.top='-2px';
```

### LINKED ISSUE #5723: CSS cursor not honored when element in header with titleBarStyle="hidden"
If you place an element with a css cursor style at the top of the page where the title bar would be with titleBarStyle="hidden", the cursor always displays as default.  A simple example would be a link.

### LINKED ISSUE #7696: frameless window does not play well with mouse events
- Electron version: 1.4.1
- Operating system: Mac with retina display

Step to reproduce:
1. create a frameless window on a retina device
2. put an element at the very top, say a div, and set the cursor type to pointer
3. observe that the cursor does not always change to a 'pointer' type

I have a video here for demo purpose: https://youtu.be/yFZayteopgg

The video demonstrated the issue on Mac, but it's also reproducible on Windows, and on Windows it's worse because not only the cursor type does not change, the click event won't register either. Thus it's impossible to correctly implement close/maximize/minimize buttons with CSS.

Notice it's only reproducible on hi dpi devices, everything seems to work correctly on regular displays.

the demo in the video is made by adapting the frameless window example in the electron api demo app.

### LINKED ISSUE #8730: Frameless Electron App not work css cursor:pointer
* Electron version:1.4.14
* Operating system: mac v10.12.3

### Expected behavior

setting  BrowserWindow options frame false

browser Top frame zone 

There is an invisible window

i want work css cursor:pointer

my option code

	mainWindow = new BrowserWindow({
            show: false,
            frame: false,// look
            title: "",
            useContentSize: false,
            width: mainWindowWidth,
            minWidth: mainWindowWidth,
            height: mainWindowHeight,
            minHeight: mainWindowHeight,
            maximizable:false,
            fullscreenable:false,
            icon: iconPath
        });

### PR DESCRIPTION
**Pull request by mst128256**
Reason for the behaviour is usage of NSTitledWindowMask - even though the title bar is then set to be hidden. The window has to draw semaphore buttons on its own - it is solved as separate subview within the hierarchy. The semaphore buttons are being shown only when the cursor is nearby. Added code to let keyboard shortcuts for close and minimise work properly.

Fixes #8730 
Fixes #7696 
Fixes #5723
Fixes #983

### CODE REVIEW

**Comment by alvesl** [comment]
Hello friends, any news on this?
I still have the problem with the cursor:pointer at the top of the window.
thanks!

**Comment by tonyganch** [comment]
@poiru, ping

**Comment by groundwater** [comment]
Notes from weekly meeting:

1. can we create a flag to isolate these changes
2. @kevinsawicki up for helping merge and implement the feature flag

**Comment by kevinsawicki** [comment]
Thanks for this @mst128256 👍

Discussed this with @tonyganch in this morning's meeting and I've updated this pull request to put this behind a new flag so existing apps using `frame: false` are not affected by this new behavior.

Apps can opt-in to this feature by setting `titleBarStyle` to `customButtonsOnHover` on the `BrowserWindow` options constructor when using frameless windows.

@poiru You mentioned having some edits/differences in your custom implementation of this, we can work those out in any follow up PRs, but this seems solid to initially ship as an opt-in experimental option.

File: atom/browser/native_window_mac.mm [hunk 1]
```diff
@@ -46,6 +46,107 @@
...
+    [self setAutoresizingMask: NSViewMaxXMargin | NSViewMinYMargin];
+
+    // refresh for initial conditions
+    [self setNeedsDisplayForButtons];
+  }
+
+  return self;
+}
+
+- (BOOL)_mouseInGroup:(NSButton*)button {
```
Comment (MarshallOfSound) [inline atom/browser/native_window_mac.mm]: Quick question regarding this, itsn't this a private / undocumented API and if so will it prevent apps getting added to he mac app store, this feature might have to be disabled in MAS builds?

Comment (poiru) [inline atom/browser/native_window_mac.mm]: I'm not sure, but note that `_mouseInGroup` is called by macOS, not by us. Not sure if that makes a difference.
