### PR TITLE
fix: Menu accelerators not working

### LINKED ISSUE #14252: MenuItem Accelerators Not Working in Ubuntu 16.04.2 LTS for 3.0.0-beta.1~6
* Electron Version: 3.0.0-beta.1 ~ 3.0.0-beta.6
* Operating System (Platform and Version): Ubuntu 16.04.2 LTS
* Last known working Electron version: versions before 3.0.0-beta.1

**Expected Behavior**
Console prints out `time to print stuff` when `Ctrl+P` is pressed.
```
const {Menu, MenuItem} = require('electron')
const menu = new Menu()
  
app.on('ready', () => {
  createWindow()
  menu.append(new MenuItem({
    label: 'Print',
    accelerator: 'CmdOrCtrl+P',
    click: () => { console.log('time to print stuff') }
  }))
  Menu.setApplicationMenu(menu)
})
```
https://github.com/hackjutsu/electron-quick-start/commit/6ceb5d7dcd2d946c071b43a3fdd1b0434ddebff5
**Actual behavior**
No output. The accelerator event is not triggered.

**To Reproduce**
```sh
git clone https://github.com/hackjutsu/electron-quick-start
cd electron-quick-start
npm install
npm run start
```
Try pressing `Ctrl+P`, and observe the output. (nothing happen...)
Change the electron version back to 2.0.0 in `pakcage.json`
```sh
npm install
npm run start
```
Try pressing `Ctrl+P`, and observe the output. (the log `time to print stuff` will show up in console)

### PR DESCRIPTION
**Pull request by nitsakh**
##### Description of Change
This PR fixes #14252.
Menu Accelerators were not working on Linux with Unity, global menus.

##### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

##### Release Notes

Notes: Fixed bug that caused menu accelerators to stop working on some linux

### CODE REVIEW

**Comment by nornagon** [comment]
LGTM once the CI passes :)

File: spec/api-menu-spec.js [hunk 1]
```diff
@@ -721,5 +721,28 @@ describe('Menu module', () => {
       Menu.setApplicationMenu(null)
       expect(Menu.getApplicationMenu()).to.be.null()
     })
+
+    it('provides working menu accelerators', (done) => {
```
Comment (MarshallOfSound) [inline spec/api-menu-spec.js]: You'll need to conditionally skip this test if `robotjs` failed to install.

E.g. the devtools spec does this

```js
let testFn = it
try {
  // We have other tests that check if native modules work, if we fail to require
  // robotjs let's skip this test to avoid false negatives
  require('robotjs')
} catch (err) {
  testFn = it.skip
}

testFn('my test', ...
```

**Comment by codebytere** [comment]
@nitsakh what's the current status of this?

**Comment by nitsakh** [comment]
@codebytere it'll be great if you can please take another look at this one. Should be ready to merge once approved again.
