### PR TITLE
fix: prevent title change for within page navigation

### LINKED ISSUE #44144: [Bug]: When `window.webContents.navigationHistory.goBack()` is called, the title set by the HTML's `<title>` tag will override the title set by `window.setTitle()`.
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.0.1

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11	23H2	22631.4169	Windows Feature Experience Pack 1000.22700.1034.0

### What arch are you using?

x64

### Last Known Working Electron version

_No response_

### Expected Behavior

```
const window = new BrowserWindow();
window.setTitle('myTitle');
// After a route change in my HTML file, execute:
window.webContents.navigationHistory.goBack();
// => The title of the window should not be overridden by the HTML's title when `goBack()` is called.
```

### Actual Behavior

```
const window = new BrowserWindow();
window.setTitle('myTitle');
// After a route change in my HTML file, execute:
window.webContents.navigationHistory.goBack();
// => At this point, the title of the window is no longer 'myTitle', but the content of the title tag in the HTML file.
```

### Testcase Gist URL

_No response_

### Additional Information

The front-end uses Vue.js + Vue-Router

### PR DESCRIPTION
**Pull request by mlaurencin**
#### Description of Change

Closes #44144

Previously the call to update the title occurred after any forward/backward navigation. Now it only occurs if that navigation is not done in page.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed title changes to not occur while navigating within a page

### CODE REVIEW

**Review by ckerr — APPROVED** [review]

**Review by codebytere — COMMENTED** [review]
The issue initially could be triggered programmatically via `window.webContents.navigationHistory.goBack()` so we should add a regression test to
this!

File: shell/browser/api/electron_api_web_contents.cc [hunk 1]
```diff
@@ -2057,6 +2057,17 @@ void WebContents::DidFinishNavigation(
       if (is_main_frame) {
         Emit("did-navigate", url, http_response_code, http_status_text);
       }
+
+      content::NavigationEntry* entry = navigation_handle->GetNavigationEntry();
+
+      // This check is needed due to an issue in Chromium
+      // Check the Chromium issue to keep updated:
+      // https://bugs.chromium.org/p/chromium/issues/detail?id=1178663
```
Comment (deepak1556) [inline shell/browser/api/electron_api_web_contents.cc:2065]: FYI, The issue referenced is closed, last time I checked upstream is open for patch but no updates will happen unless we pursue it :) Maybe a tracking issue on our end is needed ?

Comment (mlaurencin) [reply shell/browser/api/electron_api_web_contents.cc:2065]: Thanks for the heads up. Just to confirm, do you mean making an issue in our own tracker to indicate that a patch should be made upstream?

Comment (deepak1556) [reply shell/browser/api/electron_api_web_contents.cc:2065]: Yup if we want to pursue, but given the workaround is solid for years there is no real urgency as well. Just thought of highlighting since the code touched the comment, not really blocking this PR :)

Comment (mlaurencin) [reply shell/browser/api/electron_api_web_contents.cc:2065]: Gotcha! Yeah, I can go ahead and make an issue after this PR is merged that brings together all the relevant links/info for that as a discussion

**Comment by ckerr** [comment]
@deepak1556 OK to merge?

**Review by codebytere — APPROVED** [review]
