### PR TITLE
fix: run subframe preload bundles in isolated context

### LINKED ISSUE #16804: Sub frames should get an isolated context when node is enabled in sub frames
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 5.x.x

### Expected Behavior
Context isolation should be enabled in subframes when the `nodeIntegrationInSubFrames` option is provided.

### Actual behavior
Context isolation is not enabled for node environments in subframes.

### To Reproduce
Enable `nodeIntegrationInSubFrames` and load any content in a subframe.

### Additional Information
See #16425 and https://github.com/electron/electron/blob/master/atom/renderer/atom_render_frame_observer.cc#L92-L104

I started working on a fix, but wasn't sure if the `preload_bundle` was actually being run in the correct context.
```diff
diff --git a/atom/renderer/atom_render_frame_observer.cc b/atom/renderer/atom_render_frame_observer.cc
index f8a54a199..b878954cc 100644
--- a/atom/renderer/atom_render_frame_observer.cc
+++ b/atom/renderer/atom_render_frame_observer.cc
@@ -12,6 +12,8 @@
 #include "atom/common/heap_snapshot.h"
 #include "atom/common/native_mate_converters/value_converter.h"
 #include "atom/common/node_includes.h"
+#include "atom/common/options_switches.h"
+#include "base/command_line.h"
 #include "base/strings/string_number_conversions.h"
 #include "base/threading/thread_restrictions.h"
 #include "base/trace_event/trace_event.h"
@@ -95,9 +97,17 @@ void AtomRenderFrameObserver::DidCreateScriptContext(
   if (ShouldNotifyClient(world_id))
     renderer_client_->DidCreateScriptContext(context, render_frame_);
 
-  if (renderer_client_->isolated_world() && IsMainWorld(world_id) &&
-      // Only the top window's main frame has isolated world.
-      render_frame_->IsMainFrame() && !render_frame_->GetWebFrame()->Opener()) {
+  bool use_context_isolation = renderer_client_->isolated_world();
+  bool is_main_world = IsMainWorld(world_id);
+  bool is_main_frame = render_frame_->IsMainFrame();
+  bool is_not_opened = !render_frame_->GetWebFrame()->Opener();
+  bool allow_node_in_sub_frames =
+      base::CommandLine::ForCurrentProcess()->HasSwitch(
+          switches::kNodeIntegrationInSubFrames);
+  bool should_create_isolated_context =
+      use_context_isolation && (is_main_frame || allow_node_in_sub_frames) && is_main_world && is_not_opened;
+
+  if (should_create_isolated_context) {
     CreateIsolatedWorldContext();
     renderer_client_->SetupMainWorldOverrides(context, render_frame_);
   }
```

### PR DESCRIPTION
**Pull request by samuelmaddock**
#### Description of Change

fixes #16804

The isolated context was only being created for the main frame. This creates an isolated context for subframes when `nodeIntegrationInSubFrames` is true.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: no-notes

### CODE REVIEW

File: spec/api-subframe-spec.js [hunk 1]
```diff
@@ -74,15 +76,38 @@ describe('renderer nodeIntegrationInSubFrames', () => {
...
         w.loadFile(path.resolve(__dirname, 'fixtures/sub-frames/frame-with-frame-container.html'))
-        const [,, event3] = await detailsPromise
+        const [, , event3] = await detailsPromise
         const pongPromise = emittedOnce(remote.ipcMain, 'preload-pong')
         event3[0].reply('preload-ping')
         const details = await pongPromise
         expect(details[1]).to.equal(event3[0].frameId)
       })
+
+      if (webPreferences.contextIsolation) {
```
Comment (MarshallOfSound) [inline spec/api-subframe-spec.js]: Because it's bitten us in the past, can we invert the test when `contextIsolation` is `false`?

E.g. 

```js
if (webPreferences.contextIsolation) {
  expect(result).to.be.null();
} else {
  expect(result).to.equal(true);
}
```
