### PR TITLE
fix: bypass DOM storage quota

### LINKED ISSUE #8337: localStorage values are limited to 10Mb
localStorage is still limited to 10Mb. After running a few tests, it throws a:
> DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'data' exceeded the quota.

Also reported in [issue 897](https://github.com/electron/electron/issues/897), which is closed.

* Electron version: 1.4.13
* Operating system: Windows 7

### Expected behavior

No limit/quota

### Actual behavior

Limited to 10Mb

### How to reproduce

Run `localStorage.setItem('data', (new Array(11*1024*1024)).join("x"));`

### PR DESCRIPTION
**Pull request by jacobq**
#### Description of Change
This updates the `dom_storage_map` patch to include bypassing the 2 additional locations of quota checking. It also adds a test to ensure that at least 50MiB of data can be stored in `localStorage` and `sessionStorage` (I'm surprised that I didn't find something like that already in place. Perhaps that's how the regression sneaked in.) Since the usual limit is about 10MiB the test will fail if the patch has not been applied or is not working.
Fixes #8337.

cc @MarshallOfSound you [mentioned](https://github.com/electron/electron/issues/897#issuecomment-412779881) you might be willing to help land this. (Thanks in advance!)
cc @zcbenz It looks like you [wrote the original patch](https://github.com/electron/electron/issues/897#issuecomment-66856924). (Thank you! That helped me understand how electron's build system applies chromium patches)
cc @asinbow You [pointed out the additional checks](https://github.com/electron/electron/issues/897#issuecomment-412461917) that needed to be disabled. (Thank you!)

#### Checklist
- [X] PR description included and stakeholders cc'd
- [X] `npm test` passes (CI is green)
- [X] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [X] relevant documentation is changed or added (see note below)
- [X] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines) (once WIP prefix is removed)

**Note about documentation:**
Since this is fixing a regression (doing what the previous patch used to do), I don't think there's any need to change documentation. However, it might make sense to record this behavior in the documentation somewhere (I couldn't find it). Perhaps in the FAQ where [`localStorage` is mentioned](https://electronjs.org/docs/faq#how-to-share-data-between-web-pages).

**Note about running tests locally:**
It seems that I can't run the test suite locally, though I can build a release and manually test in the console. Here's what I get on my (Debian 9.5) machine when I try to build the debug version (needed for running tests, right?) It seems like my system's libc version does not match the required one.
</summary><details>

```sh
$ ninja -C out/Debug electron
ninja: Entering directory `out/Debug'
[7817/18095] ACTION //components/url_formatter/top_domains:generate_top_domains_trie(//build/toolchain/linux:clang_x64)
FAILED: gen/components/url_formatter/top_domains/alexa_domains-trie-inc.cc 
python ../../build/gn_run_binary.py top_domain_generator /home/jquant/tmp/electron-gn/src/components/url_formatter/top_domains/alexa_domains.skeletons /home/jquant/tmp/electron-gn/src/components/url_formatter/top_domains/top_domains_trie.template gen/components/url_formatter/top_domains/alexa_domains-trie-inc.cc
./top_domain_generator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /home/jquant/tmp/electron-gn/src/out/Debug/./libbase.so)
top_domain_generator failed with exit code 1
[7818/18095] ACTION //net/http:generate_transport_security_state(//build/toolchain/linux:clang_x64)
FAILED: gen/net/http/transport_security_state_static.h 
python ../../build/gn_run_binary.py transport_security_state_generator ../../net/http/transport_security_state_static.json ../../net/http/transport_security_state_static.pins ../../net/http/transport_security_state_static.template gen/net/http/transport_security_state_static.h
./transport_security_state_generator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /home/jquant/tmp/electron-gn/src/out/Debug/./libbase.so)
transport_security_state_generator failed with exit code 1
[7826/18095] CXX obj/third_party/ots/ots/ots.o
ninja: build stopped: subcommand failed.
```

</details></summary>

#### Release Notes
notes: Fixes regression regarding `localStorage` quota not being bypassed.

### CODE REVIEW

**Comment by deepak1556** [comment]
Although the patch looks good, I would like to get a better understanding of the side effects from changing the rate limiter for writes, [storage-dev](https://groups.google.com/a/chromium.org/forum/#!forum/storage-dev) would be the best place to get more thoughts on this approach.

**Comment by jacobq** [comment]
> I would like to get a better understanding of the side effects from changing the rate limiter for writes, [storage-dev](https://groups.google.com/a/chromium.org/forum/#!forum/storage-dev)

I just threw that in there "just in case" as, once again, it seems like something that shouldn't be restricted in Electron. If it will help land this sooner I will take that out.

**Comment by jacobq** [comment]
@deepak1556 I removed the change about which you had concerns. Would you mind reviewing again?

**Comment by jacobq** [comment]
@deepak1556 Sure, description [starts here](https://github.com/electron/electron/pull/15596/commits/918586cd04b70e3bc1bafda76eaebd4c309b2a34#diff-4f520c30cd64052725f3e62cec3379cdR6). More discussion may also be found in the related issues.

**Comment by jacobq** [comment]
Could this also be backported to 3-0-x?

**Comment by jacobq** [comment]
Note: failed win-ia32 test [appears unrelated](https://windows-ci.electronjs.org/project/AppVeyor/electron-hew04/build/1.0.2476#L21272). Would one of the [releasers](https://github.com/electron/electron/blob/8ba271efba691357ab1970c1a553b4e019125574/docs/development/pull-requests.md#continuous-integration-testing) please restart the failed build(s)?

**Comment by jacobq** [comment]
Similar to the [`win-ia32` false positive](https://github.com/electron/electron/pull/15596#issuecomment-436668442), would one of the reviewers please restart the build for `mas-testing-tests` and `osx-testing-tests`. I don't think those failures were caused by this PR.

File: spec/chromium-spec.js [hunk 1]
```diff
@@ -937,6 +937,23 @@ describe('chromium feature', () => {
...
+    describe('DOM storage quota override', () => {
+      ['localStorage', 'sessionStorage'].forEach((storageName) => {
+        it(`can store at least 50MiB in ${storageName}`, (done) => {
+          assert.doesNotThrow(() => {
+            const storage = window[storageName]
+            const testKeyName = '_electronDOMStorageQuotaOverrideTest'
+            // 25 * 2^20 UTF-16 characters will require 50MiB
+            const arraySize = 25 * Math.pow(2, 20)
+            storage[testKeyName] = new Array(arraySize).fill('X').join('')
+            assert.strictEqual(storage[testKeyName].length, arraySize)
```
Comment (alexeykuzmin) [inline spec/chromium-spec.js]: We are in the process of moving away from `assert`s in favour of [Chai](https://www.chaijs.com)'s `expect`s.
Can you please replace this line with the following?
```suggestion
            expect(storage[testKeyName])to.have.lengthOf(arraySize)
```

File: spec/chromium-spec.js [hunk 2]
```diff
@@ -937,6 +937,23 @@ describe('chromium feature', () => {
   })
 
   describe('storage', () => {
+    describe('DOM storage quota override', () => {
+      ['localStorage', 'sessionStorage'].forEach((storageName) => {
+        it(`can store at least 50MiB in ${storageName}`, (done) => {
+          assert.doesNotThrow(() => {
```
Comment (alexeykuzmin) [inline spec/chromium-spec.js]: `assert.doesNotThrow` is not needed here, please remove it.
The whole test kind of serves as an expectation that its body doesn't throw, it will fail if there are any exceptions.

File: spec/chromium-spec.js [hunk 3]
```diff
@@ -937,6 +937,23 @@ describe('chromium feature', () => {
   })
 
   describe('storage', () => {
+    describe('DOM storage quota override', () => {
+      ['localStorage', 'sessionStorage'].forEach((storageName) => {
+        it(`can store at least 50MiB in ${storageName}`, (done) => {
```
Comment (alexeykuzmin) [inline spec/chromium-spec.js]: A `done` callback is not needed for synchronous tests, please remove it.

File: spec/chromium-spec.js [hunk 4]
```diff
@@ -937,6 +937,23 @@ describe('chromium feature', () => {
   })
 
   describe('storage', () => {
+    describe('DOM storage quota override', () => {
+      ['localStorage', 'sessionStorage'].forEach((storageName) => {
```
Comment (alexeykuzmin) [inline spec/chromium-spec.js]: Btw, you could have listed storages here, not their names.

```js
for (const storage of [localStorage, sessionStorage]) {
  <...>
}
```

**Comment by alexeykuzmin** [comment]
> Could this also be backported to 3-0-x?

@jacobq 
Yes, but not automatically. We have significantly changed a layout of the Electron repositories between versions 3 and 4.
If you want to see this change in the Electron 3.x release line, please open a PR against the `electron-3-0-x` branch of the https://github.com/electron/libchromiumcontent repo, changing [the same patch file](https://github.com/electron/libchromiumcontent/blob/electron-3-0-x/patches/common/chromium/dom_storage_map.patch). Thank you.

File: spec/chromium-spec.js (hunk 4 above)
Comment (jacobq) [reply spec/chromium-spec.js]: Indeed, I started with that, but I wanted to associate the name with the test (e.g. in the string parameter to `it(...)`) and didn't see a better way to do that (e.g. `localStorage.toString()` just returns
`"[object Storage]"`). If you like I can use an array of objects like `{name: 'localStorage', storage: localStorage}`.

File: spec/chromium-spec.js (hunk 2 above)
Comment (jacobq) [reply spec/chromium-spec.js]: Oh, duh, yes. I think I wrote that originally because I didn't realize there was anything else to `assert`, but then I added a check for length.

File: spec/chromium-spec.js (hunk 1 above)
Comment (jacobq) [reply spec/chromium-spec.js]: Sure -- I had just attempted to copy the conventions from a nearby test.

**Comment by jacobq** [comment]
@alexeykuzmin OK, I just added some more commits and think I got all the changes you requested. Once this lands I'll open a separate PR for 3.0.x backport.

**Comment by jacobq** [comment]
Hello again...would someone please re-run the 2 failed CI jobs? (mas-testing-tests & osx-testing-tests)

File: spec/chromium-spec.js (hunk 4 above)
Comment (alexeykuzmin) [reply spec/chromium-spec.js]: Oh, right, you use the names to build a test name. That's perfectly fine then.

File: spec/chromium-spec.js [hunk 5]
```diff
@@ -937,6 +937,20 @@ describe('chromium feature', () => {
...
+        it(`allows saving at least 50MiB in ${storageName}`, () => {
+          const storage = window[storageName]
+          const testKeyName = '_electronDOMStorageQuotaOverrideTest'
+          // 25 * 2^20 UTF-16 characters will require 50MiB
+          const arraySize = 25 * Math.pow(2, 20)
+          storage[testKeyName] = new Array(arraySize).fill('X').join('')
+          expect(storage[testKeyName]).to.have.lengthOf(arraySize)
```
Comment (jacobq) [inline spec/chromium-spec.js]: @deepak1556 I think this test is actually not working correctly. It appears to pass because no exceptions are thrown, but the data isn't really being persisted, and this can be seen by separating the read and write operations by a `setTimeout`, page refresh, etc. See https://github.com/electron/electron/issues/13465#issuecomment-494983533 . Any idea how we can fix this?
