### PR TITLE
fix: prevent crash on Windows when closing child windows

### LINKED ISSUE #49893: Electron 41.0.0-beta.4 crashes when closing child windows
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

41.0.0-beta.4

### What operating system(s) are you using?

Windows

### Operating System Version

Win 11

### What arch are you using?

x64

### Last Known Working Electron version

41.0.0-beta.3

### Does the issue also appear in Chromium / Google Chrome?

I don't know how to test

### Expected Behavior

Child window with `titleBarStyle: 'hidden'` should closes corectly

### Actual Behavior

When closing child windows with `titleBarStyle: 'hidden'` setting - Electron 41.0.0-beta.4 app crashes. Please see repro

### Testcase Gist URL

https://gist.github.com/bukharin/830066af609975d6a475a873428599de

### Additional Information

I tested only on win32, but it may be related to other platforms

### PR DESCRIPTION
**Pull request by mitchchn**
#### Description of Change

Prevents a null raw pointer de-reference in the hit test path introduced in #49822.

I also added some additional null pointer checks on Windows that had been accidentally left out of #49209.

Fixes #49893.

#### Checklist

- [x] PR description included
- [x] I have built and tested this PR
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant API documentation, tutorials, and examples are updated and follow the [documentation style guide](https://github.com/electron/electron/blob/main/docs/development/style-guide.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes:  none

### CODE REVIEW

**Review by codebytere — DISMISSED** [review]

**Comment by codebytere** [comment]
<details><summary>Stacktrace</summary>
<p>

```
Received signal 11 SEGV_MAPERR 000013163243
#0 0x000007d44652 base::debug::CollectStackTrace() [../../base/debug/stack_trace_posix.cc:1048:7]
#1 0x000007d349e0 base::debug::StackTrace::StackTrace() [../../base/debug/stack_trace.cc:280:20]
#2 0x000007d4453c base::debug::(anonymous namespace)::StackDumpSignalHandler() [../../base/debug/stack_trace_posix.cc:483:3]
#3 0x0000f65dd6f0 (/usr/lib/arm-linux-gnueabihf/libc.so.6+0x2d6ef)
#4 0x000008cbc92c ui::PropertyHandler::GetPropertyInternal() [../../third_party/libc++/src/include/__tree:1818:17]
#5 0x00000929cef2 aura::client::GetFocusChangeObserver() [../../ui/base/class_property.h:240:55]
#6 0x00000971a322 wm::FocusController::SetFocusedWindow() [../../ui/wm/core/focus_controller.cc:321:7]
#7 0x00000971aa28 wm::FocusController::OnWindowHierarchyChanged() [../../ui/wm/core/focus_controller.cc:211:5]
#8 0x0000092a664c aura::Window::NotifyWindowHierarchyChangeAtReceiver() [../../ui/aura/window.cc:1296:18]
#9 0x0000092a6252 aura::Window::NotifyWindowHierarchyChangeDown() [../../ui/aura/window.cc:1271:3]
#10 0x0000092a6282 aura::Window::NotifyWindowHierarchyChangeDown() [../../ui/aura/window.cc:1274:12]
#11 0x0000092a3f66 aura::Window::NotifyWindowHierarchyChange() [../../ui/aura/window.cc:1256:18]
#12 0x0000092a1b44 aura::Window::RemoveChild() [../../ui/aura/window.cc:593:3]
#13 0x0000096ed1f2 views::NativeViewHostAura::RemovedFromWidget() [../../ui/views/controls/native/native_view_host_aura.cc:182:39]
#14 0x00000969ba78 views::NativeViewHost::ViewHierarchyChanged() [../../third_party/libc++/src/include/__memory/unique_ptr.h:265:101]
#15 0x0000096bc5f2 views::View::ViewHierarchyChangedImpl() [../../ui/views/view.cc:3409:3]
#16 0x0000096bc84c views::View::PropagateRemoveNotifications() [../../ui/views/view.cc:3363:8]
#17 0x0000096bc806 views::View::PropagateRemoveNotifications() [../../ui/views/view.cc:3352:14]
#18 0x0000096bc806 views::View::PropagateRemoveNotifications() [../../ui/views/view.cc:3352:14]
#19 0x0000096b314a views::View::DoRemoveChildView() [../../ui/views/view.cc:3311:9]
#20 0x0000096b1fac views::View::~View() [../../ui/views/view.cc:353:3]
#21 0x000003519dba electron::InspectableWebContentsView::~InspectableWebContentsView() [../../electron/shell/browser/ui/inspectable_web_contents_view.cc:98:1]
#22 0x000003519e8a electron::InspectableWebContentsView::~InspectableWebContentsView() [../../electron/shell/browser/ui/inspectable_web_contents_view.cc:94:59]
#23 0x00000351423a electron::InspectableWebContents::~InspectableWebContents() [../../third_party/libc++/src/include/__memory/unique_ptr.h:74:5]
#24 0x00000351440a electron::InspectableWebContents::~InspectableWebContents() [../../electron/shell/browser/ui/inspectable_web_contents.cc:345:51]
#25 0x000003474006 electron::api::WebContents::~WebContents() [../../third_party/libc++/src/include/__memory/unique_ptr.h:74:5]
#26 0x00000347459a electron::api::WebContents::DeleteThisIfAlive() [../../electron/shell/browser/api/electron_api_web_contents.cc:1159:3]
#27 0x0000033e3d8a base::OnceCallback<>::Run() [../../base/functional/callback.h:155:12]
#28 0x000007cc8fa6 base::TaskAnnotator::RunTaskImpl() [../../base/task/common/task_annotator.cc:229:34]
#29 0x000007cef35a base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl() [../../base/task/common/task_annotator.h:112:5]
#30 0x000007ceeb4c base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() [../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:346:40]
#31 0x000007d5a462 base::MessagePumpGlib::Run() [../../base/message_loop/message_pump_glib.cc:782:48]
#32 0x000007cefed6 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run() [../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:650:12]
#33 0x000007cb32f6 base::RunLoop::Run() [../../base/run_loop.cc:135:14]
#34 0x00000672a00e content::BrowserMainLoop::RunMainMessageLoop() [../../content/browser/browser_main_loop.cc:1103:18]
#35 0x00000672b98c content::BrowserMainRunnerImpl::Run() [../../content/browser/browser_main_runner_impl.cc:151:15]
#36 0x0000067277fa content::BrowserMain() [../../content/browser/browser_main.cc:32:28]
#37 0x00000391c1c4 content::RunBrowserProcessMain() [../../content/app/content_main_runner_impl.cc:701:10]
#38 0x00000391de88 content::ContentMainRunnerImpl::RunBrowser() [../../content/app/content_main_runner_impl.cc:1317:10]
#39 0x00000391daa6 content::ContentMainRunnerImpl::Run() [../../content/app/content_main_runner_impl.cc:1150:12]
#40 0x00000391b056 content::RunContentProcess() [../../content/app/content_main.cc:356:36]
#41 0x00000391b20e content::ContentMain() [../../content/app/content_main.cc:369:10]
#42 0x0000033dbed6 main [../../electron/shell/app/electron_main_linux.cc:43:10]
#43 0x0000f65cd7d6 (/usr/lib/arm-linux-gnueabihf/libc.so.6+0x1d7d5)
#44 0x0000f65cd886 __libc_start_main
[end of stack trace]
```

</p>
</details>

File: shell/browser/ui/views/win_frame_view.cc [hunk 1]
```diff
@@ -275,12 +275,16 @@ bool WinFrameView::GetShouldPaintAsActive() {
...
+  if (!window_)
+    return gfx::Size();
   // Chromium expects minimum size to be in content dimensions on Windows
   // because it adds the frame border automatically in OnGetMinMaxInfo.
   return window_->GetContentMinimumSize();
 }
 
 gfx::Size WinFrameView::GetMaximumSize() const {
+  if (!window_)
+    return gfx::Size();
```
Comment (ckerr) [inline shell/browser/ui/views/win_frame_view.cc:287]: I'm not sure if this plays nicely with the issue described in the code comment right below this. Maybe we should follow the behavior below?

Comment (mitchchn) [reply shell/browser/ui/views/win_frame_view.cc:287]: The window would only be null during destruction. The guard is related to the question you had in this PR: https://github.com/electron/electron/pull/49209#discussion_r2772076100. (I could also remove it since it's not necessary for this particular crasher.)

**Comment by quanglam2807** [comment]
@mitchchn @codebytere Could you backport this to 40.x, please? I'm having the same issue with v40.6.1. If it's not related to this, I can create a new issue. Thank you!!!

**Comment by lishid** [comment]
Also seeing the same issue on 39.7.0 on Windows.

**Comment by gtritchie** [comment]
We're also seeing this with 39.7.0 on Windows.

**Comment by samuelmaddock** [comment]
Ah, these backport attempts can be ignored. The issue is handled by https://github.com/electron/electron/pull/50042
