### PR TITLE
fix: create `userData` on requestSingleInstanceLock() if needed

### LINKED ISSUE #33547: [Bug]: `app.requestSingleInstanceLock()` returns false on first start
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.3.1, also affected: 16, 17, 18, 19, 20

### What operating system are you using?

macOS

### Operating System Version

12.3, also affected: Win, Linux

### What arch are you using?

x64

### Last Known Working Electron version

15.3.4

### Expected Behavior

Requesting `app.requestSingleInstanceLock()` on first start of the app should return `true`.

### Actual Behavior

Requesting `app.requestSingleInstanceLock()` on first start of the app returns `false`.

### Testcase Gist URL

https://gist.github.com/6d51100568b78f98c5177cb27d370f9f

### Additional Information

It seems that the issue only exists when setting the `userData` path to a non-existent folder (which is most likely the case when you start the app for the first time on a fresh computer). Subsequent starts result in correct behavior because the folder has been created by then. The issue was not present in E15 and below; I'll bisect further.

The issue becomes problematic when implementing a behavior as described [in the docs](https://www.electronjs.org/docs/latest/api/app#apprequestsingleinstancelockadditionaldata) because the app will just quit on first start:
```js
const gotTheLock = app.requestSingleInstanceLock(additionalData)
if (!gotTheLock) {
  app.quit()
} else {...
```

cc @miniak 

_funfact: this was a pain to debug since it crashed our CI in a very obscure way 😆_

### PR DESCRIPTION
**Pull request by deermichel**
#### Description of Change
Closes #33547.

Regression introduced by https://github.com/electron/electron/pull/30594. The patch removed the behavior of [creating the `userData` folder](https://github.com/electron/electron/blob/5554de0237cd029a38806405ca771c57db529fa1/chromium_src/chrome/browser/process_singleton_posix.cc#L720) if needed. Without it, the single instance lock cannot be aquired and `app.requestSingleInstanceLock()` incorrectly returns false on first start of the app.

This PR restores the behavior from Electron 15 and below (= before the refactor landed). Test to prevent future regressions added as well ☺️ .

cc @magom001 @miniak @rzhao271

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed incorrect return value of `app.requestSingleInstanceLock()` when setting non-existent user data folder.

### CODE REVIEW

File: spec-main/api-app-spec.ts [hunk 1]
```diff
@@ -228,6 +228,13 @@ describe('app module', () => {
       expect(code1).to.equal(0);
     });
 
+    it.only('returns true when setting non-existent user data folder', async function () {
```
Comment (deepak1556) [inline spec-main/api-app-spec.ts:231]:
```suggestion
    it('returns true when setting non-existent user data folder', async function () {
```

File: spec/fixtures/api/singleton-userdata/main.js [hunk 2]
```diff
@@ -0,0 +1,12 @@
+const { app } = require('electron');
+const fs = require('fs');
+const path = require('path');
+
+// non-existing user data folder should not break requestSingleInstanceLock()
+// ref: https://github.com/electron/electron/issues/33547
+const userDataFolder = path.join(app.getPath('home'), 'singleton-userdata');
```
Comment (deepak1556) [inline spec/fixtures/api/singleton-userdata/main.js:7]: Can you also prefix this with `electron-test-` to align with https://github.com/electron/electron/pull/33511

File: patches/chromium/process_singleton.patch [hunk 3]
```diff
@@ -279,7 +290,16 @@ index e2312c65623a3f54ecbc18058720ccae53822e76..ec725b44296266bea1a51aea889463a0
        is_virtualized_(false),
        lock_file_(INVALID_HANDLE_VALUE),
        user_data_dir_(user_data_dir),
-@@ -368,13 +379,16 @@ ProcessSingleton::NotifyOtherProcessOrCreate() {
+       should_kill_remote_process_callback_(
+-          base::BindRepeating(&DisplayShouldKillMessageBox)) {}
++          base::BindRepeating(&DisplayShouldKillMessageBox)) {
++  // The user_data_dir may have not been created yet.
++  base::CreateDirectoryAndGetError(user_data_dir, nullptr);
```
Comment (deepak1556) [inline patches/chromium/process_singleton.patch:297]: I see this is based on the previous code, instead of having to check for the directory in both the windows and linux implementation, it can instead be performed at the single entry point before creating the `ProcessSingleton` instance https://github.com/electron/electron/blob/main/shell/browser/api/electron_api_app.cc#L1149-L1150

**Review by deepak1556 — COMMENTED** [review]
Thanks for catching this!

Left comments for minor improvements

File: spec-main/api-app-spec.ts (hunk 1 above)
Comment (deermichel) [reply spec-main/api-app-spec.ts:231]: right, a leftover 👍🏽

**Comment by deepak1556** [comment]
@jkleinsc how to trigger linux and mac CI for PR from forks ?

**Comment by deermichel** [comment]
(@deepak1556 it's not a fork, it's just the branch name)

**Comment by deepak1556** [comment]
Sorry missed that, we still need to trigger the linux and mac CI for this branch, not sure why they are not run.

**Comment by deermichel** [comment]
all green :)

**Review by deepak1556 — APPROVED** [review]

**Review by miniak — APPROVED** [review]

**Review by zcbenz — APPROVED** [review]
