### PR TITLE
fix: shell.trashItem crash when called in renderer

### LINKED ISSUE #28029: shell.trashItem crashes the process
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

`shell.trashItem` should just work.

### Actual Behavior

It does its job, and then immediately crashes the process.

### To Reproduce

I don't have a fiddle, but this line makes the process crash for me:

```js
return shell.trashItem ( path ).then ( () => true, () => false );
```

While this works:

```js
return Promise.resolve ( shell.moveItemToTrash ( path, false ) );
```

In addition I'm getting as output from the main process:

```
{ reason: 'crashed', exitCode: 11 }
{ reason: 'crashed', exitCode: 5 }
{ reason: 'crashed', exitCode: 5 }
{ reason: 'crashed', exitCode: 5 }
{ reason: 'crashed', exitCode: 5 }
{ reason: 'crashed', exitCode: 5 }
{ reason: 'crashed', exitCode: 5 }
{ reason: 'crashed', exitCode: 5 }
and so on...
```

Basically it crashes the window with exit code 11, then my app opens gain the window after it crashed, and it crashes again immediately with exit code 5.

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Fixes #28029. This has been broken in the renderer since it was introduced (by me 😳 ) in #25114.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed a crash when calling `shell.trashItem()` from the renderer process.

### CODE REVIEW

**Review by codebytere — APPROVED** [review]

**Review by jkleinsc — CHANGES_REQUESTED** [review]
Looks like newly added test is failing on all Windows platforms.

File: spec-main/api-shell-spec.ts [hunk 1]
```diff
@@ -74,5 +76,11 @@ describe('shell module', () => {
       const filename = path.join(app.getPath('temp'), 'does-not-exist');
       await expect(shell.trashItem(filename)).to.eventually.be.rejected();
     });
+
+    it('works in the renderer process', async () => {
+      const w = new BrowserWindow({ show: false, webPreferences: { nodeIntegration: true, contextIsolation: false } });
+      w.loadURL('about:blank');
+      await expect(w.webContents.executeJavaScript('require(\'electron\').shell.trashItem(\'does-not-exist\')')).to.be.rejectedWith(/does-not-exist|Failed to move item/);
```
Comment (nornagon) [inline spec-main/api-shell-spec.ts:83]:
```suggestion
      await expect(w.webContents.executeJavaScript('require(\'electron\').shell.trashItem(\'does-not-exist\')')).to.be.rejectedWith(/does-not-exist|Failed to move item|Failed to create FileOperation/);
```

**Comment by zcbenz** [comment]
@nornagon The newly added test seems to fail consistently on ia32 Windows.

**Comment by nornagon** [comment]
@zcbenz thanks for the ping. I have no idea why this test would fail on ia32 windows but not x64 windows, so for now I'm just going to disable the test to unbreak master.
