### PR TITLE
:bug: Fix #9231: Don't load url when detached.

### LINKED ISSUE #9231: Crashes on webview.loadURL()
* Electron version: 1.6.5
* Operating system: Windows 10 64bit

### Actual behavior

Crashes

### How to reproduce
```
git clone https://github.com/S--Minecraft/Electron-Webview-Bug.git
npm install
npm start
```

1. click "change" button
1. click "hide" button
1. click "change" button

https://github.com/S--Minecraft/Electron-Webview-Bug

### PR DESCRIPTION
**Pull request by ferreus**
I tracked down this crash to https://chromium.googlesource.com/experimental/chromium/src/+/58.0.3029.110/content/browser/browser_plugin/browser_plugin_guest.h#153
```
WebContentsImpl* embedder_web_contents() const {
    return attached_ ? owner_web_contents_ : nullptr;
}
```

Which results in null pointer access on LoadURL when the view is hidden (Because it's detached).
This is actually not a matter of race condition. As it's simply enough to hide the webview, then issue LoadURL to crash it.

This will avoid the crash by simply refusing to navigate when the view is not attached.

### CODE REVIEW

File: atom/browser/web_view_guest_delegate.h [hunk 1]
```diff
@@ -116,6 +120,9 @@ class WebViewGuestDelegate : public content::BrowserPluginGuestDelegate,
   // Whether the guest view is inside a plugin document.
   bool is_full_page_plugin_;
 
+  // Whether attached.
+  bool attached_;
```
Comment (zcbenz) [inline atom/browser/web_view_guest_delegate.h]: It should be initialized.

```c++
bool attached_ = false;
```

File: atom/browser/web_view_guest_delegate.h [hunk 2]
```diff
@@ -47,13 +47,17 @@ class WebViewGuestDelegate : public content::BrowserPluginGuestDelegate,
   // and normal sizes.
   void SetSize(const SetSizeParams& params);
 
+  // Return true if attached.
+  bool Attached() const { return attached_; }
```
Comment (zcbenz) [inline atom/browser/web_view_guest_delegate.h]: Should be `IsAttached` to match the style of other method names.

File: atom/browser/web_view_guest_delegate.h (hunk 1 above)
Comment (ferreus) [inline atom/browser/web_view_guest_delegate.h]: done
