### PR TITLE
Fix context menu for sandbox devtools

### LINKED ISSUE #10398: Mixed mode sandbox breaks right-click context menu in devtools
* Electron version: 1.7.6
* Operating system: macOS 10.12, Windows 10

### Expected behavior

Right clicking should open context menu in devtools

### Actual behavior

Right clicking does not open the context menu in devtools

### How to reproduce

- `open Electron.app --args --enable-mixed-sandbox`
- open devtools
- right click in the source tab for example

### PR DESCRIPTION
**Pull request by nitsakh**
This PR fixes #10398.
The init script did not override the inspector APIs for sandbox mode, like the non sandbox mode. This adds that.
This also allows this init script to run for dev tools window.

### CODE REVIEW

File: lib/sandboxed_renderer/init.js [hunk 1]
```diff
@@ -73,6 +77,9 @@ function preloadRequire (module) {
 // and any `require('electron')` calls in `preload.js` will work as expected
 // since browserify won't try to include `electron` in the bundle, falling back
 // to the `preloadRequire` function above.
+if (!preloadPath)
+  return
```
Comment (codebytere) [inline lib/sandboxed_renderer/init.js]: i don't think you can return outside the context of a function

Comment (tarruda) [reply lib/sandboxed_renderer/init.js]: The file is wrapped in an anonymous function in order to be executed, though this should break linting

File: atom/renderer/atom_sandboxed_renderer_client.cc [hunk 2]
```diff
@@ -38,6 +39,11 @@ namespace {
 const std::string kIpcKey = "ipcNative";
 const std::string kModuleCacheKey = "native-module-cache";
 
+bool IsDevTools(content::RenderFrame* render_frame) {
+  return static_cast<GURL>(render_frame->GetWebFrame()->GetDocument().Url())
```
Comment (deepak1556) [inline atom/renderer/atom_sandboxed_renderer_client.cc]: Its better to use `blink::WebURL::ProtocolIs` method rather casting it to `GURL`

Comment (nitsakh) [reply atom/renderer/atom_sandboxed_renderer_client.cc]: The `WebURL` constructor takes a `GURL`. (https://cs.chromium.org/chromium/src/third_party/WebKit/public/platform/WebURL.h?rcl=daaf59e82687dd66f862f33cb6615b52d18a2d89&l=73)

Comment (deepak1556) [reply atom/renderer/atom_sandboxed_renderer_client.cc]: Yes but it is not necessary to do a cast here, when we have a helper method on `WebURL` to verify the scheme.

**Comment by codebytere** [comment]
looks like typescript defs are failing on
`TS2345: Argument of type '{ url: string; headers: { key: string; }; serverType: string; }' is not assignable to parameter of type 'string'.`

**Comment by jkleinsc** [comment]
@nitsakh can you rebase against master?  That will fix the lint issue.

**Comment by miniak** [comment]
@juturu we should cherry pick this fix

**Comment by miniak** [comment]
@alexeykuzmin we should backport this fix to 1.8 and 2.0
