### PR TITLE
fix: correct window sizing on Linux when constraints on resizability are enforced

### LINKED ISSUE #49902: Wayland: some frame configurations still have incorrect bounds
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

41.0.0-beta.4

### What operating system(s) are you using?

Ubuntu

### Operating System Version

Ubuntu 25.10

### What arch are you using?

x64

### Last Known Working Electron version

_No response_

### Does the issue also appear in Chromium / Google Chrome?

No, but it's caused by Chromium ;)

### Expected Behavior

This configuration would produce an 800x600 window:

```
const WIDTH = 800;
const HEIGHT = 600;
  const mainWindow = new BrowserWindow({
	width: WIDTH,
	height: HEIGHT,
	minHeight: HEIGHT,
	minWidth: WIDTH,
	maxWidth: WIDTH,
	maxHeight: HEIGHT,
	resizable: false,
	maximizable: false,
	minimizable: false,
	frame: true // true on gnome in 41 beta, true or false on all Wayland configs in electron 42 nightly
  })
```

### Actual Behavior

The window is smaller, roughly by the size of its shadows.

### Testcase Gist URL

https://gist.github.com/5f58f8432044e740ce73f60d5dc35ea7

### Additional Information

The changes in https://github.com/electron/electron/pull/49835 need to account for size constraints, especially when combined.

### PR DESCRIPTION
**Pull request by mitchchn**
#### Description of Change

Followup to #49835, which normalized bounds operations on Linux to use logical coordinates. That PR left two edge cases where windows could still draw at the wrong sizes if certain properties were set on the browser window:

1. Max size constraints

Windows with max  width and height constraints appeared smaller than they should be. This is because Chromium calls `GetMinimumSize` and `GetMaximumSize` directly and expects them to use widget's total coordinate space, not the logical max window size. To account for this, these methods need to inflate constraints by insets on Linux. This is now handled by the tree host for all Linux frame classes to keep this quirk away from the rest of the API.

2. Resizable property

Setting `resizable: false` was causing the window to _grow taller_ on Linux in some configurations. I traced this down to a couple related issues in `setResizable`:
- Code which was supposed to be Linux-specific was not actually gated to Linux, so it was running unnecessarily on Windows as well.
- Content size constraints were being applied to the _window_. This caused ClientFrameViewLinux to change its height whenever this method is called.

I gated the Linux-specific logic and updated it to use window size constraints to prevent resizability, which is the right thing to do even if content size is in use. I also tested for resizability regressions on Windows with frame: true/false, thickFrame: true/false, and transparent: true/false.

(Note: On X11 or Wayland environments with SSD, the window manager draws the frame externally, so a framed window will still be taller than whatever height/max height is requested This is expected and not a bug introduced in this PR.)

Fixes #49902.

#### Checklist

- [x] PR description included
- [x] I have built and tested this PR
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant API documentation, tutorials, and examples are updated and follow the [documentation style guide](https://github.com/electron/electron/blob/main/docs/development/style-guide.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes:  Fixed window sizing on Linux when min/max size constraints are set or `resizable` is `false`. Windows no longer shrink below the requested max size or grow taller when resizability is disabled.

### CODE REVIEW

**Review by jkleinsc — CHANGES_REQUESTED** [review]
These changes appear to have broken Windows testing

**Comment by mitchchn** [comment]
@jkleinsc https://github.com/electron/electron/pull/49903/changes/949e2ee2ab80c7786c46609e382965419f2debd0 makes setResizable work more like other window style setters on Windows. If it's too much of a change in this PR I can put back the previous impl, but it passes the tests and worked in my own testing on Windows.

File: shell/browser/native_window_views.cc [hunk 1]
```diff
@@ -961,18 +963,23 @@ extensions::SizeConstraints NativeWindowViews::GetContentSizeConstraints()
...
     // On Linux there is no "resizable" property of a window, we have to set
     // both the minimum and maximum size to the window size to achieve it.
     if (resizable) {
-      SetContentSizeConstraints(old_size_constraints_);
+      SetSizeConstraints(old_size_constraints_);
     } else {
-      old_size_constraints_ = GetContentSizeConstraints();
-      gfx::Size content_size = GetContentSize();
-      SetContentSizeConstraints(
-          extensions::SizeConstraints(content_size, content_size));
```
Comment (jkleinsc) [inline shell/browser/native_window_views.cc:972]: @mitchchn why is this code no longer necessary on non Linux OSes?

**Comment by jkleinsc** [comment]
@mitchchn my main concern here is that logic that is currently running on all OSes has been removed/changed.  Unless there's a good reason for these changes, I'd prefer that this PR just address the issue specifically for Linux.

File: shell/browser/native_window_views.cc (hunk 1 above)
Comment (mitchchn) [reply shell/browser/native_window_views.cc:972]: So leaving aside Mac because it doesn't use this class: the existing code makes a compromise that isn't accurate for Linux, and only works for Windows in a roundabout way.

Windows controls resizability with window styles (`WS_THICKFRAME`, `WS_MAXIMIZEBOX`). The code worked before because setting size constraints (to any value) triggers `SizeConstraintsChanged` in Chromium. That method does reapply window styles including resizability, but it doesn't depend on the actual constraint values changing or their state in this class.

Linux otoh does depend on the specific value of the size constraints and their cached state, but it needs to use window size constraints instead of content size otherwise some kinds of windows will shrink.

Another option is to bring the code back for Windows, but still change it to use window size constraints instead of content size This would fix Linux but still need to be tested on Windows. But it's a more conservative change if you'd rather I try it.

Comment (mitchchn) [reply shell/browser/native_window_views.cc:972]: Trying the less invasive approach: https://github.com/electron/electron/pull/49903/changes/2ddce9bc4288ec7a294d44cafc2c604a7aaa31e4. I also updated the test that guards against window size changes to cover Windows.
