### PR TITLE
fix: command-line scheme switch values' spillover

### LINKED ISSUE #19911: command-line scheme switches' values spill over into other switches
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.0-nightly.20190821
* **Operating System:**
  * Ubuntu 19.04 x64
* **Last Known Working Electron version:**
  * Unknown. Broken in `4-1-x` upwards.

### Expected Behavior

Passing additional schemes on the command line, e.g. `--standard-schemes=foo,bar,mum`, should not affect other schemes, e.g. cors enabled schemes or secure schemes.

### Actual Behavior

The schemes from earlier checks bleed into all the following switches checked.

This happens due to the "splitted" variable in `shell/app/atom_content_client.cc`'s `AtomContentClient::AddAdditionalSchemes()` being reused for each switch without being cleared first.

### To Reproduce

On the command line, add schemes for one of the argument switches handled in `AtomContentClient::AddAdditionalSchemes()`.

### PR DESCRIPTION
**Pull request by ckerr**
## Description of Change

Fixes #19911: don't spill command-line switch scheme values into other switches.

In addition, this PR uses move semantics to move the tokens from a temporary container into their destination container.

Verified by adding this temporary code to the end of `AtomContentClient::AddAdditionalSchemes()`:

```cc
#define DUMP_SCHEMES(name) \
  std::cout << #name << std::endl; \
  for (const auto& scheme : schemes->name) std::cout << scheme << ", "; \
  std::cout <<std::endl;

  DUMP_SCHEMES(service_worker_schemes)
  DUMP_SCHEMES(standard_schemes)
  DUMP_SCHEMES(secure_schemes)
  DUMP_SCHEMES(csp_bypassing_schemes)
  DUMP_SCHEMES(cors_enabled_schemes)
```

and invoking Electron with `--standard-schemes=foo,bar,mum`.

Without PR:
```text
service_worker_schemes
file, 
standard_schemes
foo, bar, mum, chrome-extension, 
secure_schemes
foo, bar, mum, 
csp_bypassing_schemes
foo, bar, mum, 
cors_enabled_schemes
foo, bar, mum, 
```

With PR:
```
service_worker_schemes
file, 
standard_schemes
foo, bar, mum, chrome-extension, 
secure_schemes

csp_bypassing_schemes

cors_enabled_schemes
```
(`file` and `chrome-extension` are added automatically and unrelated to this PR).

#### ChecklistAtomContentClient::AddAdditionalSchemes

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed command-line scheme arguments from spilling over into each other.

### CODE REVIEW

File: shell/app/atom_content_client.cc [hunk 1]
```diff
@@ -200,30 +206,19 @@ base::RefCountedMemory* AtomContentClient::GetDataResourceBytes(
 }
 
 void AtomContentClient::AddAdditionalSchemes(Schemes* schemes) {
-  std::vector<std::string> splited;
```
Comment (codebytere) [inline shell/app/atom_content_client.cc]: nittiest of nits: `split_args` maybe?

Comment (ckerr) [reply shell/app/atom_content_client.cc]: That variable was replaced with `tokens` in the PR. Is that an improvement?

Comment (codebytere) [reply shell/app/atom_content_client.cc]: on second thought that's also fine :)
