### PR TITLE
Fix protocol filtering of net.request

### LINKED ISSUE #11657: Downloads are failing with state 'interrupted' from custom protocols in 1.8.2-beta.3
* Electron version: 1.8.2-beta.3
* Operating system: MacOS 10.12

### Expected behavior

File downloads from custom protocols should complete without issue.

### Actual behavior

Before even triggering the custom protocol handler, the download-item emits 'done' with a state of 'interrupted'. In my demo linked below, I use the new registerStreamProtocol, but I was able to reproduce using registerHttpProtocol as well.

### How to reproduce

Use https://github.com/pfrazee/electron-download-interrupt-bug

### PR DESCRIPTION
**Pull request by tarruda**
net::URLRequest inherits from base::SupportsUserData, which allows
associating arbitrary data with the request. Use this mechanism as a
condition for filtering requests from custom protocols.

Close #11657

### CODE REVIEW

**Comment by tarruda** [comment]
@pfrazee can you test this branch?

File: atom/browser/api/atom_api_protocol.h [hunk 1]
```diff
@@ -28,6 +28,7 @@ namespace atom {
 
 namespace api {
 
+const void* DisableProtocolInterceptFlagKey();
```
Comment (deepak1556) [inline atom/browser/api/atom_api_protocol.h]: It would be better to declare the key in `AtomURLRequestJobFactory` and perform the check there. Should avoid the dependency of api class methods if possible.

File: atom/browser/net/atom_url_request.cc [hunk 2]
```diff
@@ -121,6 +124,9 @@ void AtomURLRequest::DoInitialize(
   request_->set_method(method);
   // Do not send cookies from the cookie store.
   DoSetLoadFlags(net::LOAD_DO_NOT_SEND_COOKIES);
+  // Set a flag to stop custom protocol from intercepting this request.
+  request_->SetUserData(api::DisableProtocolInterceptFlagKey(),
```
Comment (deepak1556) [inline atom/browser/net/atom_url_request.cc]: This can just be `request_->SetUserData(key, base::MakeUnique<base::SupportsUserData::Data>())` , can avid declaring `class DisableProtocolInterceptFlag`

File: atom/browser/api/atom_api_protocol.h (hunk 1 above)
Comment (tarruda) [reply atom/browser/api/atom_api_protocol.h]: :+1:

File: atom/browser/net/atom_url_request.cc (hunk 2 above)
Comment (tarruda) [reply atom/browser/net/atom_url_request.cc]: :+1:

**Comment by pfrazee** [comment]
Hey, I'm traveling till monday so I'll try to get a quick second, may be next week

**Comment by pfrazee** [comment]
Confirmed this PR fixes my issue.

**Comment by MarshallOfSound** [comment]
This is just pending some tests if possible @tarruda

**Comment by pfrazee** [comment]
I made a PR with a test. Checked that it fails prior to this PR, and passes after. https://github.com/electron/electron/pull/11931

**Comment by zeke** [comment]
@pfrazee was this one of your Beaker showstopper bugs, or was that something else?

**Comment by pfrazee** [comment]
@zeke I think this was it

**Comment by zeke** [comment]
🎉

**Comment by pfrazee** [comment]
Thanks all!
