### PR TITLE
Initialize script context in DidClearWindowObject

### LINKED ISSUE #5712: node integration fails when webSecurity is disabled
* Electron version: 1.2.0
* Operating system: Mac OS X - 10.11.5

I upgraded from 1.1.1 to 1.2.0. 1.2.0 breaks on the following `index.html`:

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<script>
			console.log(process.env.NODE_ENV)
		</script>
	</head>
	<body>
		<div id="app-container"></div>
	</body>
</html>
```

Error:

```
Uncaught ReferenceError: process is not defined
```

### LINKED ISSUE #5721: Preload script errors no longer going to console
* Electron version: 1.2.0

If you have a preload script with something like:

```js
window.methodDoesNotExist()
```

The error from that script no longer displays in the console in 1.2.0.

Here is what the Console looked like on 1.1.3 where it currently works:

screen shot 2016-05-26 at 11 33 15 am

### LINKED ISSUE #5727: Webview executeJavaScript method not working in Electron 1.2.0 but 1.1.3 is okay
Electron version: 1.2.0
Operating system: Windows 10 x64

When I invoke the webview executeJavaScript method under Electron 1.2.0 it appears as though my code is not executed. If I execute the method under Electron 1.1.3 everything is okay and my code gets executed.

### PR DESCRIPTION
**Pull request by zcbenz**
Doing it in RunScriptsAtDocumentStart would somehow result in weird results when webSecurity is off.

Close #5712.
Close #5721.
Close #5727.

### CODE REVIEW

File: spec/api-ipc-spec.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ describe('ipc module', function () {
       assert.equal(a.id, 1127)
     })
 
-    it.only('should work when object has no prototype', function () {
+    it('should work when object has no prototype', function () {
```
Comment (kevinsawicki) [inline spec/api-ipc-spec.js]: Sorry about this one 😞

**Comment by aggregatejeff** [comment]
Thanks for fixing. This one was painful to find. 

I'm also seeing errors with setting webframe zoom level in 1.2.0. It seems related as 1.1.3 is fine...

**Comment by kevinsawicki** [comment]
> I'm also seeing errors with setting webframe zoom level in 1.2.0. It seems related as 1.1.3 is fine...

@aggregatejeff can you open a separate issue for this with details about the error and reproduction steps? Thanks.

**Comment by aggregatejeff** [comment]
Will do
