### PR TITLE
Fix context menus selecting first item by default.

### LINKED ISSUE #6109: Context menu should not have the first item selected on right-click on macOS
### Actual

screen shot 2016-06-17 at 18 27 29

### Expected

screen shot 2016-06-17 at 18 28 00

This is how all other macOS apps work.

### Test-case

Right-click in window when loaded.

```js
const electron = require('electron');

electron.app.on('ready', () => {
	const win = new electron.BrowserWindow();

	win.loadURL(`https://github.com`);

	win.webContents.on('context-menu', () => {
		electron.Menu.buildFromTemplate([{
			label: 'Foo'
		}, {
			label: 'Bar'
		}]).popup(win);
	});
});
```

-

* Electron version: 1.2.3
* Operating system: macOS 10.11.5

### PR DESCRIPTION
**Pull request by danhp**
This sets the default value for `positioningItem` to -1 (an invalid value) so that no item is selected.
The proper checks are performed by https://github.com/electron/electron/blob/79cb648b6b15ae0cc25e1bf528f3f4fbd1fed710/atom/browser/api/atom_api_menu_mac.mm#L39

Closes #6109

### CODE REVIEW

File: lib/browser/api/menu.js [hunk 1]
```diff
@@ -150,10 +150,12 @@ Menu.prototype.popup = function (window, x, y, positioningItem) {
     window = BrowserWindow.getFocusedWindow()
   }
 
-  // Default parameters.
+  // Default to showing under mouse location.
   if (typeof x !== 'number') x = -1
   if (typeof y !== 'number') y = -1
-  if (typeof positioningItem !== 'number') positioningItem = 0
+
+  // Default to not highliting any item.
```
Comment (kevinsawicki) [inline lib/browser/api/menu.js]: `highliting` -> `highlighting`

**Comment by kevinsawicki** [comment]
👍 🚢
