### PR TITLE
Fix missing warning icon with dialog.showMessageBox() on macOS

### LINKED ISSUE #9183: No yellow triangle in warning dialog on macOS
* Electron version: 1.6.2
* Operating system: macOS 10.12.4 (Sierra)

### Expected behavior

App icon should appear smaller next to the system warning dialog triangle icon:

screen shot 2017-04-13 at 13 35 32

([source](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/WindowAlerts.html))

### Actual behavior

Only the app icon is shown at full size

### How to reproduce

```javascript
var options = {
    type: 'warning',
    title: "Warning",
    message: "Message.",
    detail: "Detailed description.",
    buttons: ['Reset AppName', 'Quit'],
    cancelId: 1,
    defaultId: 0
};
dialog.showMessageBox(options, function (index) {
    // Clicked button index
});
```

### PR DESCRIPTION
**Pull request by poiru**
Fixes #9183.

### CODE REVIEW

File: atom/browser/ui/message_box_mac.mm [hunk 1]
```diff
@@ -71,10 +71,14 @@ - (void)alertDidEnd:(NSAlert*)alert
 
   switch (type) {
     case MESSAGE_BOX_TYPE_INFORMATION:
-      [alert setAlertStyle:NSInformationalAlertStyle];
+      alert.alertStyle = NSAlertStyleInformational;
       break;
     case MESSAGE_BOX_TYPE_WARNING:
-      [alert setAlertStyle:NSWarningAlertStyle];
+    case MESSAGE_BOX_TYPE_ERROR:
+      // NSAlertStyleWarning shows the app icon while NSAlertStyleCritical
```
Comment (MarshallOfSound) [inline atom/browser/ui/message_box_mac.mm]: Might be worth adding this to the docs just like the windows note over at https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowmessageboxbrowserwindow-options-callback

Just something like "On macOS 'error' and 'warning' result in the same dialog"

Comment (poiru) [inline atom/browser/ui/message_box_mac.mm]: Done!
