### PR TITLE
Fix notification crash when using permission handler

### LINKED ISSUE #7645: Crash when a notification is fired and is given permission after a delay
- Electron version: 1.4.3
- Operating system: MacOS 10.11.6

App which reproduces the issue: https://github.com/pfrazee/electron-bug-notifications

Here's the code that causes the crash:

``` js
app.on('ready', () => {
  session.defaultSession.setPermissionRequestHandler(onPermissionRequestHandler)
})

function onPermissionRequestHandler (webContents, permission, cb) {
  console.log('waiting 5 seconds', permission)
  setTimeout(() => { console.log('allowing', permission); cb(true) }, 5e3)
}
```

It appears that, when you create notifications with an async permission handler, the app crashes.

It may be relevant that:
1. A webview is involved
2. More than one notification is created at once

### PR DESCRIPTION
**Pull request by kevinsawicki**
This pull request upgrades Brightray to include https://github.com/electron/brightray/pull/258 and also adds a spec for using `setPermissionRequestHandler` with notifications.

Also updates a few asserts that were using `assert` instead of `assert.equal`/`assert.deepEqual`.

/cc @deepak1556 :eyes:

Fixes #7645

### CODE REVIEW

File: spec/webview-spec.js [hunk 1]
```diff
@@ -946,6 +946,24 @@ describe('<webview> tag', function () {
...
+        assert.deepEqual(e.args, ['granted'])
+        done()
+      })
+      webview.src = 'file://' + fixtures + '/pages/permissions/notification.html'
+      webview.partition = 'permissionTest'
+      webview.setAttribute('nodeintegration', 'on')
+      session.fromPartition(webview.partition).setPermissionRequestHandler(function (webContents, permission, callback) {
+        if (webContents.getId() === webview.getId()) {
+          assert.equal(permission, 'notifications')
+          callback(true)
```
Comment (deepak1556) [inline spec/webview-spec.js]: Do we want to add a delay here before responding, just so it tests for the original issue ?

**Comment by deepak1556** [comment]
looks good to me :+1:

**Comment by kevinsawicki** [comment]
Thanks @deepak1556 for fixing this 👍
