### PR TITLE
Fix treat packaged app as directory

### LINKED ISSUE #8948: <input type='file' /> and special folders
* Electron version: 1.6.2
* Operating system: macOS 10.12.3

### Actual behavior
I faced with strange behaviour of `<input type='file' />` in Electron.
You can select special Macs' folders - app folders (for example `/Applications/Calculator.app`).
In Finder it looks like file, but it's directory!

### Expected behavior
There are two possible ways.

1. `Chrome`way (and Safari). In real Chrome you can select `Calculator.app` from `<input type='file' />`. But Chrome transparently created `Calculator.app.zip` and attached this archive to input.
2. `Firefox` way. In Firefox you can not select any folders from `<input type='file' />`

### How to reproduce
I have created simple fiddle for that https://jsfiddle.net/s7c7k33b/ for testing in different browsers and Electron

### PR DESCRIPTION
**Pull request by shubham2892**
Fixes #8948 
Added the flag that enables treating file packages as directories.

### CODE REVIEW

File: atom/browser/ui/file_dialog_mac.mm [hunk 1]
```diff
@@ -93,6 +93,7 @@ void SetupDialog(NSSavePanel* dialog,
 
 void SetupDialogForProperties(NSOpenPanel* dialog, int properties) {
   [dialog setCanChooseFiles:(properties & FILE_DIALOG_OPEN_FILE)];
+  [dialog setTreatsFilePackagesAsDirectories:YES];
```
Comment (kevinsawicki) [inline atom/browser/ui/file_dialog_mac.mm]: @shubham2892 what do you think about making this an option instead of always on? Similar to how `setResolveAliases` support was added in #8617.

Comment (shubham2892) [inline atom/browser/ui/file_dialog_mac.mm]: Yes adding the option instead of making it mandatory would be better. Made the changes.

**Comment by kevinsawicki** [comment]
Thanks for this @shubham2892 👍 🍎 🍏
