### PR TITLE
fix: make screen wrapper remote-friendly again

### LINKED ISSUE #26610: Methods on remote.screen are not defined
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.2
* **Operating System:**
  * NixOS 21.03 x86_64
* **Last Known Working Electron version:**
  * 10.1.6

### Expected Behavior
`remote.screen.getPrimaryDisplay()` works.

### Actual Behavior
`Uncaught TypeError: remote.screen.getPrimaryDisplay is not a function`

### To Reproduce
Electron Fiddle: https://gist.github.com/andersk/6158c0016c56e52c58cec4aa4cd8317e

### Additional Information
This broke between 11.0.0-nightly.20200724 and 11.0.0-nightly.20200729, probably in #24677. Cc @nornagon.

See also electron-userland/spectron#771, webtorrent/webtorrent-desktop#1896.

### PR DESCRIPTION
**Pull request by andersk**
#### Description of Change

This restores accessibility of `screen` methods via `remote.screen`.

Fixes #26610.

Cc @nornagon.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed `screen` methods not being accessible via `remote.screen`.

### CODE REVIEW

**Review by MarshallOfSound — CHANGES_REQUESTED** [review]
Instead of manually listing all APIs / keys of the `screen` module, can we just implement the `ownKeys` method of the ES6 proxy.

**Comment by andersk** [comment]
Only if it doesn’t need to be lazy when used via `remote`. Given the use case documented in the comment, I guess that’s probably okay.

I had to also implement `getOwnPropertyDescriptor` for this to work, and implemented `has` for completeness.

File: lib/browser/api/screen.ts [hunk 1]
```diff
@@ -16,5 +16,23 @@ export default new Proxy({}, {
...
+    if (_screen === undefined) {
+      _screen = createScreen();
+    }
+    return Reflect.ownKeys(_screen);
+  },
+  has: (target, prop: string) => {
+    if (_screen === undefined) {
+      _screen = createScreen();
+    }
+    return prop in _screen;
```
Comment (MarshallOfSound) [inline lib/browser/api/screen.ts:30]: For completeness should this be `Reflect.has`?

Comment (andersk) [reply lib/browser/api/screen.ts:30]: That’s [identical](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/has).

**Review by nornagon — APPROVED** [review]

**Review by codebytere — APPROVED** [review]

**Review by MarshallOfSound — APPROVED** [review]
