### PR TITLE
fix: requestSingleInstanceLock API sometimes hangs

### LINKED ISSUE #33736: Hang in ConnectNamedPipe when using requestSingleInstanceLock
We are seeing a hang in ConnectNamedPipe on some machines with Electron 18 when a second instance launches:
```
Thread 0
 0  ntdll.dll!NtFsControlFile + 0x14
 1  KERNELBASE.dll!ConnectNamedPipe + 0x76
 2  slack.exe!static void `anonymous namespace'::SendBackAck() [process_singleton_win.cc : 204 + 0xf]
 3  slack.exe!base::OneShotTimer::FireNow() [timer.cc : 306 + 0x2c]
 4  slack.exe!void base::internal::DelayTimerBase::OnScheduledTaskInvoked(class std::__1::unique_ptr<base::internal::TaskDestructionDetector,std::__1::default_delete<base::internal::TaskDestructionDetector> >) [timer.cc : 283 + 0x10]
[...]
```

I believe this is due to https://github.com/electron/electron/pull/31460, which added the `SendBackAck` function. cc @rzhao271

### PR DESCRIPTION
**Pull request by rzhao271**
#### Description of Change

Backport of https://github.com/electron/electron/pull/33777
Fixes #33736

CC @nornagon @deepak1556 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed an issue with the `app.requestSingleInstanceLock()` API where it would sometimes hang.

### CODE REVIEW

**Review by nornagon — APPROVED** [review]

File: shell/browser/api/electron_api_app.cc [hunk 1]
```diff
@@ -1103,35 +1077,70 @@ void App::OnFirstInstanceAck(
...
+        void(const base::CommandLine& command_line,
+             const base::FilePath& current_directory,
+             const std::vector<const uint8_t> additional_data,
+             const ProcessSingleton::SendAckCallback& ack_callback)>&
+        callback,
+    const base::CommandLine& cmd,
+    const base::FilePath& cwd,
+    const std::vector<const uint8_t> additional_data,
+    const ProcessSingleton::SendAckCallback& ack_callback) {
+  send_ack_ = !Browser::Get()->is_shutting_down();
```
Comment (rzhao271) [inline shell/browser/api/electron_api_app.cc:1130]: Question: can I call `Browser::Get()->is_shutting_down()` at this point, or do I have to call it at the end before returning?
Note that the next line is `Browser::Get()->is_ready()`.
If `is_shutting_down` must be called at the end, we'll probably need a much larger fix to send back the ack properly.

**Review by rzhao271 — COMMENTED** [review]
I refactored the code a bit so that:
- A user can now call `ackCallback` after doing a long-running operation, and we would be able to send back the ack successfully in that case.
- The patch doesn't use separate `StoreAck` and `SendBackAck` functions. Instead, it uses just `SendBackAck`, and we create a new variable `send_ack_` in `electron_api_app` to determine whether to send back the ack. When this variable is true, we will send back the ack, and the other application will read the ack. Otherwise, the ack will not be sent back, and the other application will not read the ack. This change should prevent getting blocked by unanswered `ConnectNamedPipe` calls.

File: spec/fixtures/api/singleton-data/main.js [hunk 2]
```diff
@@ -56,11 +59,21 @@ app.on('second-instance', (event, args, workingDirectory, data, ackCallback) =>
...
+    if (!doSetTimeout) {
+      sendAck ? ackCallback(ackObj) : ackCallback();
+      setImmediate(() => {
+        app.exit(0);
+      });
+    } else {
+      setTimeout(() => {
+        sendAck ? ackCallback(ackObj) : ackCallback();
+        // cannot be setImmediate
+        setTimeout(() => {
```
Comment (rzhao271) [inline spec/fixtures/api/singleton-data/main.js:71]: When we use `setImmediate` here, the test case fails because the app's exit code is -1 (displayed as a large unsigned integer). I'm not sure what is causing that, yet.

File: shell/browser/api/electron_api_app.cc [hunk 3]
```diff
@@ -1101,37 +1074,90 @@ void App::OnFirstInstanceAck(
...
+// This function helps the first instance send an acknowledgement
+// back to the second instance.
+void App::SendBackAck(const ProcessSingleton::SendAckCallback& ack_callback,
+                      std::vector<const uint8_t>* ack_data) {
+#if BUILDFLAG(IS_WIN)
+  // For Windows, we use a timer to call the callback async,
+  // because we must exit ProcessSingleton::ProcessLaunchNotification
+  // before sending back the acknowledgement, otherwise
+  // the program will hang on the ConnectNamedPipe call.
+  ack_timer_.Start(FROM_HERE, base::Seconds(0),
```
Comment (deepak1556) [inline shell/browser/api/electron_api_app.cc:1086]: The timer here only hides the underlying issue, if there is a separate message window available for the second instance then the first instance can first attempt to send a message from `SendBackAck` before attempting connection on the pipe. It will also simply the callback jumps in `electron_api_app.cc`. This will also protect against the case where the second instance exits before the first instance can call `ConnectNamedPipe` which would cause a hang.

Comment (deepak1556) [reply shell/browser/api/electron_api_app.cc:1086]: For addressing the immediate issue, I am fine with the changes in https://github.com/electron/electron/pull/33777, the timer refactor can be done as follow-up.

Comment (rzhao271) [reply shell/browser/api/electron_api_app.cc]: Changed this patch to only contain the fix for the immediate issue.

**Review by deepak1556 — APPROVED** [review]

**Review by zcbenz — APPROVED** [review]
