### PR TITLE
fix contextIsolation issue while webPreference sandbox is on

### LINKED ISSUE #9971: contextIsolation doesn't work with when sandbox is true
* Electron version: 1.7.3
* Operating system: Windows, MacOS, Linux

### Expected behavior
Context Isolation should work when sandbox option is set to true

### Actual behavior
Context Isolation should work when sandbox option is set to true

### How to reproduce

Turn on contextIsolation and sandbox on browser window. contextIsolation doesn't work. 

contextIsolation work needs to happen on sandbox renderer client as well. 

cc: @tarruda @kevinsawicki @chandrachivukula

### PR DESCRIPTION
**Pull request by psh0628**
Fixes #9971

### CODE REVIEW

File: spec/fixtures/api/isolated-preload.js [hunk 1]
```diff
@@ -1,14 +1,11 @@
 // Ensure fetch works from isolated world origin
 fetch('http://localhost:1234')
 fetch('https://localhost:1234')
-fetch(`file://${__filename}`)
 
 const {ipcRenderer, webFrame} = require('electron')
 
 window.foo = 3
 
-webFrame.executeJavaScript('window.preloadExecuteJavaScriptProperty = 1234;')
```
Comment (tarruda) [inline spec/fixtures/api/isolated-preload.js]: Instead of removing this, why not add `webFrame` to sandboxed renderer? A simple addition to https://github.com/electron/electron/blob/master/lib/sandboxed_renderer/api/exports/electron.js should do the trick.

Comment (psh0628) [inline spec/fixtures/api/isolated-preload.js]: yes, I added webFrame to sandboxed renderer. thanks

File: atom/renderer/renderer_client_base.cc [hunk 2]
```diff
@@ -197,4 +199,12 @@ void RendererClientBase::AddSupportedKeySystems(
   AddChromeKeySystems(key_systems);
 }
 
+v8::Local<v8::Context> RendererClientBase::GetContext(
+	blink::WebFrame* frame, v8::Isolate* isolate) {
+	if (isolated_world())
+		return frame->worldScriptContext(isolate, World::ISOLATED_WORLD);
```
Comment (kevinsawicki) [inline atom/renderer/renderer_client_base.cc]: :shirt: Please use spaces instead of hard tabs for indentations

File: docs/api/sandbox-option.md [hunk 3]
```diff
@@ -166,7 +166,7 @@ Currently the `require` function provided in the preload scope exposes the
 following modules:
 
 - `child_process`
-- `electron` (crashReporter, remote and ipcRenderer)
+- `electron` (crashReporter, remote, ipcRenderer, and webFrame)
```
Comment (kevinsawicki) [inline docs/api/sandbox-option.md]: Maybe this is a good time to add the supported modules as a sub-list now that it is starting to get long.

```
- `electron`
  - `crashReporter`
  - `ipcRenderer`
  - `remote`
  - `webFrame`
```

Which will render like:

- `electron`
  - `crashReporter`
  - `ipcRenderer`
  - `remote`
  - `webFrame`

File: atom/renderer/renderer_client_base.cc (hunk 2 above)
Comment (psh0628) [inline atom/renderer/renderer_client_base.cc]: will fix this

File: docs/api/sandbox-option.md (hunk 3 above)
Comment (psh0628) [inline docs/api/sandbox-option.md]: will fix this

**Comment by psh0628** [comment]
@tarruda @kevinsawicki 
I took care of your comments and I am still waiting for your approval.

**Comment by zeke** [comment]
Hey @tarruda and @miniak can you take another look?
