### PR TITLE
Fixed font DPI scaling

### LINKED ISSUE #9665: Windows 7 notifications taking up half the screen
* Electron version: 1.6.10
* Operating system: Windows 7

### Expected behavior

Notification size should be smaller, similar to the one you can just see in the screenshot below that you can just see the bottom of, behind the large notification.

### Actual behavior

The new notifications for windows 7 are taking up half of the screen space as seen in the image below:
image

I'm running windows in parallels on a mac, so I expect it to be a screen resolution issue (2880x1800)

### How to reproduce

Test notifications on Windows 7 with parallels on a mac, or use Windows with a high screen resolution (e.g. 2880x1800).

### PR DESCRIPTION
**Pull request by alespergl**
Fixes #9665

### CODE REVIEW

File: brightray/browser/win/win32_desktop_notifications/common.h [hunk 1]
```diff
@@ -21,8 +21,8 @@ struct NotificationData {
 };
 
 template<typename T>
-inline T ScaleForDpi(T value, unsigned dpi) {
-    return value * dpi / 96;
+constexpr T ScaleForDpi(T value, unsigned dpi, unsigned source_dpi = 96) {
+    return value * dpi / source_dpi;
```
Comment (felixrieseberg) [inline brightray/browser/win/win32_desktop_notifications/common.h]: YES! Thank you.

**Comment by felixrieseberg** [comment]
Looks wonderful to me, let's merge this in.
