### PR TITLE
Fix context leak in ObjectLifeMonitor.

### LINKED ISSUE #9191: memory leak in 1.6.7 when using window.open
* Electron version: 1.6.7
* Operating system: Mac OS X 10.10.5 and Windows 8.1

I realize 1.6.7 is still in beta but thought I should report a memory leak I am seeing...  in a simple app that does window.open with every new window opened the memory keeps growing and is never released when the sub-windows get closed.

The demo repo is committed here: https://github.com/lneir/electron-memory-leak

To repo.
1. git clone https://github.com/lneir/electron-memory-leak.git
2. npm i
3. npm run start
4. in the main window click the open window button 5 times.
Notice: the memory goes very high (approx 500 Mbytes) because each sub-window is allocating a big chunk of memory.
5. now close all the open windows.

Result: the memory of the renderer process stays very high
Expected: memory to go back to original before all sub-windows were opened.

Note: This does not happen on electron 1.4.16 but only appears to be a problem in electron 1.6.7.  
Note: Also the problem seems to be related to the having preload enabled

### PR DESCRIPTION
**Pull request by tarruda**
The RemoteObjectFreer class is keeping the context alive even when the window is
closed. For electron applications that use sandbox, this will cause a memory
leak every time a new window is created with `window.open`.

Close #9191

### CODE REVIEW

File: atom/common/api/object_life_monitor.cc [hunk 1]
```diff
@@ -16,6 +16,7 @@ ObjectLifeMonitor::ObjectLifeMonitor(v8::Isolate* isolate,
       target_(isolate, target),
       weak_ptr_factory_(this) {
   target_.SetWeak(this, OnObjectGC, v8::WeakCallbackType::kParameter);
+  context_.SetWeak();
```
Comment (kevinsawicki) [inline atom/common/api/object_life_monitor.cc]: Is this context used elsewhere? I'm not seeing other references to it, looks like it was added in https://github.com/electron/electron/commit/bd64f5ced2b5d2680d9bf2cea28ec038dfe62b49 but then was no longer used after https://github.com/electron/electron/commit/06cf0406fe8ddcef3a500a689952c77fdfb9c9a8.

@zcbenz do you think it could be completely removed now?

Comment (tarruda) [inline atom/common/api/object_life_monitor.cc]: I've updated to remove `context_` instead of making it a weakref
