### PR TITLE
Offscreen rendering enhancements

### LINKED ISSUE #8051: Memory leaks when changing window size in offscreen mode
* Electron version: 1.4.7
* Operating system: Mac OS 10.11.6 & Ubuntu 14.04

### Expected behavior

Garbage collector should clean memory.

### Actual behavior

Memory usage increases rapidly in Main process. Eventually app performance will degrade until unusable.

### How to reproduce

```js
const path = require('path');
const {app, BrowserWindow} = require('electron');
app.disableHardwareAcceleration();

app.once('ready', () => {
  const win = new BrowserWindow({
    width: 4096,
    height: 3072,
    useContentSize: true,
    enableLargerThanScreen: true,
    show: false,
    frame: false,
    hasShadow: false,
    transparent: true,
    webPreferences: {
      devTools: false,
      webSecurity: false,
      textAreasAreResizable: false,
      defaultEncoding: 'utf8',
      backgroundThrottling: false,
      offscreen: true,
      zoomFactor: 1,
      experimentalFeatures: false,
      experimentalCanvasFeatures: false
    }
  });

  let index = 0;
  const sizes = [
    {width: 1024, height: 768},
    {width: 2048, height: 1536},
    {width: 4096, height: 3072}
  ];

  win.loadURL('https://www.apple.com');
  win.webContents.setFrameRate(60);
  win.webContents.once('dom-ready', () => {
    setInterval(() => {
      if (index === sizes.length) {
        index = 0;
      }
      const size = sizes[index++];

      // changing the window size causes the memory leak
      win.setSize(size.width, size.height, false);
    }, 100);
  })
});

```

### LINKED ISSUE #8599: Crash with offscreen webview on Linux/Windows
Electron version: 1.14.15

NodeJS version: v6.9.5

Operating system: Linux ip-172-31-47-144 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I have an app that creates a webview, loads a URL, and writes the current image to a file when ready. Setting offscreen: true so I can receive paint events causes Electron to segfault with the following stack trace:

```
Received signal 11 SEGV_MAPERR 000000000018
#0 0x000001e580f7 <unknown>
#1 0x7f1fb053d390 <unknown>
#2 0x00000329c109 <unknown>
#3 0x000002701928 <unknown>
#4 0x000002706512 <unknown>
#5 0x000002706407 <unknown>
#6 0x000002700ced <unknown>
#7 0x000002700c21 <unknown>
#8 0x000002a068e7 <unknown>
#9 0x0000027c4360 <unknown>
#10 0x000002928434 <unknown>
#11 0x00000330c195 <unknown>
#12 0x000001e59226 <unknown>
#13 0x000001e74755 <unknown>
#14 0x000001e74a48 <unknown>
#15 0x000001e74e9b <unknown>
#16 0x000001e4dffa <unknown>
#17 0x7f1fac2d1197 g_main_context_dispatch
#18 0x7f1fac2d13f0 <unknown>
#19 0x7f1fac2d149c g_main_context_iteration
#20 0x000001e4ded6 <unknown>
#21 0x000001e8d41e <unknown>
#22 0x0000026fd569 <unknown>
#23 0x0000026fd3b5 <unknown>
#24 0x00000270023d <unknown>
#25 0x0000026f93ec <unknown>
#26 0x000001221af7 <unknown>
#27 0x0000012205d0 <unknown>
#28 0x000003479633 main
#29 0x7f1fa9edb830 __libc_start_main
#30 0x000000579189 <unknown>
  r8: 000000000000fff8  r9: 000000000000001c r10: 0000003d1409b4a0 r11: 00007f1faa04f390
 r12: 0000000000000000 r13: 0000000000000000 r14: 0000003d1424d2c0 r15: 0000003d1424d2c0
  di: 0000000000000000  si: 0000003d141e6040  bp: 00007ffe34f74901  bx: 0000000000000000
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000003d141e6060  sp: 00007ffe34f74680
  ip: 000000000329c109 efl: 0000000000010246 cgf: 0000000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000018
[end of stack trace]
```

### PR DESCRIPTION
**Pull request by brenca**
This adds support for `webview` tags and "popup windows" (`select` element for example) inside an offscreen window. Also implements a CEF PR that simplifies and possibly speeds up GPU offscreen rendering.

Depends on electron/libchromiumcontent#265 :heavy_check_mark:

Fixes #8599
Might fix #8051 (with the added `ResizeLock`)

Currently only `webview`s that are created when the offscreen window is initialized are renderable inside the offscreen windows, I'm not sure how to change the `RenderWidgetHostView` under a `webview` tag's `webContents`, but if I (or someone else) can figure that out, that would allow us to swap in other `webContents` into an offscreen `webview` as well as rendering a `devTools` window inside the offscreen window.

'popup' windows inside offscreen `webview` tags are still not working.

### CODE REVIEW

**Comment by gerhardberger** [comment]
Read for review! 👀 

/cc @kevinsawicki @zcbenz

File: atom/common/api/atom_api_native_image.cc [hunk 1]
```diff
@@ -200,22 +200,29 @@ void Noop(char*, void*) {
 }  // namespace
 
 NativeImage::NativeImage(v8::Isolate* isolate, const gfx::Image& image)
-    : image_(image) {
-  Init(isolate);
+    : image_(image), isolate_(isolate) {
+  Init(isolate_);
+  isolate_->AdjustAmountOfExternalAllocatedMemory(
+    image_.Width() * image_.Height() * 4);
```
Comment (zcbenz) [inline atom/common/api/atom_api_native_image.cc]: It is possible to get the precise memory used by the image:

```c++
if (image_.HasRepresentation(gfx::Image::kImageRepSkia)) {
  image_.ToImageSkia()->bitmap()->getSize();
}
```

File: atom/browser/api/atom_api_web_contents.h [hunk 2]
```diff
@@ -183,6 +183,7 @@ class WebContents : public mate::TrackableObject<WebContents>,
   void SetFrameRate(int frame_rate);
   int GetFrameRate() const;
   void Invalidate();
+  gfx::Size GetSizeForNewRenderView(content::WebContents*) const override;
```
Comment (zcbenz) [inline atom/browser/api/atom_api_web_contents.h]: This does not seem to be used anywhere.

Comment (brenca) [inline atom/browser/api/atom_api_web_contents.h]: This seems to be called form the chromium side, but I'm not sure why this is here, maybe @gerhardberger can help me out.

**Comment by brenca** [comment]
@zcbenz shall I change the target to the `chrome58` branch, or should I leave it like this so it can be pulled in after that is pulled in?

**Comment by brenca** [comment]
I've rebased this to the latest commit on `chrome58`

**Comment by brenca** [comment]
@zcbenz I've fixed that crash now, the tests seem to be passing.
