### PR TITLE
fix: do not cancel CORS preflight request on proxy auth.

### LINKED ISSUE #25184: Second socket on a session does not send Proxy-Authenticate for ntlm
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
* 9.0.0, 9.2.0, 9.2.1 0 All broken

* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**
  * 8.5.0

### Expected Behavior
When requesting url's and having a socket connect, when it is rejected with proxy authentication required, consistently try again with the proxy authentication credentials.

### Actual Behavior
See logs - good and bad.
In the good logs, electron always makes a 2nd socket request with the proxy authentication headers and succeeds. In the bad logs, electron does not make a 2nd socket request.
Note that for the first socket request on a web page, it works, but when a second socket is opened to make requests it seems to fail.

### To Reproduce
Be behind a NTLM proxy that requires authentication for a domain
Visit a website that makes multiple requests so that multiple sockets are opened.

### LINKED ISSUE #25758: Every CORS (preflight) request fails when behind a proxy and listener attached
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.3
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  * 8

### Expected Behavior
CORS preflight request should work normally

### Actual Behavior
The console logs net::ERR_FAILED and the request fails

### To Reproduce
We have a company proxy that seems to interfere for certain domains (requiring auth).
This issue only happens when attaching any kind of webRequest listener like onBeforeSendHeaders or onBeforeRequest. When the listener is attached the request fails with net::ERR_FAILED in the devtools console. The response headers (logged via webRequest listener) of the request will look like:
"statusLine":"HTTP/1.1 407 Proxy Authentication Required",
	"statusCode":407,
	"responseHeaders":{
		"Connection":["close"],
		"Content-Length":["827"],
		"Proxy-Authenticate": ["NEGOTIATE", "NTLM", "BASIC realm=\"Auth_Seq_NTLM_to_ldap\""],
		"Proxy-Connection":["close"]
	},

This happens for any kind of cors request. i.e.:
fetch("some url", {method: "GET", mode: "cors", headers: {"Content-Type": "application/json"}});

I found this bug report: https://github.com/electron/electron/issues/22242 Maybe it is related?
In the pull request I can see that net::ERR_FAILED responses have been added for cors preflight:
https://github.com/electron/electron/pull/22407/commits/1f59f57908f5f6fae1845209e85300a01a1f264a

### PR DESCRIPTION
**Pull request by marekharanczyk**
#### Description of Change
If connecting via proxy, preflight request can receive 407 header response from proxy. This does not mean request was finished even though it received headers (from proxy, not the destination server), so prevent "completing" and most importantly deleting it, which causes request to be canceled in network layer. Just continue to monitor it and await proper response from server. Also add circuit breaker to cancel request if proxy auth failed 3 times (for example user keeps cancelling auth). This behavior happens only when app registered WebRequest api listeners.

Fixes #25184
Fixes #25758

#### Checklist
- [x] PR description included and stakeholders cc'd
- [X] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes
Notes: Fixed CORS preflight request always being cancelled when connecting via proxy requiring authentication for apps that had registered WebRequest listeners.

### CODE REVIEW

**Comment by marekharanczyk** [comment]
This PR fixes the problem described in https://github.com/electron/electron/issues/29265

**Comment by marekharanczyk** [comment]
Marked issue is a duplicate of #25758.

**Review by nornagon — CHANGES_REQUESTED** [review]
This doesn't match the related code in Chromium: https://source.chromium.org/chromium/chromium/src/+/main:extensions/browser/api/web_request/web_request_proxying_url_loader_factory.cc;l=857-869;drc=924ddf7fffcdc465838e48a40b08ed41bf480a5c

Can you expand on why this is necessary?

**Comment by marekharanczyk** [comment]
I've already reported https://chromium-review.googlesource.com/c/chromium/src/+/2910336 to chromium, which is similar change in their code.
This change is necessary because electron always sets "extraHeader" mode for WebRequests api. When connection is established through proxy requiring auth, 407 response is received from proxy to force client to authenticate itself with proxy. Extension/electron code assumed that any response that is received for CORS preflight (HTTP OPTIONS) completes the requests, but for proxy auth case, request is not yet finished, so it should be kept alive to allow network service to start authentication process. Deleting preflight request immediately after receiving 407 caused it to be cancelled, causing original request to be cancelled as well, making CORS unusable and breaking pages by rpeventing resource loads.
The only difference between CL and this PR is to provide failsafe and abort the request after 3 auth attempts to prevent unintentional infinite auth request loop. Authentication hooks in electron are different from chromium auth code and UI.

**Review by zcbenz — APPROVED** [review]
I'm good with this change, but we should wait for how Chromium reviewers say before merging.

**Comment by lukeapage** [comment]
Amazing this is being fixed now. I’ve received the issue intermittently in chrome too where by I have to reset my settings and it goes away - I can only guess something in my setup pushes chrome into this extra header mode.

**Comment by miniak** [comment]
@marekharanczyk the Chromium change does not have the maximum of 3 attempts, why do we need it here?
https://chromium-review.googlesource.com/c/chromium/src/+/2910336/12/extensions/browser/api/web_request/web_request_proxying_url_loader_factory.cc

**Comment by miniak** [comment]
@marekharanczyk looks like we should also include https://chromium-review.googlesource.com/c/chromium/src/+/2011781
I had the DCHECK when testing the fix with our repro

**Comment by marekharanczyk** [comment]
@miniak The retry check is because electron does not have same handling of auth that chromium has, just a safety measure to prevent infinite loop. I can remove it if it bothers you. Regarding second chromium fix you pointed: I will move it as well.

**Comment by miniak** [comment]
@marekharanczyk I was mostly just wondering why the fix is different between Chromium and Electron. If you believe the retry limit makes sense we can keep it.

**Comment by marekharanczyk** [comment]
Updated code to final version that just got merged upstream and removed fail safe.

File: shell/browser/net/proxying_url_loader_factory.cc [hunk 1]
```diff
@@ -326,6 +326,14 @@ bool ProxyingURLLoaderFactory::IsForServiceWorkerScript() const {
 
 void ProxyingURLLoaderFactory::InProgressRequest::OnLoaderCreated(
     mojo::PendingReceiver<network::mojom::TrustedHeaderClient> receiver) {
+  // When CORS is involved there may be multiple network::URLLoader associated
+  // with this InProgressRequest, because CorsURLLoader may create a new
+  // network::URLLoader for the same request id in redirect handling - see
+  // CorsURLLoader::FollowRedirect. In such a case the old network::URLLoader
+  // is going to be detached fairly soon, so we don't need to take care of it.
+  // We need this explicit reset to avoid a DCHECK failure in mojo::Receiver.
+  header_client_receiver_.reset();
```
Comment (nornagon) [inline shell/browser/net/proxying_url_loader_factory.cc:335]: Is this `.reset()` needed given we immediately `.Bind()` on the next line?

Comment (marekharanczyk) [reply shell/browser/net/proxying_url_loader_factory.cc:335]: This is a cherry-pick of https://chromium-review.googlesource.com/c/chromium/src/+/2011781. Reason for reset is stated above in comment by original author, it is here to prevent DCHECK in mojo receiver.

**Review by nornagon — APPROVED** [review]

**Comment by nornagon** [comment]
11.x is security fixes only now.
