### PR TITLE
fix: don't assign NSAlert to window which is not visible

### LINKED ISSUE #22671: message box can't be dismissed on mac
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.0.0-nightly.20200309
* **Operating System:**
  * macOS 10.15.2
* **Last Known Working Electron version:**
  * Probably never

### Expected Behavior
It's possible to dismiss message box created with `dialog.showMessageBoxSync`

### Actual Behavior
It's not possible to dismiss message box created with `dialog.showMessageBoxSync` if window which is not visible is provided as parameter (it is not possible to focus such box and clicking its ok button doesn't close it).

### To Reproduce
Run following app:
```const { app, dialog, BrowserWindow } = require('electron')

function createWindow() {
  let win = new BrowserWindow({
    show: false
  });
  dialog.showMessageBoxSync(win, { message: "Message" });
}

app.on('ready', createWindow)
```

### PR DESCRIPTION
**Pull request by CezaryKulakowski**
Closes #22671.

Fixes an issue with possible creation of a messageBox which cannot be dismissed on macOS.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed an issue with possible creation of a messageBox which cannot be dismissed on macOS.

### CODE REVIEW

**Comment by codebytere** [comment]
@CezaryKulakowski this appears to be causing a crash on Linux.

**Comment by CezaryKulakowski** [comment]
@codebytere this fix changes only `mm` file which is not being compiled on linux or windows.

**Comment by codebytere** [comment]
@CezaryKulakowski misread - you're correct. Thought it was a `.cc` file on first glance.

**Comment by codebytere** [comment]
@MarshallOfSound in that case, would we want to show the window ourselves if it's hidden before invoking the message box? I wanted to avoid the breaking change in this PR but it might be something to consider

**Comment by CezaryKulakowski** [comment]
@MarshallOfSound what do you mean by documenting this behavior and telling folks to avoid this scenario to call window.show() before opening the modal? Leaving it as it is now and adding some information to documentation? The scenario leading to it isn't very unusual and it breaks the ui.

**Comment by MarshallOfSound** [comment]
> Leaving it as it is now and adding some information to documentation?

Yes exactly that

**Comment by zcbenz** [comment]
@MarshallOfSound @CezaryKulakowski Maybe we can do this fix and document it explicitly? The `showMessageBoxSync` is totally broken under this case, I don't think we should just leave a broken case there and tell users not to do it in the documentation.

File: shell/browser/ui/message_box_mac.mm [hunk 1]
```diff
@@ -98,7 +98,7 @@ int ShowMessageBoxSync(const MessageBoxSettings& settings) {
 
   // Use runModal for synchronous alert without parent, since we don't have a
   // window to wait for.
-  if (!settings.parent_window)
+  if (!settings.parent_window || !settings.parent_window->IsVisible())
```
Comment (zcbenz) [inline shell/browser/ui/message_box_mac.mm]: Should leave a comment on why `IsVisible` is checked here.

**Comment by zcbenz** [comment]
@CezaryKulakowski Can you also document this behavior? (On macOS showing message box on invisible parent window would behave the same with no parent window.)

@MarshallOfSound Are you OK with both documenting this scenario and having a workaround?

**Comment by CezaryKulakowski** [comment]
@zcbenz I've pushed a fixup which updates documentation. I hope this is what you meant.
