### PR TITLE
Fix random crash on app quit

### LINKED ISSUE #10051: Crash on app quit at atom::AtomCTDelegate::ClearCTExcludedHostsList
* Electron version: 1.7.1
* Operating system: Windows / Mac

### Expected behavior
no crash on quit

### Actual behavior
Crash on app quit

```
Thread 23 Crashed:: Chrome_IOThread
0   com.github.electron.framework 	0x000000010e3761f2 std::__1::__tree<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::destroy(std::__1::__tree_node<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>*) + 18 (__tree:1828)
1   com.github.electron.framework 	0x000000010dac0047 std::__1::__tree<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::clear() + 23 (__tree:1831)
2   com.github.electron.framework 	0x000000010dabffed atom::AtomCTDelegate::ClearCTExcludedHostsList() + 13 (atom_ct_delegate.cc:23)
3   com.github.electron.framework 	0x000000010dabe69a atom::AtomCertVerifier::Verify(net::CertVerifier::RequestParams const&, net::CRLSet*, net::CertVerifyResult*, base::Callback<void (int), (base::internal::CopyMode)1, (base::internal::RepeatMode)1> const&, std::__1::unique_ptr<net::CertVerifier::Request, std::__1::default_delete<net::CertVerifier::Request> >*, net::NetLogWithSource const&) + 58 (atom_cert_verifier.cc:170)
4   com.github.electron.framework 	0x000000010f5104fa net::SSLClientSocketImpl::DoVerifyCert(int) + 586 (ssl_client_socket_impl.cc:1273)
5   com.github.electron.framework 	0x000000010f50e3a0 net::SSLClientSocketImpl::DoHandshakeLoop(int) + 160 (ssl_client_socket_impl.cc:1404)
6   com.github.electron.framework 	0x000000010f50ffd5 net::SSLClientSocketImpl::OnHandshakeIOComplete(int) + 21 (ssl_client_socket_impl.cc:1370)
7   com.github.electron.framework 	0x000000010f5192e3 net::TCPClientSocket::DidCompleteRead(base::Callback<void (int), (base::internal::CopyMode)1, (base::internal::RepeatMode)1> const&, int) + 115 (tcp_client_socket.cc:357)
8   com.github.electron.framework 	0x000000010f51c09f net::TCPSocketPosix::ReadCompleted(scoped_refptr<net::IOBuffer> const&, base::Callback<void (int), (base::internal::CopyMode)1, (base::internal::RepeatMode)1> const&, int) + 31 (tcp_socket_posix.cc:590)
9   com.github.electron.framework 	0x000000010f4d972f net::SocketPosix::ReadCompleted() + 207 (socket_posix.cc:465)
10  com.github.electron.framework 	0x000000010f4d9626 net::SocketPosix::OnFileCanReadWithoutBlocking(int) + 310 (trace_event.h:1033)
11  com.github.electron.framework 	0x000000010dc4c8b7 base::MessagePumpLibevent::OnLibeventNotification(int, short, void*) + 215 (message_pump_libevent.cc:341)
12  com.github.electron.framework 	0x000000010dcb7e85 event_base_loop + 1205 (event.c:521)
13  com.github.electron.framework 	0x000000010dc4cadf base::MessagePumpLibevent::Run(base::MessagePump::Delegate*) + 127 (message_pump_libevent.cc:224)
14  com.github.electron.framework 	0x000000010dc498ee base::MessageLoop::RunHandler() + 94 (message_loop.cc:388)
15  com.github.electron.framework 	0x000000010dc634f3 base::RunLoop::Run() + 115 (run_loop.cc:38)
16  com.github.electron.framework 	0x000000010ded33d8 content::BrowserThreadImpl::IOThreadRun(base::RunLoop*) + 24 (browser_thread_impl.cc:278)
17  com.github.electron.framework 	0x000000010ded3566 content::BrowserThreadImpl::Run(base::RunLoop*) + 294 (browser_thread_impl.cc:312)
18  com.github.electron.framework 	0x000000010dc83c59 base::Thread::ThreadMain() + 393 (thread.cc:336)
19  com.github.electron.framework 	0x000000010dc57a87 base::(anonymous namespace)::ThreadFunc(void*) + 87 (platform_thread_posix.cc:73)
20  libsystem_pthread.dylib       	0x00007fff8344c99d _pthread_body + 131
21  libsystem_pthread.dylib       	0x00007fff8344c91a _pthread_start + 168
22  libsystem_pthread.dylib       	0x00007fff8344a351 thread_start + 13
```

### How to reproduce
No consistent repro. May be happening after #7651

cc: @kevinsawicki @deepak1556

### PR DESCRIPTION
**Pull request by tarruda**
Close #10051

@juturu can you confirm if this PR fixes the issue for you?

### CODE REVIEW

File: atom/browser/net/atom_cert_verifier.h [hunk 1]
```diff
@@ -34,7 +34,7 @@ class AtomCertVerifier : public net::CertVerifier {
   void SetVerifyProc(const VerifyProc& proc);
 
   const VerifyProc verify_proc() const { return verify_proc_; }
-  AtomCTDelegate* ct_delegate() const { return ct_delegate_; }
+  AtomCTDelegate* ct_delegate() const { return ct_delegate_.get(); }
```
Comment (ckerr) [inline atom/browser/net/atom_cert_verifier.h]: As a side issue, returning a raw pointer to a managed resource like this worries me a little... but in this case we have a cheap workaround, the only customer of this method is `CertVerifierRequest` which is already a `friend`, so we could move `ct_delegate()` a few lines down here into the `protected` section of the class

File: atom/browser/net/atom_cert_verifier.h [hunk 2]
```diff
@@ -25,7 +25,7 @@ struct VerifyRequestParams {
 
 class AtomCertVerifier : public net::CertVerifier {
  public:
-  explicit AtomCertVerifier(AtomCTDelegate* ct_delegate);
+  explicit AtomCertVerifier(std::shared_ptr<AtomCTDelegate> ct_delegate);
```
Comment (ckerr) [inline atom/browser/net/atom_cert_verifier.h]: This should be a `const std::shared_ptr<AtomCTDelegate>&` here and in the .cc to avoid unnecessary temporaries

**Comment by tarruda** [comment]
> In the first place, who is still trying to use the delegate after the context is destroyed?

I can't answer that as I'm not very familiar with how chromium code works. In fact, I don't event know what the purpose of `AtomBrowserContext` is :)

What I can say is that our application was randomly crashing with a similar stack as the one posted in #10051, and that ensuring `AtomCTDelegate` alive after `AtomBrowserContext is destroyed seemed to fix it.

It appears that whatever chromium object that calls `AtomBrowserContext::CreateCertVerifier()` has a possibility of using it after `AtomBrowserContext` is deleted, so wrapping `AtomCTDelegate` in a `shared_ptr` seemed like an appropriate fix.

File: atom/browser/net/atom_cert_verifier.h (hunk 2 above)
Comment (tarruda) [reply atom/browser/net/atom_cert_verifier.h]: :+1:

File: atom/browser/net/atom_cert_verifier.h (hunk 1 above)
Comment (tarruda) [reply atom/browser/net/atom_cert_verifier.h]: :+1:

**Comment by deepak1556** [comment]
> In the first place, who is still trying to use the delegate after the context is destroyed? Is this a question of the context needing to clean up better in its dtor?

Its possible for `URLRequestContextGetter` to outlive a `BrowserContext` lifetime and the cert verifier and all other network stuff are owned by it. Hence, the crash. That said, I am not sure why I made `AtomBrowserContext` the owner of `AtomCTDelegate` :/ The better fix here is to make `brightray::URLRequestContextGetter` own the delegate.

**Comment by tarruda** [comment]
> The better fix here is to make brightray::URLRequestContextGetter own the delegate.

:+1: I will adjust the PR

**Comment by tarruda** [comment]
@deepak1556 moved `AtomCTDelegate` to brightray (as `RequireCTDelegate`) and made it owned by `brightray::URLRequestContextGetter`.

File: brightray/browser/url_request_context_getter.cc [hunk 3]
```diff
@@ -138,6 +139,7 @@ URLRequestContextGetter::URLRequestContextGetter(
       in_memory_(in_memory),
       io_task_runner_(io_task_runner),
       file_task_runner_(file_task_runner),
+      ct_delegate_(new RequireCTDelegate),
```
Comment (deepak1556) [inline brightray/browser/url_request_context_getter.cc]: This creates the delegate on the UI thread, we should move the initialization into `GetURLRequestContext` method below.

File: brightray/browser/url_request_context_getter.cc [hunk 4]
```diff
@@ -280,8 +282,7 @@ net::URLRequestContext* URLRequestContextGetter::GetURLRequestContext() {
 
     std::unique_ptr<net::TransportSecurityState> transport_security_state =
         base::WrapUnique(new net::TransportSecurityState);
-    transport_security_state->SetRequireCTDelegate(
-        delegate_->GetRequireCTDelegate());
+    transport_security_state->SetRequireCTDelegate(ct_delegate_.get());
     storage_->set_transport_security_state(std::move(transport_security_state));
     storage_->set_cert_verifier(delegate_->CreateCertVerifier());
```
Comment (deepak1556) [inline brightray/browser/url_request_context_getter.cc]: Its better to pass the `ct_delegate` as a parameter of `CreateCertVerifier`, can avoid having a `GetRequireCTDelegate` getter.

File: brightray/browser/url_request_context_getter.cc (hunk 3 above)
Comment (tarruda) [reply brightray/browser/url_request_context_getter.cc]: :+1:

File: brightray/browser/url_request_context_getter.cc (hunk 4 above)
Comment (tarruda) [reply brightray/browser/url_request_context_getter.cc]: :+1:

**Comment by tarruda** [comment]
@deepak1556 done, addressed the requests.
