### PR TITLE
Always set NSScrollViewRubberbanding scroll bounce pref

### LINKED ISSUE #9033: Enabled webPreferences.scrollBounce not working
* Electron version: 1.6.2
* Operating system: macOS 10.12.3 (Sierra)

### Expected behavior

Scrollable elements should bounce (rubber band) when reaching the bounds if a window's `webPreferences.scrollBounce = true`

### Actual behavior

Bouncing does not happen

### How to reproduce

```javascript
var win = new BrowserWindow({
    width:800,
    height:600,
    webPreferences:{
        scrollBounce:true
    }
});
```

### PR DESCRIPTION
**Pull request by kevinsawicki**
Previously Electron was only ever setting this pref to `false` when the `scrollBounce` web preferences was set `false`.

Now it is always set, and set to `true` when enabled so Chrome picks it up and enables it on the renderer.

scroll-bounce

Refs #5412
Closes #9033

### CODE REVIEW

File: atom/renderer/renderer_client_base.cc [hunk 1]
```diff
@@ -96,16 +96,14 @@ void RendererClientBase::RenderThreadStarted() {
...
-    CFPreferencesSetAppValue(key, value, kCFPreferencesCurrentApplication);
-    CFPreferencesAppSynchronize(kCFPreferencesCurrentApplication);
-  }
+  bool scroll_bounce = command_line->HasSwitch(switches::kScrollBounce);
+  base::ScopedCFTypeRef<CFStringRef> rubber_bandking_key(
+    base::SysUTF8ToCFStringRef("NSScrollViewRubberbanding"));
+  CFPreferencesSetAppValue(rubber_bandking_key,
+                           scroll_bounce ? kCFBooleanTrue : kCFBooleanFalse,
+                           kCFPreferencesCurrentApplication);
+  CFPreferencesAppSynchronize(kCFPreferencesCurrentApplication);
```
Comment (tarruda) [inline atom/renderer/renderer_client_base.cc]: Suggestion: Instead of `--scroll-bounce`, the renderer could receive `--enable-scroll-bounce`/`--disable-scroll-bounce` and only set the option if one of these two is passed. If no option is passed, use the default value from the operating system.(For an example of how to use the default OS value, see CEF implementation: https://bitbucket.org/chromiumembedded/cef/src/2f6475c0d89c8b94458b6f7a1146724dbccde09f/libcef/renderer/content_renderer_client.cc?at=master&fileviewer=file-view-default#content_renderer_client.cc-424:438)

Comment (kevinsawicki) [inline atom/renderer/renderer_client_base.cc]: > If no option is passed, use the default value from the operating system

I think this would "break" existing apps that aren't setting the `scrollBounce` key currently since it would use the OS setting and possibly be enabled unknowingly.

Does that sound right to you?

I like the idea of somehow supporting the OS default though 👍 .

Comment (tarruda) [inline atom/renderer/renderer_client_base.cc]: 👍

**Comment by Dexwell** [comment]
I was expecting this setting to enable scroll bouncing for DOM elements such as scrollable divs, but it only seems to apply to the BrowserWindow itself. Per Chromium [#546520](https://bugs.chromium.org/p/chromium/issues/detail?id=546520) it seems like this won't be possible soon.

**Comment by ianpaschal** [comment]
Same. When using...
```
body, html {
  width: 100%;
  height: 100%;
  overflow: hidden;
}
```
...in Safari, only the body from bouncing but allows DOM elements to, as it though.

...in Chromium, however, no-go. :(
