### PR TITLE
fix: do not initialize extension system in in-memory sessions

### LINKED ISSUE #22414: session.fromPartition crashes the app since 9.x
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `9.0.0-beta.1` -- terminates silently
  * `9.0.0-beta.3` -- terminates silently
  * master (`10.0.0-nightly.20200225`) -- crashes with `[448015:0227/160341.082069:FATAL:dependency_manager.cc(144)] Check failed: false. Attempted to access a context that was ShutDown()`
* **Operating System:**
  * Arch Linux current
* **Last Known Working Electron version:**
  * 8.0.2

### Expected Behavior
I don't expect `session.fromPartition()` to terminate or crash the app.
I expect that I will be able to use that session later.
Note that attempting to use the returned session does not prevent the crash/termination.

### Actual Behavior
The app terminates in 9.0.0-beta.* and crashes on master.

Crash log:
```
[449023:0227/160822.369119:FATAL:dependency_manager.cc(144)] Check failed: false. Attempted to access a context that was ShutDown(). This is most likely a heap smasher in progress. After KeyedService::Shutdown() completes, your service MUST NOT refer to depended services again.
#0 0x561dae402699 base::debug::CollectStackTrace()
#1 0x561dae32b223 base::debug::StackTrace::StackTrace()
#2 0x561dae3412a4 logging::LogMessage::~LogMessage()
#3 0x561daf440189 DependencyManager::AssertContextWasntDestroyed()
#4 0x561daf43f98c KeyedServiceBaseFactory::AssertContextWasntDestroyed()
#5 0x561db29d3adb BrowserContextKeyedServiceFactory::GetContextToUse()
#6 0x561daf441280 KeyedServiceFactory::GetServiceForContext()
#7 0x561dae031d95 extensions::BrowserContextKeyedAPIFactory<>::BuildServiceInstanceFor()
#8 0x561db29d3a45 BrowserContextKeyedServiceFactory::BuildServiceInstanceFor()
#9 0x561daf44131a KeyedServiceFactory::GetServiceForContext()
#10 0x561daf43fea9 DependencyManager::CreateContextServices()
#11 0x561db29d3727 BrowserContextDependencyManager::DoCreateBrowserContextServices()
#12 0x561daac4b583 electron::ElectronBrowserContext::ElectronBrowserContext()
#13 0x561daac4cddc electron::ElectronBrowserContext::From()
#14 0x561daabe645f electron::api::Session::FromPartition()
#15 0x561daabe8609 (anonymous namespace)::FromPartition()
#16 0x561daabe88b7 gin_helper::Invoker<>::DispatchToCallback<>()
#17 0x561daabe87ab gin_helper::Dispatcher<>::DispatchToCallback()
#18 0x561dabe90a30 v8::internal::FunctionCallbackArguments::Call()
#19 0x561dabe8f0d1 v8::internal::(anonymous namespace)::HandleApiCallHelper<>()
#20 0x561dabe8d0da v8::internal::Builtin_Impl_HandleApiCall()
#21 0x561dabe8cb89 v8::internal::Builtin_HandleApiCall()
#22 0x561dace0c03f Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit

Received signal 6
#0 0x561dae402699 base::debug::CollectStackTrace()
#1 0x561dae32b223 base::debug::StackTrace::StackTrace()
#2 0x561dae4021b0 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f306a24c800 (/usr/lib/libpthread-2.31.so+0x147ff)
#4 0x7f3068c27ce5 __GI_raise
#5 0x7f3068c11857 __GI_abort
#6 0x561dae400f65 base::debug::BreakDebugger()
#7 0x561dae34174e logging::LogMessage::~LogMessage()
#8 0x561daf440189 DependencyManager::AssertContextWasntDestroyed()
#9 0x561daf43f98c KeyedServiceBaseFactory::AssertContextWasntDestroyed()
#10 0x561db29d3adb BrowserContextKeyedServiceFactory::GetContextToUse()
#11 0x561daf441280 KeyedServiceFactory::GetServiceForContext()
#12 0x561dae031d95 extensions::BrowserContextKeyedAPIFactory<>::BuildServiceInstanceFor()
#13 0x561db29d3a45 BrowserContextKeyedServiceFactory::BuildServiceInstanceFor()
#14 0x561daf44131a KeyedServiceFactory::GetServiceForContext()
#15 0x561daf43fea9 DependencyManager::CreateContextServices()
#16 0x561db29d3727 BrowserContextDependencyManager::DoCreateBrowserContextServices()
#17 0x561daac4b583 electron::ElectronBrowserContext::ElectronBrowserContext()
#18 0x561daac4cddc electron::ElectronBrowserContext::From()
#19 0x561daabe645f electron::api::Session::FromPartition()
#20 0x561daabe8609 (anonymous namespace)::FromPartition()
#21 0x561daabe88b7 gin_helper::Invoker<>::DispatchToCallback<>()
#22 0x561daabe87ab gin_helper::Dispatcher<>::DispatchToCallback()
#23 0x561dabe90a30 v8::internal::FunctionCallbackArguments::Call()
#24 0x561dabe8f0d1 v8::internal::(anonymous namespace)::HandleApiCallHelper<>()
#25 0x561dabe8d0da v8::internal::Builtin_Impl_HandleApiCall()
#26 0x561dabe8cb89 v8::internal::Builtin_HandleApiCall()
#27 0x561dace0c03f Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
  r8: 0000000000000000  r9: 00007ffd4147e670 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffd4147e8d0 r13: aaaaaaaaaaaaaaaa r14: 00007ffd4147f938 r15: 00007ffd4147e8d0
  di: 0000000000000002  si: 00007ffd4147e670  bp: 00007ffd4147e8c0  bx: 00007f3067929c40
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f3068c27ce5  sp: 00007ffd4147e670
  ip: 00007f3068c27ce5 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
```

### To Reproduce
```js
const { BrowserWindow, app, session } = require('electron')
console.log(process.versions)
app.on('ready', () => {
  const foo = session.fromPartition('foo')
  const window = new BrowserWindow({
    webPreferences: {
      // session: foo
    }
  })
  window.webContents.loadURL('about:blank')
  window.show()
})
```

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #22414

Some parts of Chrome in the extension logic expect at least one persistent (not off the record) BrowserContext to exist even when creating an off-the-record context.  This change ensures we don't initialize extensions in a context that does not meet that expectation.  It also adds some handy new infra in our test suite to make it really easy to test crash regressions in the future 👍 

Notes: fixed crash that could occur when calling `session.fromPartition` inside the ready event

### CODE REVIEW

**Comment by deepak1556** [comment]
We don't allow loading extensions in temp session for the same reason https://github.com/electron/electron/pull/22090 

But at the same time if an app wants to run completely off an in memory session it should be allowed.

In this case we just have to make sure the extension dependencies are not loaded for in memory session rather than always creating a permanent session.

**Comment by MarshallOfSound** [comment]
@deepak1556 Took an alternative approach of just not initializing any of the extension stuff in contexts that are in memory

**Comment by deepak1556** [comment]
Sorry for the delay, looked further into the original crash, it was happening because the keyed service was trying to register on a browser context that was destroyed. Even if the extension system is registered on an in memory context, the keyed services that need persistence will rely on `ExtensionBrowserClient::GetOriginalContext` to return a persistent context.

We currently do the following:

```c++
BrowserContext* ElectronExtensionsBrowserClient::GetOriginalContext(
    BrowserContext* context) {
  DCHECK(context);
  if (context->IsOffTheRecord()) {
    return ElectronBrowserContext::From("", false); // cause of the crash
  } else {
    return context;
  }
}
```

`ElectronBrowserContext::From` only maintains a weak map, the caller needs to make sure the return context is managed. So your original solution of having to create a persistent context is correct but its better we create it through `ElectronExtensionsBrowserClient::GetOriginalContext`

https://gist.github.com/deepak1556/fccbfd62d4a5ada87dc9b5aca58f75dc

**Comment by MarshallOfSound** [comment]
@deepak1556 This change ensures that we don't register the extensions system on in-memory contexts (and therefore also fixes this).  Do we want to create (and leak) a default session when an. in-memory session is created (and that in-memory session can't use extensions APIs anyway)?

**Comment by deepak1556** [comment]
> Do we want to create (and leak) a default session when an. in-memory session is created 

By leak do you mean the persistent stuff being created on the user's file system ?

> that in-memory session can't use extensions APIs anyway

Yeah but realized there are other components that rely just on extension system being initialized without the use of extension api we expose, for ex: PDF viewer.

Chrome is slightly different but it does piggyback an incognito context on top of a permanent context to make these things work. So maybe its better we follow that as well ?

But if we are good with ignoring features like PDF viewer for in-memory context then we can stick with the current solution.

**Comment by MarshallOfSound** [comment]
@nornagon Thoughts on the above?

**Comment by nornagon** [comment]
IMO:

- The PDF viewer should work in in-memory sessions.
- It's OK to create a default session even if it's not explicitly used. Not having a default session is a relatively rare use-case, and the memory overhead is not that high afaik.

**Comment by bughit** [comment]
> But at the same time if an app wants to run completely off an in memory session it should be allowed.

It's not entirely clear from this discussion, will that still be possible? AFAIK the following used to accomplish that:

```js
  new BrowserWindow({
    webPreferences: {
      partition: 'memory_partition_1',
    },
  });
```

**Comment by nornagon** [comment]
@bughit that will continue to work; however, the default session will be created behind the scenes.

If there's a compelling reason not to create the default session, we could potentially consider alternatives, but I'm not aware of any such reason.

**Comment by bughit** [comment]
>  however, the default session will be created behind the scenes.

So this default session is a persistent one and will be reading/writing to the userData path?

> If there's a compelling reason not to create the default session

My use-case is multiple parallel instances of the app. They have the save userData. Usually they use memory partitions, When they use persistent partitions they are distinct per process, so there's no interference.

If they now start sharing a persistent default session, isn't that going to be a problem? The ability to run without any persistence seems like a valuable feature, worth keeping.

**Comment by nornagon** [comment]
> > however, the default session will be created behind the scenes.
> 
> So this default session is a persistent one and will be reading/writing to the userData path?

Only data relevant to the session will be written to disk, so if you never open a window or make a request in the default session, no meaningful data will be written. This change doesn't alter observable behavior other than perhaps creating a few empty files and directories in the userData directory that otherwise might not have been created.

> > If there's a compelling reason not to create the default session
> 
> My use-case is multiple parallel instances of the app. They have the save userData. Usually they use memory partitions, When they use persistent partitions they are distinct per process, so there's no interference.

This ought to continue to work. As above, the persistence or otherwise of actual session data isn't affected by this change; it's just creating an empty/unused session behind the scenes, because Chromium's infrastructure expects it.

**Comment by bughit** [comment]
> This change doesn't alter observable behavior other than perhaps creating a few empty files and directories in the userData directory that otherwise might not have been created

My understanding is that chrome does not support sharing its data directory among multiple browser instances. So even though this default sessions will not be used explicitly, it seems to me its implicit use, which at least involves file creation and ultimately whatever else chrome decides to do with it, is not instance-safe. What if two instances start creating it at the same time?

**Comment by bughit** [comment]
I ran the following test with 9.0, which creates but does not use a default session

```js
'use strict';

const {app, BrowserWindow, session} = require('electron'),
      Path = require('path');

let win;

app.setPath('userData', Path.join(__dirname, 'chrome_user_data'));

app.once('ready', async () => {

  session.defaultSession;

  win = new BrowserWindow({
    webPreferences: {
      partition: 'memory_partition_1',
    },
  });

});
```

And captured the writing with procmon

```
6:56:24.3193390 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Dictionaries	
6:56:24.3626403 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage	
6:56:24.3633425 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage\leveldb	
6:56:24.3656301 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage\leveldb\LOG	
6:56:24.3668767 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage\leveldb\LOCK	
6:56:24.3677877 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage\leveldb\MANIFEST-000001	
6:56:24.3690609 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage\leveldb\MANIFEST-000001	
6:56:24.3691502 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage\leveldb\MANIFEST-000001	
6:56:24.3693444 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache	
6:56:24.3693903 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage\leveldb\000001.dbtmp	
6:56:24.3699456 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\js	
6:56:24.3701963 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage\leveldb\000001.dbtmp	
6:56:24.3703091 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage\leveldb\000001.dbtmp	
6:56:24.3719080 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\wasm	
6:56:24.3738669 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\wasm\index	
6:56:24.3739064 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\js\index	
6:56:24.3752255 PM	electron.exe	7624	Write	SetRenameInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage\leveldb\000001.dbtmp	
6:56:24.3759430 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\js\index	
6:56:24.3762444 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\wasm\index	
6:56:24.3793089 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage\leveldb\LOG	
6:56:24.3801179 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Local Storage\leveldb\000003.log	
6:56:24.4152386 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\FontLookupTableCache	
6:56:24.4372853 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\blob_storage	
6:56:24.4401104 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\blob_storage\20399d0c-a5e0-4c6d-8777-87723a04b9c5	
6:56:24.4623401 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\wasm\index-dir	
6:56:24.4624150 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\js\index-dir	
6:56:24.4668419 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\wasm\index-dir\temp-index	
6:56:24.4675323 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\js\index-dir\temp-index	
6:56:24.4678371 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\wasm\index-dir\temp-index	
6:56:24.4686223 PM	electron.exe	7624	Write	SetRenameInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\wasm\index-dir\temp-index	
6:56:24.4686618 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\js\index-dir\temp-index	
6:56:24.4729793 PM	electron.exe	7624	Write	SetRenameInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Code Cache\js\index-dir\temp-index	
6:56:24.4871992 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\FontLookupTableCache\font_unique_name_table.pb	
6:56:24.4888344 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\FontLookupTableCache\font_unique_name_table.pb	
6:56:24.4893837 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\FontLookupTableCache\font_unique_name_table.pb	
6:56:24.6615181 PM	electron.exe	6300	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache	
6:56:24.6630549 PM	electron.exe	6300	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\index	
6:56:24.6643207 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\index	
6:56:24.6676773 PM	electron.exe	6300	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_0	
6:56:24.6685239 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_0	
6:56:24.6693022 PM	electron.exe	6300	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_1	
6:56:24.6697802 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_1	
6:56:24.6708353 PM	electron.exe	6300	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_2	
6:56:24.6717552 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_2	
6:56:24.6725234 PM	electron.exe	6300	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_3	
6:56:24.6732632 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_3	
6:56:24.6748630 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_1	
6:56:24.6749909 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_0	
6:56:24.6750554 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_0	
6:56:24.9973814 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_1	
6:56:24.9974064 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_3	
6:56:24.9974435 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_0	
6:56:24.9976137 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_1	
6:56:24.9998967 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_0	
6:56:24.9999776 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_0	
6:56:25.0000331 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_0	
6:56:25.2202132 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Dictionaries\en-US-9-0.bdic	
6:56:25.2207295 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Dictionaries\en-US-9-0.bdic	
6:56:25.2320184 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_1	
6:56:25.2320563 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_3	
6:56:25.2341299 PM	electron.exe	6300	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\f_000001	
6:56:25.2349635 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Dictionaries\en-US-9-0.bdic
6:56:25.2349772 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_1	
6:56:25.2350842 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\en-US-9-0.bdic	
6:56:25.2352752 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\f_000001	
6:56:25.2355163 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_0	
6:56:25.2360866 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\en-US-9-0.bdic	
6:56:34.3624166 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\66c10975-431d-4c22-8496-5cc819ce9b68.tmp	
6:56:34.3652618 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\66c10975-431d-4c22-8496-5cc819ce9b68.tmp	
6:56:34.3653794 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\66c10975-431d-4c22-8496-5cc819ce9b68.tmp	
6:56:34.3678524 PM	electron.exe	7624	Write	SetRenameInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\66c10975-431d-4c22-8496-5cc819ce9b68.tmp	
6:56:34.3802212 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\4ae30b76-14d0-4738-891c-5f1fbddf4a7a.tmp	
6:56:34.3817802 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\4ae30b76-14d0-4738-891c-5f1fbddf4a7a.tmp	
6:56:34.3818740 PM	electron.exe	7624	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\4ae30b76-14d0-4738-891c-5f1fbddf4a7a.tmp	
6:56:34.3834764 PM	electron.exe	7624	Write	SetRenameInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\4ae30b76-14d0-4738-891c-5f1fbddf4a7a.tmp
6:56:34.3844087 PM	electron.exe	7624	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Preferences~RF2999ebb.TMP	
6:56:34.3854539 PM	electron.exe	7624	Write	SetRenameInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Preferences	
6:56:34.3863501 PM	electron.exe	7624	Write	SetRenameInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\4ae30b76-14d0-4738-891c-5f1fbddf4a7a.tmp	
6:56:34.3874649 PM	electron.exe	7624	Write	SetDispositionInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Preferences~RF2999ebb.TMP	
6:56:34.6567804 PM	electron.exe	6300	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\c8fe231a-1242-4e94-9570-37b98bb0428f.tmp	
6:56:34.6579051 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\c8fe231a-1242-4e94-9570-37b98bb0428f.tmp	
6:56:34.6579809 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\c8fe231a-1242-4e94-9570-37b98bb0428f.tmp	
6:56:34.7592163 PM	electron.exe	6300	Write	SetRenameInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\c8fe231a-1242-4e94-9570-37b98bb0428f.tmp	
6:57:24.3457955 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Cache\data_1	
6:57:24.3493841 PM	electron.exe	6300	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\f091f18a-4019-4e1a-99b2-3a27a9344a04.tmp	
6:57:24.3506746 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\f091f18a-4019-4e1a-99b2-3a27a9344a04.tmp	
6:57:24.3507898 PM	electron.exe	6300	Write	WriteFile	C:\src\electron_test_apps\start_crash\chrome_user_data\f091f18a-4019-4e1a-99b2-3a27a9344a04.tmp	
6:57:24.4535771 PM	electron.exe	6300	Write	SetRenameInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\f091f18a-4019-4e1a-99b2-3a27a9344a04.tmp
6:57:24.4558891 PM	electron.exe	6300	Write	CreateFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Network Persistent State~RF29a6248.TMP	
6:57:24.4569007 PM	electron.exe	6300	Write	SetRenameInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Network Persistent State	
6:57:24.4575626 PM	electron.exe	6300	Write	SetRenameInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\f091f18a-4019-4e1a-99b2-3a27a9344a04.tmp	
6:57:24.4583792 PM	electron.exe	6300	Write	SetDispositionInformationFile	C:\src\electron_test_apps\start_crash\chrome_user_data\Network Persistent State~RF29a6248.TMP	
```
- that's a lot of writing to a lot of files
- some at the beginning, some later, some on exit

Does this test capture what your defaultSession creation will do? If so, I can't imagine this is multi-instance safe. If you believe it is, please explain, otherwise please continue supporting runing without a persistent defaultSession.

**Comment by bughit** [comment]
@nornagon Regardless of how this shakes out, it's important to understand the ramifications, so to that end, could you (or others in this thread) please comment on my previous two posts?

**Comment by nornagon** [comment]
@bughit I agree that we should be sure not to break multiple instances of Electron running at the same time. I don't have enough context right now to say for sure how Chromium's internals would handle multiple processes accessing that directory, or whether this PR would break that use case.

**Comment by bughit** [comment]
Here's a confirmation from chromium docs
https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md

>two running Chrome instances cannot share the same user data directory

also an internal bug report mentions it

[WebView should make sure it's not used multiple times at once from the same data dir](https://bugs.chromium.org/p/chromium/issues/detail?id=558377)

> This will cause both instances to open the same database/cache/etc files at the same time, which will probably malfunction and/or corrupt data

File: shell/browser/electron_browser_context.h [hunk 1]
```diff
@@ -138,6 +138,8 @@ class ElectronBrowserContext
   }
 
 #if BUILDFLAG(ENABLE_ELECTRON_EXTENSIONS)
+  // Guard usages of extension_system() with !IsOffTheRecord()
+  // There is no extension system for in-memory sessions
```
Comment (nornagon) [inline shell/browser/electron_browser_context.h:142]: `DCHECK` perhaps?

File: spec-main/crash-spec.ts [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+      const fixture = path.resolve(fixturePath, crashCase)
+      const argsFile = path.resolve(fixture, 'electron.args')
+      const args = [fixture]
+      if (fs.existsSync(argsFile)) {
+        args.push(...fs.readFileSync(argsFile, 'utf8').trim().split('\n'))
+      }
+      return runFixtureAndEnsureCleanExit(args)
+    })
+  }
+})
```
Comment (nornagon) [inline spec-main/crash-spec.ts:54]: this should go in the extensions spec file

Comment (MarshallOfSound) [reply spec-main/crash-spec.ts:54]: This was starting a new thing / easy way to add "this used to crash" style specs instead of scattering them around with re-implementation of the bootstrapping logic.  Now you can just add fixtures to the crash cases folder and assert they no longer crash

**Comment by bughit** [comment]
@nornagon 

> see above, we need to confirm that the use-case for multiple instances of electron isn't broken.

I took that to mean that you would to avoid a persistent defaultSession which is not multi-instance safe, unless the app chose to use it.

> [two running Chrome instances cannot share the same user data directory](https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md)

However, looking at v18 it's created by default and it doesn't appear possible to avoid it.

So can this be considered a bug and be addressed? I am comparing with v4.2 which did not create a persistent default sessions unless a BrowserWindows was configured to use it.

**Comment by bughit** [comment]
@nornagon filed a bug for this: #33663
