### PR TITLE
fix: Pass on errors thrown in `executeJavaScript`

### LINKED ISSUE #11155: executeJavaScript does not reject with the Error of the rejected eval result Promise
* Electron version: 1.7.9 x86
* Operating system: Win7 x64

```js
  try {
    await web.executeJavaScript('new Promise(() => {throw new Error("exec error");});');
    // or
    await web.executeJavaScript('Promise.reject(new Error("exec error"));'); 
  } catch (e) {
    // e should be an Error('exec error')
  }
```
### Expected behavior

 e should be an Error('exec error')

### Actual behavior

e is an empty Object

### PR DESCRIPTION
**Pull request by felixrieseberg**
When you reject a Promise from a `executeJavaScript` call, we pass on the rejection. That's good! However, [if you write JavaScript as recommended by the pros](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject), you'll be rejecting with an instance of `Error`, which results in an broken result of `{}`.

The reason is simple: `Error` objects don't serialize. This is true for all of them (`ReferenceError`, `TypeError`, `URIError`, etc).

```js
const myError = new Error('Something went wrong')
JSON.stringify(myError) === '{}' // true
```

The result is this, which makes no sense to developers who haven't studied Error objects and the IPC:
```js
webContents.executeJavaScript('Promise.reject(new Error("Something went wrong"));')
  .catch((error) => {
     console.log(error) // This will log '{}'
  })
```

This PR provides a fix: Let's serialize known and common Error objects for these calls in the renderer and recreate them in the main process. Also: Tests!

With this PR:
```js
webContents.executeJavaScript('Promise.reject(new Error("Something went wrong"));')
  .catch((error) => {
     console.log(error)
     // This will now log:
     // Error: Something went wrong
     //     at <anonymous>:1:16
     //     at EventEmitter.electron.ipcRenderer.on(...
     //     ...
  })
```

Closes #11155

### CODE REVIEW

File: lib/browser/api/web-contents.js [hunk 1]
```diff
@@ -120,7 +130,18 @@ const asyncWebFrameMethods = function (requestId, method, callback, ...args) {
         if (typeof callback === 'function') callback(result)
         resolve(result)
       } else {
-        reject(error)
+        if (error && error.__ELECTRON_SERIALIZED_ERROR__) {
```
Comment (alexeykuzmin) [inline lib/browser/api/web-contents.js]: `error` is guaranteed to be not `null` nor `undefined` here, do you really need `if (error &&`?

File: lib/browser/api/web-contents.js [hunk 2]
```diff
@@ -120,7 +130,18 @@ const asyncWebFrameMethods = function (requestId, method, callback, ...args) {
...
+          let rehydratedError = error
+
+          if (errorConstructors[error.name]) {
```
Comment (alexeykuzmin) [inline lib/browser/api/web-contents.js]: I guess this check can be moved to a condition above, so the whole change will be:

```js
} else {
  if (/* is a serialized error */) {
    const rehydratedError = new errorConstructors[error.name](error.message)
    rehydratedError.stack = error.stack
    reject(rehydratedError)
  } else {
    reject(error)
  }
}
```

File: spec/api-browser-window-spec.js [hunk 3]
```diff
@@ -2514,6 +2514,15 @@ describe('BrowserWindow module', () => {
...
     const asyncCode = `(() => new Promise(r => setTimeout(() => r("${expected}"), 500)))()`
     const badAsyncCode = `(() => new Promise((r, e) => setTimeout(() => e("${expectedErrorMsg}"), 500)))()`
+    const errorCodes = {
+      Error: 'Promise.reject(new Error("Wamp-wamp"))',
+      ReferenceError: 'Promise.reject(new ReferenceError("Wamp-wamp"))',
+      EvalError: 'Promise.reject(new EvalError("Wamp-wamp"))',
+      RangeError: 'Promise.reject(new RangeError("Wamp-wamp"))',
+      SyntaxError: 'Promise.reject(new SyntaxError("Wamp-wamp"))',
+      TypeError: 'Promise.reject(new TypeError("Wamp-wamp"))',
+      URIError: 'Promise.reject(new URIError("Wamp-wamp"))'
```
Comment (alexeykuzmin) [inline spec/api-browser-window-spec.js]: Maybe calls of `Promise.reject()` should be part of the test, not the list of error types?

```js
const errorTypes = new Set([
  Error,
  ReferenceError,
  <...>
])

<...>

for (const ErrorType of errorTypes) {
  <...>
  ipcRenderer.send('executeJavaScript', `Promise.reject(new ${ErrorType}("Wamp-wamp"))`, true)
  <...>
}
```

File: spec/static/main.js [hunk 4]
```diff
@@ -217,6 +217,10 @@ app.on('ready', function () {
       window.webContents.send('executeJavaScript-promise-response', result)
     }).catch((error) => {
       window.webContents.send('executeJavaScript-promise-error', error)
+
+      if (error && error.name) {
+        window.webContents.send('executeJavaScript-promise-error-name', error.name)
```
Comment (alexeykuzmin) [inline spec/static/main.js]: Do you need this only for tests? Can the `'executeJavaScript-promise-error'` message be used instead?

Comment (felixrieseberg) [reply spec/static/main.js]: Sadly not (but this is a wonderful example of how un-intuitive this is) - if we send the received error over the IPC again, we'll get `{}` again 😆
