### PR TITLE
fix: destroy WebContents synchronously on shutdown

### LINKED ISSUE #15133: 4.0 crashes on shutdown when using BrowserView
* Output of `node_modules/.bin/electron --version`:  4.0.0-beta.3
* Operating System (Platform and Version): macOS 10.13.5
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.3

**Expected Behavior**
Electron shouldn't crash.

**Actual behavior**
A crash occurs.

**To Reproduce**
* Make a copy of `electron-quick-start`, and add the following to `main.js`:
```
const BrowserView = require("electron").BrowserView;
app.on('ready', function () {
  new BrowserView({})
})
```
* Quit the app.

Crash report:
```

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

VM Regions Near 0:
--> 
    __TEXT                 000000010283e000-000000010283f000 [    4K] r-x/rwx SM=COW  /Users/USER/Documents/*/Electron.app/Contents/MacOS/Electron

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   com.github.Electron.framework 	0x00000001081f8d45 0x10740c000 + 14601541
1   com.github.Electron.framework 	0x00000001081f9cfe 0x10740c000 + 14605566
2   com.github.Electron.framework 	0x000000010919563b 0x10740c000 + 30971451
3   com.github.Electron.framework 	0x000000010919574e 0x10740c000 + 30971726
4   com.github.Electron.framework 	0x00000001090e9ef2 0x10740c000 + 30269170
5   com.github.Electron.framework 	0x00000001091c4e31 0x10740c000 + 31166001
6   com.github.Electron.framework 	0x00000001091c59e2 0x10740c000 + 31168994
7   com.github.Electron.framework 	0x00000001091cf98e 0x10740c000 + 31209870
8   com.github.Electron.framework 	0x000000010902f828 0x10740c000 + 29505576
9   com.github.Electron.framework 	0x000000010a45e731 0x10740c000 + 50669361
10  com.github.Electron.framework 	0x0000000108e5a8c4 0x10740c000 + 27584708
11  com.github.Electron.framework 	0x000000010740e114 AtomMain + 84
12  libdyld.dylib                 	0x00007fff78bb7015 start + 1
```

### PR DESCRIPTION
**Pull request by zcbenz**
#### Description of Change

Destroying WebContents asynchronously on shutdown may delay the destroying task after the shutdown task, resulting in an assertion in `ResourceDispatcherHostImpl::OnShutdown`.

This PR destroys WebContents synchronously on shutdown, so we can fix #15133 without breaking https://github.com/electron/electron/issues/8930.

I have also added notes for `DestroyWebContents` on how to use it correctly.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: Fix crash on exit when using `BrowserView`.

### CODE REVIEW

**Comment by zcbenz** [comment]
The crash turned out to be a mistake when refactoring.

All tests are passing now.

**Comment by MarshallOfSound** [comment]
@zcbenz The `4.0` backport failed, trop failed to report it because of a GitHub API error.  Will work on a fix for trop for that but just a heads up for now 👍

File: spec/fixtures/api/leak-exit-browserview.js [hunk 1]
```diff
@@ -0,0 +1,6 @@
+const { BrowserView, app } = require('electron')
+app.on('ready', function () {
+  new BrowserView({})  // eslint-disable-line
+
+  process.nextTick(() => app.quit())
```
Comment (deepak1556) [inline spec/fixtures/api/leak-exit-browserview.js]: Any reason this has to be on the next tick ?

Comment (zcbenz) [reply spec/fixtures/api/leak-exit-browserview.js]: I'm trying to emulate the original crash case, having `process.nextTick` or not does not really affect the test.

**Comment by deepak1556** [comment]
@zcbenz just remembered, we had disabled a spec in 69 due to the same crash https://github.com/orgs/electron/projects/24#card-13687849, can you try enabling it in this PR ? Thanks!
