### PR TITLE
Redispatch events to handle native OSX shortcuts

### LINKED ISSUE #5246: Move Focus to Next Window not working anymore
* Electron version: 0.37.6
* Operating system: Mac OS X 10.11

A user reported that with VS Code running with Electron 0.37.6 would no longer allow him to "Move Focus to Next Window". It seems you can assign a keybinding for this globally in settings (in this case he tried with Cmd+F1).

I verified that the same keybinding works just fine with our VS Code on Electron 0.35.6.

When I look through the release notes, I see an entry in v0.36.8 that might be suspicious?

> Fix Command + ~ not switching windows sometimes.

### LINKED ISSUE #6016: [OS X] Ctrl+F2 keyboard shortcut to focus menu bar does not work
* Electron version: 1.2.2
* Operating system: OS X 10.9.5

Pressing Ctrl+F2 should focus the menu bar. It works in all native Mac applications. It does nothing in Electron apps. This is a quite serious accessibility issue.

### PR DESCRIPTION
**Pull request by kevinsawicki**
This pull request pulls in code from [command_dispatcher.mm](https://cs.chromium.org/codesearch/f/chromium/src/ui/base/cocoa/command_dispatcher.mm) that redispatches events in an attempt to correctly handle native keyboard shortcuts like `Ctrl+F2` and `Cmd-~` on Mac OS X.

### Tested Scenarios

- [x] Menu-based shortcuts like `Cmd-R`, `Cmd-A`, `Cmd-Alt-I`.
- [x] Native shortcuts like `Cmd-~` and `Ctrl-F2`
- [x] Calling `preventDefault()` on a `keydown` event to disable something native like `Cmd-A` to select all
- [x] Typing and keybindings in `<input>` elements 
- [x] Docked devtools window
- [x] Undocked devtools window
- [ ] Others?

If anyone is able to test this branch for their app and verify menus and shortcuts still work as expected, that would be really helpful. /cc @electron/maintainers 

Closes #5246 
Closes #6016 
Depends on https://github.com/electron/brightray/issues/227

Related reading:

https://www.chromium.org/developers/os-x-keyboard-handling
https://github.com/nwjs/nw.js/commit/6658fbb839a9623f373b51fee37370f5bf500a6d

### CODE REVIEW

**Comment by kevinsawicki** [comment]
@zcbenz do you think it makes more sense to try and use the Chromium classes directly here like `CommandDispatcher`, `CommandDispatcherTarget`, and `CommandDispatcherDelegate`?

File: atom/browser/common_web_contents_delegate_mac.mm [hunk 1]
```diff
@@ -22,17 +23,9 @@
...
-    if ((event.os_event.modifierFlags & NSCommandKeyMask) /* cmd */ &&
-        (event.os_event.keyCode == 50  /* ~ */)) {
-      if (event.os_event.modifierFlags & NSShiftKeyMask) {
-        [NSApp sendAction:@selector(_cycleWindowsReversed:) to:nil from:nil];
-      } else {
-        [NSApp sendAction:@selector(_cycleWindows:) to:nil from:nil];
-      }
-    }
+  if (event.os_event.window) {
+    AtomNSWindow* native_window = static_cast<AtomNSWindow*>(event.os_event.window);
```
Comment (zcbenz) [inline atom/browser/common_web_contents_delegate_mac.mm]: For undocked devtools window, it is not an `AtomNSWindow`.

**Comment by zcbenz** [comment]
> @zcbenz do you think it makes more sense to try and use the Chromium classes directly here like CommandDispatcher, CommandDispatcherTarget, and CommandDispatcherDelegate?

I think current implementation is perfect.

File: atom/browser/common_web_contents_delegate_mac.mm (hunk 1 above)
Comment (kevinsawicki) [inline atom/browser/common_web_contents_delegate_mac.mm]: > Also I haven't tried, but I think we should be able to just call [window redispatchKeyEvent:] without type conversion.

Yeah, when I try that I get the following compiler error:

`error: 'NSWindow' may not respond to 'redispatchKeyEvent:' [-Werror]`

File: atom/browser/common_web_contents_delegate_mac.mm [hunk 2]
```diff
@@ -22,17 +23,9 @@
...
-    if ((event.os_event.modifierFlags & NSCommandKeyMask) /* cmd */ &&
-        (event.os_event.keyCode == 50  /* ~ */)) {
-      if (event.os_event.modifierFlags & NSShiftKeyMask) {
-        [NSApp sendAction:@selector(_cycleWindowsReversed:) to:nil from:nil];
-      } else {
-        [NSApp sendAction:@selector(_cycleWindows:) to:nil from:nil];
-      }
-    }
+  NSWindow* window = event.os_event.window;
+  if (window && [window isKindOfClass:[AtomNSWindow class]]) {
```
Comment (kevinsawicki) [inline atom/browser/common_web_contents_delegate_mac.mm]: @zcbenz Switched it to use `isKindOfClass` instead.

Comment (zcbenz) [inline atom/browser/common_web_contents_delegate_mac.mm]: @kevinsawicki The devtools window also needs the same handling code, otherwise it won't respond to `cmd+~`, steps to reproduce:

1. Open devtools window in detached state
1. Press `cmd+~` in it

Comment (kevinsawicki) [inline atom/browser/common_web_contents_delegate_mac.mm]: Oh, yeah, didn't realize that, thanks 👍

Comment (kevinsawicki) [inline atom/browser/common_web_contents_delegate_mac.mm]: @zcbenz I opened up a small brightray pull request that applies the minimal event redispatch to the `UnderlayOpenGLHostingWindow` used there for the devtools window.

Does that approach make sense?

https://github.com/electron/brightray/pull/227

**Comment by kevinsawicki** [comment]
@zcbenz I reworked this pull request to add an `EventDispatchingWindow` to brightray that gets extended by `AtomNSWindow` and used by the devtools undocked window.

`EventDispatchingWindow` does extend `UnderlayOpenGLHostingWindow` which means `AtomNSWindow` now is a `UnderlayOpenGLHostingWindow` instead of a `NSWindow`. This seems okay since `UnderlayOpenGLHostingWindow` is pretty simple, https://cs.chromium.org/chromium/src/ui/base/cocoa/underlay_opengl_hosting_window.mm?q=UnderlayOpenGLHostingWindow&sq=package:chromium&dr=C

Let me know if you have concerns with this approach.

**Comment by zcbenz** [comment]
> you can hide the internal members using class extension:
> https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html#//apple_ref/doc/uid/TP40011210-CH6-SW3

👍
