### PR TITLE
fix: use `temp` directory for singleton test and clean up at end

### LINKED ISSUE #49539: Running Electron tests should not create folder in home directory
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

42, 41

### What operating system(s) are you using?

macOS

### Operating System Version

Tahoe 26.2

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

_No response_

### Does the issue also appear in Chromium / Google Chrome?

No

### Expected Behavior

Running `e test` does not create folders in my home directory.

### Actual Behavior

I found a folder called `electron-test-singleton-userdata` in my home directory from the last time I ran `e test`.

It contained files related to single instance lock.

This is where that folder name is referenced in our source code:

https://github.com/electron/electron/blob/0cc15a6386f192691f74a65dcee4a2304a375fc1/spec/fixtures/api/singleton-userdata/main.js#L8

### Testcase Gist URL

_No response_

### Additional Information

Fix ideas:

- Create the folder in `/tmp`
- Delete the folder at the end of that test

### PR DESCRIPTION
**Pull request by nmggithub**
#### Description of Change

This should resolve #49539. Some minor refactoring of the test was done, but can be reverted if desired.

#### Checklist

- [x] PR description included
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none.

### CODE REVIEW

File: spec/fixtures/api/singleton-userdata/main.js [hunk 1]
```diff
@@ -3,11 +3,13 @@ const { app } = require('electron');
 const fs = require('node:fs');
 const path = require('node:path');
 
+app.setPath('userData', path.join(app.getPath('temp'), 'electron-test-singleton-userdata'));
+
 // non-existent user data folder should not break requestSingleInstanceLock()
```
Comment (nmggithub) [inline spec/fixtures/api/singleton-userdata/main.js:8]: Tangential: this comment references an issue that has since been closed. Should it be removed?

Comment (dsanders11) [reply spec/fixtures/api/singleton-userdata/main.js:8]: The comment should be left, it provides the historical context for why `fs.rmSync` is being done before `app. requestSingleInstanceLock()`.

**Comment by nmggithub** [comment]
> Thanks for the clean up! I think the motivating change for this PR is a good one, but I think the implementation should be tweaked:
> 
> * Leave `const userDataFolder`, but change `app.getPath('home')` to be `app.getPath('temp')`
> * Put the final cleanup on the line before `app.exit` - while `app.exit` is not sync, we shouldn't rely on that behavior for doing the cleanup here.
> 
> The main reason to leave `userDataFolder` as a variable is to ensure we're only removing the directory we intend to. If `app.setPath` had a bug that caused it to silently fail, `fs.rmSync(app.getPath('userData'), ...)` would remove the default `userData` and leave the temp one.

@dsanders11 Changes have been made. Thanks for the feedback!

File: spec/fixtures/api/singleton-userdata/main.js [hunk 2]
```diff
@@ -3,11 +3,14 @@ const { app } = require('electron');
 const fs = require('node:fs');
 const path = require('node:path');
 
+const userDataFolder = path.join(app.getPath('temp'), 'electron-test-singleton-userdata')
+app.setPath('userData', userDataFolder);
```
Comment (nmggithub) [inline spec/fixtures/api/singleton-userdata/main.js]: Nit: honestly it might make sense now to move the `app.setPath` line back down to after the first `rmSync`. But I think it's a matter of preference.

**Comment by nmggithub** [comment]
@dsanders11 I just noticed the linter doesn't like the missing semicolon. I'll add it.

File: spec/fixtures/api/singleton-userdata/main.js [hunk 3]
```diff
@@ -3,11 +3,13 @@ const { app } = require('electron');
...
-const userDataFolder = path.join(app.getPath('home'), 'electron-test-singleton-userdata');
-fs.rmSync(userDataFolder, { force: true, recursive: true });
+const userDataFolder = path.join(app.getPath('temp'), 'electron-test-singleton-userdata');
 app.setPath('userData', userDataFolder);
 
+// non-existent user data folder should not break requestSingleInstanceLock()
+// ref: https://github.com/electron/electron/issues/33547
+fs.rmSync(userDataFolder, { recursive: true, force: true });
 const gotTheLock = app.requestSingleInstanceLock();
+fs.rmSync(userDataFolder, { recursive: true, force: true });
```
Comment (nikwen) [inline spec/fixtures/api/singleton-userdata/main.js:17]: I like the idea of cleaning up after the test. I think we should do it after `app.exit()` though.

File: spec/fixtures/api/singleton-userdata/main.js [hunk 4]
```diff
@@ -3,11 +3,13 @@ const { app } = require('electron');
...
-// non-existent user data folder should not break requestSingleInstanceLock()
-// ref: https://github.com/electron/electron/issues/33547
-const userDataFolder = path.join(app.getPath('home'), 'electron-test-singleton-userdata');
-fs.rmSync(userDataFolder, { force: true, recursive: true });
+const userDataFolder = path.join(app.getPath('temp'), 'electron-test-singleton-userdata');
 app.setPath('userData', userDataFolder);
 
+// non-existent user data folder should not break requestSingleInstanceLock()
+// ref: https://github.com/electron/electron/issues/33547
+fs.rmSync(userDataFolder, { recursive: true, force: true });
```
Comment (nikwen) [inline spec/fixtures/api/singleton-userdata/main.js:10]: I think we should call `fs.rmSync` before `app.setPath()`. It's thinkable that Electron would start using the folder as soon as it's set as the `userData` path, so we should clear it before that happens, not after.

File: spec/fixtures/api/singleton-userdata/main.js [hunk 5]
```diff
@@ -3,11 +3,13 @@ const { app } = require('electron');
 const fs = require('node:fs');
 const path = require('node:path');
 
-// non-existent user data folder should not break requestSingleInstanceLock()
-// ref: https://github.com/electron/electron/issues/33547
-const userDataFolder = path.join(app.getPath('home'), 'electron-test-singleton-userdata');
-fs.rmSync(userDataFolder, { force: true, recursive: true });
+const userDataFolder = path.join(app.getPath('temp'), 'electron-test-singleton-userdata');
```
Comment (nikwen) [inline spec/fixtures/api/singleton-userdata/main.js:6]: What do you think about adding a timestamp at the end of the folder name?

```js
`electron-test-singleton-userdata-${Date.now()}`
```

Makes it safe that we don't reuse an existing folder.

(This part is not required for me to approve the PR.)

File: spec/fixtures/api/singleton-userdata/main.js (hunk 3 above)
Comment (dsanders11) [reply spec/fixtures/api/singleton-userdata/main.js:17]: Why after? I actually requested it be moved before. 😅

File: spec/fixtures/api/singleton-userdata/main.js (hunk 5 above)
Comment (nmggithub) [reply spec/fixtures/api/singleton-userdata/main.js:6]: We remove it before creating it again. So I don't think it would even be possible to re-use an existing folder?

File: spec/fixtures/api/singleton-userdata/main.js (hunk 4 above)
Comment (nmggithub) [reply spec/fixtures/api/singleton-userdata/main.js:10]: Fixed as of 83eaa3f.

File: spec/fixtures/api/singleton-userdata/main.js (hunk 2 above)
Comment (nmggithub) [reply spec/fixtures/api/singleton-userdata/main.js]: Migrated to https://github.com/electron/electron/pull/49604#discussion_r2751798150 and fixed there.

File: spec/fixtures/api/singleton-userdata/main.js (hunk 5 above)
Comment (nikwen) [reply spec/fixtures/api/singleton-userdata/main.js:6]: It's not strictly necessary as I mentioned above. :)

File: spec/fixtures/api/singleton-userdata/main.js (hunk 3 above)
Comment (nikwen) [reply spec/fixtures/api/singleton-userdata/main.js:17]: Hm, my thought was that we should wait for the app to quit fully before we delete the directory. Otherwise, we'd have a race condition where the app could recreate the directory before it's fully quit.

But it's probably not the most important thing in the world. Not sure if we should waste time on that. I'll approve the PR as is.

**Review by ckerr — APPROVED** [review]

**Comment by nmggithub** [comment]
> Relevant test(s) on Windows are failing after this change. Please correct the test failures

Looks like a timeout. Might have something to do with file handles and such being more strict on Windows. I don't have easy access to test on a Windows box at the moment, so I might have to wait for CI to tell me if my later changes work or not.
