### PR TITLE
Do not emit did-fail-load for canceled requests

### LINKED ISSUE #4396: redirect response emits "did-fail-load" event
for version > 0.36.5 
when load a url return redirect，webContents first emit "did-fail-load"(errorCode=-3) ，then emit "did-finish-load"

for version = 0.36.5
only emit "did-finish-load"

### PR DESCRIPTION
**Pull request by zcbenz**
For all `ERR_ABORTED ` errors happened in `DidFailProvisionalLoad`, the requests are actually canceled, like:

* page redirects
* page starts a download
* have two calls of `loadURL` together

Which do not satisfy the use cases of `did-fail-load` event, and causes surprises to users.

So this PR suppresses `ERR_ABORTED` for `DidFailProvisionalLoad`, closes #4396.

### CODE REVIEW

File: atom/browser/api/atom_api_web_contents.cc [hunk 1]
```diff
@@ -607,7 +607,10 @@ void WebContents::DidFailProvisionalLoad(
     bool was_ignored_by_handler) {
   bool is_main_frame = !render_frame_host->GetParent();
   Emit("did-fail-provisional-load", code, description, url, is_main_frame);
-  Emit("did-fail-load", code, description, url, is_main_frame);
+
+  // Do not emit "did-fail-load" for canceled requests.
+  if (code != net::ERR_ABORTED)
+    Emit("did-fail-load", code, description, url, is_main_frame);
```
Comment (nfantone) [inline atom/browser/api/atom_api_web_contents.cc]: @zcbenz This is still being emitted on `<webview>` tag using `2.0.0-beta.1`.
