### PR TITLE
fix: Don't ignore the referer header in net.request

### LINKED ISSUE #22411: Cant't set referer header when using `net.request`
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  8.0.1
* **Operating System:**
  macOS 10.14.6

### Expected Behavior
Send a request with `referer` header. It's worked with Node's `http/https` module, but failed when I change to `net.request`.

### Actual Behavior
No referer header

### To Reproduce
```js
ses.protocol.interceptStreamProtocol("https", (request, callback) => {
	const resp = sendRequestWithNetRequest({
       url: request.url,
       method: request.method,
	   headers: {
			...request.headers,
			referer: request.referrer  // only referrer has been ignored!!
       }
    })
    callback({
        data: resp.body,
        statusCode: resp.statusCode,
        headers: resp.headers
      });
});
```

### PR DESCRIPTION
**Pull request by LuoJinghua**
#### Description of Change
Don't ignore the referrer header for a request, fixes #22411 #23102.

@zcbenz @MarshallOfSound 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Don't ignore the referrer header in net.request

### CODE REVIEW

**Comment by LuoJinghua** [comment]
Done, please review my changes again.

**Comment by LuoJinghua** [comment]
@nornagon @zcbenz any comment for my latest change?

File: shell/browser/api/electron_api_url_loader.cc [hunk 1]
```diff
@@ -352,6 +352,7 @@ gin::Handle<SimpleURLLoaderWrapper> SimpleURLLoaderWrapper::Create(
   request->force_ignore_site_for_cookies = true;
   opts.Get("method", &request->method);
   opts.Get("url", &request->url);
+  opts.Get("referrer", &request->referrer);
```
Comment (MarshallOfSound) [inline shell/browser/api/electron_api_url_loader.cc:355]: Is there a reason this has to be a new `option` and we can't just read it off the `headers` object if it's defined?  That would make it easier to use I think / be more expected that the header _just works_ ™️

Comment (LuoJinghua) [reply shell/browser/api/electron_api_url_loader.cc:355]: En, this way works too and less burden for user, but the current approach matches the window.fetch() better and even better if we'll introduce the referrer policy later. I don't have opinion which one is better.

Comment (nornagon) [reply shell/browser/api/electron_api_url_loader.cc:355]: I think we should probably go with what @MarshallOfSound said and read this out of the headers option.

This API is designed to be similar to the NodeJS http API (though it doesn't match it in every respect). In the NodeJS API, setting the `Referer` header is done through the `headers` object (or `setHeader`), so it would be more consistent with NodeJS for us to respect that here. Additionally, the two linked bugs in the PR description show two examples of how people _expect_ the API to work, which is similarly to the NodeJS API. I think we can avoid confusion by matching NodeJS here.

Comment (LuoJinghua) [reply shell/browser/api/electron_api_url_loader.cc:355]: Ok, I just pushed the branch forcely and changed the code to read the referrer url from headers instead.

File: typings/internal-ambient.d.ts [hunk 2]
```diff
@@ -58,6 +58,7 @@ declare namespace NodeJS {
     body: Uint8Array | BodyFunc;
     session?: Electron.Session;
     partition?: string;
+    referrer?: string;
```
Comment (jkleinsc) [inline typings/internal-ambient.d.ts:61]: This change is no longer needed.

Comment (LuoJinghua) [reply typings/internal-ambient.d.ts]: But I got build failures without this change.

Comment (nornagon) [reply typings/internal-ambient.d.ts]: @jkleinsc this is in the internal typings

**Comment by 0xdeadbae** [comment]
I have the same issue on Windows. Electron 8.2.5.

Does this fix also solve the issue for Windows user?

**Comment by LuoJinghua** [comment]
> I have the same issue on Windows 1909. Electron 8.2.5.
> 
> Does this fix also solve the issue for Windows user?

Yes, this pull request fixes the issue for all platforms.

File: typings/internal-ambient.d.ts (hunk 2 above)
Comment (LuoJinghua) [reply typings/internal-ambient.d.ts:61]: I have added this line back to fix the build failure.

**Comment by LuoJinghua** [comment]
Thank you for merging，how to backport this to stable branches atomatically？

**Comment by nornagon** [comment]
welp

**Comment by LuoJinghua** [comment]
Should be backport the 7e841ceb to stable branches first? If we don't want backport it, I think I have to backport this pull manually.

**Comment by nornagon** [comment]
I don't think we should backport 7e841ce to older branches, please go ahead and create manual backports.

(there's no need to backport to 7.x since this was only an issue since the 8.x branch)

**Comment by LuoJinghua** [comment]
Ok. I'm going to backport this manually.
