### PR TITLE
fix: make menu.popup options optional

### LINKED ISSUE #12915: menu.popup options object should be optional
I have the following code that worked in versions before 2.0.0
------------------------------------------
const remote = require('electron').remote

const contextMenu = new remote.Menu();
contextMenu.append(new remote.MenuItem({label: "myLabel", click: () => console.log("click")}));

function showContextMenu() {
	contextMenu.popup();
}

<body onContextMenu="showContextMenu()" />

------------------------------------------

This code throws:

remote.js:209 Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Options must be an object
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Options must be an object
    at callFunction (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at callFunction (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:209:30)
    at metaToValue (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:213:28)
    at Object.remoteMemberFunction (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:113:16)
    at showContextMenu (file:///Users/vassilev/Projects/electron-test-app/index.js:49:14)
    at HTMLBodyElement.oncontextmenu (file:///Users/vassilev/Projects/electron-test-app/index.html:8:96)
exception @ /Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:209
metaToValue @ /Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:213
remoteMemberFunction @ /Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:113
showContextMenu @ index.js:49
oncontextmenu @ index.html:8

### PR DESCRIPTION
**Pull request by doms**
## Background

fixes #12915 

The menu.popup `options` object has all optional fields. One would think with that being the case, the `options` object as a whole could be optional.

## Implementation

This PR adds a default param to `Menu.prototype.popup` that will allow the function to work, even when an object is passed in.

```js
Menu.prototype.popup = function (options = {}) {
	// ...
}
```

##### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

File: lib/browser/api/menu.js [hunk 1]
```diff
@@ -47,8 +47,8 @@ Menu.prototype._init = function () {
   this.delegate = delegate
 }
 
-Menu.prototype.popup = function (options) {
-  if (options == null || typeof options !== 'object') {
+Menu.prototype.popup = function (options = {}) {
+  if (typeof options !== 'object') {
```
Comment (MarshallOfSound) [inline lib/browser/api/menu.js]: We still need the `null` check here, `null` won't be defaulted and `typeof null === 'object'`

File: spec/api-menu-spec.js [hunk 2]
```diff
@@ -633,10 +633,16 @@ describe('Menu module', () => {
 
     it('throws an error if options is not an object', () => {
       expect(() => {
-        menu.popup()
+        menu.popup('this is a string, not an object')
```
Comment (ckerr) [inline spec/api-menu-spec.js]: :smiley:

**Comment by ckerr** [comment]
Merging because the CI failures appear to be unrelated flakes. The `menu.popup` tests are passing:

```
ok 405 Menu module Menu.popup throws an error if options is not an object
ok 406 Menu module Menu.popup allows for options to be optional
ok 407 Menu module Menu.popup should emit menu-will-show event
ok 408 Menu module Menu.popup should emit menu-will-close event
ok 409 Menu module Menu.popup returns immediately
ok 410 Menu module Menu.popup works without a given BrowserWindow and options
ok 411 Menu module Menu.popup works with a given BrowserWindow, options and callback
ok 412 Menu module Menu.popup works with a given BrowserWindow, no options, and a callback
```
