### PR TITLE
fix: set `XDG_CURRENT_DESKTOP` env var back to original value before invoking xdg utils

### LINKED ISSUE #45129: Wrong web browser opened when clicking links
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

33.3.0

### What operating system(s) are you using?

Ubuntu

### Operating System Version

24.04

### What arch are you using?

x64

### Last Known Working Electron version

_No response_

### Expected Behavior

Links open in the configured default browser

### Actual Behavior

Links open in Chrome/Chromium instead, regardless of the configured default browser

### Testcase Gist URL

https://gist.github.com/Viicos/d77af018be1b7b27294a74c378731992

### Additional Information

This is a re-open of https://github.com/electron/electron/issues/42611 (by @bittylicious) after @viicos was so kind to add a repro gist (adding a gist was an absolute requirement by the Electron team on the original issue).

The original issue already well pointed out that this issue seems to be new with Ubuntu 24 and wasn't present on 22.

Workarounds presented in in the original issue:

* Uninstalling all chrome/chromium (then e.g. a firefox will be correctly opened)
* Adding the following to `~/.local/share/applications/mimeapps.list`

```
[Default Applications]
x-scheme-handler/http=firefox_firefox.desktop
x-scheme-handler/https=firefox_firefox.desktop
```

There are some additional details available in the original issue.

### PR DESCRIPTION
**Pull request by esimkowitz**
#### Description of Change

This PR corrects the XDG_CURRENT_DESKTOP environment variable, with the goal of ensuring that `electron.shell.openExternal` and `electron.shell.openPath` actually honor the user-defined system defaults on Linux.

Currently, this variable is [overridden by Electron to `Unity`](https://www.electronjs.org/docs/latest/api/environment-variables#original_xdg_current_desktop) (the original value is preserved in the `ORIGINAL_XDG_CURRENT_DESKTOP` variable). This was introduced by https://github.com/electron/electron/pull/23512 to workaround https://github.com/electron/electron/issues/5050 and https://github.com/electron/electron/issues/9046, however it causes `xdg-open` and similar utilities which `electron.shell` relies on to no longer honor the system defaults if a user is running the GNOME desktop environment (I have only tested this on GNOME, but I assume this is valid for all non-Unity environments).

This change preserves the overridden environment variable value for use by Electron and Chromium. When a call needs to be made to the XDG utilities, the original value will be dynamically injected back into the environment variable set that is sent to the spawned XDG process.

cc @clavin @mlaurencin 

fixes #45129

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed `electron.shell.openExternal` and `electron.shell.openPath` to honor user-defined system defaults on Linux

### CODE REVIEW

**Comment by ckerr** [comment]
some breadcrumbs: looks like the `XDG_CURRENT_DESKTOP` change was introduced by #23512  to workaround #5050 and #9046.

@esimkowitz would this PR make `ORIGINAL_XDG_CURRENT_DESKTOP` moot?

**Comment by esimkowitz** [comment]
It may make sense, though, if the updated XDG value is only being used for the app indicators, to limit its application to only system calls that update the app indicators.

**Comment by esimkowitz** [comment]
Looks like one of the builds failed, it seems like a transient error. @ckerr can you restart the failing job?

**Comment by esimkowitz** [comment]
@samuelmaddock can you rerun the build for this? I believe the Windows ARM build failure was transient

**Comment by esimkowitz** [comment]
@samuelmaddock @ckerr checking as this has been dormant for a month, can you rerun the checks for this? I believe they should all pass and the failures were transient.

File: shell/common/platform_util_linux.cc [hunk 1]
```diff
@@ -282,6 +285,13 @@ bool XDGUtil(const std::vector<std::string>& argv,
     base::nix::CreateLaunchOptionsWithXdgActivation(base::BindOnce(
         [](base::RepeatingClosure quit_loop, base::LaunchOptions* options_out,
            base::LaunchOptions options) {
+          // Correct the XDG_CURRENT_DESKTOP environment variable before calling
+          // XDG, in case it was changed for compatibility.
+          if (options.environment.find(kOriginalXdgCurrentDesktopEnvVar) !=
+              options.environment.end()) {
+            options.environment[kXdgCurrentDesktopEnvVar] =
+                options.environment[kOriginalXdgCurrentDesktopEnvVar];
+          }
```
Comment (ckerr) [inline shell/common/platform_util_linux.cc:294]: Concept LGTM.

One impl suggestion -- we can avoid second map lookup by holding onto the return value of the `find()` call. Chromium has a helper convenience function for this, [`base::FindOrNull()`](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/base/containers/map_util.h#24):

```c++
// Correct the XDG_CURRENT_DESKTOP environment variable before calling
// XDG, in case it was changed for compatibility.
if (const auto* orig = base::FindOrNull(
        options.environment, kOriginalXdgCurrentDesktopEnvVar))
  options.environment.emplace(kXdgCurrentDesktopEnvVar, *orig);
```

You'll need to `#include` the header for this at the top of the file:

```diff
 #include "base/cancelable_callback.h"
 #include "base/containers/contains.h"
+#include "base/containers/map_util.h"
 #include "base/environment.h"
 #include "base/files/file_util.h"
 #include "base/files/scoped_file.h"
```
 #include "base/cancelable_callback.h"
 #include "base/containers/contains.h"
+#include "base/containers/map_util.h"
 #include "base/environment.h"
 #include "base/files/file_util.h"
 #include "base/files/scoped_file.h"

**Review by ckerr — COMMENTED** [review]
Thanks for the fix!

File: shell/common/platform_util_linux.cc (hunk 1 above)
Comment (esimkowitz) [reply shell/common/platform_util_linux.cc]: applied your suggestion, thanks for the tip!

**Comment by esimkowitz** [comment]
@ckerr I've rebased my PR to the latest main, can you re-review when you get a chance?

**Comment by esimkowitz** [comment]
Hi @ckerr @codebytere, the backport checks are failing for this, it seems like it's triggering for an unchanged file, can you help me understand what's causing this? I'd like to get this merged soon as it's been open for 2 months and I keep having to rebase it...

**Review by clavin — CHANGES_REQUESTED** [review]
Requesting one small change 😄

With the original issues about Pantheon for reference, I also took the time to go through all the uses of the `XDG_CURRENT_DESKTOP` env var in Chromium. I only found [one bit of code](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/download/download_status_updater_linux.cc;l=65-73;drc=f667feb8a5c6f227b49328ce78a062acc4f81187) that could have different behavior, but [we don't use that Chromium code](https://github.com/electron/electron/blob/32fea719b393c2757c4737386564c910d49b529e/shell/browser/browser_process_impl.cc#L245). So, I believe this change to be reasonably safe.

As a separate follow-up to this PR we should look at removing the `XDG_CURRENT_DESKTOP` workaround entirely imo.

File: shell/common/platform_util_linux.cc [hunk 2]
```diff
@@ -58,6 +59,9 @@ const char kFreedesktopPortalName[] = "org.freedesktop.portal.Desktop";
 const char kFreedesktopPortalPath[] = "/org/freedesktop/portal/desktop";
 const char kFreedesktopPortalOpenURI[] = "org.freedesktop.portal.OpenURI";
 
+const char kXdgCurrentDesktopEnvVar[] = "XDG_CURRENT_DESKTOP";
```
[the remark this answers is not in the document]
Comment (esimkowitz) [reply shell/common/platform_util_linux.cc]: done, thanks for the tip!

**Comment by clavin** [comment]
The failing Lint check is an old issue, not caused by this PR. @esimkowitz Sorry, could you also merge/rebase `main`?

**Comment by esimkowitz** [comment]
rebased from main

**Comment by esimkowitz** [comment]
Looks like the windows arm build is failing when copying dependencies, likely a transient error

**Review by clavin — APPROVED** [review]
Thanks for this contribution! 🙇

**Review by ckerr — APPROVED** [review]

**Review by codebytere — APPROVED** [review]
