### PR TITLE
fix: remove bad usages of for-in and guard against it

### LINKED ISSUE #22615: Adding any Object prototype throws an error
* **Electron Version:**
  v8.1.0
* **Operating System:**
  macOS 10.15.3
* **Last Known Working Electron version:**
  N/A

### Expected Behavior
I expect to be able to add an Object prototype without Electron throwing an error.

### Actual Behavior
Electron throws an error on startup, then otherwise seems to work fine.

### To Reproduce
Electron fiddle: https://gist.github.com/d3238b39f2b33493e0d7dbfc4c3b6afe

### Screenshots
A screenshot by another user already exists here (different code than in the Fiddle, though) on this old Stackoverflow Question: https://stackoverflow.com/questions/54179169/object-prototype-break-electron

### PR DESCRIPTION
**Pull request by MarshallOfSound**
`for (... in ...)` is a bad idea as it will pick up everything on the prototype as well not just keys on that object.  Where appropriate I've replaced it with `for (const key of Object.keys...)` and enabled the eslint rule that guards against it so that future occurrences to not slip through.

Fixes #22615

Notes: fixed issue where mutating the global `Object` prototype could cause internal Electron logic to throw errors

### CODE REVIEW

File: lib/browser/utils.ts [hunk 1]
```diff
@@ -18,7 +18,7 @@ export function createLazyInstance (
 ) {
   let lazyModule: Object
   const module: any = {}
-  for (const method in (holder as any).prototype) {
+  for (const method in (holder as any).prototype) { // eslint-disable-line guard-for-in
```
Comment (nornagon) [inline lib/browser/utils.ts]: hmm is this correct? we should probably guard with `hasOwnProperty` here...

File: lib/renderer/api/remote.js [hunk 2]
```diff
@@ -72,7 +72,7 @@ function wrapArgs (args, visited = new Set()) {
         members: []
       }
       visited.add(value)
-      for (const prop in value) {
+      for (const prop in value) { // eslint-disable-line guard-for-in
```
Comment (nornagon) [inline lib/renderer/api/remote.js]: I think this could be `Object.keys`?

File: lib/browser/utils.ts (hunk 1 above)
Comment (MarshallOfSound) [reply lib/browser/utils.ts]: We want to lazily access inherited prototypes here, so I think `in` is right 🤔

File: lib/renderer/api/remote.js (hunk 2 above)
Comment (MarshallOfSound) [reply lib/renderer/api/remote.js]: Maybe, but I'm scared it will result in a side-effect breaking change.  We can flip it to `Object.keys` in a major version or when we extract `remote`

File: lib/browser/guest-view-manager.js [hunk 3]
```diff
@@ -74,7 +74,7 @@ const createGuest = function (embedder, params) {
 
   // Clear the guest from map when it is destroyed.
   guest.once('destroyed', () => {
-    if (guestInstanceId in guestInstances) {
+    if (Object.keys(guestInstances).includes(guestInstanceId)) {
```
Comment (samuelmaddock) [inline lib/browser/guest-view-manager.js]:
```suggestion
    if (guestInstances.hasOwnProperty(guestInstanceId)) {
```

File: lib/renderer/api/remote.js [hunk 4]
```diff
@@ -219,7 +219,7 @@ function metaToValue (meta) {
     exception: () => { throw metaToError(meta.value) }
   }
 
-  if (meta.type in types) {
+  if (Object.keys(types).includes(meta.type)) {
```
Comment (samuelmaddock) [inline lib/renderer/api/remote.js]:
```suggestion
  if (types.hasOwnProperty(meta.type)) {
```

File: lib/browser/guest-view-manager.js [hunk 5]
```diff
@@ -74,7 +74,7 @@ const createGuest = function (embedder, params) {
 
   // Clear the guest from map when it is destroyed.
   guest.once('destroyed', () => {
-    if (Object.keys(guestInstances).includes(guestInstanceId)) {
+    if (guestInstances.hasOwnProperty(guestInstanceId)) {
```
Comment (nornagon) [inline lib/browser/guest-view-manager.js]: I have sad news, this breaks if `guestInstances` has a property named `"hasOwnProperty"`. It is, I think, _never_ correct to call `x.hasOwnProperty(y)`, always always use `Object.prototype.hasOwnProperty.call(x, y)`.
```suggestion
    if (Object.prototype.hasOwnProperty.call(guestInstances, guestInstanceId)) {
```

File: lib/renderer/api/remote.js [hunk 6]
```diff
@@ -219,7 +219,7 @@ function metaToValue (meta) {
     exception: () => { throw metaToError(meta.value) }
   }
 
-  if (Object.keys(types).includes(meta.type)) {
+  if (types.hasOwnProperty(meta.type)) {
```
Comment (nornagon) [inline lib/renderer/api/remote.js]:
```suggestion
  if (Object.prototype.hasOwnProperty(types, meta.type)) {
```

File: lib/browser/guest-view-manager.js (hunk 5 above)
Comment (MarshallOfSound) [reply lib/browser/guest-view-manager.js]: Ah good catch 👍

**Comment by ckerr** [comment]
I'm :heavy_check_mark: on putting this in new releases, but before we backport this -- is this fixing some known existing problems?

I _think_ some of these objects being looped through are coming from users, e.g. extraHeaders is coming from the 'headers' property of the options object passed to ClientRequest's constructor. It's possible that some oddball setup out in the wild works under `for...in` but not under `for..of Object.keys()`.

Which is why I ask if this is fixing any known bugs. If this is a cleanliness PR, I don't see the upside in backporting.

**Comment by ckerr** [comment]
...or I could've just, you know, read the description and click through to #22615 to see what this fixes.

Perhaps a more limited scope of changes in the backports?

**Comment by MarshallOfSound** [comment]
@ckerr Sending properties of the `headers` object prototype through would also be considered a bug (hence the change instead of the lint-ignore).  These cases were carefully chosen as to whether to update the usage or ignore the lint rule.  Things like `remote` were left alone out of fear of side-effect breakages and will be dealt with later, the `headers` object though it is never intended or expected behavior to send a stringified prototype function as a header so I switched it to not do that any more.
