### PR TITLE
fix: properly stream `uploadData` in `protocol.handle()`

### LINKED ISSUE #39658: [Bug]: protocol.handle unexpected behavior when request.body is a ReadableStream
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

26.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2

### What arch are you using?

x64

### Last Known Working Electron version

_No response_

### Expected Behavior

Iterating on a `ReadableStream` inside `protocol.handle` should not output anything except what is fed into the stream.

### Actual Behavior

Currently, doing this outputs a bunch of `undefined` entries when it shouldn't

```ts
protocol.handle(SCHEME, async (request) => {
  console.log("starting stream");
  for await (const p of request.body) {
    console.log(p);
  }
  console.log("ending stream");
});
```
For some reason, the first few logs are correct outputting `Uint8Array` as expected but it eventually starts outputting `undefined`:

```
starting stream
Uint8Array(5) [ 84, 104, 105, 115, 32 ]
Uint8Array(3) [ 105, 115, 32 ]
Uint8Array(2) [ 97, 32 ]
Uint8Array(5) [ 115, 108, 111, 119, 32 ]
Uint8Array(8) [
  114, 101, 113,
  117, 101, 115,
  116,  46
]
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
ending stream
```

The main problem is that such a `ReadableStream` is not accepted by `net.fetch` or `fetch` and they crash with the following error:

```
node:52760) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at _write (node:internal/streams/writable:315:13)
    at ClientRequest.write (node:internal/streams/writable:337:10)
    at Object.write (node:internal/webstreams/adapters:179:63)
    at ensureIsPromise (node:internal/webstreams/util:192:19)
    at writableStreamDefaultControllerProcessWrite (node:internal/webstreams/writablestream:1115:5)
    at writableStreamDefaultControllerAdvanceQueueIfNeeded (node:internal/webstreams/writablestream:1230:5)
    at writableStreamDefaultControllerWrite (node:internal/webstreams/writablestream:1104:3)
    at writableStreamDefaultWriterWrite (node:internal/webstreams/writablestream:994:3)
    at [kChunk] (node:internal/webstreams/readablestream:1399:28)
(Use `Notesnook --trace-warnings ...` to show where the warning was created)
(node:52760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
```

On the browser side, I am doing a simple fetch like so:

```ts
  function wait(milliseconds: number) {
    return new Promise((resolve) => setTimeout(resolve, milliseconds));
  }

  const stream = new ReadableStream({
    async start(controller) {
      await wait(1000);
      controller.enqueue("This ");
      await wait(1000);
      controller.enqueue("is ");
      await wait(1000);
      controller.enqueue("a ");
      await wait(1000);
      controller.enqueue("slow ");
      await wait(1000);
      controller.enqueue("request.");
      controller.close();
    }
  }).pipeThrough(new TextEncoderStream());

const response = await fetch(uploadUrl, {
    method: "PUT",
    body: stream,
    signal,
    duplex: "half"
  });
```

### Testcase Gist URL

https://gist.github.com/thecodrr/ddabb97be1e93435f9e25dcfab76876e

### Additional Information

_No response_

### LINKED ISSUE #40754: [Bug]: `net.fetch()` fails to forward html form submissions intercepted with `protocol.handle()`
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

`25.9.8`, `26.6.2`, `28.0.0`, `29.0.0-alpha.3`

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise 22H2 22621.2715

### What arch are you using?

x64

### Last Known Working Electron version

None--it doesn't work with any electron version shipping `protocol.handle()`. 

### Expected Behavior

It is [documented](https://www.electronjs.org/docs/latest/api/net#netfetchinput-init) that if one intercepts a protocol (e.g. given `s: Electron.Session` `s.protocol.handle('http', ...)`) one can forward a request to the built-in handler by passing `bypassCustomProtocolHandlers: true` in the `RequestInit` parameter. 

### Actual Behavior

However, if the request originates from a plain html `<form>` submission, the built-in handler fails with
```
Error: net::ERR_FAILED
at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49030)
at SimpleURLLoaderWrapper.emit (node:events:517:28)
(node:9824) electron: Failed to load URL: http://127.0.0.1:3000/ with error: ERR_UNEXPECTED
```
I observed that the form submission request contains an `origin: null` header and that removing said header from the request allows the request to succeed. The request also succeeds if no custom protocol handler is installed.

### Testcase Gist URL

https://gist.github.com/BurningEnlightenment/83ef1268fa71ebe0fafd9dfa4cc2811f

### Additional Information

The Testcase contains an html form which can be submitted to the included koa webserver.

### LINKED ISSUE #40826: [Bug]: protocol.handle `file` issue when dealing with FormData
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

27.1.3

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

_No response_

### Expected Behavior

1. Intercept `file` protocol using `protocol.handle`
2. Sending FormData in the renderer
3. Request intercepted in the function registered in 1
4. The File's blob size in the form should have correct content and size

### Actual Behavior

In step 4, the File's size is 0

### Testcase Gist URL

https://gist.github.com/pengx17/d7b9f3e0f16fd362b44510d3842e90d4

### Additional Information

Please see the console output. The printed File is something like this:
```
FormData { [Symbol(state)]: [ { name: 'file', value: [File] } ] } File {
  size: 0,
  type: 'application/octet-stream',
  name: 'test.txt',
  lastModified: 1703500799473
}
```

### PR DESCRIPTION
**Pull request by BurningEnlightenment**
#### Description of Change

Fixes a few annoying bugs which prevented requests intercepted with `protocol.handle()` from being properly forwarded to `net.fetch()`:
Fixes #39658
Fixes #40754 
Fixes #40826

I considered submitting multiple pull requests, but the fixes would've generated conflicts with each other. In essence I've just streamlined the `pull()` implementation of `convertToRequestBody()` and added a test case for every fixed bug. I also added an explicit error condition in case an unknown/new chunk type gets pushed into the protocol handler. Otherwise it is _very_
unobvious and hard to figure out why your request has been mutilated.

If you like, I am willing to fix the chunk type definitions / remove the `any` casts. However, I'd need some guidance on whether I should introduce local `type`s or add them to the public API.

Additionally I noticed while reviewing the C++ parts that the `cb`, which is passed to the actual handler function `async (preq: ProtocolRequest, cb: any)`, never accesses the `statusText` property. Is there a reason for passing `statusText` in anyways?

cc: @nornagon, @codebytere 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fix various bugs which could prevent forwarding requests intercepted with protocol.handle().

### CODE REVIEW

**Comment by codebytere** [comment]
hey @BurningEnlightenment - thanks for this! We'll try to get to reviewing it soon - `@nornagon` is out until the end of the month so we might want to wait until he can take a look as well.

**Comment by ckerr** [comment]
> Additionally I noticed while reviewing the C++ parts that the cb, which is passed to the actual handler function async (preq: ProtocolRequest, cb: any), never accesses the statusText property. Is there a reason for passing statusText in anyways?

@codebytere and @nornagon know the context better than me but it looks like `statusText` was added in the initial feature commit @ #36674 but AFAICT isn't used or documented. So maybe we should remove it?

File: lib/browser/api/protocol.ts [hunk 1]
```diff
@@ -37,30 +52,42 @@ function convertToRequestBody (uploadData: ProtocolRequest['uploadData']): Reque
...
           current = makeStreamFromPipe(chunk.body).getReader();
-          this.pull!(controller);
+          return this.pull!(controller);
+        } else if (chunk.type === 'blob') {
+          // Note that even though `getBlobData()` is a `Session` API, it doesn't
+          // actually use the `Session` context. Its implementation solely relies
+          // on global variables which allows us to implement this feature without
+          // knowledge of the `Session` associated with the current request by
+          // always pulling `Blob` data out of the default `Session`.
+          controller.enqueue(await session.defaultSession.getBlobData(chunk.blobUUID));
```
Comment (nornagon) [inline lib/browser/api/protocol.ts:82]: I feel like this should be fixed to not be an instance method then 😅 but won't block on it.

**Review by nornagon — APPROVED** [review]
Thanks, these are good changes (and good tests!)

Regarding the unused `statusText` property, good catch, that should probably be plumbed through to the underlying HttpResponseHeaders—currently we use `net::GetHttpReasonPhrase` to derive the status text from the status code instead.

File: lib/browser/api/protocol.ts (hunk 1 above)
Comment (BurningEnlightenment) [reply lib/browser/api/protocol.ts:82]: I agree with you. I just wanted to sidestep a potential API design review process (and it would've bumped this from semver/patch to at least a semver/minor change). 

Btw. if the `getBlobData()` API gets touched it might also be prudent to rename `blobUUID` to just `blobId` as the implementation hasn't used UUIDs for quite some time. Should I submit a follow up PR potentially including some further changes outlined in my previous comments?

**Review by zcbenz — APPROVED** [review]

**Review by zcbenz — APPROVED** [review]

**Comment by codebytere** [comment]
@BurningEnlightenment would you mind rebasing this to fix CI? there was an issue with WOA CI that's since been addressed. Beyond that:

> Should I submit a follow up PR potentially including some further changes outlined in my previous comments?

Yes, I think your best course of action is to open a follow-up! The scope of this PR is good to merge for now and i'd rather address the issues herein first.

**Comment by BurningEnlightenment** [comment]
@codebytere done. LGTM

**Review by jkleinsc — APPROVED** [review]
