### PR TITLE
fix: electron path for postinstall

### LINKED ISSUE #14127: [MAC] Electron rebuild issue on version v3.0.0
* Electron Version: `v3.0.0`
* Operating System (Platform and Version): `Mac`
* Last known working Electron version: `2.0.7`

**Expected Behavior**
Run `npm rebuild` should not fail

**Actual behavior**
```
$ npm rebuild

> electron@3.0.0-beta.5 postinstall /Users/${user}/Desktop/ele/node_modules/electron
> node install.js

/Users/${user}/Desktop/ele/node_modules/electron/install.js:47
  throw err
  ^

Error: EEXIST: file already exists, symlink 'Versions/Current/Electron Framework' -> '/Users/${user}/Desktop/ele/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@3.0.0-beta.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@3.0.0-beta.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/${user}/.npm/_logs/2018-08-16T11_03_51_217Z-debug.log
```
**To Reproduce**
```
$ npm install electron@3.0.0-beta.5
$ npm rebuild
```

### PR DESCRIPTION
**Pull request by keerthi16**
##### Description of Change
Fixes #14127

##### Checklist
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

Notes: Fix issue where npm installing electron would throw errors on reinstalls

### CODE REVIEW

File: npm/install.js [hunk 1]
```diff
@@ -17,7 +17,9 @@ try {
 
 var platformPath = getPlatformPath()
 
-if (installedVersion === version && fs.existsSync(path.join(__dirname, platformPath))) {
+var electronPath = process.env.ELECTRON_OVERRIDE_DIST_PATH || path.join(__dirname, 'dist', platformPath)
```
Comment (MarshallOfSound) [inline npm/install.js]: I'm not sure how this fixes the linked issue, the linked issue is actually caused by `electron-download` not this module afaik

Comment (keerthi16) [reply npm/install.js]: @MarshallOfSound 
The error is not coming from `electron-download` it's from `extract-zip` code below
screen shot 2018-08-18 at 9 41 20 am

This is because of `fs.existsSync(path.join(__dirname, platformPath))` is always false as the electron path from the `npm install` is `dist/Electron.app/Contents/MacOS/Electron`.

If the path check is false `process.exit(0)` won't execute and  `extract-zip` is trying to symlink the path which already exists.

Comment (MarshallOfSound) [reply npm/install.js]: Ah I see, the actual fix here is the inclusion of `dist`, the process env var is just for consistency with the download script
