### PR TITLE
fix: PDF support when site isolation trials disabled

### LINKED ISSUE #50657: Electron exited with signal SIGTRAP with PDF and disable-site-isolation-trials
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

41.1.1

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Tahoe 26.3.1 

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

40.8.5

### Does the issue also appear in Chromium / Google Chrome?

No

### Expected Behavior

The pdf is loaded and doesn't crash.

Electron 40.8.5:
Image

### Actual Behavior

Electron crashes with:

Electron exited with signal SIGTRAP.

Electron 41.1.1:

Image

### Testcase Gist URL

https://gist.github.com/mschile/ea93d959bd824fd738b3bff7047526b2

### Additional Information

Hello from the Cypress.io team 👋🏼, I was upgrading to the latest Electron version and noticed this issue. I assume it has to do with the following [breaking change](https://www.electronjs.org/blog/electron-41-0#breaking-changes) in 41:

> Breaking Changes
Behavior Changed: PDFs no longer create a separate WebContents
Previously, PDF resources created a separate guest [WebContents](https://www.electronjs.org/docs/latest/api/web-contents) for rendering. Now, PDFs are rendered within the same WebContents instead. If you have code to detect PDF resources, use the [frame tree](https://www.electronjs.org/docs/latest/api/web-frame-main) instead of WebContents.
>
> Under the hood, Chromium [enabled](https://chromium-review.googlesource.com/c/chromium/src/+/7239572) a feature that changes PDFs to use out-of-process iframes (OOPIFs) instead of the MimeHandlerViewGuest extension.

### PR DESCRIPTION
**Pull request by nmggithub**
#### Description of Change

Resolves #50657. For full transparency, I wrote most of this with the help of GPT-5.4. I talked through the situation with it and it suggested many parity additions to more align Electron with Chrome (as this bug did not appear to exhibit upstream). Ultimately, it seems like the `DoesSiteRequireDedicatedProcess` override is the one that ultimately fixed the issue, but the rest _do_ seem to be valid parity additions.

#### Checklist

- [x] PR description included
- [x] I have built and tested this PR
- [ ] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed a crash when rendering PDFs when Site Isolation is disabled.

### CODE REVIEW

**Comment by nmggithub** [comment]
Had to commit the `git merge main` with `--no-verify` due to my pre-commit hooks seeming to not want to behave. It was a simple conflict, so I don't think I missed anything important.

**Comment by nmggithub** [comment]
I see failing tests. Will investigate when I have the time (hopefully later this evening).

**Comment by nmggithub** [comment]
Failure looks like it might be an unrelated, maybe flaky, test. Maybe we can retry the tests and see if they work?

File: shell/browser/electron_browser_client.h [hunk 1]
```diff
@@ -106,6 +113,10 @@ class ElectronBrowserClient : public content::ContentBrowserClient,
   bool IsFullscreenAllowedForUnfocusedWebContents(
       content::WebContents* unfocused_web_contents) override;
 
+  // extensions::ChromeContentBrowserClientExtensionsPart:
```
Comment (ckerr) [inline shell/browser/electron_browser_client.h]: `DoesSiteRequireDedicatedProcess()` comes from `content::ContentBrowserClient` and should go in that override section above & this comment about extensions::ChromeContentBrowserClientExtensionsPart should be removed

Comment (nmggithub) [reply shell/browser/electron_browser_client.h]: Good to know! I'll make the change.

Comment (nmggithub) [reply shell/browser/electron_browser_client.h]: Fixed as of 111c988b1e4667b455c13e125b3fcbbe427340c3.

**Comment by nmggithub** [comment]
More CI failures, but those seem to be weird infrastructure issues unrelated to my changes.

**Comment by ckerr** [comment]
@nmggithub which branches should this PR target?

**Comment by ckerr** [comment]
> More CI failures, but those seem to be weird infrastructure issues unrelated to my changes.

Looks like there's been a lot of wg-infr changes today. You might want to rebase this on top of `main`

**Comment by nmggithub** [comment]
> @nmggithub which branches should this PR target?

Given this bug seems to only exhibit on 41(+?), we may not need to backport further than that, unless 40 later rolls Chromium (or if there's benefit to this alignment work outside of squashing this specific bug).

**Comment by nmggithub** [comment]
> > More CI failures, but those seem to be weird infrastructure issues unrelated to my changes.
> 
> Looks like there's been a lot of wg-infr changes today. You might want to rebase this on top of `main`

Just did so. Hopefully it works better now.
