### PR TITLE
fix: don't re-parse URL unnecessarily when handling dialogs

### LINKED ISSUE #50059: Calling `window.open('javascript:alert()') from the renderer causes unhandled exception
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

38 and up

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Tahoe 26.2

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

Not sure

### Does the issue also appear in Chromium / Google Chrome?

I don't know how to test

### Expected Behavior

The page loads and the alert is shown.

### Actual Behavior

The page throws an `Invalid URL` exception

### Testcase Gist URL

https://gist.github.com/devinbinnie/cca61abe95811764736c99f2d6cb6799

### Additional Information

This doesn't seem super exploitable if you don't allow any `about:blank` windows to open, or any non-HTTP URLs through, or any windows at all.

However in that case, you will see an exception thrown which will crash your app if not handled.

In Chrome, the alert seems to be shown as should be expected.

### PR DESCRIPTION
**Pull request by nmggithub**
#### Description of Change

Should resolve #50059. The crash was due to our code assuming that the frame where a dialog is being shown will always have a parseable URL.

~~This PR makes two changes:~~

~~1. it falls back to a generated URL (based on frame identity) when the frame URL is an empty string, and~~
2. it tightens up the origin calculation, falling back to the entire href when, by spec, the `origin` is a non-unique ~~opaque origin (the string `"null"`).~~

~~The only edge case I see here is if the frame URL is a non-empty string _and_ is un-parsable, but that should be rare. I can add a `try`-`catch` if we decide it's worth it.~~

This PR removes an unnecessary `new URL()` call that could lead to crashing.

#### Checklist

- [x] PR description included
- [x] I have built and tested this PR
- [ ] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed crash when handling JavaScript dialogs from windows opened with invalid or empty URLs.

### CODE REVIEW

**Comment by ckerr** [comment]
@nmggithub the bots want `target/*` labels. Which branches should this fix be applied to?

**Comment by nmggithub** [comment]
@ckerr Apologies for the delay in getting back to you. Honestly, this should apply to any and all branches / versions. It appears to be a long-standing issue. Any cases where its not an issue would likely be different enough to where this diff wouldn't be viable.

File: lib/browser/api/web-contents.ts [hunk 1]
```diff
@@ -782,8 +782,9 @@ WebContents.prototype._init = function () {
   const originCounts = new Map<string, number>();
   const openDialogs = new Set<AbortController>();
   this.on('-run-dialog', async (info, callback) => {
-    const originUrl = new URL(info.frame.url);
-    const origin = originUrl.protocol === 'file:' ? originUrl.href : originUrl.origin;
+    const originUrl = new URL(info.frame.url || `unknown:${info.frame.processId}:${info.frame.routingId}`);
+    // By spec, a URL origin may be "null" (an "opaque origin") in some cases, so we use the href as a fallback.
+    const origin = originUrl.origin === 'null' ? originUrl.href : originUrl.origin;
```
Comment (deepak1556) [inline lib/browser/api/web-contents.ts]: This should instead use `info.frame.origin` that would provide proper origin based on the spec https://source.chromium.org/chromium/chromium/src/+/main:url/origin.cc;l=138-146;bpv=0;bpt=1. Not to your change but the original implementation could have relied on Chrome's origin parsing don't remember why it was decided to parse again with Node.js URL.

Comment (nmggithub) [reply lib/browser/api/web-contents.ts]: Yeah, it is a bit strange to re-parse. I'll work on this!

Comment (nmggithub) [reply lib/browser/api/web-contents.ts]: Actually, based on the code from that link you sent, Chromium falls back to `file://` for file-scheme origins, but [the WHATWG URL spec](https://url.spec.whatwg.org/#origin) merely reads as such for these cases:
> Unfortunate as it is, this is left as an exercise to the reader. When in doubt, return a new [opaque origin](https://html.spec.whatwg.org/multipage/browsers.html#concept-origin-opaque).

I'm not saying Chromium would ever change what they return from that, but given the spec could allow for it, I don't think we should check against that string. And Chromium's API, unfortunately, doesn't provide a way to check the scheme of a frame's URL without (re-)parsing. Maybe that's why it was done originally?

EDIT: It seems we do, indeed, have a test around that return value: https://github.com/electron/electron/blob/v40.8.0/spec/api-web-frame-main-spec.ts#L148

Comment (nmggithub) [reply lib/browser/api/web-contents.ts]: Adjusted as of `09d5563`. The totality of `safeDialogs` feels a bit flaky still, though.

File: spec/fixtures/crash-cases/dialog-on-invalid-url/index.js [hunk 2]
```diff
@@ -0,0 +1,9 @@
+const { app, BrowserWindow } = require('electron');
+
+app.whenReady().then(() => {
+  const win = new BrowserWindow({ show: false });
+  win.loadFile('index.html');
+  setTimeout(() => {
+    process.exit(0);
+  }, 1000);
+});
```
Comment (deepak1556) [inline spec/fixtures/crash-cases/dialog-on-invalid-url/index.js]: What about the following to make the test reliable without timeout

```suggestion
process.on('uncaughtException', (err) => {
  console.error(err);
  process.exit(1);
});

process.on('unhandledRejection', (reason) => {
  console.error(reason);
  process.exit(1);
});

app.on('browser-window-created', (ev, window) => {
  window.webContents.once('did-frame-navigate', (ev, url) => {
    process.exit(0);
  });
});

app.whenReady().then(() => {
  const win = new BrowserWindow({ show: false });
  win.loadFile('index.html');
});
```

**Comment by nmggithub** [comment]
> Failing tests need to be addressed.

Just now noticed this. I'll see what I can do, but I think this might also be some of the flakiness of `safeDialogs` that I've been sensing while working on this. This might require some more substantial work, but I could potentially work around it for now.
