### PR TITLE
Fix window.opener being null when nativeWindowOpen is used

### LINKED ISSUE #9581: iframe window.open broken
* Electron version: 1.6.8
* Operating system: MacOS

Apologies if this is a duplicate, I found issues related to `window.open`, however I believe none covered my use case

### Expected behavior

Communication between an iframe and windows it opens should be possible (via `postMessage` API). Therefore, `window.open` should behave correctly when used within an iframe.

#### Opener to opened

Calling `window.open` from within an iframe should return the created `BrowserProxyWindow`, allowing the **opener** to post messages to the **opened**

#### Opened to opener

The opened windows `window.opener` should point back to the iframes window (the window that opened it), allowing the **opened** to post messages to the **opener**

### Actual behavior

Communication between the opener and the opened window is broken in both directions when the 
opener is an iframe.

#### Opener to opened

`window.open` returns `null` when called within an iframe. Therefore,  it is impossible for the opener to communicate to the opened window. 

`window.open` uses Chromiums implementation instead of Electron's proxy from within an iframe.

#### Opened to opener

`window.opener` points to `top` instead of the iframe which opened the window. Therefore, it is impossible to communicate from the opened window to the opener window (the iframe).

### How to reproduce

The easiest way to reproduce is to:

1. open up the example electron app
2. open dev tools and insert an iframe
3. from dev tools console set the context to the iframe, and execute `window.open` (it will return `null`)
4. open the dev tools in the opened window and inspect `window.opener`... it will NOT point to the opener (the iframe) instead it will be pointing at `top`

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #9581 #8100 #9533

Not 100% sure if this is the correct fix but (a) it works and (b) it looks right to me 😆 

/cc @zcbenz @kevinsawicki Can you make sure this isn't doing something silly

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
This appears to cause the renderer process to crash after the second navigation.  This is due to the webContents launched from `window.open` not maintaining the `nativeWindowOpen: true` property resulting in the above check being false 😕 Exploring how to detect this atm

**Comment by MarshallOfSound** [comment]
Two additional things here.

* Child windows now inherit the `nativeWindowOpen` setting of the opener
* We now check directly against the web contents as at `RenderProcessWillLaunch` the web contents isn't actually ready so the webPreferences we save are just the defaults every time

**Comment by MarshallOfSound** [comment]
The newly opened window appears to crash when switching domains in some cases, can't figure out why.  If anyone has any ideas would be appreciated 👍

**Comment by gerges** [comment]
Possibly related to if `window.open` is called directly from a `<webview>` or from an `<iframe>` inside a `<webview>`

**Comment by kevinsawicki** [comment]
> Child windows now inherit the nativeWindowOpen setting of the opener

Yeah, I was looking into this a bit as well via #9928, I think we need to get all the preferences supported that can overridden via `new-window` so that they properly take effect if set via that event, right now I believe any overrides are ignored when it is triggered via `-add-new-contents`.

**Comment by kevinsawicki** [comment]
> The newly opened window appears to crash when switching domains in some cases, can't figure out why.

Do you have the stack trace for this crash?

**Comment by MarshallOfSound** [comment]
> Do you have the stack trace for this crash?

@kevinsawicki As much as I try I can't get Electron to dump a crash stack on me.  The renderer window just closes by itself just after a page navigation is started.  Repro is as easy as `window.open('https://www.google.com')` then just search around and go to a different site, it should crash.

**Comment by MarshallOfSound** [comment]
Just figured out how to stop the random crash on navigation in the opened window

Pinging @electron/maintainers this is a pretty important fix for `window.open` compatibility, would be good to get some 👀 on it and hopefully some ✔️

File: atom/browser/atom_browser_client.cc [hunk 1]
```diff
@@ -100,20 +100,29 @@ bool AtomBrowserClient::ShouldCreateNewSiteInstance(
...
       // (Non-root WebContents opened by window.open() should try to
       //  reuse process to allow synchronous cross-window scripting.)
       return true;
     }
+
+    // In a non-sandboxed renderer with native window open we should
+    // reuse the same site to allow cross-window scripting.  We do
+    // not need to check urls / domains as native window open logic
+    // handles cross site scripting protection.
+    if (WebContentsPreferences::UsesNativeWindowOpen(web_contents)) {
```
Comment (poiru) [inline atom/browser/atom_browser_client.cc]: Isn't this `if` guaranteed to always be `true` since we didn't enter the `if (!WebContentsPreferences::UsesNativeWindowOpen(web_contents))` block above?

Comment (MarshallOfSound) [inline atom/browser/atom_browser_client.cc]: Technically yeah, thought it would be good to be explicit in code though.  I'll change it to still be explicit but not fetch the preferences twice :+1:

File: atom/browser/atom_browser_client.cc [hunk 2]
```diff
@@ -120,9 +120,12 @@ bool AtomBrowserClient::ShouldCreateNewSiteInstance(
     // reuse the same site to allow cross-window scripting.  We do
     // not need to check urls / domains as native window open logic
     // handles cross site scripting protection.
-    if (WebContentsPreferences::UsesNativeWindowOpen(web_contents)) {
-      return false;
-    }
+    //
+    // NOTE: We know that nativeWindowOpen is enabled at this point
+    // because we check if it is NOT enabled above this point.  We
+    // will only reach this return if sanbox is disabled but
```
Comment (malept) [inline atom/browser/atom_browser_client.cc]: sandbox
