### PR TITLE
fix: menu should not be garbage-collected when popuping

### LINKED ISSUE #20737: crash in AtomMenuController.menuDidClose
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.0.0, 6.1.2, 5.0.11
* **Operating System:**
  *  macOS 10.15
* **Last Known Working Electron version:**
  *  unknown

### Expected Behavior

When using the Menu.popup API, Electron should not crash in AtomMenuController.menuDidClose.

### Actual Behavior

When using the Menu.popup API, Electron will sometimes crash in AtomMenuController.menuDidClose.

### To Reproduce

Add this to main.js after creating mainWindow:
```javascript
  mainWindow.webContents.on('context-menu', () => {
    Menu.buildFromTemplate([{role: 'paste'}]).popup(mainWindow);
  });
```
Here is a gist with that change: https://gist.github.com/jeremyspiegel/53afd0127ec3fc3e1cad5bbef0e4c390

Then keep right-clicking to invoke the menu repeatedly until you see a crash.

You can make the crash happen reliably on the first time invoking the menu by forcing garbage collection — add `setTimeout(() => global.gc(), 0);` after running `Menu.popup`, and run Electron with `--js-flags="--expose-gc"` on the command line.

### Additional Information

@MarshallOfSound added a speculative fix in https://github.com/electron/electron/pull/20111 but it doesn't fix the issue.

The problem isn't that `model_` is null, but rather it appears to be that the `MenuMac` API object is destroyed while `MenuMac::PopupOnUI` is running (inside the `[menu popUpMenuPositioningItem:item atLocation:position inView:view]` call).

I added the following to the top of `MenuMac::PopupOnUI` to try to make it so that the object could not be garbage collected while in that function:
```c++
v8::HandleScope handle_scope(isolate());
GetWrapper();
```
That seemed to make the problem go away.

### PR DESCRIPTION
**Pull request by zcbenz**
#### Description of Change
Fixes #20737

This PR makes sure the Menu object is being retained when popuping, so it won't be garbage-collected until the menu is closed. This is done by keeping a strong reference to the menu when `popup` is called, and release it when the close callback is called.

Most changes in this PR are about changing the callback of `popup` from `RepeatingCallback` to `OnceCallback`, so we can ensure the strong reference is released correctly during compile time.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [ ] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fix context menu disappearing when showing.

### CODE REVIEW

File: spec-main/api-menu-spec.ts [hunk 1]
```diff
@@ -822,6 +822,31 @@ describe('Menu module', function () {
...
       })
     })
+
+    it('prevents menu from getting garbage-collected when popuping', (done) => {
+      const menu = Menu.buildFromTemplate([{ role: 'paste' }])
+      menu.popup({ window: w })
+
+      // Keep a weak reference to the menu.
+      const v8Util = process.electronBinding('v8_util')
+      const map = (v8Util as any).createIDWeakMap() as any
```
Comment (miniak) [inline spec-main/api-menu-spec.ts]: can you add `createIDWeakMap()` to `V8UtilBinding` in `typings/internal-ambient.d.ts` instead?

Comment (miniak) [reply spec-main/api-menu-spec.ts]: ref #21171

File: shell/browser/api/atom_api_menu.cc [hunk 2]
```diff
@@ -217,6 +218,16 @@ void Menu::OnMenuWillShow() {
   Emit("menu-will-show");
 }
 
+base::OnceClosure Menu::BindSelfToClosure(base::OnceClosure callback) {
+  // return ((callback, ref) => { callback() }).bind(null, callback, this)
+  v8::Global<v8::Value> ref(isolate(), GetWrapper());
```
Comment (deepak1556) [inline shell/browser/api/atom_api_menu.cc]: Cool hack 👍

File: spec-main/api-menu-spec.ts (hunk 1 above)
Comment (miniak) [reply spec-main/api-menu-spec.ts]: let's merge this one first, I will fix this in the other PR

**Comment by miniak** [comment]
rebased to fix the unrelated flaky tests
