### PR TITLE
fix: use OOPIF for webview tag

### LINKED ISSUE #12291: Move implementation from BrowserPlugin -> OOPIF
Then enable `GuestViewCrossProcessFrames` feature.

/cc @deepak1556

### PR DESCRIPTION
**Pull request by zcbenz**
Close https://github.com/electron/electron/issues/13503.
Close #12291.

notes: Migrate `<webview>` to use out-of-process iframe.

### CODE REVIEW

**Comment by zcbenz** [comment]
This is kind of working for now, but I have identified another problem that, the webview refuses to render once the renderer process gets restarted. This is also why our current implementation does not work after navigations.

By disabling renderer process swapping for webview, I can make the old implementation work like before, but this is not an acceptable solution.

**Comment by zcbenz** [comment]
Currently webview can not load local files, and certain events are not emitting.

**Comment by zcbenz** [comment]
Due to moving to OOPIF, all size related attributes (`autoresize`, `disableguestresize`, etc.) and `WebContents.setSize` will stop working and there is no way to work around that.

**Comment by zcbenz** [comment]
Another bad news, we have to abandon the `guestinstance` attribute after moving to OOPIF webview. With the OOPIF implementation, the guest WebContents is bound to a web frame forever, and it can not be detached and bound to another web frame. This is a design decision made from Chromium's side that we can not work around.

File: atom/browser/web_view_guest_delegate.cc [hunk 1]
```diff
@@ -7,142 +7,61 @@
...
-  attached_ = true;
-  api_web_contents_->Emit("did-attach");
+  int embedder_process_id =
+      embedder_web_contents_->GetMainFrame()->GetProcess()->GetID();
+  auto* embedder_frame =
+      content::RenderFrameHost::FromID(embedder_process_id, embedder_frame_id);
+  // If we're creating a new guest through window.open /
+  // RenderViewImpl::CreateView, the embedder may not be the same as
+  // the original creator/owner, so update embedder_web_contents here.
+  embedder_web_contents_ =
```
Comment (deepak1556) [inline atom/browser/web_view_guest_delegate.cc]: Is this possible in our implementation, don't we attach the guest only after finalizing the embedder in `guest-view-manager` ?

File: lib/browser/guest-view-manager.js [hunk 2]
```diff
@@ -303,9 +282,19 @@ const watchEmbedder = function (embedder) {
   }
   watchedEmbedders.add(embedder)
 
+  // The embedder may be manually destroyed earlier than guest.
+  embedder.once('will-destroy', () => {
+    for (const guestInstanceId in guestInstances) {
+      const guestInstance = guestInstances[guestInstanceId]
+      if (guestInstance.embedder === embedder) {
+        detachGuest(embedder, parseInt(guestInstanceId))
```
Comment (deepak1556) [inline lib/browser/guest-view-manager.js]: Shouldn't the `embedder` be removed from `watchedEmbedders` and also the event listener `-window-visibility-change` for embedder ?

File: lib/browser/guest-view-manager.js [hunk 3]
```diff
@@ -314,34 +303,6 @@ const watchEmbedder = function (embedder) {
     }
   }
   embedder.on('-window-visibility-change', onVisibilityChange)
-
-  const destroyEvents = ['will-destroy', 'crashed', 'did-navigate']
```
Comment (deepak1556) [inline lib/browser/guest-view-manager.js]: Is it okay to not care about the `crashed` event ?

Comment (zcbenz) [reply lib/browser/guest-view-manager.js]: The lifetime  of guest WebContents is now automatically managed by the embedder iframe, when the embedder iframe is gone because crashing or navigation, the guest WebContents will be automatically destroyed.

We still listen to `will-destroy` of embedder, because if we manually destroy embedder, the embedder will be destroyed earlier than the guests, and the embedder will become invalid when calling `detachGuest` later in guest's `destroyed` event.

**Comment by zcbenz** [comment]
> Want to create an issue to track the list of technical debts after this migration, just create appropriate deprecation notices ?

Have created #14120.

**Comment by deepak1556** [comment]
**electron-ia32-branch** failed with

```
not ok 886 chromium feature window.opener access from <webview> works when origin matches
  Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\projects\electron-39ng6\spec\chromium-spec.js)
```

can we rerun to make sure its not a flake ?

File: lib/browser/guest-view-manager.js (hunk 3 above)
Comment (deepak1556) [reply lib/browser/guest-view-manager.js]: Awesome, thanks for the clarification!

**Comment by zcbenz** [comment]
> not ok 886 chromium feature window.opener access from <webview> works when origin matches
>   Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\projects\electron-39ng6\spec\chromium-spec.js)

This is a flaky test, and after trying to fix it I triggered more flaky tests. They are essentially caused by some race conditions in the webview implementation, I'll try to fix them.

**Comment by zcbenz** [comment]
> not ok 886 chromium feature window.opener access from works when origin matches
> Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\projects\electron-39ng6\spec\chromium-spec.js)

After more investigation with it, I think it is caused by some issues with `window.open` implementation, not with the webview implementation. After rerunning the CI job the flaky failure is gone.

This PR should be ready to go.

**Comment by codebytere** [comment]
@zcbenz do you think you could potentially manually backport this by midday tomorrow?

**Comment by javan** [comment]
> Migrate `<webview>` to use out-of-process iframe.

Can you explain what an out-of-process iframe is or point me to any related docs? Curious if it's possibly related to / the cause of https://github.com/electron/electron/issues/12939.

**Comment by KochiyaOcean** [comment]
Seems this issue https://github.com/electron/electron/issues/13712 still occurs in latest 3.0.0 nightly

**Comment by zcbenz** [comment]
> Can you explain what an out-of-process iframe is or point me to any related docs? Curious if it's possibly related to / the cause of #12939.

The only documentation can be found at:
https://www.chromium.org/developers/design-documents/oop-iframes

I'll write on how OOPIF webview works in future.
