### PR TITLE
fix: use no-op header client for Fetch-intercepted requests

### LINKED ISSUE #50678: Intermittent ERR_FAILED when using CDP.Fetch.requestPaused
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

41.1.1

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Tahoe 26.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

40.8.5

### Does the issue also appear in Chromium / Google Chrome?

No

### Expected Behavior

Able to pause requests with `CDP.Fetch.requestPaused` and the url is loaded without any errors.

Image

### Actual Behavior

When loading a url using `CDP.Fetch.requestPaused`, I receive the following error intermittently:

```
error loading page Error: ERR_FAILED (-2) loading 'http://localhost:1414/'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:89325)
    at WebContents.finishListener (node:electron/js2c/browser_init:2:89487)
    at WebContents.emit (node:events:508:28) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'http://localhost:1414/'
}
```

Image

If I add any [WebRequest](https://www.electronjs.org/docs/latest/api/web-request) listeners then the url always loads correctly.

### Testcase Gist URL

https://gist.github.com/46739f4be69d7e07245ba4517334581c

### Additional Information

Hello again from the Cypress.io team 👋🏼, I was upgrading to the latest Electron version and noticed this issue. We are currently working around this issue by calling `mainWindow.webContents.session.webRequest.onErrorOccurred(() => {})`.

### PR DESCRIPTION
**Pull request by nmggithub**
#### Description of Change

Resolves #50678.

cc: @deepak1556 

~~This is a naïve fix to the original issue. I did some digging to figure out what was causing it (and Deepak seems to have found the same thing), but ultimately this just keys off of state that happens when the CDP Fetch API (that was previously erroring) is being used and pushes the request handling down the same path as those with `webRequest` handlers.~~

~~There may be more proper ways to do this, and~~ I welcome Deepak's fix ~~over mine~~ if it is desired.

EDIT: This PR uses Deepak's suggested approach (see: https://github.com/electron/electron/pull/50744#pullrequestreview-4064502355).

#### Checklist

- [x] PR description included
- [x] I have built and tested this PR
- [ ] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed a bug where errors would occur when using the Chrome DevTools Fetch API.

### CODE REVIEW

**Review by deepak1556 — CHANGES_REQUESTED** [review]
Please make the noop header client change as discussed in the issue, this adds an additional InProgressRequest tracking for devtools interception which it shouldn't need.

**Comment by nmggithub** [comment]
@deepak1556 I just changed the approach! Let me know what you think. For context, I did have GPT-5.4 write this particular patch for me. I'm totally willing to also get you in as co-author on the merged commit (since the approach was your idea). Not entirely sure how to do that, but I do want to make sure you get credit.

File: shell/browser/net/proxying_url_loader_factory.cc [hunk 1]
```diff
@@ -869,11 +894,21 @@ void ProxyingURLLoaderFactory::OnLoaderCreated(
...
+    // Chromium can require the header client pipe to be bound even when
+    // Electron is using the pass-through path. Dropping the receiver here
+    // disconnects the URLLoader and causes the request to fail with ERR_FAILED.
+    mojo::MakeSelfOwnedReceiver(std::make_unique<NoOpHeaderClient>(),
+                                std::move(receiver));
     return;
+  }
 
   auto request_it = requests_.find(it->second);
-  DCHECK(request_it != requests_.end());
```
Comment (deepak1556) [inline shell/browser/net/proxying_url_loader_factory.cc:876]: what is the reason to change this DCHECK ?

**Comment by deepak1556** [comment]
The change looks good with a question.

>  Not entirely sure how to do that, but I do want to make sure you get credit.

Thank you, its fine the current way :)

File: shell/browser/net/proxying_url_loader_factory.cc (hunk 1 above)
Comment (nmggithub) [reply shell/browser/net/proxying_url_loader_factory.cc:876]: I talked to GPT-5.4 and determined that it wanted, as much as possible, to avoid a case where the receiver ends up unbound, as that likely leads to an error. Might have been a bit overzealous. I'm willing to revert this part if you think we should.

Comment (deepak1556) [reply shell/browser/net/proxying_url_loader_factory.cc:876]: When a loader is created a valid entry in `network_request_id_to_web_request_id_` should have an associated InProgressRequest, otherwise it breaks the request lifecycle. We can make this into a `CHECK` to guarantee the expectation, the current condition is not ideal.

Comment (nmggithub) [reply shell/browser/net/proxying_url_loader_factory.cc:876]: Will revert then. Thanks for the note!

Comment (nmggithub) [reply shell/browser/net/proxying_url_loader_factory.cc:876]: Should be fixed by 921a134.

**Review by deepak1556 — APPROVED** [review]
Thanks!

**Review by nikwen — DISMISSED** [review]
Could you please rebase this on `main` and run `npm run format`? (Feel free to then dismiss this review.)

**Review by ckerr — CHANGES_REQUESTED** [review]
@nmggithub can you rebase this on `main` ?

**Review by ckerr — APPROVED** [review]

**Review by jkleinsc — APPROVED** [review]
