### PR TITLE
fix: maintain a ref count for objects sent over remote

### LINKED ISSUE #17039: remote API is flaking on 5.0.x
The current `5-0-x` branch and `master` are experiencing random `remote` API failures again.  We should look into this and fix before 5.0 stable.

Example: https://circleci.com/gh/electron/electron/138325

### PR DESCRIPTION
**Pull request by MarshallOfSound**
#### Remote Fix
See https://github.com/electron/electron/pull/17464#issuecomment-483506489 for explanation

Fixes #17039

Refs: https://chromium-review.googlesource.com/c/chromium/src/+/1514516

This also includes the test change as that is the "repro" for this issue 😕 

#### Testing Changes
Previously when this assertion failed all tests that ran after the failed assertion also failed.  This ensure that the assertion fails for the test that actually caused the issue but cleans up the left-over windows so that future tests do not fail.

#### Release Notes

Notes: Fixed race condition where the `remote` module would sometimes fail to fetch properties of a remote object

### CODE REVIEW

**Comment by zcbenz** [comment]
This would trigger another regression. Consider following situation:

1. `remote.getCurrentWindow()` to create remote object A for current window
2. Garbage collection
3. `OnObjectGC` called for remote object A, `RunDestructor` schedule for next tick
4. `remote.getCurrentWindow()` to create remote object B for current window
5. `RunDestructor` gets called, and the `objectRegistry` in the main process clears the entry for current window
6. Any operations on remote object B now ends up with `missing remote object` error

See https://github.com/electron/electron/issues/4733#issuecomment-198197090 for more history on the original regression, and #4869 for the fix.

I think this PR fixes the CI failure because it deferred the `RunDestructor` so the actual problem is now hidden.

**Comment by MarshallOfSound** [comment]
@zcbenz I have updated the PR with a (IMO) better approach to ensuring that we only ever remove an object from the cache if all sent references have been dereffed.

**Comment by MarshallOfSound** [comment]
IMG_20190415_190716

This is the exact race condition we were hitting.  In a rare case when a remote object was fetched a second time and a GC occured at the right time (between the main process sending the remote object metadata and the renderer process pulling the proxy out of a weak map) the renderer would tell the main process that the object had been GC'ed but would then on the next tick receive a remote message telling it to use the object it just free'ed.

I've included the commit message below for more info:

> Previously there was a race condition where a GC could occur in the
renderer process between the main process sending a meta.id and the
renderer pulling the proxy out its weakmap to stop it being GC'ed.

> This fixes that race condition by maintaining a "sent" ref count in the
object registry and a "received" ref count in the object cache on the
renderer side.  The deref request now sends the number of refs the
renderer thinks it owns, if the number does not match the value in the
object registry it is assumed that there is an IPC message containing a
new reference in flight and this race condition was hit.

> The browser side ref count is then reduced and we wait for the new deref
message.  This guaruntees that an object will only be removed from the
registry if every reference we sent has been guarunteed to be unreffed.

File: atom/common/api/object_life_monitor.cc [hunk 1]
```diff
@@ -7,6 +7,7 @@
 
 #include "base/bind.h"
 #include "base/message_loop/message_loop.h"
+#include "third_party/blink/public/platform/task_type.h"
```
Comment (zcbenz) [inline atom/common/api/object_life_monitor.cc]: Changes to this file can be removed .

File: atom/common/api/remote_object_freer.cc [hunk 2]
```diff
@@ -62,6 +70,10 @@ void RemoteObjectFreer::RunDestructor() {
   base::ListValue args;
   args.AppendString(context_id_);
   args.AppendInteger(object_id_);
+  args.AppendInteger(ref_mapper_[context_id_][object_id_]);
+  // Reset our local ref count in case we are in a GC race condition and will
+  // get more references in an inbound IPC message
+  ref_mapper_[context_id_][object_id_] = 0;
```
Comment (zcbenz) [inline atom/common/api/remote_object_freer.cc]: The key should be erased otherwise memory would not be freed.

```c++
ref_mapper_[context_id_].erase(object_id_);
if (ref_mapper_[context_id_].empty())
  ref_mapper_.erase(context_id_);
```

File: atom/common/api/remote_object_freer.h [hunk 3]
```diff
@@ -27,6 +29,8 @@ class RemoteObjectFreer : public ObjectLifeMonitor {
 
   void RunDestructor() override;
 
+  static std::map<std::string, std::map<int, int>> ref_mapper_;
```
Comment (zcbenz) [inline atom/common/api/remote_object_freer.h]: Can you add a comment describing what the key and value are?

File: lib/browser/objects-registry.js [hunk 4]
```diff
@@ -49,14 +51,28 @@ class ObjectsRegistry {
   // Dereference an object according to its ID.
   // Note that an object may be double-freed (cleared when page is reloaded, and
   // then garbage collected in old page).
-  remove (webContents, contextId, id) {
+  // rendererSideRefCount is the ref count that the renderer process reported
+  // at time of GC if this is different to the number of references we sent to
+  // the given owner then a GC occurred between a ref being sent and the value
+  // being pulled out of the weak map.
+  // In this case we decrement out ref count and do not delete the stored
+  // object
```
Comment (zcbenz) [inline lib/browser/objects-registry.js]: Can you add the link of this PR in the comment as it describes why we introduced `rendererSideRefCount`?

```md
For more details on why we introduced rendererSideRefCount, please see https://...
```

Otherwise some other developer may want to optimize this code out a few years later.

**Comment by MarshallOfSound** [comment]
Note to self: test failures are because I didn't update https://github.com/electron/electron/blob/master/lib/browser/objects-registry.js#L69

Secondary note to self: typescript would have caught this 😆

**Comment by zcbenz** [comment]
This test is failing:

```
ipc main module remote objects registry does not dereference until the render view is deleted (regression) - does not dereference until the render view is deleted (regression)
```

I guess it is because the code of `clear` method has not been updated for the new type of `this.owners`:

```js
for (const id of owner) this.dereference(id)
```
