### PR TITLE
fix: logical bug in install.js env var handling

### LINKED ISSUE #48594: Fix logical bug in checksums environment variable handling in npm/install.js
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

36.0.0 and above 

### What operating system(s) are you using?

Ubuntu

### Operating System Version

Ubuntu 25.04

### What arch are you using?

x86_64 

### Last Known Working Electron version

_No response_

### Does the issue also appear in Chromium / Google Chrome?

I don't know how to test

### Expected Behavior

This makes the intent clearer:  
   if either environment variable is truthy, skip local checksums

``` checksums: (process.env.electron_use_remote_checksums || process.env.npm_config_electron_use_remote_checksums) ? undefined : require('./checksums.json'), ```

### Actual Behavior

There is a logical bug in   _install.js_   line 47  where the environment variable check for _electron_use_remotechecksums_     doesn't work correctly due to operator precedence 

The ternary operator (?:) has lower precedence than the nullish coalescing operator (??), so the code is evaluated as:

``` checksums: (process.env.electron_use_remote_checksums ?? process.env.npm_config_electron_use_remote_checksums) ? undefined : require('./checksums.json') ```

- If either variable is set to a truthy value, it uses remote checksums 
- But the logic is confusing and not what was likely intended

### Testcase Gist URL

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ckerr**
#### Description of Change

If either `NPM_CONFIG_ELECTRON_USE_REMOTE_CHECKSUMS` or `ELECTRON_USE_REMOTE_CHECKSUMS` are set as environment variables, then force Electron to verify with remote checksums instead of embedded ones.

Fixes #48594.

Thanks to @KinshukSS2 for reporting this and suggesting a solution.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed an error when checking environmental variables when using remote checksums when installing Electron via npm.

### CODE REVIEW

File: npm/install.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ downloadArtifact({
   artifactName: 'electron',
   force: process.env.force_no_cache === 'true',
   cacheRoot: process.env.electron_config_cache,
-  checksums: process.env.electron_use_remote_checksums ?? process.env.npm_config_electron_use_remote_checksums ? undefined : require('./checksums.json'),
+  checksums: (process.env.electron_use_remote_checksums || process.env.npm_config_electron_use_remote_checksums) ? undefined : require('./checksums.json'),
```
Comment (nikwen) [inline npm/install.js:47]: Just noting that this is a behavior change for rare cases where `electron_use_remote_checksums` is false and `npm_config_electron_use_remote_checksums` is true (if that is even possible). Should be fine though because that's unlikely.

**Review by codebytere — APPROVED** [review]

**Review by dsanders11 — APPROVED** [review]
