### PR TITLE
Smooth corners for vibrancy view

### LINKED ISSUE #8305: Border renders wrong when using Vibrancy
I'm using the settings below to create my MainWindow (notice the Vibrancy). 
In my index.html I have a header component which has a white background color. As you can see in the image below it renders wrong. Is there anything I can do to fix this?

**Settings:**
```
    mainWindow = new BrowserWindow({
        center: true,
        show: false,
        width: 360,
        height: 440,
        minWidth: 300,
        minHeight: 300,
        vibrancy: 'ultra-dark',
        frame: false,
        transparent: true
    });
```

**Image:**
image

### PR DESCRIPTION
**Pull request by gerhardberger**
This PR adds a workaround to smooth the corners of the vibrancy view.

Fixes #8305

### CODE REVIEW

File: atom/browser/native_window_mac.mm [hunk 1]
```diff
@@ -1283,6 +1291,28 @@ static bool FromV8(v8::Isolate* isolate, v8::Handle<v8::Value> val,
     [effect_view setAutoresizingMask:NSViewWidthSizable | NSViewHeightSizable];
     [effect_view setBlendingMode:NSVisualEffectBlendingModeBehindWindow];
     [effect_view setState:NSVisualEffectStateActive];
+
+    // The default corner radius of a macOS window.
+    CGFloat radius = 5.0f;
+    CGFloat dimension = 2 * radius + 1;
+    NSSize size = NSMakeSize(dimension, dimension);
+    NSImage* maskImage = [[NSImage imageWithSize:size
+                                        flipped:NO
```
Comment (kevinsawicki) [inline atom/browser/native_window_mac.mm]: I think this needs to move over a space to align the `:`

**Comment by kevinsawicki** [comment]
Awesome, thanks for fixing this 👍

**Comment by kevinsawicki** [comment]
After some more testing, it looks like this caused the border/shadow to not display correctly on windows with no vibrancy set.

Reverted in https://github.com/electron/electron/pull/8376

**Comment by natew** [comment]
Did this ever get un-reverted? I can't seem to get vibrancy + border-radius working in electron.

**Comment by controversial** [comment]
Will there be a fix for this soon?
