### PR TITLE
fix: do not allow the window to grab focus when tabbing / shift+tabbing

### LINKED ISSUE #12919: Browser windows have an extra tab focus which can not be disabled and is not visible
* Electron Version: 2.0.0
* Operating System (Platform and Version): Windows 10
* Last known working Electron version:  N/A

**Expected Behavior**
If the last focusable HTML element is focused and I press 'tab', then the next thing that is focused should either be the first focusable HTML element, or if not, then whatever is focused should have a visible focus.

**Actual behavior**
Something is being focused (I think it is the entire HTML document?) and there is no visual indication as to what it is. It is fine that this other thing is being focused, what is not fine is that I/a user does not know where the keyboard focus has gone.

**To Reproduce**
- Checkout the [electron-quick-start](https://github.com/electron/electron-quick-start)- Put an `<input type="text"/>` before the `renderer.js` script
- Launch quick start
- Set focus in the input
- Press 'tab'

### PR DESCRIPTION
**Pull request by ppontes**
#### Description of Change
Keep the focus restrained to the set of focusable elements when the user tabs or SHIFT + tabs through the focusable elements in a page. Do not allow it to move to the browser window as it is unexpected in a desktop app and no visual indication is given that the browser window is focused.

Fixes #12919.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [X] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

#### Release Notes

Notes: Fixed a problem where the focus would move to the browser window after the user (SHIFT +) tabbed through all the elements in the page (#12919).

### CODE REVIEW

File: spec/chromium-spec.js [hunk 1]
```diff
@@ -1411,6 +1411,83 @@ describe('chromium feature', () => {
...
+      const [, focusedElementId, focusedElementTag] = await focusedElementIdResult
+      return [focusedElementId, focusedElementTag]
+    }
+
+    const getFinalFocusedElementId = async () => {
+      const [focusedElementId, focusedElementTag] = await getCurrentFocusedElement()
+      if (focusedElementTag === 'BODY') {
+        // Wait for Electron to react and move the focus back
+        // to the first / last element if necessary.
+        const waitTimeMs = 10
```
Comment (ppontes) [inline spec/chromium-spec.js]: Hate this magic constant, but the test has to wait a bit until Electron reacts to Chromium's notification that the focus has gone through all the focusable elements and sets it back to the first or last element. Any idea to implement this in a better way?

File: spec/chromium-spec.js [hunk 2]
```diff
@@ -1411,6 +1411,83 @@ describe('chromium feature', () => {
       await new Promise((resolve) => { utter.onend = resolve })
     })
   })
+
+  describe('focus handling', () => {
```
Comment (ppontes) [inline spec/chromium-spec.js]: Is chromium-spec.js the best place for this test?

**Comment by bpasero** [comment]
Very cool, looking forward to have this in VSCode 👍

File: spec/chromium-spec.js (hunk 2 above)
Comment (deepak1556) [reply spec/chromium-spec.js]: Yup it looks good since we aren't testing any webContent specific apis.

File: spec/chromium-spec.js (hunk 1 above)
Comment (deepak1556) [reply spec/chromium-spec.js]: Rather than requesting the currently focused element, the loaded page can signal when an element receives focus and the test can validate with it.

File: spec/fixtures/pages/tab-focus-loop-elements.html [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+    })
+  </script>
+  <body>
+    <div>
+      <button id="element-1">Button 1</button>
+      <button id="element-2">Button 2</button>
+      <button id="element-3">Button 3</button>
+    </div>
+  </body>
+</html>
```
Comment (deepak1556) [inline spec/fixtures/pages/tab-focus-loop-elements.html]: nit: new line missing at EOF

File: spec/chromium-spec.js (hunk 1 above)
Comment (ppontes) [reply spec/chromium-spec.js]: Excellent idea, changed accordingly.

File: spec/fixtures/pages/tab-focus-loop-elements.html (hunk 3 above)
Comment (ppontes) [reply spec/fixtures/pages/tab-focus-loop-elements.html]: Fixed, thanks.

**Comment by ppontes** [comment]
@deepak1556 Thanks for the review and great suggestion to include a webview in the tests, I had tested it manually but we should ensure it doesn't regress. It has been included in the tests..
