### PR TITLE
fix: add support for --ozone-platform-hint flag on Linux

### LINKED ISSUE #33810: [Bug]: --ozone-platform-hint command line flag ignored
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.3

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Last Known Working Electron version

_No response_

### Expected Behavior

Setting the `--ozone-platform-hint` flag to `auto` or `wayland` should make electron use wayland (assuming `--enable-features=UseOzonePlatform` is also set)

### Actual Behavior

The flag is ignored.

### Testcase Gist URL

_No response_

### Additional Information

Using `--ozone-platform=wayland` does work, but then it fails when not running wayland.

### PR DESCRIPTION
**Pull request by vially**
#### Description of Change

Add support for the `--ozone-platform-hint` flag in order to make it easier for users to switch between the X11 and Wayland platforms (e.g.: by using `--ozone-platform-hint=auto`).

##### Implementation details

~This was implemented by reusing the [same logic from upstream](https://chromium-review.googlesource.com/c/chromium/src/+/3188974), but it required implementing [`chrome::SessionEnding()`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/lifetime/application_lifetime.h;l=84-85;drc=627a149e7e191267a05b354a2bb697394bf4e1ae) which is a bit hacky. This was necessary due to [this call](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/chrome_browser_main_extra_parts_ozone.cc;l=23;drc=627a149e7e191267a05b354a2bb697394bf4e1ae) from ` ChromeBrowserMainExtraPartsOzone::PostCreateMainMessageLoop()`.~

~Another option would have been to either [patch](https://www.electronjs.org/docs/latest/development/patches) that method or copy the logic from [`ChromeBrowserMainExtraPartsOzone`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/chrome_browser_main_extra_parts_ozone.cc;drc=627a149e7e191267a05b354a2bb697394bf4e1ae) and [`ChromeBrowserMainExtraPartsLinux`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/chrome_browser_main_extra_parts_linux.cc;drc=31a79911d78501ef1bcf4673ce59ec5ea9ba1322) inside Electron. If Electron maintainers think that's a more reasonable approach I'll update this pull-request accordingly.~

EDIT: This description is no longer relevant because the implementation has been reworked with feedback from Electron maintainers.

Fixes #33810

#### Checklist

- [x] PR description included and stakeholders cc'd (@deepak1556 @ckerr @MarshallOfSound)
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Added support for `--ozone-platform-hint` flag on Linux

### CODE REVIEW

**Review by deepak1556 — CHANGES_REQUESTED** [review]
Can you copy the logic to support this flag into `ElectronBrowserMainParts` https://github.com/electron/electron/blob/f1746c81c66d6857e8b857a6eaedee8cc123c942/shell/browser/electron_browser_main_parts.cc#L214

Electron has its own shutdown logic and bringing in `ChromeBrowserMainExtraParts` overrides this, also it is not necessary to support this flag.

**Comment by vially** [comment]
@deepak1556 I've copied the logic from [`ChromeBrowserMainExtraPartsLinux`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/chrome_browser_main_extra_parts_linux.cc;drc=31a79911d78501ef1bcf4673ce59ec5ea9ba1322) into `ElectronBrowserMainParts`, as you've suggested (unless I've misunderstood).

However, it is a bit verbose so it may be worth moving it someplace else in order to keep `ElectronBrowserMainParts` a bit cleaner. Let me know what you think and whether you have any suggestions for refactoring it to make it slightly cleaner.

File: shell/browser/electron_browser_main_parts.cc [hunk 1]
```diff
@@ -217,6 +319,21 @@ int ElectronBrowserMainParts::PreEarlyInitialization() {
...
+      command_line->AppendSwitchASCII(
+          switches::kOzonePlatform, MaybeFixPlatformName(ozone_platform_hint));
+    }
+  }
+
+  auto env = base::Environment::Create();
+  std::string desktop_startup_id;
+  if (env->GetVar("DESKTOP_STARTUP_ID", &desktop_startup_id))
+    command_line->AppendSwitchASCII("desktop-startup-id", desktop_startup_id);
+
```
Comment (deepak1556) [inline shell/browser/electron_browser_main_parts.cc:336]: I like the idea of keeping this file minimal. We can have a new file `electron_browser_main_parts_linux.cc` and move this logic to a new helper method `void DetectOzonePlatform()` and also move the other static helper functions `MaybeFixPlatformName`, `HasWaylandDisplay` into that file.

Comment (vially) [reply shell/browser/electron_browser_main_parts.cc]: These suggested changes have now been implemented.

**Review by deepak1556 — APPROVED** [review]
Thanks!
