### PR TITLE
Fix GTK+ 3 deprecations

### LINKED ISSUE #10780: Fix GTK deprecation warnings
During upgrade to the Chromium 61 we have switched from GTK2 to GTK3
and now we have a few warnings about stuff being deprecated in GTK3.
Check any Linux build to get a list of them.

/cc @zcbenz

### PR DESCRIPTION
**Pull request by ckerr**
Fixes #10780

### CODE REVIEW

File: atom/browser/ui/views/menu_bar.cc [hunk 1]
```diff
@@ -24,26 +24,62 @@ namespace atom {
...
+  *disabled   = GetStyleContextFgColor(sc, GTK_STATE_FLAG_INSENSITIVE);
+  *highlight  = GetStyleContextFgColor(sc, GTK_STATE_FLAG_SELECTED);
+  *hover      = GetStyleContextFgColor(sc, GTK_STATE_FLAG_PRELIGHT);
+  *background = GetStyleContextBgColor(sc, GTK_STATE_FLAG_NORMAL);
+  g_object_unref(G_OBJECT(menu_bar));
+}
 
+#else  // GTK_CHECK_VERSION(3,0,0)
+
+// GTK+ 2 impl
```
Comment (alexeykuzmin) [inline atom/browser/ui/views/menu_bar.cc]: Do we still need GTK 2 implementation?

File: atom/browser/ui/views/menu_bar.cc [hunk 2]
```diff
@@ -24,26 +24,62 @@ namespace atom {
...
+  GtkWidget* menu_bar = gtk_menu_bar_new();
   GtkStyle* style = gtk_rc_get_style(menu_bar);
-  *enabled = libgtkui::GdkColorToSkColor(style->fg[GTK_STATE_NORMAL]);
-  *disabled = libgtkui::GdkColorToSkColor(style->fg[GTK_STATE_INSENSITIVE]);
-  *highlight = libgtkui::GdkColorToSkColor(style->fg[GTK_STATE_SELECTED]);
-  *hover = libgtkui::GdkColorToSkColor(style->fg[GTK_STATE_PRELIGHT]);
+  *enabled    = libgtkui::GdkColorToSkColor(style->fg[GTK_STATE_NORMAL]);
+  *disabled   = libgtkui::GdkColorToSkColor(style->fg[GTK_STATE_INSENSITIVE]);
+  *highlight  = libgtkui::GdkColorToSkColor(style->fg[GTK_STATE_SELECTED]);
+  *hover      = libgtkui::GdkColorToSkColor(style->fg[GTK_STATE_PRELIGHT]);
```
Comment (alexeykuzmin) [inline atom/browser/ui/views/menu_bar.cc]: Is linter ok with this?

File: atom/browser/ui/views/menu_bar.cc (hunk 1 above)
Comment (ckerr) [reply atom/browser/ui/views/menu_bar.cc]: Good question! I'll be back in the office on Thursday and will revisit this patch then and find out about GTK 2

File: atom/browser/ui/views/menu_bar.cc (hunk 2 above)
Comment (ckerr) [reply atom/browser/ui/views/menu_bar.cc]: Seems so; all 8 checks passed :smile:

Comment (alexeykuzmin) [reply atom/browser/ui/views/menu_bar.cc]: That's weird =/ Ok.

Comment (poiru) [reply atom/browser/ui/views/menu_bar.cc]: Do you use clang-format? `git-clang-format efb44050dbaab32128777cf70c0095d43f13083e` changes a few things in this branch. It would be nice if everyone used clang-format, I'm not sure what the policy is right now.

File: atom/browser/ui/views/menu_bar.cc (hunk 1 above)
Comment (ckerr) [reply atom/browser/ui/views/menu_bar.cc]: As one would expect, `electron` is linked against `gtk3`:

```sh
$ ldd ./electron | grep gtk
libgtk3ui.so => /home/charles/src/electron/electron/out/D/./libgtk3ui.so (0x00007ff3cd4d5000)
libgtk-3.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007ff3c9986000)
```

and I don't see any conditionals in `electron/electron` or `electron/libchromiumcontent` that would let a build choose between 2 and 3... so I suspect it's safe & desirable to remove the references to 2 and I'll do that in a followup push today
