### PR TITLE
fix: menu bar visibility when exiting full screen

### LINKED ISSUE #35807: [Bug]: Menu Bar Visibility
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

20.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 36

### What arch are you using?

x64

### Last Known Working Electron version

19.0.0

### Expected Behavior

If I specify:

```js
win.setMenuBarVisibility(false);
```
then menu bar will be hidden which is great. But if you spam F11 key, menu bar will become visible again.

### Actual Behavior

If I specify:

```js
win.setMenuBarVisibility(false);
```
Menu bar shouldn't be visible even while spamming F11.

### Testcase Gist URL

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by wugaosheng123**
#### Description of Change

Closes #35807.

As mentioned in https://github.com/electron/electron/issues/35807#issuecomment-1567678931, when exiting fullscreen, in addition to judging the `IsMenuBarAutoHide()` of the window, you should also judge the user-set visibility property of menu bar. As I known, when entering fullscreen, `IsMenuBarVisible()` will change and may not be consistent with the state set by `mainWindow.setMenuBarVisibility` .

Therefore, I added the `menu_bar_visible_before_fullscreen_`  to identify the visibility of the menu bar before entering fullscreen, and when exiting fullscreen to set the visibility of the menu bar, I also need to determine the value of this variable.

First time PR, not sure if this is the best way. Works for me though.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixes visibility of menu bar when exiting full screen

### CODE REVIEW

File: shell/browser/native_window_views.h [hunk 1]
```diff
@@ -321,6 +321,9 @@ class NativeWindowViews : public NativeWindow,
   // Handles unhandled keyboard messages coming back from the renderer process.
   views::UnhandledKeyboardEventHandler keyboard_event_handler_;
 
+  // Whether the menubar is visible before fullscreen entered
```
Comment (codebytere) [inline shell/browser/native_window_views.h:324]: Let's tweak this slightly to:

`// Whether the menubar is visible before the window enters fullscreen`

**Review by codebytere — COMMENTED** [review]
Thanks for opening this PR! This change creates the following, which looks good to me:

|                                           | !IsMenuBarAutoHide() TRUE | !IsMenuBarAutoHide() FALSE |
|-------------------------------------------|---------------------------|----------------------------|
| menu_bar_visible_before_fullscreen_ TRUE  | VISIBLE ✅                 | NOT VISIBLE ✅              |
| menu_bar_visible_before_fullscreen_ FALSE | NOT VISIBLE ✅             | NOT VISIBLE ✅              |

However, I think we can and should add a test for this. We can add a new test [here](https://github.com/electron/electron/blob/40e724e5ddd92879a73fd3eb53af2b128947e9d6/spec/api-browser-window-spec.ts#L5340), where we validate the new expectations. This should look something like the following:

```js
describe('when fullscreen state is changed', () => {
  it('correctly remembers state prior to fullscreen change', async () => {
     const w = new BrowserWindow({ show: false });
     expect(w.isMenuBarVisible()).to.be.true('isMenuBarVisible');
     w.setMenuBarVisibility(false);
     expect(w.isMenuBarVisible()).to.be.false('isMenuBarVisible');

     const enterFS = once(w, 'enter-full-screen');
     w.setFullScreen(true);
     await enterFS;
     expect(w.fullScreen).to.be.true('not fullscreen');

     const exitFS = once(w, 'leave-full-screen');
     w.setFullScreen(false);
     await exitFS;
     expect(w.fullScreen).to.be.true('not fullscreen');

     expect(w.isMenuBarVisible()).to.be.false('isMenuBarVisible');
   });

   it('correctly remembers state prior to fullscreen change with autoHide', async () => {
      // Test assertions here.
   });
}); 
```

**Comment by wugaosheng123** [comment]
> Thanks for opening this PR! This change creates the following, which looks good to me:
> 	!IsMenuBarAutoHide() TRUE 	!IsMenuBarAutoHide() FALSE
> menu_bar_visible_before_fullscreen_ TRUE 	VISIBLE white_check_mark 	NOT VISIBLE white_check_mark
> menu_bar_visible_before_fullscreen_ FALSE 	NOT VISIBLE white_check_mark 	NOT VISIBLE white_check_mark
> 
> However, I think we can and should add a test for this. We can add a new test [here](https://github.com/electron/electron/blob/40e724e5ddd92879a73fd3eb53af2b128947e9d6/spec/api-browser-window-spec.ts#L5340), where we validate the new expectations. This should look something like the following:
> 
> ```js
> describe('when fullscreen state is changed', () => {
>   it('correctly remembers state prior to fullscreen change', async () => {
>      const w = new BrowserWindow({ show: false });
>      expect(w.isMenuBarVisible()).to.be.true('isMenuBarVisible');
>      w.setMenuBarVisibility(false);
>      expect(w.isMenuBarVisible()).to.be.false('isMenuBarVisible');
> 
>      const enterFS = once(w, 'enter-full-screen');
>      w.setFullScreen(true);
>      await enterFS;
>      expect(w.fullScreen).to.be.true('not fullscreen');
> 
>      const exitFS = once(w, 'leave-full-screen');
>      w.setFullScreen(false);
>      await exitFS;
>      expect(w.fullScreen).to.be.true('not fullscreen');
> 
>      expect(w.isMenuBarVisible()).to.be.false('isMenuBarVisible');
>    });
> 
>    it('correctly remembers state prior to fullscreen change with autoHide', async () => {
>       // Test assertions here.
>    });
> }); 
> ```
Thank you very much for the test code, but there may be a problem with your code, when leave fullscreen, the value of `w.fullScreen` should be false.
图片

File: spec/api-browser-window-spec.ts [hunk 2]
```diff
@@ -5338,6 +5338,48 @@ describe('BrowserWindow module', () => {
       });
     });
 
+    describe('when fullscreen state is changed', () => {
```
Comment (codebytere) [inline spec/api-browser-window-spec.ts:5341]: `isMenuBarVisible` and `setMenuBarVisible` are Windows/Linux only - you'll need to change this `describe` to

```
ifdescribe(process.platform !== 'darwin')('when fullscreen state is changed', () => {
```

**Review by codebytere — APPROVED** [review]
thanks for this!
