### PR TITLE
fix: use powerMonitor.on() only after app is ready

### LINKED ISSUE #21716: importing powerMonitor from electron before 'ready' event causes crash
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Same as #18966, app crashed when launched.

```typescript
import electron, { app } from "electron";

let mainWindow: electron.BrowserWindow;

app.on("ready", () => {
  mainWindow = new electron.BrowserWindow({
    width: 800,
    height: 600,
  });
});
```

Here is my repro sample.
https://github.com/mtgto/sample-electron-crash

Here is compiled index.ts
https://gist.github.com/mtgto/2a60ed4ce2e280c7577412884cde166e

* **Electron Version:**
  * v7.1.8
* **Operating System:**
  * Ubuntu 18.04.3
* **Last Known Working Electron version:**
  * Don't know

### Expected Behavior

Open an empty window.

### Actual Behavior

```console
$ yarn start
yarn run v1.21.1
$ electron index.js
App threw an error during load
Error: The 'powerMonitor' module can't be used before the app 'ready' event
    at Object.module.<computed> [as on] (electron/js2c/browser_init.js:6800:30)
    at Object../lib/browser/api/power-monitor.ts (electron/js2c/browser_init.js:2671:18)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at loader (electron/js2c/browser_init.js:2060:41)
    at Object.powerMonitor (electron/js2c/browser_init.js:7079:17)
    at __importStar (/home/user/sample-electron-crash/index.js:5:96)
    at Object.<anonymous> (/home/user/sample-electron-crash/index.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: The 'powerMonitor' module can't be used before the app 'ready' event
    at Object.module.<computed> [as on] (electron/js2c/browser_init.js:6800:30)
    at Object../lib/browser/api/power-monitor.ts (electron/js2c/browser_init.js:2671:18)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at loader (electron/js2c/browser_init.js:2060:41)
    at Object.powerMonitor (electron/js2c/browser_init.js:7079:17)
    at __importStar (/home/user/sample-electron-crash/index.js:5:96)
    at Object.<anonymous> (/home/user/sample-electron-crash/index.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
```

### To Reproduce

```console
$ git clone https://github.com/mtgto/sample-electron-crash.git
$ cd sample-electron-crash
$ yarn install
$ yarn build
$ yarn start
```

### Screenshots

N/A

### Additional Information
Stacktrace says `__importStar` calls powerMonitor. It happens when tsconfig uses `esModuleInterop: true` (default is true)
In macOS, app doesn't crash.

### PR DESCRIPTION
**Pull request by ckerr**
#### Description of Change

powerMonitor can't be used until the app is ready; however, on Linux, `powerMonitor.on()` was called as soon as lib/browser/api/power-monitor.ts was loaded.

This patch takes @vladimiry's [suggestion](https://github.com/electron/electron/issues/21716#issuecomment-572701025) of wrapping the calls in an app.on('ready') handler to prevent `powerMonitor.on()` from being called prematurely. It also adds an app.isReady() test in case powerMonitor is imported after the app is ready.

Note about the caveat described there about possible sequencing errors from the lazy loading &mdash; I don't _think_ this is an issue, because `powerMonitor.on()` can't be called by user code before the app is ready, and power-monitor.ts' on-ready-handler is registered as soon as power-monitor.ts is loaded. I'd welcome a second opinion on that though.

Fixes #21716.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed error thrown when importing powerMonitor on Linux before app's 'ready' event.

### CODE REVIEW

File: lib/browser/api/power-monitor.ts [hunk 1]
```diff
@@ -18,21 +18,27 @@ if (process.platform === 'linux') {
...
+      // whenever the listener count is decremented to zero...
       if (event === 'shutdown' && powerMonitor.listenerCount('shutdown') === 0) {
         powerMonitor.unblockShutdown()
       }
     })
-  })
+  }
+
+  const { app } = require('electron')
+  if (app.isReady()) {
```
Comment (vladimiry) [inline lib/browser/api/power-monitor.ts]: This is nice. I was not ware of `app.isReady()` existence.

File: lib/browser/api/power-monitor.ts [hunk 2]
```diff
@@ -10,19 +10,35 @@ Object.setPrototypeOf(PowerMonitor.prototype, EventEmitter.prototype)
...
 const powerMonitor = createLazyInstance(createPowerMonitor, PowerMonitor, true)
 
-// On Linux we need to call blockShutdown() to subscribe to shutdown event.
 if (process.platform === 'linux') {
-  powerMonitor.on('newListener', (event:string) => {
-    if (event === 'shutdown' && powerMonitor.listenerCount('shutdown') === 0) {
-      powerMonitor.blockShutdown()
-    }
-  })
+  /* In order to delay system shutdown when e.preventDefault() is invoked
```
Comment (zcbenz) [inline lib/browser/api/power-monitor.ts]: While we don't have a guide on comments, most files are using `//` for multi-line comments, I think it is better being consistent here.

File: lib/browser/api/power-monitor.ts [hunk 3]
```diff
@@ -10,19 +10,35 @@ Object.setPrototypeOf(PowerMonitor.prototype, EventEmitter.prototype)
...
-  powerMonitor.on('removeListener', (event: string) => {
-    if (event === 'shutdown' && powerMonitor.listenerCount('shutdown') === 0) {
-      powerMonitor.unblockShutdown()
-    }
-  })
+  const { app } = require('electron')
+  if (app.isReady()) {
+    onceReady()
+  } else {
+    app.once('ready', onceReady)
```
Comment (zcbenz) [inline lib/browser/api/power-monitor.ts]: Using `app.whenReady` can make this simpler.

Comment (vladimiry) [reply lib/browser/api/power-monitor.ts]: > Using `app.whenReady` can make this simpler.

Yay for `app.whenReady`. So it would be the same thing as I suggested initially, ie using `app.promises.ready`. But I was not aware of `app.whenReady`, same as `app.isReady()`.

Comment (ckerr) [reply lib/browser/api/power-monitor.ts]: This is a great idea. 6798825a8f1c49cb4e40dfb57fa5d42fac8cb0b2

File: lib/browser/api/power-monitor.ts (hunk 2 above)
Comment (ckerr) [reply lib/browser/api/power-monitor.ts]: Sounds good. Changed in ff0e17428827dbadbe2f97190a5483494f39192b

**Comment by ckerr** [comment]
> Will the `ready` event be replayed if it got fired already before this code starts? I mean `power-monitor` module could be loaded lazily after `ready` got fired already and the guess is `ready` event won't be replayed in this case. This is why I was thinking about using/introducing something like `app.promises.ready` (the promise gets resolved by `app` module in along with firing the `ready` event).

@zcbenz's suggestion of app.whenReady() takes care of this :tada:
