### PR TITLE
fix: use chrome headers in net.request for everything except cookie

### LINKED ISSUE #27895: net.request response is missing content-type header in 304 responses
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
10.1.7
* **Operating System:**
Windows 10 Enterprise 1909

When making a request with `net.request`, I can see that my response has a `content-type` header of `application/json; charset=utf-8` inside of my `webRequest.onHeadersReceived` handler:

```
electron.session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
  // details.responseHeaders['content-type'] === 'application/json; charset=utf-8'
});
```

But by the time the `net.request` `request.on('response')` handler receives the headers, the content-type is gone.

```
request.on('response', (response) => {
  /* 
  response.headers === {
    // no content-type
  };
  */
});
```

I haven't tested if this is an issue in all types of responses, but I can tell you this is occurring without fail for the case when the `response.statusCode === 200`, but the `response.headers.status === 304`.

### Expected Behavior
For `net.request` response handler to receive the content-type that clearly should exist on the response (proved by `webRequest.onHeadersReceived`).

### Actual Behavior
`net.request` response handler is receiving what seems to be a cached set of headers (or something?), which do not match what is seen in `webRequest.onHeadersReceived`.

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change

Chrome's parsed headers contain everything except the cookies ([ref](https://source.chromium.org/chromium/chromium/src/+/main:services/network/public/cpp/net_ipc_param_traits.cc;l=190;drc=098756533733ea50b2dcb1c40d9a9e18d49febbe)), so use those and add in the set-cookie header at the end.

Closes #27895.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation, tutorials, templates and examples are changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed net.request response headers missing `Content-Type`.

### CODE REVIEW

**Review by PraveenNanda124 — COMMENTED** [review]
Good work

File: shell/browser/api/electron_api_url_loader.cc [hunk 1]
```diff
@@ -577,9 +577,7 @@ void SimpleURLLoaderWrapper::OnResponseStarted(
   dict.Set("statusCode", response_head.headers->response_code());
   dict.Set("statusMessage", response_head.headers->GetStatusText());
   dict.Set("httpVersion", response_head.headers->GetHttpVersion());
-  // Note that |response_head.headers| are filtered by Chromium and should not
-  // be used here.
-  DCHECK(!response_head.raw_response_headers.empty());
+  dict.Set("headers", response_head.headers.get());
```
Comment (VerteDinde) [inline shell/browser/api/electron_api_url_loader.cc:580]: Just curious, did this filtering behavior change? I just want to make sure we're not in a situation where they would be filtered by Chromium again

**Review by VerteDinde — APPROVED** [review]
One question, but not blocking

File: shell/browser/api/electron_api_url_loader.cc (hunk 1 above)
Comment (nornagon) [reply shell/browser/api/electron_api_url_loader.cc:580]: I don't think so—I think the comment here was a bit misguided; I believe the only header that was being filtered out was set-cookie. I checked through most of our test requests and couldn't find anything that was being filtered besides set-cookie, though our tests are not complete coverage.

I suppose we'll find out sooner or later via bug report if I'm wrong!
