### PR TITLE
fix: crash when creating interface for speculative frame

### LINKED ISSUE #33880: [Bug]: Crash in WebFrameMain::Connect() -> GetInterface -> GetInterfaceByName
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17, 18

### What operating system are you using?

Windows

### Operating System Version

Windows 10 19042.985

### What arch are you using?

x64

### Last Known Working Electron version

14

### Expected Behavior

No crash

### Actual Behavior

Electron crashes
2022-04-21 10_07_53-Source Not Found (Debugging) - Microsoft Visual Studio

This does not happen consistently but fairly often and can be reproduced in the app.
I have not been able yet to make a small/standalone reproducable example

### Testcase Gist URL

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by samuelmaddock**
#### Description of Change

fixes #33880

Speculative render frames are created with pending cross-origin navigation requests. Their RenderFrameHost is not fully active until the navigation is later committed.

There seems to be a crash with our code to handle new RFHs. I've added a check to make sure the RFH has been notified of the RenderFrame being created prior to connecting the WebFrameMain's Mojo interface.

I wasn't able to reproduce the crash in a test.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed potential crash with WebFrameMain when navigating between cross-origin websites.

### CODE REVIEW

**Review by VerteDinde — APPROVED** [review]

**Comment by miniak** [comment]
@samuelmaddock Electron 16 is not affected?

**Comment by samuelmaddock** [comment]
> @samuelmaddock Electron 16 is not affected?

Looks like it should be backportable to 15 and 16.

**Review by zcbenz — APPROVED** [review]

File: shell/browser/api/electron_api_web_frame_main.cc [hunk 1]
```diff
@@ -316,7 +316,7 @@ std::vector<content::RenderFrameHost*> WebFrameMain::FramesInSubtree() const {
 }
 
 void WebFrameMain::Connect() {
-  if (pending_receiver_) {
+  if (pending_receiver_ && render_frame_->IsRenderFrameCreated()) {
```
Comment (nornagon) [inline shell/browser/api/electron_api_web_frame_main.cc:319]: I have questions..! Will this _reconnect_ later once the render frame is actually created? Will we miss any events or anything by not connecting immediately? Basically: is this the _correct_ fix?

Comment (samuelmaddock) [reply shell/browser/api/electron_api_web_frame_main.cc:319]: When I initially implemented this change, I think I may have overlooked the case where a speculative frame becomes active and we're sending messages using the `frame.send()` API. I do wonder if it's possible that messages aren't received when using `ipcRenderer.send` early in a preload script. I'd like to try creating a test to see whether we can break it this way.

[`WebContentsObserver::RenderFrameHostStateChanged(new_frame, old_state, new_state)`](https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/web_contents_observer.h;l=166-197;drc=cfb4b86c4d5138964cbcac7424ba3c4563775b49) is called when the speculative frame, or any other frame, changes to active.
```
  // When committing a cross-document, cross-RenderFrameHost navigation,
  // navigation-related callbacks are dispatched in the following order:
  // - RenderFrameHostStateChanged(new_frame, old_state, new_state)
  // - RenderFrameHostChanged(old_frame, new_frame)
  // - RenderFrameHostStateChanged(old_frame, old_state, new_state)
  // - DidFinishNavigation(navigation_handle)
```
If we do end up missing reconnecting the frame, listening for `new_state == contents::RenderFrameHost::LifecycleState::kActive` should help resolve it.

I'll followup once I've been able to experiment writing a test against early preload messages.

Comment (samuelmaddock) [reply shell/browser/api/electron_api_web_frame_main.cc]: I attempted several different methods of creating a WebContents (window.open, new BrowserWindow, window dispositions) and was unable to ever reproduce the crash. The stack trace included with the reported issue simply called `webContents.loadURL(url)` with a cross-origin URL. There may possibly be a race condition somewhere in Chromium leading to this behavior...

As for "is this the correct fix?", you might be right about the call to `GetInterface(pending_receiver_)` never happening. To ensure that it eventually gets called, I made it so `MaybeSetupMojoConnection()` will always check this when we need to get the renderer API. 4a91a92

**Comment by samuelmaddock** [comment]
Mac build failed due to maximum build time (120m), likely due to fork. Windows build has timeouts on `document.visibilityState` tests; seems unrelated.

**Review by nornagon — APPROVED** [review]
I'm not 100% sure this is the right fix but the tests pass and it theoretically fixes a crash (which we can't repro?)

LGTM to unblock but I'm a bit iffy.

**Comment by nornagon** [comment]
Starting next week, 17.x will be our earliest supported version, and we only do security backports to our earliest supported version, so i've updated the targets for this PR.
