### PR TITLE
fix: ensure autofill popup view is > 1x1 in size

### LINKED ISSUE #26667: DCHECK in autofill relating to zero-sized windows on macOS
Version: 6932e02eb862080f56d5ae811f3f3efce4309221
OS: macOS

No repro unfortunately, observed running Slack under a debug build of Electron.

```
[29366:1123/155917.793910:FATAL:native_widget_ns_window_bridge.mm(499)] Check failed: !clamped_content_size.IsEmpty(). Zero-sized windows not supported on Mac
0   Electron Framework                  0x0000000120a74569 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   Electron Framework                  0x00000001206fc9f3 base::debug::StackTrace::StackTrace() + 19
2   Electron Framework                  0x000000012076cd0a logging::LogMessage::~LogMessage() + 1146
3   Electron Framework                  0x000000012076fa6e logging::LogMessage::~LogMessage() + 14
4   Electron Framework                  0x0000000128d8b21f remote_cocoa::NativeWidgetNSWindowBridge::SetBounds(gfx::Rect const&, gfx::Size const&) + 799
5   Electron Framework                  0x00000001348ef62a views::NativeWidgetMacNSWindowHost::SetBoundsInScreen(gfx::Rect const&) + 794
6   Electron Framework                  0x0000000134923cd1 views::NativeWidgetMac::SetBounds(gfx::Rect const&) + 289
7   Electron Framework                  0x000000010fb72e49 electron::AutofillPopupView::Show() + 1401
8   Electron Framework                  0x000000010f8e45f8 electron::AutofillPopup::CreateView(content::RenderFrameHost*, content::RenderFrameHost*, bool, views::View*, gfx::RectF const&) + 1336
9   Electron Framework                  0x000000010f7a376c electron::AutofillDriver::ShowAutofillPopup(gfx::RectF const&, std::__1::vector<std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> >, std::__1::allocator<std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > > > const&, std::__1::vector<std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> >, std::__1::allocator<std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > > > const&) + 1244
10  Electron Framework                  0x000000011e85c519 electron::mojom::ElectronAutofillDriverStubDispatch::Accept(electron::mojom::ElectronAutofillDriver*, mojo::Message*) + 1577
[...]
```

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Fixes #26667

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes

#### Release Notes

Notes: none

### CODE REVIEW

**Review by codebytere — DISMISSED** [review]

**Review by zcbenz — APPROVED** [review]

File: shell/browser/ui/views/autofill_popup_view.cc [hunk 1]
```diff
@@ -224,7 +224,8 @@ void AutofillPopupView::DoUpdateBoundsAndRedrawPopup() {
   if (!popup_)
     return;
 
-  GetWidget()->SetBounds(popup_->popup_bounds_);
+  GetWidget()->SetBounds(popup_->popup_bounds_.Union(
+      gfx::Rect(popup_->popup_bounds_.origin(), gfx::Size(1, 1))));
```
Comment (zcbenz) [inline shell/browser/ui/views/autofill_popup_view.cc:228]: If `popup_->popup_bounds_` could be empty, then so would be `popup_->popup_bounds_in_view()`, which is used in some other places.

**Review by zcbenz — CHANGES_REQUESTED** [review]

**Comment by zcbenz** [comment]
It was also mentioned in https://github.com/electron/electron/issues/26667 that passing zero size to `BrowserWindow` could cause the same problem.

File: shell/browser/ui/views/autofill_popup_view.cc (hunk 1 above)
Comment (codebytere) [inline shell/browser/ui/views/autofill_popup_view.cc:228]:
```suggestion
  // Clamp popup_bounds_ to ensure it's never zero-width.
  popup_->popup_bounds_.Union(
      gfx::Rect(popup_->popup_bounds_.origin(), gfx::Size(1, 1)));
  GetWidget()->SetBounds(popup_->popup_bounds_);
```

**Review by zcbenz — APPROVED** [review]
