### PR TITLE
Ensure that a document has been created before sending IPC messages

### LINKED ISSUE #12045: Preload script executed twice on Electron 2.0.x
* Electron version: `2.0.0-beta.1`
* Operating system: macOS

### Expected behavior

Preload script should execute once

### Actual behavior

Preload script (and in fact `node_bootstrap.js`) is executed twice in the same process but in a different context.

### How to reproduce

Struggling to isolate this from the application that is experiencing it but I have narrowed it down to this being _kind of_ expected behavior but with a newly introduced bug in `2.0.x`.  Basically when you call `loadURL` a renderer process is initially launched pointing at `about:blank`.  In this process `renderer/init.js` is called and then the window navigates to the URL you requested.

For an as yet unknown reason in `2.0.x` the `--preload` argument is present on the renderer process when the `about:blank` page is loaded causing user code to execute twice in the same process.  This is only a problem because native modules can only be loaded once in a given process.

The fix for this would be to revert to original behavior where the `--preload` (amongst others) arguments are not sent to the renderer until the users page is loaded.  (Don't send them for `about:blank`).

I'm currently working on a minimal sample

### PR DESCRIPTION
**Pull request by MarshallOfSound**
* Reverts 370476c4affc56ed9799068187b1e8fd5d1beb0a in favor of moving the previous logic to the new RenderFrameObserver instead of RenderViewObserver

Fixes #12045

🎉

### CODE REVIEW

File: atom/renderer/atom_render_frame_observer.cc [hunk 1]
```diff
@@ -99,4 +142,78 @@ bool AtomRenderFrameObserver::ShouldNotifyClient(int world_id) {
...
+  // to a web page, and when we do that Blink creates an empty
+  // document element if it hasn't been created yet, and it makes our init
+  // script to run while `window.location` is still "about:blank".
+  if (!document_created_)
+    return;
+
+  if (!render_frame()->GetRenderView()->GetWebView())
+    return;
+
+  blink::WebFrame* frame = render_frame()->GetRenderView()->GetWebView()->MainFrame();
```
Comment (zcbenz) [inline atom/renderer/atom_render_frame_observer.cc]: atom/renderer/atom_render_frame_observer.cc:174:  Lines should be <= 80 characters long  [whitespace/line_length] [2]

**Comment by deepak1556** [comment]
I will add changes from ch63 branch that does rvo->rfo transition here https://github.com/electron/electron/pull/11459/commits/a31decaf7595ce6582a1db916b402dcb54abae7b.
