### PR TITLE
fix: `net.isOnline` always true in utility processes

### LINKED ISSUE #48100: `net.isOnline()`/`net.online` always returns `true` when called from module running as a utility process.
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

37.3.0

### What operating system(s) are you using?

macOS

### Operating System Version

Sequoia 15.6

### What arch are you using?

x64

### Last Known Working Electron version

_No response_

### Does the issue also appear in Chromium / Google Chrome?

I don't know how to test

### Expected Behavior

Using Electron's [`net`](https://www.electronjs.org/docs/latest/api/net) module, calling `net.isOnline()` or `net.online` within a module that's running as a utility process should reflect the actual state of the host device.

### Actual Behavior

When I've disconnected wifi on the device and call `net.isOnline()` from within the utility process module, the result is `true`.

### Testcase Gist URL

https://gist.github.com/achou11/159165d915505372f1450177757e9aa8

### Additional Information

The gist shows the disparity between what can be determined within different processes i.e. renderer vs main vs utility. The renderer uses the [NetworkInformation API](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation) while the main and utility processes use Electron's [`net`](https://www.electronjs.org/docs/latest/api/net) module

When running the reproduction while disconnect from wifi, you'll noticed that the renderer and main log the expected results, whereas the utility process logs an unexpected result.

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Closes #48100.

Fixes an issue where `net.isOnline()` always returned `true` in utilityProcesses. This happened because utility processes never created a `net::NetworkChangeNotifier`, so `net.isOnline()` always saw a null [global](https://source.chromium.org/chromium/chromium/src/+/main:net/base/network_change_notifier.cc;drc=280cd6cc9ad696c74313035a0bbaab8f4f8c4bf4;bpv=1;bpt=1;l=52) and defaulted to “online”.

Fix this by adding a per‑utility‑process `NetworkChangeNotifier` during `NodeService::Initialize()]`, allowing `net.isOnline()`  to reflect real connectivity. 

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed an issue where `net.isOnline()` always returned `true` in utilityProcesses.

### CODE REVIEW

File: shell/services/node/node_service.cc [hunk 1]
```diff
@@ -127,6 +128,12 @@ void NodeService::Initialize(
 
   node_bindings_->Initialize(isolate, isolate->GetCurrentContext());
 
+  if (!network_change_notifier_) {
+    network_change_notifier_ = net::NetworkChangeNotifier::CreateIfNeeded(
+        net::NetworkChangeNotifier::CONNECTION_UNKNOWN,
+        net::NetworkChangeNotifier::ConnectionSubtype::SUBTYPE_UNKNOWN);
+  }
```
Comment (deepak1556) [inline shell/services/node/node_service.cc]: can be, NodeService::Initialize is not re-entrant

```suggestion
    network_change_notifier_ = net::NetworkChangeNotifier::CreateIfNeeded(
        net::NetworkChangeNotifier::CONNECTION_UNKNOWN,
        net::NetworkChangeNotifier::ConnectionSubtype::SUBTYPE_UNKNOWN);
```

**Review by dsanders11 — APPROVED** [review]
