### PR TITLE
fix: stop menu minimization if set false

### LINKED ISSUE #43130: [Bug]: "window" tab in Menu,the Minimize button can still be clicked for windows those have minimized disabled
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.2.0

### What operating system(s) are you using?

macOS

### Operating System Version

MacOS 13.5.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

_No response_

### Expected Behavior

image
minisize disabled like this

### Actual Behavior

image

minisize button can still be clicked，but the window will not minisize actually when click 😄

### Testcase Gist URL

_No response_

### Additional Information

_No response_

### LINKED ISSUE #46676: Window with `minimizable: false` still minimizes using "Minimize" menu item on Windows
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

35.0.0

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working Electron version

_No response_

### Expected Behavior

After creating a window with `minimizable: false`, the window should not be minimizable by any means

### Actual Behavior

After creating a window with `minimizable: false` on Windows, the window is still minimizable via a menu item with the `minimize` role

### Testcase Gist URL

https://gist.github.com/mlaurencin/288aad20449c92f3749121a496c0011f

### Additional Information

Discovered triaging https://github.com/electron/electron/issues/43130

### PR DESCRIPTION
**Pull request by mlaurencin**
#### Description of Change

Closes #46676

Previously the "Minimize" menu button would still allow the user to minimize the window on Windows, even if the window was created with `minimizable: false`. Now the window will not be able to be minimized via that button.

A follow-up PR is necessary to disable the button such that it is grayed out as well on both macOS and Windows.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: fix Minimize menu button to follow set window minimizability on Windows

### CODE REVIEW

**Review by codebytere — CHANGES_REQUESTED** [review]
At the moment I think this combines two separate changes that should be handled differently:

1. Preventing the minimize role from having an effect when the window isn’t minimizable. 
2. Disabling the minimize button visually on macOS. This approach is platform-specific and should imo be another PR, ideally as part of a broader cross-platform solution.

1 should have some tests as well!

**Comment by mlaurencin** [comment]
I've updated my description to now properly reflect the changes made by this PR. It is only Windows that is incorrectly minimizing through a menu button when minimizable is set to false. The macOS functionality goes along a different code path and is not effected like this. However, both are still not shown to be disabled (grayed out) when `minimizable: false`, so that will be a follow up PR to this. I'll also update the test to reflect this.

File: spec/api-menu-item-spec.ts [hunk 1]
```diff
@@ -205,6 +205,22 @@ describe('MenuItems', () => {
       const canExecute = execute(item.role as any, win, win.webContents);
       expect(canExecute).to.be.true('can execute');
     });
+
+    ifit(process.platform === 'win32')('does not execute minimize role when minimizable false', () => {
```
Comment (codebytere) [inline spec/api-menu-item-spec.ts:209]: Wouldn't we want to make sure this is true on all platforms?

Comment (mlaurencin) [reply spec/api-menu-item-spec.ts:209]: I created an issue to better document the specifics of the bug being fixed here. So with this new code only the Windows functionality is effected. The specific test I added is only applicable to Windows since the macOS path does not involve _executeCommand when it comes to executing menu items with assigned “roles”. I could add a macOS specific test for overall test suite completeness, but in terms of testing the added functionality, this test should cover it.

**Review by codebytere — APPROVED** [review]
