### PR TITLE
fix: avoid redundant `page-favicon-updated` events on `setBounds`

### LINKED ISSUE #49392: `setBounds` a WebContentsView will trigger `page-favicon-updated` event on some websites
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

39.2.7

### What operating system(s) are you using?

Windows

### Operating System Version

Windows 11 25H2

### What arch are you using?

x64

### Last Known Working Electron version

_No response_

### Does the issue also appear in Chromium / Google Chrome?

I don't know how to test

### Expected Behavior

Intuitively, `setBounds` is related to positions and has nothing to do with the favicon. So `page-favicon-updated` event should not be emitted when calling `setBounds` with a new `bounds` on a WebContentsView.

### Actual Behavior

Construct a WebContentsView, listen its `page-favicon-updated` event, add it to the main window, and `loadURL` for like `https://electronjs.org`. Then call `setBounds` with a new `bounds` on the WebContentsView, `page-favicon-updated` will be triggered.

This doesn't occur on all websites, but many websites have this problem, including `https://github.com`.

Usually this won't lead to noticeable problems. But if the user wants to auto resize the WebContentsView when the main window resizes, `setBounds` will be frequently called and a series of  `page-favicon-updated` event will be emitted, even if the favicon urls array is not changed.

Image

### Testcase Gist URL

https://gist.github.com/z0gSh1u/72fe6f155e1f145385461853d7ef2782

### Additional Information

Can be reproduced on macOS too.

### PR DESCRIPTION
**Pull request by ANANYA542**
#### Description of Change

Closes #49392

Fixes an issue where calling `setBounds` on a `WebContentsView` unintentionally triggers the `page-favicon-updated` event even when the favicon has not actually changed.

Currently, layout-related updates such as resizing or repositioning a `WebContentsView` can cause redundant emissions of `page-favicon-updated`, which is unexpected and leads to duplicate callbacks in user code. This change ensures that the event is only emitted when there is a real change in the favicon data, preventing unnecessary and misleading notifications.

This makes the `page-favicon-updated` event more semantically correct and avoids side effects caused by purely visual or layout updates.

#### Checklist

- [ x] PR description included
- [ ] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant API documentation, tutorials, and examples are updated and follow the [documentation style guide](https://github.com/electron/electron/blob/main/docs/development/style-guide.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers and are [capitalized, punctuated, and in past tense](https://github.com/electron/clerk/blob/main/README.md#examples).
---

#### Release Notes

Notes: Fixed an issue where calling `setBounds` on a `WebContentsView` could trigger redundant `page-favicon-updated` events even when the favicon had not changed.

### CODE REVIEW

File: shell/browser/api/electron_api_web_contents.cc [hunk 1]
```diff
@@ -2176,6 +2175,11 @@ void WebContents::DidUpdateFaviconURL(
         iter->icon_url.is_valid())
       unique_urls.insert(iter->icon_url);
   }
+    // Deduplicate: only emit if favicon URLs actually changed
```
Comment (codebytere) [inline shell/browser/api/electron_api_web_contents.cc]:
```suggestion
    // Only emit if favicon URLs actually changed
```

**Review by codebytere — COMMENTED** [review]
Confirmed this corrects the issue. Please add a test [here](https://github.com/electron/electron/blob/b51e82c5fbec9c6d0bbf68bcfd51ec5309596cbc/spec/webview-spec.ts#L1525-L1539) to validate the fix. You also need to [sign your commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

**Comment by nikwen** [comment]
I wonder if this just works around an upstream issue that should really be fixed in Chromium. Why would `WebContentsObserver::DidUpdateFaviconURL` be called in the first place when changing bounds?

File: shell/browser/api/electron_api_web_contents.h [hunk 2]
```diff
@@ -461,6 +461,9 @@ class WebContents final : public ExclusiveAccessContext,
   WebContents& operator=(const WebContents&) = delete;
 
  private:
+  // Store last emitted favicon URLs to avoid duplicate page-favicon-updated
+  // events
+  base::flat_set<GURL> last_favicon_urls_;
```
Comment (ckerr) [inline shell/browser/api/electron_api_web_contents.h:467]: _(nit)_ Needs `#include "base/containers/flat_set.h"` at the top of the header file

**Comment by ANANYA542** [comment]
@ckerr , @codebytere  Thanks for the reviews!
I’ve addressed the requested changes, added a regression test for the favicon behavior, and synced the branch with main. I’m keeping an eye on the CI results.Do recommend further changes if needed.

**Comment by ANANYA542** [comment]
@nikwen I tried looking into whether this should be handled upstream, but I couldn’t find a clear Chromium issue or documentation that explains exactly why DidUpdateFaviconURL fires on bounds/layout changes from what I could observe while testing locally, the callback was getting triggered even when the favicon URL itself didn’t actually change, but I don’t have a solid upstream reference yet that proves the root cause so for now I treated this more like an electron-side safeguard so app developers don’t get duplicate page-favicon-updated events I’m still pretty new to digging into Chromium internals and trying to understand how these observers propagate, so I might be missing some deeper context here if there’s an existing upstream issue or a better place to fix this, I’d definitely be happy to explore that direction too.

**Comment by nikwen** [comment]
I don't think you'd find an issue already filed upstream or any documentation on it. It would require reading the relevant Chromium code and debugging why the event fires multiple times.

**Comment by ANANYA542** [comment]
@ckerr Thanks for pushing the updates and rebasing!
The changes look good to me @codebytere  please let me know if there's anything else you'd like me to adjust.
