### PR TITLE
fix: Don't crash on `setApplicationMenu(null)`

### LINKED ISSUE #11052: Exception with Menu.setApplicationMenu(null) since 1.8.2-beta.2
* Electron version: 1.8.2-beta.2
* Operating system: macOS 10.13.1

### Expected behavior

As per documentation `Menu.setApplicationMenu(null)` should remove menu bar in Windows/Linux and do nothing in macOS.

### Actual behavior

Exception is thrown (starting with Electron 1.8.2-beta.2 version):

```
TypeError: Cannot read property 'constructor' of null
    at Function.Menu.setApplicationMenu (<hidden>/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/menu.js:136:21)
    at App._electron.app.on (<hidden>)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
```

### How to reproduce

Try calling static `Menu.setApplicationMenu(null)` from app `ready` event.

### PR DESCRIPTION
**Pull request by felixrieseberg**
We found a little bug that snuck in during the ES6 transition. This PR ensures that calling `setApplicationMenu(null)` (which removes the current menu) doesn't crash.

Also: A spec!

Fixes #11052

### CODE REVIEW

File: lib/browser/api/menu.js [hunk 1]
```diff
@@ -133,7 +133,7 @@ Menu.sendActionToFirstResponder = bindings.sendActionToFirstResponder
 
 // set application menu with a preexisting menu
 Menu.setApplicationMenu = function (menu) {
-  if (!(menu || menu.constructor === Menu)) {
+  if (!(!menu || menu.constructor === Menu)) {
```
Comment (poiru) [inline lib/browser/api/menu.js]: I think this would be easier to read as `menu && menu.constructor !== Menu`

File: lib/browser/api/menu.js [hunk 2]
```diff
@@ -133,7 +133,7 @@ Menu.sendActionToFirstResponder = bindings.sendActionToFirstResponder
 
 // set application menu with a preexisting menu
 Menu.setApplicationMenu = function (menu) {
-  if (!(menu || menu.constructor === Menu)) {
+  if (menu && menu.constructor !== Menu)) {
```
Comment (MarshallOfSound) [inline lib/browser/api/menu.js]: There are one to many closing brackets here 😄

Comment (felixrieseberg) [reply lib/browser/api/menu.js]: That's what you get for trying to fix this on the phone 🗡

**Comment by felixrieseberg** [comment]
@MarshallOfSound fixed!

**Comment by ckerr** [comment]
I'm thinking we should merge this as-is since the test failures don't seem to be related to this patch.

Anyone opposed?

**Comment by MarshallOfSound** [comment]
macOS failures have been fixed in master, linux failure appears to be flake. Merging 😄

**Comment by ckerr** [comment]
This was merged into `master` before the `1-8-x` branch was created, so both already have this fix; no need to backport to `1-8-x`
