### PR TITLE
docs: fix some string union type

### LINKED ISSUE #38339: Improve Type Union Typings in the Docs
[The phrasings that `electron/docs-parser` recognizes for string union types](https://github.com/electron/docs-parser/blob/c56164b4cebcf010306e0458729bf179bf69e650/src/markdown-helpers.ts#L459) is fairly narrow, and it looks like there's a handful of places in the docs where the phrasing is not being picked up as string union types.

Fix these and add smoke tests with `// @ts-expect-error` to ensure type unions are being used. See #38336 for an example.

Alternatively, extend the phrasings that `electron/docs-parser` recognizes, and add the smoke tests.

A (possibly non-exhaustive) list of ones which aren't being picked up. There's [an upstream issue](https://github.com/electron/docs-parser/issues/88) preventing certain values from being picked up.

https://github.com/electron/electron/blob/2a16c73834358f85ef20c07e50dfb5178c30bb1e/docs/api/webview-tag.md?plain=1#L1091-L1093

https://github.com/electron/electron/blob/2a16c73834358f85ef20c07e50dfb5178c30bb1e/docs/api/web-contents.md?plain=1#L796-L798

https://github.com/electron/electron/blob/2a16c73834358f85ef20c07e50dfb5178c30bb1e/docs/api/native-image.md?plain=1#L308-L309

https://github.com/electron/electron/blob/2a16c73834358f85ef20c07e50dfb5178c30bb1e/docs/api/session.md?plain=1#L577-L580

https://github.com/electron/electron/blob/2a16c73834358f85ef20c07e50dfb5178c30bb1e/docs/api/session.md?plain=1#L581-L582

https://github.com/electron/electron/blob/e08c583dea42ce70c926825a2f6d455bbddf2089/docs/api/desktop-capturer.md?plain=1#L91-L92

### PR DESCRIPTION
**Pull request by anyerqi**
#### Description of Change

fixes #38339

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] relevant documentation, tutorials, templates and examples are changed or added

#### Release Notes

Notes:  none

### CODE REVIEW

File: spec/api-session-spec.ts [hunk 1]
```diff
@@ -254,8 +254,8 @@ describe('session module', () => {
       await w.loadFile(path.join(fixtures, 'api', 'localstorage.html'));
       const options = {
         origin: 'file://',
-        storages: ['localstorage'],
-        quotas: ['persistent']
+        storages: ['localstorage' as const],
+        quotas: ['temporary' as const]
       };
       await w.webContents.session.clearStorageData(options);
```
Comment (dsanders11) [inline spec/api-session-spec.ts:260]: For simplicity, let's just put the value of `options` directly into the `clearStorageData` call.

**Review by dsanders11 — APPROVED** [review]
Small comment but overall LGTM.

File: spec/api-session-spec.ts (hunk 1 above)
Comment (anyerqi) [reply spec/api-session-spec.ts]: OK, corrected

**Review by zcbenz — APPROVED** [review]
