### PR TITLE
fix: load the chrome.* API on chrome-extension pages in sandbox mode

### LINKED ISSUE #15561: enableMixedSandbox blocks devtools extension context
* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version):
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.4

**Expected Behavior**
devtools extension's page (`manifest.json`'s `devtools_page`) have electron's global `chrome.*` extension api context constructed.

**Actual behavior**
`devtools_page` doesn't have context, any calls to `chrome.*` will fail

**To Reproduce**
```
const {app, BrowserWindow} = require('electron')

//enable mixed sandbox asap
app.enableMixedSandbox();

let mainWindow

function createWindow () {
  mainWindow = new BrowserWindow({width: 1024, height: 768})

 mainWindow.loadURL('https://reactjs.org')
  
  //other devtools extension can be used instead as long as `devtools_page` access chrome.* api
  require('devtron').install();
  mainWindow.webContents.openDevTools()

  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})
```

devtron is used for simplified repro, but any other devtools (i.e react devtools) will have same symptoms.
launch electron, then open devtools will emit console logs like
```
[10800:1104/011325.639:ERROR:CONSOLE(7)] "Uncaught ReferenceError: chrome is not defined", source: chrome-extension://devtron/static/devtron.html (7)
```

**Screenshots**

**Additional Information**

### PR DESCRIPTION
**Pull request by MarshallOfSound**
With mixed sandbox enabled we need to load the chrome.* APIs in the
sandbox init.js so that chrome extensions load correctly.

This mirrors the equivilant impl in `atom_renderer_client.cc`

Refs: https://github.com/electron/electron/blob/master/atom/renderer/atom_renderer_client.cc#L84-L98

Fixes #15561

Notes: fix loading chrome devtools extensions with sandbox enabled

### CODE REVIEW

File: lib/sandboxed_renderer/init.js [hunk 1]
```diff
@@ -103,9 +103,18 @@ function preloadRequire (module) {
...
-  require('@electron/internal/renderer/inspector')
+switch (window.location.protocol) {
+  case 'chrome-devtools:': {
+    // Override some inspector APIs.
+    require('@electron/internal/renderer/inspector')
+    break
+  }
+  case 'chrome-extension:': {
+    // Inject the chrome.* APIs that chrome extensions require
+    const isBackgroundPage = preloadProcess.argv.indexOf('--background-page') !== -1
```
Comment (alexeykuzmin) [inline lib/sandboxed_renderer/init.js]: `.argv.includes()` maybe?

File: atom/renderer/atom_sandboxed_renderer_client.cc [hunk 2]
```diff
@@ -197,7 +202,8 @@ void AtomSandboxedRendererClient::DidCreateScriptContext(
 
   // Only allow preload for the main frame or
```
Comment (nornagon) [inline atom/renderer/atom_sandboxed_renderer_client.cc]: ... or what

File: lib/sandboxed_renderer/init.js [hunk 3]
```diff
@@ -103,16 +103,25 @@ function preloadRequire (module) {
...
-  // Override some inspector APIs.
-  require('@electron/internal/renderer/inspector')
+switch (window.location.protocol) {
+  case 'chrome-devtools:': {
+    // Override some inspector APIs.
+    require('@electron/internal/renderer/inspector')
+    break
+  }
+  case 'chrome-extension:': {
+    // Inject the chrome.* APIs that chrome extensions require
```
Comment (nornagon) [inline lib/sandboxed_renderer/init.js]:
```suggestion
    // Inject the chrome.* APIs that devtools extensions require
```

Comment (MarshallOfSound) [reply lib/sandboxed_renderer/init.js]: I think this is currently correct, although we don't advertise it as much you can actually use some normal Chrome extensions in Electron (not just devtools extensions)
