### PR TITLE
Let Chromium manage `document.visibilityState` and `document.hidden`

### LINKED ISSUE #6860: visibilitychange and webkitvisibilitychange event issues
- Electron version: 1.3.3
- Operating system: Windows 7

Hi,

It seems there are a few issues with page visibility events.

The first is that the `visibilitychange` event fires twice, causing listeners to run twice. This does not occur for `webkitvisibilitychange`.

The second is that when a `visibilitychange` event listener runs for the first time, and when a `webkitvisibilitychange` listener runs, `document.visibilityState` does not contain the correct (new) state - it contains the previous state. If you check the property after the event has fired (e.g. in a timeout or manually), and also when the `visibilitychange` listener runs for the second time, it is then correct. It might also be worth noting that `document.webkitVisibilityState` is correct in all cases.

[page-visibility.zip](https://github.com/electron/electron/files/420080/page-visibility.zip)
[page-visibility-webkit.zip](https://github.com/electron/electron/files/420096/page-visibility-webkit.zip)

These are sample applications to reproduce the bug, which will log the two state properties (`visibilityState` and `webkitVisibilityState`) whenever the event fires. The first is listening to `visibilitychange` and the second to `webkitvisibilitychange`. Just do `npm install` then run with `./node_modules/.bin/electron .`.

If you minimize and restore the application, you should be able to see what I've described in the logs. If you open `index.html` in Chrome and do the same, you should see that both then behave correctly.

I'll admit I'm not sure if this is definitely an Electron bug - I can't see much relating to `visibilitystate` in the Electron code. If it is and you'd prefer the two issues to be raised separately I can do that, just let me know.

### PR DESCRIPTION
**Pull request by poiru**
Chromium already includes the necessary plumbing to manage the
visibility properties and `visibilitychange` event so this gets rid of
most of our custom logic for `BrowserWindow` and `BrowserView`.

Note that `webview` remains unchanged and is still affected by the issues
listed below.

User facing changes:

- The `document` visibility properties and `visibilitychange` event are
  now also updated/fired in response to occlusion changes on macOS. In
  other words, `document.visibilityState` will now be `hidden` on macOS
  if the window is occluded by another window.

- Previously, `visibilitychange` was also fired by *both* Electron and
  Chromium in some cases (e.g. when hiding the window). Now it is only
  fired by Chromium so you no longer get duplicate events.

- The visiblity state of `BrowserWindow`s created with `{ show: false }`
  is now initially `visible` until the window is shown and hidden.

- The visibility state of `BrowserWindow`s with `backgroundThrottling`
  disabled is now permanently `visible`.

This should also fix #6860 (but not for `webview`).

### CODE REVIEW

File: lib/browser/api/browser-window.js [hunk 1]
```diff
@@ -112,7 +112,6 @@ BrowserWindow.prototype._init = function () {
     if (isVisible !== newState) {
       isVisible = newState
       const visibilityState = isVisible ? 'visible' : 'hidden'
-      this.webContents.send('ELECTRON_RENDERER_WINDOW_VISIBILITY_CHANGE', visibilityState)
       this.webContents.emit('-window-visibility-change', visibilityState)
```
Comment (poiru) [inline lib/browser/api/browser-window.js]: Ideally we would also fire this when the window is occluded. I'll do that in a follow-up PR.

**Comment by lukeapage** [comment]
Is there a timeline for this PR? Looking forward to it...

**Comment by kevinsawicki** [comment]
> Is there a timeline for this PR? Looking forward to it...

@poiru did you mention you were seeing some spec crashes?

**Comment by poiru** [comment]
@kevinsawicki Fixed the crash so this is ready to be reviewed/merged.

**Comment by kevinsawicki** [comment]
@poiru merged latest master and pushed a few changes to the specs to wait for events instead of using timeouts, they worked for me locally but might be flaky on CI so I'll take care of any build failures.

**Comment by kevinsawicki** [comment]
I'm seeing a flicker when un-maximizing via clicking the icon from the macOS dock, little tricky to screen capture, but here are two gifs of this branch vs. master:

### this branch

hidden-flicker

### master

hidden-flicker2

**Comment by poiru** [comment]
@kevinsawicki I went ahead and reverted the `webview` related changes. In other words, this PR now only applies to `BrowserWindow`/`BrowserView`.

**Comment by kevinsawicki** [comment]
Tests are green now, pushed a few updates to them but I think the original cases are still covered.

Thanks for this @poiru 👍 🚀
