### PR TITLE
fix: handle window.open events in BrowserView

### LINKED ISSUE #10707: window.open windows not visible when created from BrowserView with nativeWindowOpen enabled
* Electron version: 1.7.8
* Operating system: MacOS Sierra 10.12.6

### Expected behavior
The new window should be opened, and visible

### Actual behavior
The new window is created, but it never becomes visible to the user. These windows can be accessed via the return of `window.open` and appear to be loading content internally.

### How to reproduce
Example repo here: https://github.com/gerges/electron-quick-start/tree/issue/browser-view-native-window-open

### PR DESCRIPTION
**Pull request by Anrock**
Fixes #10707

Not sure if it's a proper fix, but Work For Me™
Basically it's just a mindless copypaste of `-new-window`, `-web-contents-created`, `-add-new-contents` handlers from `lib/browser/api/browser-window.js` `_init` along with relevant unit-tests.

notes: Fixed child windows invisible if opened with window.open from BrowserView with nativeWindowOpen enabled

### CODE REVIEW

**Comment by Anrock** [comment]
Also, personally i need this backported to 1.7.x and 1.8.x branches but i haven't found the docs on how to do this: from pull request guides it seems only permitted target branch is master. Is there any docs on backporting process or could someone explain it to me?

File: lib/browser/api/browser-view.js [hunk 1]
```diff
@@ -1,9 +1,59 @@
...
+const electron = require('electron')
+const {ipcMain} = electron
 const {EventEmitter} = require('events')
 const {BrowserView} = process.atomBinding('browser_view')
+const v8Util = process.atomBinding('v8_util')
 
 Object.setPrototypeOf(BrowserView.prototype, EventEmitter.prototype)
+BrowserView.prototype._init = function () {
+  // Make new windows requested by links behave like "window.open"
+  this.webContents.on('-new-window', (event, url, frameName, disposition,
```
Comment (poiru) [inline lib/browser/api/browser-view.js]: Maybe we could just do this in `lib/browser/api/web-contents.js` to share the impl between BrowserWindow/BrowserView? cc @zcbenz

Comment (poiru) [reply lib/browser/api/browser-view.js]: @Anrock Feel free to just make new commits. We can squash it all when merging.

**Comment by Anrock** [comment]
@poiru thanks. Can it be also ported to 1.7?

**Comment by MarshallOfSound** [comment]
This is something that can't be backported right? It's semver/feature 🤔

**Comment by Anrock** [comment]
@MarshallOfSound i'd say it's a bugfix. At least i expect, from user perspective, that BrowserView should behave identically irregardless if nativeWindowOpen is true or false. Just like BrowserWindow does.

**Comment by MarshallOfSound** [comment]
@Anrock There's a line between "adding a feature that probably should have been there in the first place" and "fixing something that wasn't functioning correctly".  I think this is quite nicely fitting in the first category

**Comment by Anrock** [comment]
@MarshallOfSound ok.
Only thing that bothers me now is what should i do to get this changes to 1.7 and 1.8 branches, please advice.

**Comment by Anrock** [comment]
@poiru @ckerr any eta on merge? Two weeks and no movement.

**Comment by MarshallOfSound** [comment]
The failing tests are blocking this

**Comment by poiru** [comment]
@Anrock The test failures might be flakes. Can you rebase on top of master and force push?

**Comment by alexeykuzmin** [comment]
@Anrock 
Can you please rebase your branch onto the latest master and resolve merge conflicts?

**Comment by Anrock** [comment]
@alexeykuzmin in progress. However i suspect that test failures are not flakes actually.

**Comment by Anrock** [comment]
@alexeykuzmin done. But i don't have time to investigate test failures.

**Comment by Anrock** [comment]
@Akshat-Jain done. I think it's time to scrap this PR and rewrite from scratch. Looks like handlers have changed multiple times and given non-trivial conflicts i suspect something is missed in action.

**Comment by Anrock** [comment]
Can someone help with broken tests?
linux-arm-debug, linux-arm-testing, linux-ia32-testing: failed build with sscache error
inux-x64-testing-tests, linux-x64-testing-verify-ffmpeg: failed tests with `cannot open display`
osx-testing: marked as failed, but circleci build step is not even finished yet

**Comment by Anrock** [comment]
@Akshat-Jain i've rewritten this from scratch, so PR needs re-review.

**Comment by Anrock** [comment]
Looks like https://github.com/electron/electron/issues/14984 should fix part of failing linux tests.

**Comment by Anrock** [comment]
@alexeykuzmin regarding #15016, this is PR rebased on master and in [branch log](https://github.com/Anrock/electron/commits/browserview-handle-window-open) i see that branch includes https://github.com/electron/electron/commit/918488a2f0009ef70a0f86d9e2e504b9dc54676f commit that should fix build breakage, however build is still broken.
Anything else i'm missing?

**Comment by Anrock** [comment]
@Akshat-Jain ping

**Comment by codebytere** [comment]
hi @anrock, `@akshat-jain` isn't involved in this project at all; you can see his review wasn't a valid one  as it was a grey check. You can ping anyone in `@electron/reviewers` for future review!

**Comment by Anrock** [comment]
@codebytere thank you! How do i find member list of @electron/reviewers?

**Comment by codebytere** [comment]
ah i mean you can literally tag `@electron/reviewers`!

**Comment by Anrock** [comment]
@codebytere for some reason it doesn't appear in autocompletion list and not marked as mention after i manually type it.

**Comment by codebytere** [comment]
@anrock are you still interested in moving forward with this?

**Comment by Anrock** [comment]
@codebytere yes, but i really don't have time to do it - busy fixing window.opener in my app. And i guess code is gone stale again. Should i close PR then or there is someone else interested doing it?

**Comment by zcbenz** [comment]
I have rebased the branch and  added some fixes and tests.
