### PR TITLE
fix: flicker and ghosting in transparent windows on macOS

### LINKED ISSUE #45932: Video afterimages remain
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

35.0.0

### What operating system(s) are you using?

macOS

### Operating System Version

macOS 15.3.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

34.3.1

### Expected Behavior

Rotating `<video>` with `transform:rotate()` does not leave the video image.

### Actual Behavior

This video is a somewhat unusual media viewer that I am developing.
The landscape on the left is an image, and the rabbit on the right is a video.

in v34.3.1
<video src="https://github.com/user-attachments/assets/c6a1bb00-23a6-4ad0-beeb-ca2ffbfac15e">

Each has a `` and `<video>` placed in a window with a transparent background, and is rotated with CSS `transform:rotate()` in response to the wheel event.

There were no problems up to Electron v34.3.1. However, after updating to Electron v35.0.0, an afterimage remained when rotating the video.

in v35.0.0
<video src="https://github.com/user-attachments/assets/afe3015f-fedf-4736-98c4-3140d3d6ee5e">

There is no problem with images. It only occurs with videos.

I haven't changed any code. I've just updated the Electron version.
I think this is an Electron issue.

### Testcase Gist URL

_No response_

### Additional Information

_No response_

### LINKED ISSUE #46352: Transparent windows flickering and ghosting artifacts on MAS build
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

35.0.0 (_MAS build_)

### What operating system(s) are you using?

macOS

### Operating System Version

macOS Sequoia 15.3.2

### What arch are you using?

x64

### Last Known Working Electron version

34.0.0

### Expected Behavior

Transparent window displays canvas content the same as non-transparent window.

### Actual Behavior

Transparent window flickers and experiences visual ghosting artifacts.

### Testcase Gist URL

https://gist.github.com/clavin/d3b04ee957e81fd1e3209c123824d230

### Additional Information

**Only occurs on the MAS build.**

Video of Testcase Repro:
https://github.com/user-attachments/assets/18c2644a-e15a-4646-8ea6-89a7e904ad22

In the testcase there should only be one blue line at a time.

Historically, this bug originally was noticed after #41326 landed. That PR was later [reverted](https://github.com/electron/electron/pull/43033) and this bug disappeared. The PR recently [relanded](https://github.com/electron/electron/pull/44628) and the bug reappeared starting in Electron 35.

### PR DESCRIPTION
**Pull request by clavin**
#### Description of Change

Transparent windows suffer critical visual issues, including flickering and ghost artifacts. This PR makes the `views::Widget` for macOS windows support transparency when the window is initialized as transparent.

Fixes #45932.

#### Release Notes

Notes: Fixed flickering and ghosting artifacts in transparent windows on macOS.

### CODE REVIEW

File: shell/browser/native_window_mac.mm [hunk 1]
```diff
@@ -196,6 +196,9 @@ static bool FromV8(v8::Isolate* isolate,
   params.type = views::Widget::InitParams::TYPE_WINDOW;
   // Allow painting before shown, to be later disabled in ElectronNSWindow.
   params.headless_mode = true;
+  if (transparent()) {
```
Comment (ckerr) [inline shell/browser/native_window_mac.mm:199]: I'm coming into this with very little context so I could be wrong, but should this be `IsTranslucent()`?

The Views subclass handles it [like this](https://github.com/electron/electron/blob/main/shell/browser/native_window_views.cc#L280):

```
  // If a client frame, we need to draw our own shadows.
  if (IsTranslucent() || has_client_frame())
    params.opacity = InitParams::WindowOpacity::kTranslucent;
```

Comment (clavin) [reply shell/browser/native_window_mac.mm]: Good catch! Fixed in https://github.com/electron/electron/pull/46353/commits/d24929b2c1b22863bcf94474af2f2ce3af8ed580

**Review by VerteDinde — APPROVED** [review]
Thanks for fixing this, Calvin! 🙇‍♀️

**Review by ckerr — APPROVED** [review]
