### PR TITLE
Fix unresponsive app after fullscreen->normal state toggle (Windows)

### LINKED ISSUE #6036: Starting in fullscreen then toggling to windowed mode results in black screen (1.2.x)
- Electron version: 1.2.0, 1.2.1, 1.2.2
- Operating system: Windows

If you start an browser window in fullscreen and then attempt to toggle to windowed mode, the window will just black out and become unresponsive. Attempting to toggle back again still results in a black screen.

However, if you start the window in windowed mode and then toggle to fullscreen, it works as expected.

This maybe related to the fixes made to the fullscreen API in 1.2.x. It only occurs on Windows. It does not happen on 1.1.3.

You can reproduce easily with the `electron-api-demos` application and 1.2.2.
https://github.com/electron/electron-api-demos

Update `window-options` to set `fullscreen: true`
https://github.com/electron/electron-api-demos/blob/master/main.js#L22

```
var windowOptions = {
      width: 1080,
      minWidth: 680,
      height: 840,
      title: app.getName(),
      fullscreen: true
    }
```

Start the application and hit F11 to switch to windowed mode and you'll get a black screen.

### PR DESCRIPTION
**Pull request by dharders**
Fixes #6036

**Summary**

In **Windows only**, starting an app in the fullscreen state i.e. with the BrowserWindow options `{ fullscreen: true }` produces an unresponsive window after toggling to the normal window state. e.g. Pressing F11 or `setFullScreen(false)`. See issue #6036

The window visibility flag `WS_VISIBLE` is never set for the `GWL_STYLE` when we start in fullscreen mode. This fix simply detects the fullscreen->normal window state transition and checks if the window is visible (which it always should be). If it isn't, it sets the visibility to true. i.e. :

```cpp
void NativeWindowViews::SetFullScreen(bool fullscreen) {
   bool fullscreen_to_normal_detected = IsFullscreen() && !fullscreen;
   ...
   if (fullscreen_to_normal_detected && !IsVisible()) {
       LONG frame_style = ::GetWindowLong(GetAcceleratedWidget(), GWL_STYLE);
       frame_style |= WS_VISIBLE;
       ::SetWindowLong(GetAcceleratedWidget(), GWL_STYLE, frame_style);
   }
   ...
}
```

Includes tests (this branch passes, old behavior fails)

Fixes #6036

### CODE REVIEW

**Comment by dharders** [comment]
Hmmm, Travis is being funky. All tests passed, yet [Job #11868.1](https://travis-ci.org/electron/electron/jobs/238552497) build script still exited with 1.

Care to take a look anyone ?

/ping @kevinsawicki

**Comment by dharders** [comment]
Never mind, re-ran tests and all green now!

File: atom/browser/native_window_views.cc [hunk 1]
```diff
@@ -480,6 +480,8 @@ void NativeWindowViews::SetFullScreen(bool fullscreen) {
 
 #if defined(OS_WIN)
   // There is no native fullscreen state on Windows.
+  bool fullscreen_to_normal_detected = IsFullscreen() && !fullscreen;
```
Comment (kevinsawicki) [inline atom/browser/native_window_views.cc]: What do you think about calling this `leaving_fullscreen` instead?

File: atom/browser/native_window_views.cc [hunk 2]
```diff
@@ -505,6 +507,16 @@ void NativeWindowViews::SetFullScreen(bool fullscreen) {
...
   window_->SetFullscreen(fullscreen);
+
+  // If restoring from fullscreen and the window isn't visible, force visible,
+  // else a non-responsive window shell could be rendered.
+  // (this situation may arise when app starts with fullscreen: true)
+  // Note: the following must be after "window_->SetFullscreen(fullscreen);"
+  if (fullscreen_to_normal_detected && !IsVisible()) {
+    LONG frame_style = ::GetWindowLong(GetAcceleratedWidget(), GWL_STYLE);
+    frame_style |= WS_VISIBLE;
+    ::SetWindowLong(GetAcceleratedWidget(), GWL_STYLE, frame_style);
```
Comment (kevinsawicki) [inline atom/browser/native_window_views.cc]: This could just be:

```cpp
FlipWindowStyle(GetAcceleratedWidget(), true, WS_VISIBLE);
```

File: spec/api-browser-window-spec.js [hunk 3]
```diff
@@ -1949,6 +1949,41 @@ describe('BrowserWindow module', function () {
...
+    })
+
+    it('should keep window hidden if already in hidden state', function (done) {
+      w.webContents.once('did-finish-load', function () {
+        w.setFullScreen(false)
+        setTimeout(() => {
+          assert.equal(w.isVisible(), false)
+          assert.equal(w.isFullScreen(), false)
+          done()
+        }, 1000)
```
Comment (kevinsawicki) [inline spec/api-browser-window-spec.js]: Instead of a `setTimeout`, could this just wait for the `leave-full-screen` event and verify the state after that fires:

```js
w.once('leave-full-screen', () => {
  assert.equal(w.isVisible(), false)
  assert.equal(w.isFullScreen(), false)
  done()
})
w.setFullScreen(false)
```

**Comment by dharders** [comment]
Changes made, as requested.

ping @kevinsawicki

**Comment by kevinsawicki** [comment]
Thanks for fixing this @dharders 👍 :shipit: 🎉

**Comment by dharders** [comment]
FYI: Released in `"electron": "1.7.4 beta"`
