### PR TITLE
fix: Check minSize constraints before resizing

### LINKED ISSUE #13994: BrowserWindow minHeight can be less than BrowserWindow height
* Electron Version: 2.0.0
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: ?

**Expected Behavior**

We can not set manually a browserWindow height less than the minimum.

**Actual behavior**

We can set manually a browserWindow height less than the minimum.

**To Reproduce**

In Main Process:
```js
mainWindow = new BrowserWindow({width: 800, height: 600})
```
In Renderer Process:
```js
const remote = require('electron').remote;
const window = remote.getCurrentWindow();

window.setMinimumSize(800, 600);
debugger;
```
Now let's set manually (by resizing) window height to minimum and check in devtools:
```js
window.getSize()
```
and
```js
window.getMinimumSize()
```

**Screenshots**

screenshot

**Additional Information**

Also there is a difference between setting minHeight in constructor and in renderer process.
If we set it in constructor and our window has menu bar, window minHeight increases by menu bar height, but if we do it in renderer minHeight will not increase
```js
mainWindow = new BrowserWindow({width: 800, height: 600, minHeight: 600})
```
screenshot1

Also if we set menu to null:
```js
mainWindow.setMenu(null);
```
we have the expected behavior

screenshot2

**P.S.**
In all cases I resize BrowserWindow height to minimum manually

### PR DESCRIPTION
**Pull request by Kthulu120**
fixes #13994

Currently, when developers sets an initial Minimum Height or Minimum Width the expected functionality is that the windows size cannot be changed manually unless the `minHeight` or `minWidth` is changed. this PR sets enforcement of the the boundaries (if any)  defined by the developer.

##### Checklist
- [X] PR description included
- [x] `npm test` passes
- [x] tests are [changed or added]
- [x] relevant documentation is changed or added
- [X] PR title follows semantic [commit guidelines]

##### Release Notes
Notes: Snap to minimum size possible when `setSize` is called below size constraints

### CODE REVIEW

File: atom/browser/api/atom_api_top_level_window.cc [hunk 1]
```diff
@@ -398,8 +398,11 @@ gfx::Rect TopLevelWindow::GetContentBounds() {
 
 void TopLevelWindow::SetSize(int width, int height, mate::Arguments* args) {
   bool animate = false;
-  args->GetNext(&animate);
-  window_->SetSize(gfx::Size(width, height), animate);
+  gfx::Size size = window_->GetMinimumSize();
+  if ((size.height() <= height) | (size.width() <= width)) {
```
Comment (nornagon) [inline atom/browser/api/atom_api_top_level_window.cc]: it'd be better to snap to the smallest dimension rather than just fail to resize completely. e.g.

```cpp
size.SetToMax(gfx::Size(width, height));
```
