### PR TITLE
fix: crash when closing devtools after focus

### LINKED ISSUE #19985: Crash when closing devtools after focus
Happens on at least macOS and Linux on current master. Also reproducible on v6.0.4, v5.0.10, and v4.2.9.

Fiddle: https://gist.github.com/6872f27344c011f3565921761b6f8f5f

```js
      const w = new BrowserWindow({show: true})
      const devToolsFocused = emittedOnce(w.webContents, 'devtools-focused')
      w.webContents.openDevTools({ mode: 'detach' })
      w.webContents.inspectElement(100, 100)
      await devToolsFocused
      w.webContents.closeDevTools()
```

Stack trace:

```
Received signal 11 SEGV_MAPERR 000000000020
0   Electron Framework                  0x000000011da29da9 base::debug::CollectStackTrace(void**, unsigned long) + 9
1   Electron Framework                  0x000000011d8d4b53 base::debug::StackTrace::StackTrace() + 19
2   Electron Framework                  0x000000011da29c41 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 2385
3   libsystem_platform.dylib            0x00007fff66ab1b5d _sigtramp + 29
4   ???                                 0x00007f96d05b0f00 0x0 + 140285717450496
5   Electron Framework                  0x00000001192f37bf -[AtomInspectableWebContentsView windowDidBecomeMain:] + 63
6   CoreFoundation                      0x00007fff3a96137a __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
7   CoreFoundation                      0x00007fff3a9612f4 ___CFXRegistrationPost_block_invoke + 63
8   CoreFoundation                      0x00007fff3a96125e _CFXRegistrationPost + 404
9   CoreFoundation                      0x00007fff3a96968d ___CFXNotificationPost_block_invoke + 87
10  CoreFoundation                      0x00007fff3a8d276c -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1834
11  CoreFoundation                      0x00007fff3a8d1a17 _CFXNotificationPost + 840
12  Foundation                          0x00007fff3cb7506b -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
13  AppKit                              0x00007fff380c7a4a -[NSWindow _changeKeyAndMainLimitedOK:] + 972
14  AppKit                              0x00007fff380c7569 -[NSWindow _makeKeyRegardlessOfVisibility] + 76
15  AppKit                              0x00007fff380c7118 -[NSWindow makeKeyAndOrderFront:] + 40
16  Electron Framework                  0x00000001192f3260 -[AtomInspectableWebContentsView setIsDocked:activate:] + 512
17  Electron Framework                  0x00000001192f9600 electron::InspectableWebContentsImpl::SetIsDocked(base::RepeatingCallback<void (base::Value const*)> const&, bool) + 48
18  Electron Framework                  0x00000001192f8ffe electron::InspectableWebContentsImpl::LoadCompleted() + 430
19  Electron Framework                  0x0000000122e20c3d bool (anonymous namespace)::ParseAndHandle<>(base::RepeatingCallback<void ()> const&, base::RepeatingCallback<void (base::Value const*)> const&, base::ListValue const&) + 109
20  Electron Framework                  0x0000000122e20a6a DispatcherImpl::Dispatch(base::RepeatingCallback<void (base::Value const*)> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, base::ListValue const*) + 138
21  Electron Framework                  0x00000001192fabc5 electron::InspectableWebContentsImpl::HandleMessageFromDevToolsFrontend(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 517
22  Electron Framework                  0x00000001192fc3ef base::internal::Invoker<base::internal::BindState<void (electron::InspectableWebContentsImpl::*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), base::WeakPtr<electron::InspectableWebContentsImpl> >, void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::Run(base::internal::BindStateBase*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 191
23  Electron Framework                  0x000000011ccf01e9 non-virtual thunk to content::DevToolsFrontendHostImpl::DispatchEmbedderMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 105
24  Electron Framework                  0x000000011a2934e4 blink::mojom::DevToolsFrontendHostStubDispatch::Accept(blink::mojom::DevToolsFrontendHost*, mojo::Message*) + 388
25  Electron Framework                  0x000000011ddda238 mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*) + 1096
26  Electron Framework                  0x000000011ddd9ab6 mojo::FilterChain::Accept(mojo::Message*) + 150
27  Electron Framework                  0x000000011dddb858 mojo::InterfaceEndpointClient::HandleIncomingMessage(mojo::Message*) + 120
28  Electron Framework                  0x000000011e321e79 IPC::(anonymous namespace)::ChannelAssociatedGroupController::AcceptOnProxyThread(mojo::Message) + 761
29  Electron Framework                  0x000000011e3221ff base::internal::Invoker<base::internal::BindState<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message), scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController>, mojo::Message>, void ()>::RunOnce(base::internal::BindStateBase*) + 159
30  Electron Framework                  0x000000011d980943 base::TaskAnnotator::RunTask(char const*, base::PendingTask*) + 355
31  Electron Framework                  0x000000011d9a54ac base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*) + 652
32  Electron Framework                  0x000000011d9a5c0e base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoDelayedWork(base::TimeTicks*) + 158
33  Electron Framework                  0x000000011da5eec5 base::MessagePumpCFRunLoopBase::RunWork() + 85
34  Electron Framework                  0x000000011d8c9baa base::mac::CallWithEHFrame(void () block_pointer) + 10
35  Electron Framework                  0x000000011da5e68f base::MessagePumpCFRunLoopBase::RunWorkSource(void*) + 63
36  CoreFoundation                      0x00007fff3a91adbb __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
37  CoreFoundation                      0x00007fff3a91ad61 __CFRunLoopDoSource0 + 108
38  CoreFoundation                      0x00007fff3a8fec6b __CFRunLoopDoSources0 + 195
39  CoreFoundation                      0x00007fff3a8fe233 __CFRunLoopRun + 1196
40  CoreFoundation                      0x00007fff3a8fdb35 CFRunLoopRunSpecific + 459
41  HIToolbox                           0x00007fff39bdc96b RunCurrentEventLoopInMode + 292
42  HIToolbox                           0x00007fff39bdc6a5 ReceiveNextEventCommon + 603
43  HIToolbox                           0x00007fff39bdc436 _BlockUntilNextEventMatchingListInModeWithFilter + 64
44  AppKit                              0x00007fff37f76987 _DPSNextEvent + 965
45  AppKit                              0x00007fff37f7571f -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
46  AppKit                              0x00007fff37f6f83c -[NSApplication run] + 699
47  Electron Framework                  0x000000011da5ff4c base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) + 348
48  Electron Framework                  0x000000011da5dff8 base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) + 136
49  Electron Framework                  0x000000011d9a6232 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) + 242
50  Electron Framework                  0x000000011d950a56 base::RunLoop::Run() + 726
51  Electron Framework                  0x000000011c53044d content::BrowserMainLoop::RunMainMessageLoopParts() + 173
52  Electron Framework                  0x000000011c532026 content::BrowserMainRunnerImpl::Run() + 102
53  Electron Framework                  0x000000011c52cc7f content::BrowserMain(content::MainFunctionParams const&) + 287
54  Electron Framework                  0x000000011c3602a5 content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams&, bool) + 949
55  Electron Framework                  0x000000011c35feca content::ContentMainRunnerImpl::Run(bool) + 442
56  Electron Framework                  0x000000011fdb4bb3 service_manager::Main(service_manager::MainParams const&) + 3139
57  Electron Framework                  0x000000011a657ff4 content::ContentMain(content::ContentMainParams const&) + 68
58  Electron Framework                  0x00000001191c3854 AtomMain + 84
59  Electron                            0x000000010c55dc90 main + 240
60  libdyld.dylib                       0x00007fff668c63d5 start + 1
61  ???                                 0x0000000000000003 0x0 + 3
[end of stack trace]
```

### PR DESCRIPTION
**Pull request by codebytere**
#### Description of Change

Closes https://github.com/electron/electron/issues/19985.

Fixes an issue where closing devtools immediately after focus causes a crash. The crash happened because closing DevTools immediately destroys the DevTools WebContents while the main WebContents is still notifying observers for the focus event, which is prohibited.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: Fixed an issue where closing devtools immediately after focus caused a crash.

### CODE REVIEW

File: shell/browser/ui/inspectable_web_contents.cc [hunk 1]
```diff
@@ -441,9 +441,13 @@ void InspectableWebContents::CloseDevTools() {
     frontend_loaded_ = false;
     if (managed_devtools_web_contents_) {
       view_->CloseDevTools();
-      managed_devtools_web_contents_.reset();
+      embedder_message_dispatcher_.reset();
```
Comment (deepak1556) [inline shell/browser/ui/inspectable_web_contents.cc]: the dispatcher reset should be hoisted above outside the if statement so that it applies to external devtool contents as well.

File: shell/browser/api/electron_api_web_contents.cc [hunk 2]
```diff
@@ -2141,22 +2141,24 @@ void WebContents::DevToolsOpened() {
   v8::Isolate* isolate = JavascriptEnvironment::GetIsolate();
   v8::HandleScope handle_scope(isolate);
   DCHECK(inspectable_web_contents_);
-  DCHECK(inspectable_web_contents_->GetDevToolsWebContents());
-  auto handle = FromOrCreate(
-      isolate, inspectable_web_contents_->GetDevToolsWebContents());
+
+  content::WebContents* const dtwc = GetDevToolsWebContents();
+  if (!dtwc)
+    return;
```
Comment (deepak1556) [inline shell/browser/api/electron_api_web_contents.cc:2325]: the function gets called right after creating the webcontent on the same sequence so this should be always valid.

```suggestion
  DCHECK(GetDevToolsWebContents());
```

File: shell/browser/ui/inspectable_web_contents.cc [hunk 3]
```diff
@@ -441,9 +441,13 @@ void InspectableWebContents::CloseDevTools() {
...
+      content::GetUIThreadTaskRunner({})->PostTask(
+          FROM_HERE,
+          base::BindOnce(
+              [](std::unique_ptr<content::WebContents> web_contents) {},
+              std::move(managed_devtools_web_contents_)));
```
Comment (deepak1556) [inline shell/browser/ui/inspectable_web_contents.cc]: why make this async ? Isn't the issue that the dispatcher receives events even after the webcontent got destroyed and swapping the order of their would be good to cover that case ?

File: shell/browser/ui/inspectable_web_contents.cc [hunk 4]
```diff
@@ -533,6 +537,10 @@ void InspectableWebContents::LoadCompleted() {
   DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
 
   frontend_loaded_ = true;
+
+  if (!GetDevToolsWebContents())
+    return;
```
Comment (deepak1556) [inline shell/browser/ui/inspectable_web_contents.cc:560]: if the destruction of `managed_devtools_web_contents_` is sync then this shouldn't be needed.

Comment (deepak1556) [reply shell/browser/ui/inspectable_web_contents.cc:560]: Maybe not, what is order of the events in this case does the focus event comes in before the load completion ?

File: shell/browser/api/electron_api_web_contents.cc (hunk 2 above)
Comment (codebytere) [reply shell/browser/api/electron_api_web_contents.cc:2325]: Doesn't seem to be the case unfortunately - i added this because it got hit immediately in the repro

Comment (deepak1556) [reply shell/browser/api/electron_api_web_contents.cc:2325]: Open happens as part of load completed, based on your observation does it confirm that focus comes before load completed https://github.com/electron/electron/pull/47435#discussion_r2139406324 ?

File: shell/browser/ui/inspectable_web_contents.cc (hunk 3 above)
Comment (codebytere) [reply shell/browser/ui/inspectable_web_contents.cc]: Unfortunately no -

If `managed_devtools_web_contents_.reset()` is not async, despite moving `embedder_message_dispatcher_.reset()` up, we get this crash:
```
[47767:0613/111815.512592:FATAL:content/browser/web_contents/web_contents_impl.cc:1479] Check failed: !observers_.is_notifying_observers(). 
0   Electron Framework                  0x0000000123bbab64 base::debug::CollectStackTrace(base::span<void const*, 18446744073709551615ul, void const**>) + 28
1   Electron Framework                  0x0000000123bab060 base::debug::StackTrace::StackTrace(unsigned long) + 224
2   Electron Framework                  0x0000000123acdef8 logging::LogMessage::Flush() + 152
3   Electron Framework                  0x0000000123acdde0 logging::LogMessage::~LogMessage() + 36
4   Electron Framework                  0x0000000123ab906c logging::(anonymous namespace)::CheckLogMessage::~CheckLogMessage() + 76
5   Electron Framework                  0x0000000123ab8d34 logging::CheckNoreturnError::~CheckNoreturnError() + 16
6   Electron Framework                  0x0000000123ab8d44 logging::CheckNoreturnError::PCheck(char const*, base::Location const&) + 0
7   Electron Framework                  0x00000001225ed1d8 content::WebContentsImpl::~WebContentsImpl() + 3932
8   Electron Framework                  0x00000001225edad8 content::WebContentsImpl::~WebContentsImpl() + 12
9   Electron Framework                  0x000000011dfabefc electron::InspectableWebContents::CloseDevTools() + 100
10  Electron Framework                  0x000000011dee0668 electron::api::WebContents::CloseDevTools() + 96
11  Electron Framework                  0x000000011de038e0 base::RepeatingCallback<void (std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>> const&)>::Run(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>> const&) const & + 136
12  Electron Framework                  0x000000011de13488 gin_helper::Invoker<std::__Cr::integer_sequence<unsigned long, 0ul>, gin::Arguments*>::DispatchToCallback(base::RepeatingCallback<void (gin::Arguments*)>) + 228
13  Electron Framework                  0x000000011def6bf4 gin_helper::Dispatcher<void (electron::api::WebContents*)>::DispatchToCallbackImpl(gin::Arguments*) + 132
14  Electron Framework                  0x000000011def6af8 gin_helper::Dispatcher<void (electron::api::WebContents*)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 44
```

File: shell/browser/api/electron_api_web_contents.cc (hunk 2 above)
Comment (codebytere) [reply shell/browser/api/electron_api_web_contents.cc:2325]: Yes, it does!

File: shell/browser/ui/inspectable_web_contents.cc (hunk 4 above)
Comment (codebytere) [reply shell/browser/ui/inspectable_web_contents.cc:560]: Focus comes before load, yes!

Comment (deepak1556) [reply shell/browser/ui/inspectable_web_contents.cc:560]: Cool, lets move this check before `frontend_loaded_`

File: shell/browser/ui/inspectable_web_contents.cc (hunk 3 above)
Comment (deepak1556) [reply shell/browser/ui/inspectable_web_contents.cc]: `InspectableWebContents` is the observer of `managed_devtools_web_contents_` which gets set via https://github.com/electron/electron/blob/3c9b8475a2bc4a74fa7e5d37d494852167f0af1f/shell/browser/ui/inspectable_web_contents.cc#L431


We could remove the observer via `Observe(nullptr)` before `managed_devtools_web_contents_.reset()` to keep it sync, does that work ?

Comment (codebytere) [reply shell/browser/ui/inspectable_web_contents.cc]: It does not unfortunately (i tried this initially) - same error `FATAL:content/browser/web_contents/web_contents_impl.cc:1479] Check failed: !observers_.is_notifying_observers(). `

Comment (deepak1556) [reply shell/browser/ui/inspectable_web_contents.cc]: Oh interesting, I am just worried that async destruction can bring in reentrancy bugs from events. Lets make `managed_web_contents_ = nullptr` after moving it to the async task so that current sequence expects it is destroyed ?

```
if (managed_devtools_web_contents_) {
      Observe(nullptr);
      view_->CloseDevTools();
      content::GetUIThreadTaskRunner({})->PostTask(
          FROM_HERE,
          base::BindOnce(
              [](std::unique_ptr<content::WebContents> web_contents) {},
              std::move(managed_devtools_web_contents_)));
      managed_devtools_web_contents_ = nullptr;
```

Comment (codebytere) [reply shell/browser/ui/inspectable_web_contents.cc]: looks like this may cause the ci crashes - i'll look later

**Comment by jkleinsc** [comment]
@codebytere moving to WIP until you can get back to this.

**Review by deepak1556 — APPROVED** [review]
