### PR TITLE
fix: send guid with linux crashes

### LINKED ISSUE #24053: Linux crashReporter does not send "guid" attribute
### Issue Details

* **Electron Version:**
  * All up to and including `9-x-y`
* **Operating System:**
  * Linux
* **Last Known Working Electron version:**
  * Never 😢 

### Expected Behavior

When a crash occurs the `crashReporter` module should send the crash dump to your reporting URL along with some extra metadata including a `guid` attribute that is a UUID for the user sending the crash to you.

### Actual Behavior
No `guid` 😢

### PR DESCRIPTION
**Pull request by nornagon**
#### Description of Change
Fixes #24053.

This saves the crash reporter ID in a file in the crash dumps directory, which roughly matches how Crashpad works.

Chrome stores this as a browser preference, and also has some complicated logic around when they regenerate the token, as it's used for a lot of other metrics-related things. I don't believe it's important for Electron to replicate that logic, especially given that Chrome's Crashpad reporter doesn't seem to do so.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).
- [x] This is **NOT A BREAKING CHANGE**. Breaking changes may not be merged to master until 11-x-y is branched.

#### Release Notes

Notes: Fixed missing `guid` parameter in Linux crash reports.

### CODE REVIEW

**Comment by nornagon** [comment]
NB. not backporting to 8.x as that version predates the crashReporter refactor.

File: shell/browser/api/electron_api_crash_reporter.cc [hunk 1]
```diff
@@ -81,6 +85,40 @@ bool IsCrashReporterEnabled() {
...
+}
+
+std::string ReadClientId() {
+  base::ThreadRestrictions::ScopedAllowIO allow_io;
+  std::string client_id;
+  // "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".length == 36
+  if (!base::ReadFileToStringWithMaxSize(GetClientIdPath(), &client_id, 36) ||
+      client_id.size() != 36)
+    return std::string();
+  return client_id;
```
Comment (MarshallOfSound) [inline shell/browser/api/electron_api_crash_reporter.cc:102]: Do we have to check if it is a valid UUID or will breakpad take any 36 char string?

Comment (nornagon) [reply shell/browser/api/electron_api_crash_reporter.cc:102]: i don't think breakpad cares at all what this string is
