### PR TITLE
Fix popover items not updating

### LINKED ISSUE #9025: TouchBar PopOver items not updating when props are changed
This was reported to me through Slack, basically if you take this code.

```js
let counter = 1;
const button = new TouchBar.TouchBarButton({
  label: `${counter}`,
  click: () => {
    counter += 1;
    button.label = `${counter}`;
  }
})

let counter2 = 1;
const button2 = new TouchBar.TouchBarButton({
  label: `${counter2}`,
  click: () => {
    counter2 += 1;
    button2.label = `${counter2}`;
  }
})

const touchBar = new TouchBar([
  button2,
  new TouchBar.TouchBarPopover({
    label: 'Pop',
    items: new TouchBar([
      button,
    ])
  })
])

mainWindow.setTouchBar(touchBar)
```

You will see that tapping the first button updates the value correctly, but tapping the button inside the popover does not update the value.  This is due to us passing in the top level touch bar to our own `refreshTouchBarItems` method.

See https://github.com/electron/electron/blob/master/atom/browser/native_window_mac.mm#L382

This results in a new touchbaritem being created and updated instead of the existing touch bar item in the other touchbar.

My theoretical way of solving this issue is associating each touchbar item identifier with it's owning touchbar through a map in the `AtomTouchBar` class but regardless of how I tried to set that up, it failed miserably every time.  Mostly because each `NSTouchBarItemIdentifier*` can be associated with multiple touchbars.

I'm going to keep bashing my head against the wall trying to do this so if anyone can see an easier way please chime in 😄

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #9025 

Code to test it's working correctly

```js
let counter = 1;
const button = new TouchBar.TouchBarButton({
  label: `${counter}`,
  click: () => {
    counter += 1;
    button.label = `${counter}`;
  }
})

let counter2 = 1;
const button2 = new TouchBar.TouchBarButton({
  label: `${counter2}`,
  click: () => {
    counter2 += 1;
    button2.label = `${counter2}`;
  }
})

const touchBar = new TouchBar([
  button2,
  new TouchBar.TouchBarPopover({
    label: 'Pop',
    items: new TouchBar([
      button,
    ])
  }),
  new TouchBar.TouchBarPopover({
    label: 'Pop2',
    items: new TouchBar([
      button,
      button2
    ])
  })
])

mainWindow.setTouchBar(touchBar)
```

### CODE REVIEW

File: atom/browser/ui/cocoa/atom_touch_bar.mm [hunk 1]
```diff
@@ -113,19 +113,10 @@ - (NSTouchBarItem*)makeItemForIdentifier:(NSTouchBarItemIdentifier)identifier {
...
-  std::string item_type;
-  settings.Get("type", &item_type);
-
-  NSTouchBarItemIdentifier identifier = [self identifierFromID:item_id
-                                                          type:item_type];
-  if (!identifier) return;
-
+                         id:(NSTouchBarItemIdentifier)identifier
+                         withType:(std::string)item_type
+                         withSettings:(mate::PersistentDictionary)settings {
```
Comment (kevinsawicki) [inline atom/browser/ui/cocoa/atom_touch_bar.mm]: These should align on the `:` character

File: atom/browser/ui/cocoa/atom_touch_bar.mm [hunk 2]
```diff
@@ -135,7 +126,7 @@ - (void)refreshTouchBarItem:(NSTouchBar*)touchBar
     [self updateLabel:(NSCustomTouchBarItem*)item withSettings:settings];
   } else if (item_type == "colorpicker") {
     [self updateColorPicker:(NSColorPickerTouchBarItem*)item
-               withSettings:settings];
+              withSettings:settings];
```
Comment (kevinsawicki) [inline atom/browser/ui/cocoa/atom_touch_bar.mm]: Looks like this no longer aligns

File: atom/browser/ui/cocoa/atom_touch_bar.mm [hunk 3]
```diff
@@ -145,7 +136,30 @@ - (void)refreshTouchBarItem:(NSTouchBar*)touchBar
...
+  std::string item_type;
+  settings.Get("type", &item_type);
+
+  NSTouchBarItemIdentifier identifier = [self identifierFromID:item_id
+                                                          type:item_type];
+  if (!identifier) return;
+
+  std::vector<std::string> popover_ids;
+  if (settings.Get("_popover", &popover_ids)) {
+    for (size_t i = 0; i < popover_ids.size(); ++i) {
```
Comment (kevinsawicki) [inline atom/browser/ui/cocoa/atom_touch_bar.mm]: I think you could use `for (auto& popover_id : popover_ids)` here since it looks like `i` isn't needed.

File: lib/browser/api/touch-bar.js [hunk 4]
```diff
@@ -180,6 +180,10 @@ TouchBar.TouchBarPopover = class TouchBarPopover extends TouchBarItem {
     if (!(this.child instanceof TouchBar)) {
       this.child = new TouchBar(this.child)
     }
+    this.child.ordereredItems.forEach((item) => {
+      item._popover = item._popover || []
+      if (!item._popover.find(itemID => itemID === this.id)) item._popover.push(this.id)
```
Comment (kevinsawicki) [inline lib/browser/api/touch-bar.js]: Could you use a `Set` here so you don't need the `find` call?

**Comment by kevinsawicki** [comment]
> Code to test it's working correctly

Could we add an update call in the specs somewhere to make sure this new path is exercised, even though there is nothing to assert probably.

File: lib/browser/api/touch-bar.js (hunk 4 above)
Comment (MarshallOfSound) [inline lib/browser/api/touch-bar.js]: @kevinsawicki Will try this afternoon, but do `Set`'s get casted into `std::vector`'s automatically like normal arrays?

Comment (MarshallOfSound) [inline lib/browser/api/touch-bar.js]: Turns out a set can't be cast to a vector 👍

**Comment by MarshallOfSound** [comment]
Updated 👍

**Comment by kevinsawicki** [comment]
Thanks for the fix @MarshallOfSound 👍 🚢
