### PR TITLE
fix: setMaximizable to be true if window is resizable & maximizable

### LINKED ISSUE #13373: Calling setResizable(false) and then setResizable(true) changes maximizible state of window
* Electron Version: 2.0.2
* Operating System (Platform and Version): Win10 x64 version 1803
* Last known working Electron version: 1.9.0

**Expected Behavior**
Calling win.setResizable(false) and then win.setResizable(true) should return the window to it's original state. Specifically, it should not change the result of win.isMaximizable().

**Actual behavior**
Calling win.setResizable(false) and then win.setResizable(true) results in the window not being maximizable. The maximize button is disabled and win.isMaximizable returns false.

**To Reproduce**
In any electron application with a window that is resizable, call win.setResizable(false) and then win.setResizable(true). The window will now be impossible to maximize.

### PR DESCRIPTION
**Pull request by Kthulu120**
##### Description of Change

Fixes #13373

Currently on Windows when users have attempt to call setResizable(false) then setResizable(true) on Windows it disables the ability to be maximized again even though it is resizable. This PR adds this functionality.

##### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/electron/electron/blob/master/docs/development/pull-requests.md#commit-message-guidelines)

Notes: Allows the window to be maximization status to be restored to previous value upon being resizable again.

### CODE REVIEW

**Comment by codebytere** [comment]
Could you check into a test for this fix to ensure it doesn't regress?

**Comment by ckerr** [comment]
Is this broken in 3.0.x as well? If so, it ought to have a target/3-0-x label too

**Comment by Kthulu120** [comment]
This issue was reproduced in our official 3.0.0 version. Will be updating the `setResizable(true)` method to make the window maximizable by default, for now since its expected that a window that is now resizable also can be maximized.

**Comment by nornagon** [comment]
hmm, i think that `setResizable` shouldn’t change the value of `setMaximizable`, i.e. if you have a window and you say `win.setMaximizible(false); win.setResizable(true)` then the window should be resizable but not maximizable.

if you can get a resizable non-maximizable window by running `setResizable(true); setMaximizable(false)` then i think the reverse order should also work, i.e. `setMaximizable(false); setResizable(true)` should do the same thing

**Comment by Kthulu120** [comment]
@nornagon so my PR has changed a bit, its take the point you brought up into account. `setResizable` now  resizes a window and sets the maxmizability of window to stay with what the initial value was before calling `setResizable` and allows `isMaximizable()` to return the correct value.

File: spec/api-browser-window-spec.js [hunk 1]
```diff
@@ -2439,7 +2439,7 @@ describe('BrowserWindow module', () => {
       assert.deepStrictEqual(w.getSize(), [300, 200])
     })
 
-    describe('resizable state', () => {
+    describe.only('resizable state', () => {
```
Comment (codebytere) [inline spec/api-browser-window-spec.js]: forgot the `.only` here :)

**Comment by codebytere** [comment]
@Kthulu120 
```
not ok 254 BrowserWindow module window states (excluding Linux) maximizable state (Windows only) is set to false when resizable state is set to false
  AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
  + expected - actual
  
  - true
  + false
      at Context.it (C:\projects\src\electron\spec\api-browser-window-spec.js:2618:16)
      at callFn (C:\projects\src\electron\spec\node_modules\mocha\lib\runnable.js:372:21)
      at Test.Runnable.run (C:\projects\src\electron\spec\node_modules\mocha\lib\runnable.js:364:7)
      at Runner.runTest (C:\projects\src\electron\spec\node_modules\mocha\lib\runner.js:455:10)
      at C:\projects\src\electron\spec\node_modules\mocha\lib\runner.js:573:12
      at next (C:\projects\src\electron\spec\node_modules\mocha\lib\runner.js:369:14)
      at C:\projects\src\electron\spec\node_modules\mocha\lib\runner.js:379:7
      at next (C:\projects\src\electron\spec\node_modules\mocha\lib\runner.js:303:14)
      at Immediate._onImmediate (C:\projects\src\electron\spec\node_modules\mocha\lib\runner.js:347:5)
      at runCallback (timers.js:696:18)
      at tryOnImmediate (timers.js:667:5)
      at processImmediate (timers.js:649:5)
```

File: atom/browser/native_window_views.cc [hunk 2]
```diff
@@ -603,7 +603,8 @@ void NativeWindowViews::SetResizable(bool resizable) {
   if (has_frame() && thick_frame_)
     FlipWindowStyle(GetAcceleratedWidget(), resizable, WS_THICKFRAME);
 #endif
-
+  if (maximizable_)
+    SetMaximizable(maximizable_);
```
Comment (ckerr) [inline atom/browser/native_window_views.cc]: Should the inverse with `!maximizable_` be true too? ie should the `if (maximizable_)` conditional be removed, calling `SetMaximizable(maximizable_)` unconditionally?

Comment (Kthulu120) [reply atom/browser/native_window_views.cc]: Yea we can

**Comment by Kthulu120** [comment]
Currently there are options when addressing this PR, we can allow the status quo of `!resizable` implies `!maximizable` while fixing `resizable` toggling `maximizable` or we can change the behavior of `setResziable` which will cause developers to have to explicitly call `setMaximizable(false)`. This may be significant for some apps. But my suggestion is that in the end this provides more functionality that the developer controls that may allow for unforseen use cases. So I think the PR as is serves my suggestion as is, though I believe both options are right. If anyone has any objections feel free to comment.

**Comment by nornagon** [comment]
I agree that being allowed to make a window that's maximizable but not resizable is more flexibility, but I'm not clear on that being something that's useful? I'm struggling to think of a use case for that combination of flags. I'd support maintaining the current behaviour that `!resizable` implies `!maximizable`.
