### PR TITLE
fix: navigator.setAppBadge/clearAppBadge

### LINKED ISSUE #25141: Renderer crash after calling navigator.setAppBadge(42)
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9, 10
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  *  none

### Expected Behavior
Calling navigator.setAppBadge(42) should create an application badge on taskbar with the number 42.

### Actual Behavior
Render process crashed after calling navigator.setAppBadge(42) 

### To Reproduce
Start Electron, open console and try to execute navigator.setAppBadge(42) 

### Additional Information

https://web.dev/badging-api/

### PR DESCRIPTION
**Pull request by jkleinsc**
#### Description of Change

This PR fixes using `navigator.setAppBadge` and `navigator.clearAppBadge` in Electron.

While #25294 resolved a crash calling `navigator.setAppBadge`, this resolves #25141 by implementing the APIs in Electron.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/master/docs/development/testing.md)
- [x] relevant documentation is changed or added
- [x] [PR release notes](https://github.com/electron/clerk/blob/master/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/master/README.md#examples).

#### Release Notes

Notes: Fixed using `navigator.setAppBadge` and `navigator.clearAppBadge` in Electron.

### CODE REVIEW

File: shell/browser/badging/badge_manager.cc [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+        "|value| should not be zero when it is |number| (ClearBadge should be "
+        "called instead)!");
+    return;
+  }
+
+  base::Optional<int> value =
+      mojo_value->is_flag() ? base::nullopt
+                            : base::make_optional(mojo_value->get_number());
+
+  electron::Browser::Get()->SetBadgeCount(value);
```
Comment (zcbenz) [inline shell/browser/badging/badge_manager.cc:74]: Should `navigator.setAppBadge` only set badge for the source window instead of all windows in the app?

**Comment by zcbenz** [comment]
Also this PR has some overlap with https://github.com/electron/electron/pull/24051.

File: shell/browser/badging/badge_manager.cc (hunk 1 above)
Comment (jkleinsc) [reply shell/browser/badging/badge_manager.cc:74]: @zcbenz I'm not sure I understand what you are asking here? `navigator.setAppBadge` is not window specific but for the whole app, therefore, I just tied it into [app.setBadgeCount(count)](https://www.electronjs.org/docs/api/app#appsetbadgecountcount-linux-macos).  Am I missing something?

File: shell/browser/browser_win.cc [hunk 2]
```diff
@@ -603,8 +620,93 @@ v8::Local<v8::Promise> Browser::GetApplicationInfoForProtocol(
...
+    // Case 3.
+    badge_alt_string_ =
+        l10n_util::GetStringUTF8(IDS_BADGE_UNREAD_NOTIFICATIONS_UNSPECIFIED);
+    badge_count_ = 0;
+  }
+  return true;
+}
+
+void Browser::UpdateBadgeContents(HWND hwnd) {
+  auto badge = std::make_unique<SkBitmap>();
```
[the remark this answers is not in the document]
Comment (jkleinsc) [reply shell/browser/browser_win.cc]: makes sense.  I'll update

File: shell/browser/ui/win/taskbar_host.cc [hunk 3]
```diff
@@ -166,13 +166,12 @@ bool TaskbarHost::SetProgressBar(HWND window,
 }
 
 bool TaskbarHost::SetOverlayIcon(HWND window,
-                                 const gfx::Image& overlay,
+                                 SkBitmap* overlay,
```
[the remark this answers is not in the document]
Comment (jkleinsc) [reply shell/browser/ui/win/taskbar_host.cc]: makes sense.  I'll update

File: shell/browser/browser_win.cc [hunk 4]
```diff
@@ -603,8 +620,93 @@ v8::Local<v8::Promise> Browser::GetApplicationInfoForProtocol(
...
-bool Browser::SetBadgeCount(int count) {
-  return false;
+bool Browser::SetBadgeCount(base::Optional<int> count) {
+  if (count.has_value() && count.value() == 0) {
+    badge_content_ = base::nullopt;
+  } else {
+    badge_content_ = badging::BadgeManager::GetBadgeString(count);
+  }
+  badge_process_id = GetCurrentProcessId();
+  EnumWindows(WindowsEnumerationBadgeHandler,
```
[the remark this answers is not in the document]
Comment (jkleinsc) [reply shell/browser/browser_win.cc:630]: @zcbenz is there a path to get a HWND from electron::WindowList?  I followed what was done here https://github.com/electron/electron/blob/master/shell/browser/browser_win.cc#L46 because I needed a HWND.

[the remark this answers is not in the document]
Comment (zcbenz) [reply shell/browser/browser_win.cc:630]: You can get the HWND via `GetAcceleratedWidget()` method:

```c++
for (auto* window : WindowList::GetWindows()) {
  HWND hwnd = window->GetAcceleratedWidget();
}
```

I'll do a rewrite of `Browser::Focus` implementation, it is rather outdated code.

File: shell/browser/badging/badge_manager.cc (hunk 1 above)
Comment (zcbenz) [reply shell/browser/badging/badge_manager.cc:74]: On Windows the badge icons are set per-window, and this PR's implementation of `app.setBadgeCount` sets badge icon for all current windows to emulate the app-wide badge icons on macOS.

But to emulate app-wide badge icons we also need to automatically set badge icon for new windows, otherwise the new windows won't have the badges:

```js
app.setBadgeCount(1)
new BrowserWindow()  // window has no badge
```

So to correctly implement `app.setBadgeCount` on Windows we would end up with a rather complex system. And in future if we decide to add a per-window `BrowserWindow.setBadgeCount` API for Windows, this will get more complicated.

I think we don't really need to implement `app.setBadgeCount` on Windows, we can just add an `BrowserWindow.setBadgeCount` API and let users decide which one to use. This would also align with existing APIs, e.g. `app.dock.setIcon` and `BrowserWindow.setOverlayIcon`.

For the `navigator.setAppBadge` API, while it claims to set app badge, but it actually only works in PWA apps that run in standalone windows, so on Windows this API essentially sets badge for current window instead of all windows in the browser:
https://github.com/w3c/badging/blob/master/explainer.md#ux-treatment

Comment (jkleinsc) [reply shell/browser/badging/badge_manager.cc:74]: @zcbenz ok I understand what you are asking.  I can change the code to set the badge for all existing windows.  Since the main reason for this PR is to support navigator.setAppBadge/clearAppBadge I could just make that work in Windows and not add Windows support to app.get/setBadgeCount.  Another option would be to document in our documentation that on Windows app.setBadgeCount will only affect existing windows.  What do you think?

Comment (zcbenz) [reply shell/browser/badging/badge_manager.cc:74]: I prefer not adding `app.get/setBadgeCount` APIs for Windows, setting same badge for all windows is a weird behavior and I don't think there is any app doing that.

Comment (jkleinsc) [reply shell/browser/badging/badge_manager.cc:77]: @zcbenz I removed the changes to app.get/setBadgeCount for Windows, so this PR is now just a fix to make navigator.setAppBadge/clearAppBadge work in Electron.

File: shell/browser/browser_win.cc [hunk 5]
```diff
@@ -584,8 +589,120 @@ v8::Local<v8::Promise> Browser::GetApplicationInfoForProtocol(
...
+    badge_count_ = 0;
+  }
+  for (auto* window : WindowList::GetWindows()) {
+    // Update all the windows
+    HWND hwnd = window->GetAcceleratedWidget();
+    DWORD process_id = 0;
+
+    GetWindowThreadProcessId(hwnd, &process_id);
+    // On Windows set the badge on the first window found for this process.
+    if (process_id == GetCurrentProcessId()) {
```
Comment (zcbenz) [inline shell/browser/browser_win.cc:647]: There is no need to get and compare `process_id`, `WindowList` only returns windows for current app.

File: shell/browser/browser.h [hunk 6]
```diff
@@ -107,10 +108,21 @@ class Browser : public WindowListObserver {
...
+#else
+  bool SetBadgeCount(base::Optional<int> count);
   int GetBadgeCount();
+#endif
 
 #if defined(OS_WIN)
+  // Used by WindowsEnumerationBadgeHandler to get the window to set badge for
+  DWORD badge_process_id;
+
+  void UpdateBadgeContents(HWND hwnd);
```
Comment (zcbenz) [inline shell/browser/browser.h:124]: This line can be removed.

File: shell/browser/browser.h [hunk 7]
```diff
@@ -364,6 +376,15 @@ class Browser : public WindowListObserver {
   base::DictionaryValue about_panel_options_;
 #endif
 
+#if defined(OS_WIN)
+  void UpdateBadgeContents(HWND hwnd,
+                           const base::Optional<std::string> badge_content,
+                           const std::string badge_alt_string);
```
Comment (zcbenz) [inline shell/browser/browser.h:382]: Should use const reference `const std::string&`.

File: shell/browser/browser.h [hunk 8]
```diff
@@ -364,6 +376,15 @@ class Browser : public WindowListObserver {
   base::DictionaryValue about_panel_options_;
 #endif
 
+#if defined(OS_WIN)
+  void UpdateBadgeContents(HWND hwnd,
+                           const base::Optional<std::string> badge_content,
```
Comment (zcbenz) [inline shell/browser/browser.h:381]: Should use const reference `const base::Optional<std::string>&`.

File: shell/browser/browser_win.cc [hunk 9]
```diff
@@ -584,8 +589,120 @@ v8::Local<v8::Promise> Browser::GetApplicationInfoForProtocol(
...
+    return badge_count_;
+  } else {
+    return 0;
+  }
+}
+
+bool Browser::SetBadgeCount(base::Optional<int> count,
+                            base::Optional<bool> shouldSetBadge) {
+  if (!shouldSetBadge.has_value() || !shouldSetBadge.value()) {
+    // app.setBadgeCount(count) is not support on Windows, but
```
Comment (zcbenz) [inline shell/browser/browser_win.cc:603]: I think it is fine to make `app.setBadgeCount` silently work on Windows, as long as it is an undocumented thing we are free to do whatever we want. So there is no need to add a special `shouldSetBadge` for Windows.

File: docs/api/app.md [hunk 10]
```diff
@@ -1188,7 +1188,7 @@ On macOS, it shows on the dock icon. On Linux, it only works for Unity launcher.
 **Note:** Unity launcher requires the existence of a `.desktop` file to work,
 for more information please read [Desktop Environment Integration][unity-requirement].
 
-### `app.getBadgeCount()` _Linux_ _macOS_
+### `app.getBadgeCount()`
```
Comment (zcbenz) [inline docs/api/app.md:1191]: This change should be reverted.

**Review by zcbenz — APPROVED** [review]
