### PR TITLE
fix: modify file extension generation on Windows

### LINKED ISSUE #34450: [Bug]: File extension is missing on Windows
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 - 10.0.19042

### What arch are you using?

x64

### Last Known Working Electron version

_No response_

### Expected Behavior

When saving a file, the file type should be correctly defined and the filename should include the extension on the operating system so that the correct program is launch when double-clicking it

### Actual Behavior

The extension is missing.

image

Here is the code we are using:

```js
  const a = document.createElement('a')
  a.type = getMimeType(name)
  a.href = `data:${a.type || 'text/plain'};base64,${base64}`
  a.download = name
  a.click()
  ```

I'll try to add a fiddle later

### Testcase Gist URL

https://gist.github.com/c07b1efe128ba059d0fad7ebeb7a94cb

### Additional Information

This is reproducible only on Windows

### PR DESCRIPTION
**Pull request by mlaurencin**
#### Description of Change

Closes #34450

Previously when saving a file on Windows, the file type would not be defined based on the extension of the file. (The linked issue also mentions that the file name should include the extension, but I could not replicate this on non-Electron applications). The file dialog will now properly display the file type and the saved file will include the extension.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [ ] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [ ] relevant documentation is changed or added

#### Release Notes

Notes: None

### CODE REVIEW

File: shell/browser/electron_download_manager_delegate.cc [hunk 1]
```diff
@@ -30,6 +30,15 @@
 #include "shell/common/gin_converters/file_path_converter.h"
 #include "shell/common/options_switches.h"
 
+#if BUILDFLAG(IS_WIN)
+#include "base/i18n/case_conversion.h"
+#include "base/win/registry.h"
+#include "ui/base/l10n/l10n_util.h"
+
+#define IDS_APP_SAVEAS_ALL_FILES 35936
+#define IDS_APP_SAVEAS_EXTENSION_FORMAT 35937
```
Comment (codebytere) [inline shell/browser/electron_download_manager_delegate.cc:39]: These both come from `ui/strings/grit/ui_strings.h` - we can just include that since we shouldn't hardcode grit strings :)

**Review by codebytere — COMMENTED** [review]
It looks like there's still a bit of strange behavior here when showing extension and switching between potential save file types 🤔

If we open the html file from [this gist](https://gist.github.com/c07b1efe128ba059d0fad7ebeb7a94cb) in Edge on Windows, right click, and choose "Save Link As" - we get the following popup:

<details>
Screen Shot 2022-06-28 at 11 09 00 AM
</details>

The title of the item doesn't change if we then switch the file type to All Files:

<details>
Screen Shot 2022-06-28 at 11 11 24 AM
</details>

I would expect that if ran the fiddle and clicked the "download" link, we would see a similar popup. At first, the behavior matches:

<details>
Screen Shot 2022-06-28 at 11 12 11 AM
</details>

However, if we switch the file save type to all files, the title logic gets a little confused:

<details>
Screen Shot 2022-06-28 at 11 12 56 AM
</details>

and then if we switch back to `PDF File`, disappears altogether:

<details>
Screen Shot 2022-06-28 at 11 13 45 AM
</details>

I'd ideally like to see these match for a more intuitive user experience, and the i think we can do a final review for this :)

**Review by codebytere — CHANGES_REQUESTED** [review]
(oops see above, meant to req changes!)

File: shell/browser/electron_download_manager_delegate.h [hunk 2]
```diff
@@ -5,10 +5,15 @@
 #ifndef ELECTRON_SHELL_BROWSER_ELECTRON_DOWNLOAD_MANAGER_DELEGATE_H_
 #define ELECTRON_SHELL_BROWSER_ELECTRON_DOWNLOAD_MANAGER_DELEGATE_H_
 
+#include <vector>
```
Comment (ckerr) [inline shell/browser/electron_download_manager_delegate.h:8]: _nit_

```suggestion
#if BUILDFLAG(IS_WIN)
#include <vector>
#endif  // BUILDFLAG(IS_WIN)
```

File: shell/browser/electron_download_manager_delegate.cc [hunk 3]
```diff
@@ -130,6 +245,29 @@ void ElectronDownloadManagerDelegate::OnDownloadPathGenerated(
     const bool offscreen = !web_preferences || web_preferences->IsOffscreen();
     settings.force_detached = offscreen;
 
+#if BUILDFLAG(IS_WIN)
+    auto extension = settings.default_path.FinalExtension();
+    if (!extension.empty() && settings.filters.empty()) {
+      extension.erase(extension.begin());
+
+      std::u16string ext(extension.begin(), extension.end());
```
[the remark this answers is not in the document]
Comment (mlaurencin) [reply shell/browser/electron_download_manager_delegate.cc:253]: Yes, the additions of the constructor and below were to handle the `std::string` to `std:::u16string` conversions (and vice versa). If there is a cleaner or better way to do this, I would definitely be up for reimplementing it.

[the remark this answers is not in the document]
Comment (zcbenz) [reply shell/browser/electron_download_manager_delegate.cc:253]: You can use `base::WideToUTF16` to convert `wstring` to `u16string`.

File: shell/browser/electron_download_manager_delegate.cc [hunk 4]
```diff
@@ -130,6 +245,29 @@ void ElectronDownloadManagerDelegate::OnDownloadPathGenerated(
...
+      const std::vector<std::u16string> file_ext{u"." + ext};
+      std::vector<ui::FileFilterSpec> filter_spec =
+          FormatFilterForExtensions(file_ext, {u""}, true, true);
+
+      std::string extension_spec_conv(filter_spec[0].extension_spec.begin(),
```
Comment (zcbenz) [inline shell/browser/electron_download_manager_delegate.cc:258]: And `base::UTF16ToUTF8` to convert `u16string` to `string`.

For unicode strings one character can be stored in multiple bytes, so for the same text `std::string` and `std::u16string` can have different lengths.

File: shell/browser/electron_download_manager_delegate.h [hunk 5]
```diff
@@ -60,6 +67,17 @@ class ElectronDownloadManagerDelegate
 
   content::DownloadManager* download_manager_;
   base::WeakPtrFactory<ElectronDownloadManagerDelegate> weak_ptr_factory_{this};
+
+#if BUILDFLAG(IS_WIN)
+  // Copied from ui/shell_dialogs/select_file_dialog_win.h
+  bool GetRegistryDescriptionFromExtension(const std::u16string& file_ext,
+                                           std::u16string* reg_description);
+  std::vector<ui::FileFilterSpec> FormatFilterForExtensions(
```
Comment (zcbenz) [inline shell/browser/electron_download_manager_delegate.h:75]: For utility functions that are only used inside one file, they should usually be put in the anonymous namespace in the `.cc` file. For example the original `FormatFilterForExtensions` was in the anonymous namespace of the `select_file_dialog_win.cc` instead of being a method of `SelectFileDialogImpl`.

File: shell/browser/electron_download_manager_delegate.cc [hunk 6]
```diff
@@ -130,6 +245,29 @@ void ElectronDownloadManagerDelegate::OnDownloadPathGenerated(
     const bool offscreen = !web_preferences || web_preferences->IsOffscreen();
     settings.force_detached = offscreen;
 
+#if BUILDFLAG(IS_WIN)
+    auto extension = settings.default_path.FinalExtension();
```
Comment (zcbenz) [inline shell/browser/electron_download_manager_delegate.cc:249]: Since there are type conversions involved, explicitly declaring its type `std::wstring` will have better code readability than `auto`.

File: shell/browser/electron_download_manager_delegate.cc [hunk 7]
```diff
@@ -130,6 +245,29 @@ void ElectronDownloadManagerDelegate::OnDownloadPathGenerated(
...
+    if (!extension.empty() && settings.filters.empty()) {
+      extension.erase(extension.begin());
```
Comment (zcbenz) [inline shell/browser/electron_download_manager_delegate.cc:251]: This seems unnecessary since the `.` is added back later in `file_ext{u"." + ext}`.

File: shell/browser/electron_download_manager_delegate.h (hunk 5 above)
Comment (mlaurencin) [reply shell/browser/electron_download_manager_delegate.h:75]: I see! That makes sense. Thank you

File: shell/browser/electron_download_manager_delegate.cc [hunk 8]
```diff
@@ -130,6 +243,25 @@ void ElectronDownloadManagerDelegate::OnDownloadPathGenerated(
...
+      std::vector<ui::FileFilterSpec> filter_spec = FormatFilterForExtensions(
+          {base::WideToUTF16(extension)}, {u""}, true, true);
+
+      std::string extension_spec_conv(
+          base::UTF16ToUTF8(filter_spec[0].extension_spec));
+      const std::vector<std::string> filter{extension_spec_conv};
+      std::string description_conv(
+          base::UTF16ToUTF8(filter_spec[0].description));
+
+      settings.filters.emplace_back(std::make_pair(description_conv, filter));
```
Comment (zcbenz) [inline shell/browser/electron_download_manager_delegate.cc:258]: The extension name generated by `FormatFilterForExtensions` has `.` prefix, which should be removed before passing to `file_dialog::ShowSaveDialog`.

File: shell/browser/electron_download_manager_delegate.cc [hunk 9]
```diff
@@ -62,6 +70,111 @@ base::FilePath CreateDownloadPath(const GURL& url,
...
+// view. The purpose of the filter is to show only files of a particular type in
+// a Windows Save/Open dialog box. The resulting filter is returned. The filter
+// created here are:
+//   1. only files that have 'file_ext' as their extension
+//   2. all files (only added if 'include_all_files' is true)
+// If a description is not provided for a file extension, it will be retrieved
+// from the registry. If the file extension does not exist in the registry, a
+// default description will be created (e.g. "qqq" yields "QQQ File").
+// Copied from ui/shell_dialogs/select_file_dialog_win.cc
+std::vector<ui::FileFilterSpec> FormatFilterForExtensions(
```
[the remark this answers is not in the document]
Comment (mlaurencin) [reply shell/browser/electron_download_manager_delegate.cc:108]: Yes, I agree that having the type conversions as there are right now does not really make sense. Regarding the standard of extension names, are you referring to having the prefix `.` and All Files being denoted by `*.*`, or are there other standards I am missing?

[the remark this answers is not in the document]
Comment (zcbenz) [reply shell/browser/electron_download_manager_delegate.cc:108]: > Regarding the standard of extension names, are you referring to having the prefix `.` and All Files being denoted by `*.*`

Yes.

File: shell/browser/electron_download_manager_delegate.cc [hunk 10]
```diff
@@ -130,6 +244,18 @@ void ElectronDownloadManagerDelegate::OnDownloadPathGenerated(
...
+#if BUILDFLAG(IS_WIN)
+    std::wstring extension = settings.default_path.FinalExtension();
+    if (!extension.empty() && settings.filters.empty()) {
+      file_dialog::Filters filter_spec = FormatFilterForExtensions(
+          {base::WideToUTF8(extension)}, {""}, true, true);
+
+      for (file_dialog::Filter filter : filter_spec) {
+        settings.filters.emplace_back(filter);
+      }
+    }
```
Comment (ckerr) [inline shell/browser/electron_download_manager_delegate.cc:256]: - _(nit)_ we should check `settings.filters.empty()` first because if that test is `true` we can avoid creating the `extension` temporary

- We can avoid a lot of `std::vector<Filter>` temporaries by not iterating through `filter_spec` and by not emplacing-back by copy. In this situationsince `filter_spec` and `settings.filters` are the same type and we know the latter is empty, there's an easy solution; eliminate `filter_spec` temporary and directly assign `settings.filters` with the return value of `FormatFilterForExtensions()`:

```suggestion
      if (settings.filters.empty()) {
        const std::wstring extension = settings.default_path.FinalExtension();
        if (!extension.empty()) {
          settings.filters = FormatFilterForExtensions(
              {base::WideToUTF8(extension)}, {""}, true, true);
        }
      }
```

File: shell/browser/electron_download_manager_delegate.cc [hunk 11]
```diff
@@ -62,6 +70,112 @@ base::FilePath CreateDownloadPath(const GURL& url,
...
+// Get the file type description from the registry. This will be "Text Document"
+// for .txt files, "JPEG Image" for .jpg files, etc. If the registry doesn't
+// have an entry for the file type, we return false, true if the description was
+// found. 'file_ext' must be in form ".txt".
+// Modified from ui/shell_dialogs/select_file_dialog_win.cc
+bool GetRegistryDescriptionFromExtension(const std::string& file_ext,
+                                         std::string* reg_description) {
+  DCHECK(reg_description);
+  base::win::RegKey reg_ext(
+      HKEY_CLASSES_ROOT, base::as_wcstr(base::UTF8ToUTF16(file_ext)), KEY_READ);
```
Comment (zcbenz) [inline shell/browser/electron_download_manager_delegate.cc:83]: You can use `UTF8ToWide`.

File: shell/browser/electron_download_manager_delegate.h [hunk 12]
```diff
@@ -5,6 +5,8 @@
 #ifndef ELECTRON_SHELL_BROWSER_ELECTRON_DOWNLOAD_MANAGER_DELEGATE_H_
 #define ELECTRON_SHELL_BROWSER_ELECTRON_DOWNLOAD_MANAGER_DELEGATE_H_
 
+#include <vector>
```
Comment (zcbenz) [inline shell/browser/electron_download_manager_delegate.h:8]: This line can be removed.

**Review by zcbenz — APPROVED** [review]

**Review by ckerr — APPROVED** [review]

**Review by codebytere — APPROVED** [review]
🥳
