### PR TITLE
Fix flash context menu

### LINKED ISSUE #10464: (v1.8.x) Context menu of flash object broken
Hello folks,

Doing a right click on a flash object opens up a context menu as expected, but clicking on the entries has no effect. Can't change quality of a flash game for example.

It works fine in v1.7.x.
The attached .zip contains the newest pepper based flash plugin, a main.js and a package.json that might help you reproduce the issue.

System:
Win7 x64
Electron v1.8.x
Pepper Flash Plugin v26.0.0.151 x64
[flash-context-menu.zip](https://github.com/electron/electron/files/1285786/flash-context-menu.zip)

### PR DESCRIPTION
**Pull request by brenca**
Fixes #10464 

The pepper flash menu seems to send the commands to the plugin when the context menu is closed. Currently, we instantly send the context menu close event when the flash context menu is opened, which causes the menu to not work properly.

### CODE REVIEW

File: atom/browser/api/atom_api_web_contents.cc [hunk 1]
```diff
@@ -653,8 +653,10 @@ void WebContents::RendererResponsive(content::WebContents* source) {
 
 bool WebContents::HandleContextMenu(const content::ContextMenuParams& params) {
   if (params.custom_context.is_pepper_menu) {
-    Emit("pepper-context-menu", std::make_pair(params, web_contents()));
-    web_contents()->NotifyContextMenuClosed(params.custom_context);
+    Emit("pepper-context-menu",
+      std::make_pair(params, web_contents()),
+      base::Bind(&content::WebContents::NotifyContextMenuClosed,
+        base::Unretained(web_contents()), params.custom_context));
```
Comment (deepak1556) [inline atom/browser/api/atom_api_web_contents.cc]: Style fix: arguments can be aligned.

```
Emit("pepper-context-menu", std::make_pair(params, web_contents()),
     base::Bind(&content::WebContents::NotifyContextMenuClosed,
                base::Unretained(web_contents()), params.custom_context));
```

File: lib/browser/api/menu.js [hunk 2]
```diff
@@ -39,6 +39,9 @@ Menu.prototype._init = function () {
         const found = this.groupsMap[id].find(item => item.checked) || null
         if (!found) v8Util.setHiddenValue(this.groupsMap[id][0], 'checked', true)
       }
+    },
+    menuClosed: () => {
+      this.emit('closed')
```
Comment (deepak1556) [inline lib/browser/api/menu.js]: Should this event be documented ?

Comment (brenca) [reply lib/browser/api/menu.js]: There are no events on the Menu object currently, so that's a good question. We could add other events tho, that would make this one a bit more useful too.

Comment (brenca) [reply lib/browser/api/menu.js]: I've added the documentation for the event anyway :)

**Comment by brenca** [comment]
@ckerr I'm not sure that adding a test for the latter would be easy, we would need
 - some flash content to check the menu with
 - the flash player plugins for all the platforms (what version? always the latest? what if the latest flash plugin is broken and not the menu?)
 - simulate clicks, but that's not that hard

**Comment by brenca** [comment]
@ckerr I've added the test for the event, but I had to add a `Cancel` call on the menu when the user calls `closePopup`, because otherwise the `MenuClosed` callback wouldn't get called by chromium.

File: atom/browser/api/atom_api_menu_views.cc [hunk 3]
```diff
@@ -60,6 +60,8 @@ void MenuViews::PopupAt(Window* window, int x, int y, int positioning_item) {
 }
 
 void MenuViews::ClosePopupAt(int32_t window_id) {
+  if (menu_runners_[window_id])
+    menu_runners_[window_id]->Cancel();
```
Comment (deepak1556) [inline atom/browser/api/atom_api_menu_views.cc]: Correct me if I am wrong, doesn't the destruction of the menu runner call [Cancel](https://cs.chromium.org/chromium/src/ui/views/controls/menu/menu_runner_impl.cc?dr=CSs&l=49) eventually.

File: spec/api-menu-spec.js [hunk 4]
```diff
@@ -288,6 +288,37 @@ describe('Menu module', () => {
...
+        done()
+      })
+    })
+
+    afterEach(() => {
+      return closeWindow(w).then(() => { w = null })
+    })
+
+    it('emits closed event', (done) => {
+      menu.popup(w, {x: 100, y: 100, async: true})
```
Comment (deepak1556) [inline spec/api-menu-spec.js]: `async` option is removed with chromium 61. Also worth removing the other reference in this file that was missed out in https://github.com/electron/electron/commit/4e859b47185cb441b210e4bd85c10644088e4106#diff-0f899d7673156733456b3d561fe6c8fe

File: atom/browser/api/atom_api_menu_views.cc (hunk 3 above)
Comment (brenca) [reply atom/browser/api/atom_api_menu_views.cc]: I'm not saying you are wrong, but the test does fail if I remove this `Cancel` call, so I guess that even if it's called, the delegate is not informed about it.

File: spec/api-menu-spec.js (hunk 4 above)
Comment (brenca) [reply spec/api-menu-spec.js]: Done!

File: atom/browser/api/atom_api_menu_views.cc (hunk 3 above)
Comment (deepak1556) [reply atom/browser/api/atom_api_menu_views.cc]: @zcbenz any thoughts on this ? I am not familiar with this code path.

**Comment by zcbenz** [comment]
The failing test is not related to this PR, I'm merging anyway.

**Comment by bpasero** [comment]
@brenca would this `closed` event be a fix for https://github.com/electron/electron/issues/9441 ?

**Comment by zcbenz** [comment]
@bpasero I would say it is only a partial fix, it is not possible to tell which `closed` event matches which `popup` call when you are showing the same menu for multiple windows.

But implementing #9441 should be rather easy though, I'll take care of it next week if no one is looking into it.

**Comment by bpasero** [comment]
@zcbenz thanks, that would certainly make our life easier once we adopt newer Electron in VS Code 👍
