### PR TITLE
Correct the default of allowRunningInsecureContent as per docs

### LINKED ISSUE #12555: webSecurity false no longer implies allowRunningInsecureContent
* Electron version: 2.0.0-beta.7
* Operating system: Windows 7

### Expected behavior

`new BrowserWindow({webPreferences:{webSecurity:false}})` should not show mixed-content errors. It should show warnings and continue to load the content.

### Actual behavior

mixed-content errors are shown unless *allowRunningInsecureContent* is specified which is contrary to the documentation:

> Disabling webSecurity will disable the same-origin policy and set allowRunningInsecureContent property to true. 

This was working as expected in 1.8.2

### How to reproduce

Open a new BrowserWindow as above and load a page via `https` that contains elements using `http`.

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #12555

### CODE REVIEW

File: atom/browser/web_contents_preferences.cc [hunk 1]
```diff
@@ -64,8 +64,14 @@ WebContentsPreferences::WebContentsPreferences(
   SetDefaultBoolIfUndefined("images", true);
   SetDefaultBoolIfUndefined("textAreasAreResizable", true);
   SetDefaultBoolIfUndefined("webgl", true);
-  SetDefaultBoolIfUndefined("webSecurity", true);
-  SetDefaultBoolIfUndefined("allowRunningInsecureContent", false);
+  bool webSecurity = true;
+  SetDefaultBoolIfUndefined("webSecurity", webSecurity);
+  // If webSecurity was explicity set to false, let's inherit that into insureContent
```
Comment (poiru) [inline atom/browser/web_contents_preferences.cc]: Typo `insure`

**Comment by codebytere** [comment]
Failing on 
```
../../atom/browser/web_contents_preferences.cc:71:23: error: no member named 'GetBoolean' in 'mate::Dictionary'
  if (web_preferences.GetBoolean("webSecurity", &webSecurity) && !webSecurity) {
      ~~~~~~~~~~~~~~~ ^
```
