### PR TITLE
test: rerun failed tests individually

### LINKED ISSUE #48291: Flaky or broken test: "webContents module navigationHistory navigationHistory.restore({ index, entries }) API should restore navigation history with PageState"
### Confirmation

- [x] I am a [maintainer](https://github.com/orgs/electron/people) of the Electron project. (If not, please create a [different issue type](https://github.com/electron/electron/issues/new/).)

### Description

This issue is present in main. If you look at the CI runs in the [recent commit history there](https://github.com/electron/electron/commits/main/), nearly all of them are red.  They frequently fail in a test that was added a few months back in https://github.com/electron/electron/pull/45433

For example, some recent commits to main:

- https://github.com/electron/electron/commit/940ebb6c7a156fb7e5202ac94070631f9bedc671 failed in [this CI run](https://github.com/electron/electron/actions/runs/17562208617/job/49883372110)
  > 2025-09-08T20:25:09.4475470Z not ok 736 webContents module navigationHistory navigationHistory.restore({ index, entries }) API should restore navigation history with PageState
2025-09-08T20:25:09.4578000Z   expected 'value' to equal 'Hi!'
2025-09-08T20:25:09.4683990Z   AssertionError: expected 'value' to equal 'Hi!'
2025-09-08T20:25:09.4790090Z       at Context.<anonymous> (electron/spec/api-web-contents-spec.ts:922:30)

- https://github.com/electron/electron/commit/828fd59a72e673acf03f878b4f488a40fca46dfe failed in [this CI run](https://productionresultssa16.blob.core.windows.net/actions-results/1f3bc9d8-04fb-49cc-91a1-a1a36c54acbf/workflow-job-run-08009b6c-6b29-5450-b39f-c3aaa49a769d/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-09-10T14%3A47%3A41Z&sig=nHAq3nMkPvEr4L8ky6rirDAVec4awCsuTMtt1B9LX60%3D&ske=2025-09-11T01%3A17%3A56Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-09-10T13%3A17%3A56Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-09-10T14%3A37%3A36Z&sv=2025-05-05)
  > 2025-08-29T18:04:50.3521810Z not ok 734 webContents module navigationHistory navigationHistory.restore({ index, entries }) API should restore navigation history with PageState
2025-08-29T18:04:50.3624510Z   expected 'value' to equal 'Hi!'
2025-08-29T18:04:50.3726070Z   AssertionError: expected 'value' to equal 'Hi!'
2025-08-29T18:04:50.3827090Z       at Context.<anonymous> (electron/spec/api-web-contents-spec.ts:922:30)

- https://github.com/electron/electron/commit/e8928409755245eb706c55cb6180a5bf0d9d4fcd failed in [thise CI run](https://github.com/electron/electron/actions/runs/17326738528/job/49195928776)
  > 2025-08-29T15:34:05.2459710Z not ok 736 webContents module navigationHistory navigationHistory.restore({ index, entries }) API should restore navigation history with PageState
2025-08-29T15:34:05.2626310Z   expected 'value' to equal 'Hi!'
2025-08-29T15:34:05.2759310Z   AssertionError: expected 'value' to equal 'Hi!'
2025-08-29T15:34:05.2888660Z       at Context.<anonymous> (electron/spec/api-web-contents-spec.ts:922:30)

- https://github.com/electron/electron/commit/7373173e44d25c90a5127ad5c7b49295c12117a7 failed in [this CI run](https://github.com/electron/electron/actions/runs/17318144442/job/49167652091)
  > 2025-08-29T08:47:21.6366670Z not ok 736 webContents module navigationHistory navigationHistory.restore({ index, entries }) API should restore navigation history with PageState
2025-08-29T08:47:21.6471530Z   expected 'value' to equal 'Hi!'
2025-08-29T08:47:21.6573150Z   AssertionError: expected 'value' to equal 'Hi!'
2025-08-29T08:47:21.6703080Z       at Context.<anonymous> (electron/spec/api-web-contents-spec.ts:922:30)

- https://github.com/electron/electron/commit/5d5e672f17248519b3c7bbdf27cb803c481c4d07 failed in [this CI run](https://github.com/electron/electron/actions/runs/17313882182/job/49154216866)
  > 2025-08-29T04:11:29.4324550Z not ok 736 webContents module navigationHistory navigationHistory.restore({ index, entries }) API should restore navigation history with PageState
2025-08-29T04:11:29.4467860Z   expected 'value' to equal 'Hi!'
2025-08-29T04:11:29.4569690Z   AssertionError: expected 'value' to equal 'Hi!'
2025-08-29T04:11:29.4672490Z       at Context.<anonymous> (electron/spec/api-web-contents-spec.ts:922:30)

### PR DESCRIPTION
**Pull request by jkleinsc**
#### Description of Change
- This PR was inspired by a conversation with @reitowo. It adds logic to rerun failed tests individually.  This should help avoid having to do full reruns of test suites when flakes happen.

- Additionally, this PR fixes a CI issue where a macOS system dialog was appearing with the following text which  broke/interfered with some of our tests:
>"bash" is requesting to bypass the system private window picker and directly access your screen and audio.  

- This PR also fixes #48291.

#### Checklist

- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] tests are [changed or added](https://github.com/electron/electron/blob/main/docs/development/testing.md)
- [x] [PR release notes](https://github.com/electron/clerk/blob/main/README.md) describe the change in a way relevant to app developers, and are [capitalized, punctuated, and past tense](https://github.com/electron/clerk/blob/main/README.md#examples).

#### Release Notes

Notes: none

### CODE REVIEW

File: script/spec-runner.js [hunk 1]
```diff
@@ -212,13 +361,18 @@ async function runTestUsingElectron (specDir, testName) {
     } else {
       console.log(`${fail} Electron tests failed with kill signal ${signal}.`);
     }
-    process.exit(1);
+    if (shouldRerun) {
```
Comment (reitowo) [inline script/spec-runner.js:375]: What do you think if we use `--enableRerun=3` to rerun configurable multiple times? 

```javascript
var failed = []
while (true) { 
    failed = runTests(failed.count == 0 ? '*' : failed) 
    if (failed.count == 0 || rerunCount-- == 0) {
        break
    }
}

if (failed.count > 0) {
    console.log('ci failed')
}
```

Comment (jkleinsc) [reply script/spec-runner.js:375]: We already re-run tests up to 3 times via mocha: https://github.com/electron/electron/blob/main/spec/index.js#L76, so adding the option here would mean that we would end up re-running tests up to 9 times which I believe is not necessary.

Comment (reitowo) [reply script/spec-runner.js:375]: I 'm not sure how mocha retries, if it just rerun the test method, some test might still fail unless process restart (vague memory of some flaky process that not recoverable)

Comment (jkleinsc) [reply script/spec-runner.js:375]: Good point @reitowo.  I'll update to add retries.

Comment (jkleinsc) [reply script/spec-runner.js:375]: Resolved via https://github.com/electron/electron/pull/48205/commits/4ef17c2d1aacb2b5682e8ab9568ea0c4f744b913.

**Comment by reitowo** [comment]
I thought I could see this PR in action right in this CI, but find out it actually all passed at first time! XD

**Comment by ckerr** [comment]
@electron/wg-infra could this get a review? #48291 is still causing a lot of CI failures

**Review by VerteDinde — APPROVED** [review]

**Review by codebytere — APPROVED** [review]
