### PR TITLE
Access native window through native view

### LINKED ISSUE #6940: Calling webContents.openDevTools followed by BrowserWindow.inspectElement crash
* Electron version:
1.3.3
* Operating system:
OSX El Capitan 10.11.6

The following code crashes Electron. The dev tools don't open, but the HTML element highlights like it is open.

```javascript
selfBrowserWindow.webContents.openDevTools({mode: 'detach'})
selfBrowserWindow.inspectElement(rightClickPosition.x, rightClickPosition.y)
```

The reason I'm doing this is because I want to open the dev tools detached, then inspect. Calling inspectElement first will open the dev tools docked by default.

### PR DESCRIPTION
**Pull request by kevinsawicki**
It looks like `WebContentsView::GetTopLevelNativeWindow` falls to back calling `WebContentsViewDelegate::GetNativeWindow` when the native view has no window and since the delegate isn't checked for being `null`, a crash will happen in certain scenarios.

This pull request switches the `WebContents::IsFocused` API to access the native window directly from the native view so this delegate fallback is never performed.

This looks to be a bug in Chrome since everywhere else in `WebContentsView` uses guards around `delegate()` to check that it is present before calling into it except in `GetTopLevelNativeWindow`.

https://cs.chromium.org/chromium/src/content/browser/web_contents/web_contents_view_mac.mm?l=150

https://cs.chromium.org/chromium/src/content/browser/web_contents/web_contents_view_aura.cc?l=626

Closes #6940

### CODE REVIEW

**Comment by deepak1556** [comment]
Although i wasn't able to reproduce the crash in the issue, a weird devtools behavior was shown because of race in devtools view creation.

devtoolsview



`api::WebContents::InspectElement` should just use the view of existing agent host instead of trying to create a new one, that way the desired output in the issue can be achieved.

File: atom/browser/api/atom_api_web_contents.cc [hunk 1]
```diff
@@ -1004,7 +1004,8 @@ void WebContents::InspectElement(int x, int y) {
   if (type_ == REMOTE)
     return;
 
-  OpenDevTools(nullptr);
+  if (!managed_web_contents()->GetDevToolsWebContents())
```
Comment (kevinsawicki) [inline atom/browser/api/atom_api_web_contents.cc]: > api::WebContents::InspectElement should just use the view of existing agent host instead of trying to create a new one, that way the desired output in the issue can be achieved.

@deepak1556 thanks for mentioning that, is this what you were thinking? This worked for me locally when calling `inspectElement` immediately after calling `openDevTools`.

Comment (deepak1556) [inline atom/browser/api/atom_api_web_contents.cc]: :+1:

**Comment by zcbenz** [comment]
:+1:
